### ISSUE TITLE
pywinauto AttributeError: WindowSpecification class has no 'window' method

### ISSUE THREAD

**Issue by ugoclemente** [pywinauto/pywinauto#1003]
## Expected Behavior
using pywinauto, I should simply automate the insertion of the text "Hello World!" in a Notepad window

## Actual Behavior
when I run the program the terminal shows the following error message:
"Traceback (most recent call last):
  File "demo2.py", line 8, in <module>
    dlg = app.window(title='Senza nome - Blocco note di Windows')
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pywinauto\application.py", line 129, in __call__
    raise AttributeError(
AttributeError: WindowSpecification class has no 'window' method"

## Steps to Reproduce the Problem

  1. install python3 on Windows
  2. install pip3
  3. install pywinauto on Windows running the following command from the cmd prompt: pip3 install pywinauto
  4. create a file named "demo.py" and paste inside it the code I will write in the following example
  5. run the file by the command: python3 demo.py 

## Short Example of Code to Demonstrate the Problem

# code start

import pywinauto
from pywinauto import application

app = application.Application()
app.start('Notepad.exe')

dlg = app.window(title='Senza nome - Blocco note di Windows')
dlg.Edit.TypeKeys("Hello World!", with_spaces = True)

#code end

## Specifications

  - Pywinauto version: 0.5.4
  - Python version and bitness: Python 3.8.6
  - Platform and OS: Windows 10

**Comment by Econ808** [comment]
I cannot replicate the error with python 3.8.6 64-bit and pywinauto==0.6.8, so maybe you should try upgrading?

Else you can try to see what app.windows() results in:
![image](https://user-images.githubusercontent.com/36441764/98221606-21368d00-1f50-11eb-86d1-8b7d2da24dd7.png)
