### ISSUE TITLE
Error Only absolute paths allowed - please start the path with \ with pywinauto Example

### ISSUE THREAD

**Issue by Shaakhal** [pywinauto/pywinauto#1010]
Hello,

I wanted to try the Example for uia, but I got an Error:

"Traceback (most recent call last):
  File "C:/Users/sglad/PycharmProjects/TestRPANew/test2.py", line 10, in <module>
    common_files = app.Programme.ItemsView.get_item('Common Files')
  File "C:\ProgramData\Anaconda3\envs\TestRPANew\lib\site-packages\pywinauto\controls\uia_controls.py", line 1344, in get_item
    raise RuntimeError(
RuntimeError: Only absolute paths allowed - please start the path with \"

```
from pywinauto import Desktop, Application

Application().start('explorer.exe "C:\\Program Files"')


# connect to another process spawned by explorer.exe
# Note: make sure the script is running as Administrator!
app = Application(backend="uia").connect(path="explorer.exe", title="Program Files")


app.ProgramFiles.set_focus()
common_files = app.ProgramFiles.ItemsView.get_item('Common Files')
common_files.right_click_input()
app.ContextMenu.Properties.invoke()

# this dialog is open in another process (Desktop object doesn't rely on any process id)
Properties = Desktop(backend='uia').Common_Files_Properties
Properties.print_control_identifiers()
Properties.Cancel.click()
Properties.wait_not('visible') # make sure the dialog is closed
```

## Specifications

  - Pywinauto version: 0.6.8
  - pyWin32 version: 300
  - Python version and bitness: 3.8.5
  - Platform and OS: Windows 10 Home (German as language)

Thanks in advance

**Comment by Shaakhal** [comment]
I already found out, that it detect only the Items on the left side of the Explorer-Window than the list of Folders in the middle. How can I can the Folders as Items?
