### ISSUE TITLE
unable to click button within a pane

### ISSUE THREAD

**Issue by eitansherer** [pywinauto/pywinauto#1032]
## Expected Behavior
I am trying to automate clicking through a login sequence and running into issues in clicking a button that is nested in a dialog/dialog/pane* structure.  I am able to identify the button, however any access to .click() results in an ElementNotFoundError exception.  

if I take a coordinates-based mouse click approach, the automation works.  Since I feel this is less robust, I was wondering if I'm doing something wrong or if there is an issue in detecting buttons in panes.  

## Actual Behavior
 File ".\eitan.py", line 110, in <module>
   continue_btn.click()
 File "C:\Indivio\virtualenv\lib\site-packages\pywinauto\application.py", line 362, in get-attribute
   ctrls = self.__resolve_control(self.criteria)
 File "C:\Indivio\virtualenv\lib\site-packages\pywinauto\application.py", line 259, in __resolve_control
   raise e.original_exception
ywinauto.findwindows.ElementNotFoundError: {'title_re': 'ContinueButton', 'parent': <uia_element_info.UIAElementInfo - '', EmbeddedWB, 3146124>, 'enabled_only': False, 'visible_only': False, 'top_level_only': False, 'backend': u'uia'}

## Steps to Reproduce the Problem
Control Identifiers:

Dialog - 'Adobe After Effects 2020 - Untitled Project.aep'    (L0, T101, R1024, B739)
[u'Dialog0', u'Adobe After Effects 2020 - Untitled Project.aep', u'Dialog', u'Adobe After Effects 2020 - Untitled Project.aepDialog', u'Dialog1']
child_window(title="Adobe After Effects 2020 - Untitled Project.aep", control_type="Window")
   | 
   | Dialog - ''    (L520, T180, R1336, B819)
   | [u'Adobe After EffectsDialog', u'Dialog2']
   |    | 
   |    | Pane - ''    (L-9472, T-9789, R-8672, B-9189)
   |    | [u'', u'0', 'Pane', u'1', u'Pane1', u'Pane0']
   |    |    | 
   |    |    | Pane - ''    (L-9472, T-9789, R-8672, B-9189)
   |    |    | [u'2', 'Pane2']
   |    |    |    | 
   |    |    |    | Pane - 'about:blank'    (L-9472, T-9789, R-8672, B-9189)
   |    |    |    | [u'about:blank', u'about:blankPane', 'Pane3']
   |    |    |    | child_window(title="about:blank", control_type="Pane")
   |    |    |    |    | 
   |    |    |    |    | Pane - ''    (L-9464, T-9781, R-8680, B-9197)
   |    |    |    |    | [u'3', 'Pane4']
   |    | 
   |    | Pane - ''    (L528, T211, R1328, B811)
   |    | [u'Adobe After EffectsPane1', u'Adobe After EffectsPane0', u'Adobe After EffectsPane', 'Pane5']
   |    |    | 
   |    |    | Pane - ''    (L528, T211, R1328, B811)
   |    |    | [u'Adobe After EffectsPane2', 'Pane6']
   |    |    |    | 
   |    |    |    | Pane - 'https://auth.services.adobe.com/en_US/index.html?delegated_auth_party=requester&callback=https%3A%2F%2Fims-na1.adobelogin.com%2Fims%2Fadobeid%2Fngl_after_effects1%2FAdobeID%2Fdevice%3Fredirect_uri%3Dhttps%253A%252F%252Foobe.adobe.com%252F%26device_id%3Df97c4716-c111-4265-bea8-8bd6d99b46b1%26device_name%3DEC2AMAZ-2MNB40R%26code_challenge_method%3Dplain%26use_ms_for_expiry%3Dtrue&client_id=ngl_after_effects1&scope=openid%2CAdobeID&denied_callback=https%3A%2F%2Fims-na1.adobelogin.com%2Fims%2Fdenied%2Fngl_after_effects1%3Fredirect_uri%3Dhttps%253A%252F%252Foobe.adobe.com%252F%26response_type%3Ddevice&relay=6284dcd7-9c51-4522-b1b0-992c280482c3&locale=en_US&flow_type=device&dctx_id=ccd-after-effects-2020&idp_flow_type=login#/'    (L528, T211, R1328, B811)
   |    |    |    | [u'https://auth.services.adobe.com/en_US/index.html?delegated_auth_party=requester&callback=https%3A%2F%2Fims-na1.adobelogin.com%2Fims%2Fadobeid%2Fngl_after_effects1%2FAdobeID%2Fdevice%3Fredirect_uri%3Dhttps%253A%252F%252Foobe.adobe.com%252F%26device_id%3Df97c4716-c111-4265-bea8-8bd6d99b46b1%26device_name%3DEC2AMAZ-2MNB40R%26code_challenge_method%3Dplain%26use_ms_for_expiry%3Dtrue&client_id=ngl_after_effects1&scope=openid%2CAdobeID&denied_callback=https%3A%2F%2Fims-na1.adobelogin.com%2Fims%2Fdenied%2Fngl_after_effects1%3Fredirect_uri%3Dhttps%253A%252F%252Foobe.adobe.com%252F%26response_type%3Ddevice&relay=6284dcd7-9c51-4522-b1b0-992c280482c3&locale=en_US&flow_type=device&dctx_id=ccd-after-effects-2020&idp_flow_type=login#/Pane', u'https://auth.services.adobe.com/en_US/index.html?delegated_auth_party=requester&callback=https%3A%2F%2Fims-na1.adobelogin.com%2Fims%2Fadobeid%2Fngl_after_effects1%2FAdobeID%2Fdevice%3Fredirect_uri%3Dhttps%253A%252F%252Foobe.adobe.com%252F%26device_id%3Df97c4716-c111-4265-bea8-8bd6d99b46b1%26device_name%3DEC2AMAZ-2MNB40R%26code_challenge_method%3Dplain%26use_ms_for_expiry%3Dtrue&client_id=ngl_after_effects1&scope=openid%2CAdobeID&denied_callback=https%3A%2F%2Fims-na1.adobelogin.com%2Fims%2Fdenied%2Fngl_after_effects1%3Fredirect_uri%3Dhttps%253A%252F%252Foobe.adobe.com%252F%26response_type%3Ddevice&relay=6284dcd7-9c51-4522-b1b0-992c280482c3&locale=en_US&flow_type=device&dctx_id=ccd-after-effects-2020&idp_flow_type=login#/', 'Pane7']
   |    |    |    | child_window(title="https://auth.services.adobe.com/en_US/index.html?delegated_auth_party=requester&callback=https%3A%2F%2Fims-na1.adobelogin.com%2Fims%2Fadobeid%2Fngl_after_effects1%2FAdobeID%2Fdevice%3Fredirect_uri%3Dhttps%253A%252F%252Foobe.adobe.com%252F%26device_id%3Df97c4716-c111-4265-bea8-8bd6d99b46b1%26device_name%3DEC2AMAZ-2MNB40R%26code_challenge_method%3Dplain%26use_ms_for_expiry%3Dtrue&client_id=ngl_after_effects1&scope=openid%2CAdobeID&denied_callback=https%3A%2F%2Fims-na1.adobelogin.com%2Fims%2Fdenied%2Fngl_after_effects1%3Fredirect_uri%3Dhttps%253A%252F%252Foobe.adobe.com%252F%26response_type%3Ddevice&relay=6284dcd7-9c51-4522-b1b0-992c280482c3&locale=en_US&flow_type=device&dctx_id=ccd-after-effects-2020&idp_flow_type=login#/", control_type="Pane")
   |    |    |    |    | 
   |    |    |    |    | Pane - 'Adobe ID'    (L528, T211, R1328, B811)
   |    |    |    |    | [u'Adobe ID', u'Adobe IDPane', 'Pane8']
   |    |    |    |    | child_window(title="Adobe ID", control_type="Pane")
   |    |    |    |    |    | 
   |    |    |    |    |    | Image - ''    (L720, T265, R738, B283)
   |    |    |    |    |    | [u'4', u'Image1', u'Image0', 'Image']
   |    |    |    |    |    | 
   |    |    |    |    |    | Static - 'Adobe After Effects'    (L746, T262, R877, B286)
   |    |    |    |    |    | [u'Adobe After Effects', u'Static', u'Adobe After EffectsStatic', u'Static1', u'Static0']
   |    |    |    |    |    | child_window(title="Adobe After Effects", control_type="Text")
   |    |    |    |    |    | 
   |    |    |    |    |    | Static - 'Sign in'    (L720, T294, R827, B341)
   |    |    |    |    |    | [u'Sign in', u'Sign inStatic', u'Static2']
   |    |    |    |    |    | child_window(title="Sign in", control_type="Text")
   |    |    |    |    |    | 
   |    |    |    |    |    | Static - 'New user?'    (L720, T349, R791, B376)
   |    |    |    |    |    | [u'New user?', u'Static3', u'New user?Static']
   |    |    |    |    |    | child_window(title="New user?", control_type="Text")
   |    |    |    |    |    | 
   |    |    |    |    |    | Hyperlink - 'Create an account'    (L791, T352, R913, B372)
   |    |    |    |    |    | [u'Create an account', u'Create an accountHyperlink', u'Create an account0', u'Create an account1', u'Hyperlink0', u'Hyperlink1', 'Hyperlink']
   |    |    |    |    |    | child_window(title="Create an account", control_type="Hyperlink")
   |    |    |    |    |    |    | 
   |    |    |    |    |    |    | Static - 'Create an account'    (L791, T349, R916, B376)
   |    |    |    |    |    |    | [u'Create an account2', u'Create an accountStatic', u'Static4']
   |    |    |    |    |    |    | child_window(title="Create an account", control_type="Text")
   |    |    |    |    |    | 
   |    |    |    |    |    | Static - 'Email address'    (L720, T408, R1120, B423)
   |    |    |    |    |    | [u'Email addressStatic0', u'Email addressStatic1', u'Email address', u'Email addressStatic', u'Email address0', u'Static5', u'Email address1']
   |    |    |    |    |    | child_window(title="Email address", auto_id="react-spectrum-5", control_type="Text")
   |    |    |    |    |    |    | 
   |    |    |    |    |    |    | Static - 'Email address'    (L720, T408, R790, B423)
   |    |    |    |    |    |    | [u'Email addressStatic2', u'Static6', u'Email address2']
   |    |    |    |    |    |    | child_window(title="Email address", control_type="Text")
   |    |    |    |    |    | 
   |    |    |    |    |    | Edit - 'Email address'    (L720, T423, R1120, B451)
   |    |    |    |    |    | [u'Edit0', u'Edit1', 'Edit', u'Email addressEdit']
   |    |    |    |    |    | child_window(title="Email address", auto_id="EmailPage-EmailField", control_type="Edit")
   |    |    |    |    |    | 
   |    |    |    |    |    | Button - 'Cancel'    (L942, T498, R1015, B530)
   |    |    |    |    |    | [u'Button1', u'Button0', u'CancelButton', u'Cancel', 'Button']
   |    |    |    |    |    | child_window(title="Cancel", control_type="Button")
   |    |    |    |    |    | 
   |    |    |    |    |    | Button - 'Continue'    (L1031, T498, R1120, B530)
   |    |    |    |    |    | ['Button2', u'ContinueButton', u'Continue']
   |    |    |    |    |    | child_window(title="Continue", control_type="Button")
   |    |    |    |    |    | 
   |    |    |    |    |    | Button - 'Continue with Google'    (L720, T586, R1120, B642)
   |    |    |    |    |    | ['Button3', u'Continue with GoogleButton', u'Continue with Google1', u'Continue with Google0', u'Continue with Google']
   |    |    |    |    |    | child_window(title="Continue with Google", control_type="Button")
   |    |    |    |    |    |    | 
   |    |    |    |    |    |    | Static - 'Continue with Google'    (L862, T603, R1007, B622)
   |    |    |    |    |    |    | [u'Continue with Google2', u'Static7', u'Continue with GoogleStatic']
   |    |    |    |    |    |    | child_window(title="Continue with Google", control_type="Text")
   |    |    |    |    |    | 
   |    |    |    |    |    | Button - 'Continue with Facebook'    (L720, T658, R1120, B714)
   |    |    |    |    |    | ['Button4', u'Continue with Facebook', u'Continue with FacebookButton', u'Continue with Facebook0', u'Continue with Facebook1']
   |    |    |    |    |    | child_window(title="Continue with Facebook", control_type="Button")
   |    |    |    |    |    |    | 
   |    |    |    |    |    |    | Static - 'Continue with Facebook'    (L852, T675, R1017, B694)
   |    |    |    |    |    |    | [u'Continue with FacebookStatic', u'Static8', u'Continue with Facebook2']
   |    |    |    |    |    |    | child_window(title="Continue with Facebook", control_type="Text")
   |    |    |    |    |    | 
   |    |    |    |    |    | Button - 'Continue with Apple'    (L720, T730, R1120, B786)
   |    |    |    |    |    | ['Button5', u'Continue with Apple1', u'Continue with Apple0', u'Continue with Apple', u'Continue with AppleButton']
   |    |    |    |    |    | child_window(title="Continue with Apple", control_type="Button")
   |    |    |    |    |    |    | 
   |    |    |    |    |    |    | Static - 'Continue with Apple'    (L866, T747, R1003, B766)
   |    |    |    |    |    |    | [u'Continue with Apple2', u'Static9', u'Continue with AppleStatic']
   |    |    |    |    |    |    | child_window(title="Continue with Apple", control_type="Text")
   |    |    |    |    |    | 
   |    |    |    |    |    | Static - 'Protected by reCAPTCHA and subject to the Google'    (L0, T0, R0, B0)
   |    |    |    |    |    | [u'Protected by reCAPTCHA and subject to the Google', u'Protected by reCAPTCHA and subject to the GoogleStatic', u'Static10']
   |    |    |    |    |    | child_window(title="Protected by reCAPTCHA and subject to the Google", control_type="Text")
   |    |    |    |    |    | 
   |    |    |    |    |    | Hyperlink - 'Google Privacy Policy'    (L0, T0, R0, B0)
   |    |    |    |    |    | [u'Google Privacy PolicyHyperlink', 'Hyperlink2', u'Google Privacy Policy']
   |    |    |    |    |    | child_window(title="Google Privacy Policy", control_type="Hyperlink")
   |    |    |    |    |    |    | 
   |    |    |    |    |    |    | Static - 'Privacy Policy'    (L0, T0, R0, B0)
   |    |    |    |    |    |    | [u'Privacy PolicyStatic', u'Privacy Policy', u'Static11']
   |    |    |    |    |    |    | child_window(title="Privacy Policy", control_type="Text")
   |    |    |    |    |    | 
   |    |    |    |    |    | Static - 'and'    (L0, T0, R0, B0)
   |    |    |    |    |    | [u'andStatic', u'and', u'Static12']
   |    |    |    |    |    | child_window(title="and", control_type="Text")
   |    |    |    |    |    | 
   |    |    |    |    |    | Hyperlink - 'Google Terms of Service'    (L0, T0, R0, B0)
   |    |    |    |    |    | [u'Google Terms of ServiceHyperlink', 'Hyperlink3', u'Google Terms of Service']
   |    |    |    |    |    | child_window(title="Google Terms of Service", control_type="Hyperlink")
   |    |    |    |    |    |    | 
   |    |    |    |    |    |    | Static - 'Terms of Service'    (L0, T0, R0, B0)
   |    |    |    |    |    |    | [u'Terms of Service', u'Terms of ServiceStatic', u'Static13']
   |    |    |    |    |    |    | child_window(title="Terms of Service", control_type="Text")
   |    |    |    |    |    | 
   |    |    |    |    |    | Static - '.'    (L0, T0, R0, B0)
   |    |    |    |    |    | [u'Static14', u'.', u'.Static']
   |    |    |    |    |    | child_window(title=".", control_type="Text")
   |    |    |    |    |    | 
   |    |    |    |    |    | Hyperlink - 'Elise Mesner'    (L528, T781, R634, B811)
   |    |    |    |    |    | [u'Elise Mesner0', u'Elise Mesner1', u'Elise Mesner', u'Elise MesnerHyperlink', 'Hyperlink4']
   |    |    |    |    |    | child_window(title="Elise Mesner", control_type="Hyperlink")
   |    |    |    |    |    |    | 
   |    |    |    |    |    |    | Image - ''    (L544, T781, R562, B799)
   |    |    |    |    |    |    | ['Image2', u'5']
   |    |    |    |    |    |    | 
   |    |    |    |    |    |    | Static - 'Elise Mesner'    (L568, T781, R634, B799)
   |    |    |    |    |    |    | [u'Elise Mesner2', u'Static15', u'Elise MesnerStatic']
   |    |    |    |    |    |    | child_window(title="Elise Mesner", control_type="Text")
   |    | 
   |    | TitleBar - ''    (L528, T183, R1328, B211)
   |    | ['TitleBar', u'6', u'TitleBar0', u'TitleBar1']
   |    |    | 
   |    |    | Button - 'Close'    (L1295, T181, R1329, B211)
   |    |    | [u'Close1', 'Button6', u'CloseButton', u'Close', u'Close0', u'CloseButton0', u'CloseButton1']
   |    |    | child_window(title="Close", control_type="Button")
   | 
   | Pane - 'DroverLord - Frame Window'    (L8, T152, R1016, B731)
   | [u'DroverLord - Frame WindowPane', u'DroverLord - Frame Window', u'DroverLord - Frame WindowPane1', u'DroverLord - Frame WindowPane0', 'Pane9', u'DroverLord - Frame Window1', u'DroverLord - Frame Window0']
   | child_window(title="DroverLord - Frame Window", control_type="Pane")
   |    | 
   |    | Pane - 'OS_ViewContainer'    (L10, T181, R1014, B729)
   |    | [u'OS_ViewContainerPane1', u'OS_ViewContainerPane0', u'OS_ViewContainer0', u'OS_ViewContainer1', u'OS_ViewContainerPane', 'Pane10', u'OS_ViewContainer']
   |    | child_window(title="OS_ViewContainer", control_type="Pane")
   |    |    | 
   |    |    | Pane - 'DroverLord - TabPanel Window'    (L10, T181, R1014, B729)
   |    |    | [u'DroverLord - TabPanel Window0', u'DroverLord - TabPanel Window1', u'DroverLord - TabPanel Window', u'DroverLord - TabPanel WindowPane0', u'DroverLord - TabPanel WindowPane1', 'Pane11', u'DroverLord - TabPanel WindowPane']
   |    |    | child_window(title="DroverLord - TabPanel Window", control_type="Pane")
   |    |    |    | 
   |    |    |    | Pane - 'OS_ViewContainer'    (L42, T294, R994, B309)
   |    |    |    | [u'OS_ViewContainerPane2', u'OS_ViewContainer2', 'Pane12']
   |    |    |    | child_window(title="OS_ViewContainer", control_type="Pane")
   |    |    |    |    | 
   |    |    |    |    | Pane - 'OS_EditTextContainer'    (L42, T294, R994, B309)
   |    |    |    |    | [u'OS_EditTextContainer', 'Pane13', u'OS_EditTextContainerPane']
   |    |    |    |    | child_window(title="OS_EditTextContainer", control_type="Pane")
   |    |    |    |    |    | 
   |    |    |    |    |    | Edit - ''    (L42, T294, R994, B309)
   |    |    |    |    |    | [u'Adobe After EffectsEdit', 'Edit2']
   |    |    |    |    |    | child_window(auto_id="1", control_type="Edit")
   | 
   | Pane - 'DroverLord - Frame Window'    (L8, T152, R1016, B731)
   | ['Pane14', u'DroverLord - Frame WindowPane2', u'DroverLord - Frame Window2']
   | child_window(title="DroverLord - Frame Window", control_type="Pane")
   |    | 
   |    | Pane - 'OS_ViewContainer'    (L10, T181, R1014, B729)
   |    | [u'OS_ViewContainerPane3', 'Pane15', u'OS_ViewContainer3']
   |    | child_window(title="OS_ViewContainer", control_type="Pane")
   |    |    | 
   |    |    | Pane - 'DroverLord - TabPanel Window'    (L10, T181, R1014, B729)
   |    |    | [u'DroverLord - TabPanel Window2', u'DroverLord - TabPanel WindowPane2', 'Pane16']
   |    |    | child_window(title="DroverLord - TabPanel Window", control_type="Pane")
   | 
   | Pane - 'DroverLord - Frame Window'    (L8, T152, R1016, B731)
   | ['Pane17', u'DroverLord - Frame WindowPane3', u'DroverLord - Frame Window3']
   | child_window(title="DroverLord - Frame Window", control_type="Pane")
   |    | 
   |    | Pane - 'OS_ViewContainer'    (L9, T153, R1003, B730)
   |    | [u'OS_ViewContainerPane4', u'OS_ViewContainer4', 'Pane18']
   |    | child_window(title="OS_ViewContainer", control_type="Pane")
   |    |    | 
   |    |    | Pane - 'OS_ViewContainer'    (L9, T790, R1003, B820)
   |    |    | [u'OS_ViewContainerPane5', 'Pane19', u'OS_ViewContainer5']
   |    |    | child_window(title="OS_ViewContainer", control_type="Pane")
   |    |    | 
   |    |    | Pane - 'OS_ViewContainer'    (L9, T760, R1003, B790)
   |    |    | [u'OS_ViewContainerPane6', 'Pane20', u'OS_ViewContainer6']
   |    |    | child_window(title="OS_ViewContainer", control_type="Pane")
   |    |    | 
   |    |    | Pane - 'OS_ViewContainer'    (L9, T730, R1003, B760)
   |    |    | [u'OS_ViewContainerPane7', 'Pane21', u'OS_ViewContainer7']
   |    |    | child_window(title="OS_ViewContainer", control_type="Pane")
   |    |    | 
   |    |    | Pane - 'OS_ViewContainer'    (L9, T303, R1003, B730)
   |    |    | ['Pane22', u'OS_ViewContainer8', u'OS_ViewContainerPane8']
   |    |    | child_window(title="OS_ViewContainer", control_type="Pane")
   |    |    |    | 
   |    |    |    | Pane - 'OS_ViewContainer'    (L10, T331, R1002, B725)
   |    |    |    | ['Pane23', u'OS_ViewContainer9', u'OS_ViewContainerPane9']
   |    |    |    | child_window(title="OS_ViewContainer", control_type="Pane")
   |    |    |    |    | 
   |    |    |    |    | Pane - 'DroverLord - TabPanel Window'    (L10, T331, R1002, B725)
   |    |    |    |    | ['Pane24', u'DroverLord - TabPanel WindowPane3', u'DroverLord - TabPanel Window3']
   |    |    |    |    | child_window(title="DroverLord - TabPanel Window", control_type="Pane")
   |    |    | 
   |    |    | Pane - 'OS_ViewContainer'    (L9, T273, R1003, B303)
   |    |    | [u'OS_ViewContainerPane10', 'Pane25', u'OS_ViewContainer10']
   |    |    | child_window(title="OS_ViewContainer", control_type="Pane")
   |    |    | 
   |    |    | Pane - 'OS_ViewContainer'    (L9, T243, R1003, B273)
   |    |    | [u'OS_ViewContainerPane11', u'OS_ViewContainer11', 'Pane26']
   |    |    | child_window(title="OS_ViewContainer", control_type="Pane")
   |    |    | 
   |    |    | Pane - 'OS_ViewContainer'    (L9, T213, R1003, B243)
   |    |    | [u'OS_ViewContainerPane12', 'Pane27', u'OS_ViewContainer12']
   |    |    | child_window(title="OS_ViewContainer", control_type="Pane")
   |    |    | 
   |    |    | Pane - 'OS_ViewContainer'    (L9, T183, R1003, B213)
   |    |    | [u'OS_ViewContainerPane13', 'Pane28', u'OS_ViewContainer13']
   |    |    | child_window(title="OS_ViewContainer", control_type="Pane")
   |    |    | 
   |    |    | Pane - 'OS_ViewContainer'    (L9, T153, R1003, B183)
   |    |    | [u'OS_ViewContainerPane14', 'Pane29', u'OS_ViewContainer14']
   |    |    | child_window(title="OS_ViewContainer", control_type="Pane")
   | 
   | Pane - 'DroverLord - Frame Window'    (L8, T152, R1016, B731)
   | ['Pane30', u'DroverLord - Frame WindowPane4', u'DroverLord - Frame Window4']
   | child_window(title="DroverLord - Frame Window", control_type="Pane")
   |    | 
   |    | Pane - 'OS_ViewContainer'    (L10, T181, R1014, B729)
   |    | [u'OS_ViewContainerPane15', u'OS_ViewContainer15', 'Pane31']
   |    | child_window(title="OS_ViewContainer", control_type="Pane")
   |    |    | 
   |    |    | Pane - 'DroverLord - TabPanel Window'    (L10, T181, R1014, B729)
   |    |    | [u'DroverLord - TabPanel Window4', 'Pane32', u'DroverLord - TabPanel WindowPane4']
   |    |    | child_window(title="DroverLord - TabPanel Window", control_type="Pane")
   | 
   | Pane - 'DroverLord - Frame Window'    (L8, T152, R1016, B731)
   | [u'DroverLord - Frame WindowPane5', 'Pane33', u'DroverLord - Frame Window5']
   | child_window(title="DroverLord - Frame Window", control_type="Pane")
   | 
   | TitleBar - ''    (L24, T104, R1016, B132)
   | [u'7', 'TitleBar2']
   |    | 
   |    | Menu - 'System'    (L8, T109, R30, B131)
   |    | [u'System1', u'Menu0', u'System0', u'System', u'Menu1', u'Menu', u'SystemMenu']
   |    | child_window(title="System", auto_id="MenuBar", control_type="MenuBar")
   |    |    | 
   |    |    | MenuItem - 'System'    (L8, T109, R30, B131)
   |    |    | [u'System2', u'MenuItem0', u'MenuItem', u'SystemMenuItem', u'MenuItem1']
   |    |    | child_window(title="System", control_type="MenuItem")
   |    | 
   |    | Button - 'Minimize'    (L877, T102, R924, B132)
   |    | [u'Minimize', u'MinimizeButton', 'Button7']
   |    | child_window(title="Minimize", control_type="Button")
   |    | 
   |    | Button - 'Maximize'    (L924, T102, R970, B132)
   |    | ['Button8', u'Maximize', u'MaximizeButton']
   |    | child_window(title="Maximize", control_type="Button")
   |    | 
   |    | Button - 'Close'    (L970, T102, R1017, B132)
   |    | ['Button9', u'Close2', u'CloseButton2']
   |    | child_window(title="Close", control_type="Button")
   | 
   | Menu - 'Application'    (L8, T132, R1016, B151)
   | [u'Application', u'ApplicationMenu', u'Menu2']
   | child_window(title="Application", auto_id="MenuBar", control_type="MenuBar")
   |    | 
   |    | MenuItem - 'File'    (L8, T132, R40, B151)
   |    | [u'MenuItem2', u'FileMenuItem', u'File']
   |    | child_window(title="File", control_type="MenuItem")
   |    | 
   |    | MenuItem - 'Edit'    (L40, T132, R74, B151)
   |    | [u'Edit3', u'EditMenuItem', u'MenuItem3']
   |    | child_window(title="Edit", control_type="MenuItem")
   |    | 
   |    | MenuItem - 'Composition'    (L74, T132, R157, B151)
   |    | [u'MenuItem4', u'Composition', u'CompositionMenuItem']
   |    | child_window(title="Composition", control_type="MenuItem")
   |    | 
   |    | MenuItem - 'Layer'    (L157, T132, R199, B151)
   |    | [u'LayerMenuItem', u'Layer', u'MenuItem5']
   |    | child_window(title="Layer", control_type="MenuItem")
   |    | 
   |    | MenuItem - 'Effect'    (L199, T132, R243, B151)
   |    | [u'Effect', u'MenuItem6', u'EffectMenuItem']
   |    | child_window(title="Effect", control_type="MenuItem")
   |    | 
   |    | MenuItem - 'Animation'    (L243, T132, R313, B151)
   |    | [u'Animation', u'MenuItem7', u'AnimationMenuItem']
   |    | child_window(title="Animation", control_type="MenuItem")
   |    | 
   |    | MenuItem - 'View'    (L313, T132, R352, B151)
   |    | [u'MenuItem8', u'ViewMenuItem', u'View']
   |    | child_window(title="View", control_type="MenuItem")
   |    | 
   |    | MenuItem - 'Window'    (L352, T132, R410, B151)
   |    | [u'MenuItem9', u'Window', u'WindowMenuItem']
   |    | child_window(title="Window", control_type="MenuItem")
   |    | 
   |    | MenuItem - 'Help'    (L410, T132, R449, B151)
   |    | [u'HelpMenuItem', u'Help', u'MenuItem10']
   |    | child_window(title="Help", control_type="MenuItem")
   |    | 
   |    | MenuItem - 'Beta'    (L449, T132, R486, B151)
   |    | [u'BetaMenuItem', u'MenuItem11', u'Beta']
   |    | child_window(title="Beta", control_type="MenuItem")

****** Specifically, I am interested in the following 2 identifiers:
   |    |    |    |    |    | Edit - 'Email address'    (L720, T423, R1120, B451)
   |    |    |    |    |    | [u'Edit0', u'Edit1', 'Edit', u'Email addressEdit']
   |    |    |    |    |    | child_window(title="Email address", auto_id="EmailPage-EmailField", control_type="Edit")
   |    |    |    |    |    | 
   |    |    |    |    |    | Button - 'Continue'    (L1031, T498, R1120, B530)
   |    |    |    |    |    | ['Button2', u'ContinueButton', u'Continue']
   |    |    |    |    |    | child_window(title="Continue", control_type="Button")

I am able to see the EmailPage-EmailField attribute and use .set_edit_text(username) to set the username.  However, while Continue/ContinueButton do return a WindowSpecification object, that object is not visible, the .exists() returns False, and .click() returns the exception above.

## Short Example of Code to Demonstrate the Problem
    # NOTE:  window_handle is the correct window handle after iterating on the output of pywinauto.Desktop(backend='uia').windows() and finding the correct window of interest.
    app             = pywinauto.application.Application(backend='uia').connect(handle=window_handle)
    window      = app.window(handle=window_handle)
    user_field   = window.child_window(title="Email address", auto_id="EmailPage-EmailField", control_type="Edit")
    continue_btn = window.child_window(title_re="ContinueButton", control_type="Button", visible_only=False, enabled_only=False)
    user_field.set_edit_text(username) # WORKS OK
    continue_ctn.click() # EXCEPTION (NOTE that click_input() and rectange() also fails the same way)

I wonder if the issue comes from there being a nested dialog followed by the complex pane hierarchy.  If instead I pull coordinates from user_field and use those (+ offset) to do a mouse.click(coords), that works.  

this seems similar to https://github.com/pywinauto/pywinauto/issues/993, but that issue is on set_text while this is on click.  in both cases, there is an error identifying elements that are in fact seen in print_control_identifiers.

Appreciate any insights you might have.  thanks.

## Specifications

  - Pywinauto version:   0.6.8
  - Python version and bitness:  2.7.15
  - Platform and OS:  Windows Server 2016

**Comment by eitansherer** [comment]
A small update/correction - the above code is actually using Pywinauto as recommended from issue 817 (https://github.com/pywinauto/pywinauto/issues/817) --> 779 (https://github.com/pywinauto/pywinauto/issues/779 using https://github.com/vasily-v-ryabov/pywinauto/archive/edit_by_title.zip)

If I use the released 0.6.8 version, I get the same ElementNotFoundError when trying to access the Email address field prior:
Traceback (most recent call last):
  File ".\eitan.py", line 168, in <module>
    user_field_rect = user_field.rectangle()
  File "C:\Indivio\virtualenv\lib\site-packages\pywinauto\application.py", line 379, in __getattribute__
    ctrls = self.__resolve_control(self.criteria)
  File "C:\Indivio\virtualenv\lib\site-packages\pywinauto\application.py", line 261, in __resolve_control
    raise e.original_exception
pywinauto.findwindows.ElementNotFoundError: {'auto_id': 'EmailPage-EmailField', 'parent': <uia_element_info.UIAElementInfo - 'Adobe After Effects 2020 - Untitled Project.aep', AE_CApplication_17.5, 3932598>, 'control_type': 'Edit', 'title': 'Email address', 'enabled_only': False, 'visible_only': False, 'top_level_only' : False, 'backend': u'uia'}

thank you

**Comment by madtatu-development** [comment]
May I ask if you were able to found a solution for this ? I ran into a similar issue, and I cant find any solution for it.
