### ISSUE TITLE
Unable to access checkbox(es) inside TreeItemWrapper

### ISSUE THREAD

**Issue by TechSupportJosh** [pywinauto/pywinauto#1044]
## Expected Behavior
I expect that when I attempt to access a tree item that contains a checkbox, I am able to call is_checked() on the TreeItemWrapper to get the state of it.

## Actual Behavior
I receive a NoPatternInterfaceError and cannot access the state of it in any way. 

## Steps to Reproduce the Problem

  1. Run FileZilla installation exe found at https://download.filezilla-project.org/client/FileZilla_3.52.2_win64_sponsored-setup.exe, sha256sum  6a582d1be83f079fd584f90b5872eb186889cdcc97bd276d51e65defedd77543)
  2. Start installer
  3. Click I agree
  4. Click Next
  5. Run code below

## Short Example of Code to Demonstrate the Problem
```python
import pywinauto
app = pywinauto.Application(backend="uia")
app.connect(best_match="FileZilla Setup")

tree = app.top_window().child_window(auto_id="1032").wait("exists")
tree_item = tree.children()[1]
print("Icon sets selected: ", tree_item.is_checked())
```

Error received:
```
Traceback (most recent call last):
  File "C:\Users\piav\AppData\Local\Programs\Python\Python39\lib\site-packages\pywinauto\uia_defines.py", line 234, in get_elem_interface
    iface = cur_ptrn.QueryInterface(cls_name)
  File "C:\Users\piav\AppData\Local\Programs\Python\Python39\lib\site-packages\comtypes\__init__.py", line 1158, in QueryInterface
    self.__com_QueryInterface(byref(iid), byref(p))
ValueError: NULL COM pointer access

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Z:\piav\test.py", line 8, in <module>
    print("Icon sets selected: ", tree_item.is_checked())
  File "C:\Users\piav\AppData\Local\Programs\Python\Python39\lib\site-packages\pywinauto\controls\uia_controls.py", line 1228, in is_checked
    return (self.iface_toggle.ToggleState_On == toggle_state_on)
  File "C:\Users\piav\AppData\Local\Programs\Python\Python39\lib\site-packages\pywinauto\controls\uiawrapper.py", line 132, in __get__
    value = self.fget(obj)
  File "C:\Users\piav\AppData\Local\Programs\Python\Python39\lib\site-packages\pywinauto\controls\uiawrapper.py", line 238, in iface_toggle
    return uia_defs.get_elem_interface(elem, "Toggle")
  File "C:\Users\piav\AppData\Local\Programs\Python\Python39\lib\site-packages\pywinauto\uia_defines.py", line 236, in get_elem_interface
    raise NoPatternInterfaceError()
pywinauto.uia_defines.NoPatternInterfaceError
```

Here's the UI Spy / Inspect of the treeview element

```AutomationElement
  General Accessibility
    AccessKey:	""
    AcceleratorKey:	""
    IsKeyboardFocusable:	"True"
    LabeledBy:	"(null)"
    HelpText:	""

  State
    IsEnabled:	"True"
    HasKeyboardFocus:	"False"

  Identification
    ClassName:	""
    ControlType:	"ControlType.TreeItem"
    Culture:	"(null)"
    AutomationId:	""
    LocalizedControlType:	"tree item"
    Name:	"Icon sets"
    ProcessId:	"4380 (FileZilla)"
    RuntimeId:	"1 5048234 0 117555200"
    IsPassword:	"False"
    IsControlElement:	"True"
    IsContentElement:	"True"

  Visibility
    BoundingRectangle:	"(428, 525, 48, 16)"
    ClickablePoint:	"451,532"
    IsOffscreen:	"False"

ControlPatterns
  ExpandCollapse
    ExpandCollapseState:	"LeafNode"

  SelectionItem
    IsSelected:	"False"
    SelectionContainer:	""tree" "Space required: 39.1 MB""

```

```
How found:	Mouse move (441,534)
	hwnd=0x004D07AA 32bit class="SysTreeView32" style=0x50010013 ex=0x204
ChildId:	2
Interfaces:	IEnumVARIANT IOleWindow IAccIdentity
Impl:	Local oleacc proxy
AnnotationID:	01000080AA074D00FCFFFFFF02000000
Name:	"Icon sets"
Value:	"0"
Role:	outline item (0x24)
State:	focusable,selectable (0x300000)
Location:	{l:428, t:525, w:48, h:16}
Description:	[null]
Kbshortcut:	[Error: hr=0x80020003 - Member not found.]
DefAction:	[Error: hr=0x80020003 - Member not found.]
Help:	[null]
HelpTopic:	""
ChildCount:	0
Window:	0x4D07AA
FirstChild:	[null]
LastChild:	[null]
Next:	"Language files" : outline item : focusable,selectable
Previous:	"FileZilla Client" : outline item : selected,focusable,selectable
Left:	[null]
Up:	"FileZilla Client" : outline item : selected,focusable,selectable
Right:	[null]
Down:	"Language files" : outline item : focusable,selectable
Other Props:	Object has no additional properties
Children:	Container has no children
Ancestors:	"Space required: 39.1 MB" : outline : focusable
	"Space required: 39.1 MB" : window : focusable
	none : property page : focusable
	none : window : focusable
	"FileZilla Client 3.52.2 Setup " : dialogue : focusable
	"FileZilla Client 3.52.2 Setup " : window : moveable,focusable
	"Desktop 1" : client : focusable
	"Desktop 1" : window : focusable
	[ No Parent ]
```

## Specifications

  - Pywinauto version: 
comtypes==1.1.7
pywin32==30 0
pywinauto==0.6.8
six==1.15.0
  - Python version and bitness: Python 3.9.1 64bit
  - Platform and OS: Windows 10 Pro N

Any help would be much appreciated, thanks!

**Comment by vasily-v-ryabov** [comment]
Thanks for report! It looks like issue on the app side, but we can try to workaround it in pywinauto as for some other cases (that's why I'm marked issue as enhancement as it enhances pywinauto capabilities).

Current workaround could be just using method `.click_input()`.

BTW, this installer contains some malicious code. My antivirus blocked some side process started by this installer definitely.

**Comment by vasily-v-ryabov** [comment]
Also many installers have standard command line option like `/s` which means "silent". It helps a lot to eliminate GUI automation for such simple task like installation. Maybe it's worth starting the installer with `/?` option to get help on other parameters.

**Comment by vasily-v-ryabov** [comment]
I had a one more look into this case. It seems it's impossible to implement workaround for "uia" backend except `.click_input(coords=(5, 5), absolute=False)`.

Regarding "win32" backend method `.click_input()` is also required, but without hard-coded relative coordinates:
```python
app = Application(backend="win32").connect(name_re="FileZilla Client .* Setup.*", timeout=10)

main = app.window(name_re="FileZilla Client .* Setup.*")
main.child_window(class_name="SysTreeView32").wrapper_object()
item = tree.get_item('\\Desktop icon')
main.set_focus(); item.click_input(where='check')
```

That's all I can do with this app. I don't see any opportunities to improve pywinauto code. So closing it as question.
