### ISSUE TITLE
Crash on pywinauto.findwindows.find_window while waiting for the window start

### ISSUE THREAD

**Issue by airelil** [pywinauto/pywinauto#105]
I have a crash in find_window:
```
Unexpected error: <class 'TypeError'>
Traceback (most recent call last):
  File "find_fx.py", line 23, in <module>
    w = find_fx()
  File "find_fx.py", line 12, in find_fx
    title_re=".*Mozilla Firefox.*"
  File "...\Docs\dev\pywinauto\pywinauto\findwindows.py", line 59, in fin
d_window
    windows = find_windows(**kwargs)
  File "...\Docs\dev\pywinauto\pywinauto\findwindows.py", line 189, in fi
nd_windows
    windows = [win for win in windows
  File "...\Docs\dev\pywinauto\pywinauto\findwindows.py", line 190, in <l
istcomp>
    if handleprops.text(win) is not None and title_regex.match(handleprops.text(
win))]
TypeError: expected string or buffer
```

To reproduce, run the script below and try to launch Firefox browser several times. On my machine it crashes on first or second attempt to launch the browser.  I got the crash on Python 3.4 x64 and x86
```python
# -*- coding: utf-8 -*-

import sys, time
import pywinauto

app = pywinauto.application.Application()

def find_fx():
    while True:
        try:
            h = pywinauto.findwindows.find_window(
                    title_re=".*Mozilla Firefox.*"
                    )
            return app.Window_(handle=h)
        except(pywinauto.findwindows.WindowNotFoundError):
            # if the sleep is open the problem still happens but less frequently
            #time.sleep(0.2)
            pass
        except:
            print("Unexpected error:", sys.exc_info()[0])
            raise

count = 0
while True:
    w = find_fx()
    w.Wait("ready")
    w.Close()
    count = count + 1
    if count > 30:
        break
```

**Comment by vasily-v-ryabov** [comment]
It looks like `handleprops.text(win)` returns some string first time and `None` second time for the same handle. To avoid the second call I can suggest the following fix in `find_windows`:

```python
        windows_and_texts = [(win, handleprops.text(win)) for win in windows]
        windows = [win for win, text in windows_and_texts
            if text is not None and title_regex.match(text)]
```

**Comment by airelil** [comment]
I just went on with this:
```python
        def _title_match(w):
            t = handleprops.text(w)
            if t is not None:
                return title_regex.match(t)
            return False
        windows = [win for win in windows if _title_match(win)]
```
Looks as working for me. I was just about checking it in...

**Comment by vasily-v-ryabov** [comment]
OK, it looks great too. Go ahead please. I'm still working on SendKeys tests...
