### ISSUE TITLE
Question - Pywinauto support for Microsoft edge browser application

### ISSUE THREAD

**Issue by poornima55** [pywinauto/pywinauto#1078]
## Expected Behavior
Able to automate the Microsoft Edge browser application using pywinauto

## Actual Behavior
me_app = application.Application(backend='uia').start(r"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe")
ext = me_app.connect(title='.*New tab.*')

This results in error like below: (Also changed the 'backend' argument to win32 to see if that helps. It did not!)
Traceback (most recent call last):
  File "C:\Users\cisco\edge.py", line 19, in <module>
    ext = me_app.connect(title='.*New tab.*')
  File "C:\Users\cisco\AppData\Local\Programs\Python\Python39\lib\site-packages\pywinauto\application.py", line 997, in connect
    self.process = findwindows.find_element(**kwargs).process_id
  File "C:\Users\cisco\AppData\Local\Programs\Python\Python39\lib\site-packages\pywinauto\findwindows.py", line 87, in find_element
    raise ElementNotFoundError(kwargs)
pywinauto.findwindows.ElementNotFoundError: {'title': '.*New tab.*', 'backend': 'uia', 'visible_only': False}

## Steps to Reproduce the Problem

  1. Run the code snippet
  from pywinauto import application
  me_app = application.Application(backend='uia').start(r"C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe")
  ext = me_app.connect(title='New Tab - Google Chrome', found_index=1)

ext.NewTabGoogleChrome.print_control_identifiers()
me_app = application.Application(backend='uia').start(r"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe")
ext = me_app.connect(title='.*New tab.*')
ext.NewtabMicrosoftEdge.print_control_identifiers()

## Short Example of Code to Demonstrate the Problem
The Google chrome app opens fine and able to print the control identifiers just fine. But error  occurs with MS Edge.

## Specifications

  Pywinauto version: 0.6.8
Python version and bitness: 3.9.5, 64 bit
Platform and OS: Windows 10, 64 bit

**Comment by vasily-v-ryabov** [comment]
pywinauto is able to automate Edge as it is built on top of Chrome engine. Just run Inspect.exe and see property `FrameworkId:	"Chrome"` :)

The problem here is that Edge has launcher process which spawn a child one. So `Application(backend="uia").start("msedge.exe")` can't see anything in launcher process. Detecting child processes is a feature request #593.

But it is a bit tricky to use correct title for MS Edge window:
```python
from pywinauto import Desktop, Application

app = Application(backend="uia").start(r"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe")
print(app.process)
print(app.windows())

app = Application(backend="uia").connect(title_re=u".*Microsoft\u200b Edge", timeout=10)
print(app.process)
print(app.windows())

app.window(title_re=u".*Microsoft\u200b Edge").dump_tree()
```

See also #590 for other browsers examples.
