### ISSUE TITLE
Getting TypeError: UIAElementInfo object can be initialized with integer or IUIAutomationElement instance only!

### ISSUE THREAD

**Issue by bharatrajs** [pywinauto/pywinauto#1087]
Hi,

I am new to Pywinauto and getting below error 

## Short Example of Code to Demonstrate the Problem
from pywinauto.application import Application
import time
import pyautogui

app=Application(backend='uia').start(r"C:\Program Files (x86)\blue8\client\B8Analyser.exe")
time.sleep(5)
app=Application(backend='uia').connect(title='Main Window',timeout=10)

w1 = app.window(best_match='Main Window').wrapper_object()
w2 = app.window(handle=w1)
ctrl = w2['TreeView']

c1 = ctrl.get_item([u'xd Explorer', u'Annotation_AugCrime']).click_input(button="left", double=True)
c2 = c1.sub_elements()

getting below error at c1 line
TypeError: UIAElementInfo object can be initialized with integer or IUIAutomationElement instance only!

## Specifications

  - Pywinauto version: 0.6.8
  - Python version and bitness: 3.8.2
  - Platform and OS: windows 10

**Comment by vasily-v-ryabov** [comment]
Hi @bharatrajs thanks for the report! Can you provide the full traceback of the error? Python prints very detailed output with all .py file names and line numbers. I need this information to understand a root cause.

**Comment by bharatrajs** [comment]
Hi Vasily,

please find below full traceback of the error

Traceback (most recent call last):
  File "C:/Users/bharatraj.shetty/PycharmProjects/test111/venv/testFiles/test7.py", line 13, in <module>
    c1 = ctrl.get_item([u'xd Explorer', u'Annotation_AugCrime']).click_input(button="left", double=True)
  File "C:\Users\bharatraj.shetty\PycharmProjects\test111\venv\lib\site-packages\pywinauto\application.py", line 379, in __getattribute__
    ctrls = self.__resolve_control(self.criteria)
  File "C:\Users\bharatraj.shetty\PycharmProjects\test111\venv\lib\site-packages\pywinauto\application.py", line 250, in __resolve_control
    ctrl = wait_until_passes(
  File "C:\Users\bharatraj.shetty\PycharmProjects\test111\venv\lib\site-packages\pywinauto\timings.py", line 436, in wait_until_passes
    func_val = func(*args, **kwargs)
  File "C:\Users\bharatraj.shetty\PycharmProjects\test111\venv\lib\site-packages\pywinauto\application.py", line 203, in __get_ctrl
    dialog = self.backend.generic_wrapper_class(findwindows.find_element(**criteria[0]))
  File "C:\Users\bharatraj.shetty\PycharmProjects\test111\venv\lib\site-packages\pywinauto\findwindows.py", line 84, in find_element
    elements = find_elements(**kwargs)
  File "C:\Users\bharatraj.shetty\PycharmProjects\test111\venv\lib\site-packages\pywinauto\findwindows.py", line 181, in find_elements
    return [backend_obj.element_info_class(handle), ]
  File "C:\Users\bharatraj.shetty\PycharmProjects\test111\venv\lib\site-packages\pywinauto\uia_element_info.py", line 75, in __init__
    raise TypeError("UIAElementInfo object can be initialized " + \
TypeError: UIAElementInfo object can be initialized with integer or IUIAutomationElement instance only!

**Comment by vasily-v-ryabov** [comment]
Hi @bharatrajs thanks for details! Can you try and post the same traceback with my branch? Just install it this way:
```
pip uninstall -y pywinauto
pip install https://github.com/vasily-v-ryabov/pywinauto/archive/refs/heads/uia_elem_init_crash.zip
```
This case is handled without enough details so I've added more detailed error message.

**Comment by vasily-v-ryabov** [comment]
It is also interesting how `ctrl` object is declared before calling method `get_item(...)`.

**Comment by bharatrajs** [comment]
It works when i initiate app as below

from pywinauto import application
import time
import pyautogui

app=application.Application()
app.start(r"C:\Program Files (x86)\blue8\client\B8Analyser.exe")
time.sleep(5)

w1 = app.window(best_match='Main Window').wrapper_object()
w2 = app.window(handle=w1)
ctrl = w2['TreeView']

c1 = ctrl.get_item([u'xd Explorer', u'Annotation_AugCrime']).click_input(button="left", double=True)
c2 = c1.sub_elements()
for x in c2:
    print(x.text())
    
But throws error when i initiate app as

from pywinauto.application import Application
import time
import pyautogui

app=Application(backend='uia').start(r"C:\Program Files (x86)\blue8\client\B8Analyser.exe")
time.sleep(5)
app=Application(backend='uia').connect(title='Main Window',timeout=10)

**Comment by vasily-v-ryabov** [comment]
This is interesting. But I'd prefer to see **the full traceback with updated pywinauto code** I provided above. It's too time consuming to try downloading the app and so on. Thanks for your help!

**Comment by vasily-v-ryabov** [comment]
Particularly I need the updated message instead of this one:
```
TypeError: UIAElementInfo object can be initialized with integer or IUIAutomationElement instance only!
```

**Comment by bharatrajs** [comment]
i am getting the same message with new branch

D:\Python\Python38-32\python.exe C:/Users/bharatraj.shetty/PycharmProjects/newTest/testfiles/test1.py
Traceback (most recent call last):
  File "C:/Users/bharatraj.shetty/PycharmProjects/newTest/testfiles/test1.py", line 15, in <module>
    c1 = ctrl.get_item([u'xd Explorer', u'Annotation_AugCrime']).click_input(button="left", double=True)
  File "D:\Python\Python38-32\lib\site-packages\pywinauto\application.py", line 379, in __getattribute__
    ctrls = self.__resolve_control(self.criteria)
  File "D:\Python\Python38-32\lib\site-packages\pywinauto\application.py", line 250, in __resolve_control
    ctrl = wait_until_passes(
  File "D:\Python\Python38-32\lib\site-packages\pywinauto\timings.py", line 436, in wait_until_passes
    func_val = func(*args, **kwargs)
  File "D:\Python\Python38-32\lib\site-packages\pywinauto\application.py", line 203, in __get_ctrl
    dialog = self.backend.generic_wrapper_class(findwindows.find_element(**criteria[0]))
  File "D:\Python\Python38-32\lib\site-packages\pywinauto\findwindows.py", line 84, in find_element
    elements = find_elements(**kwargs)
  File "D:\Python\Python38-32\lib\site-packages\pywinauto\findwindows.py", line 181, in find_elements
    return [backend_obj.element_info_class(handle), ]
  File "D:\Python\Python38-32\lib\site-packages\pywinauto\uia_element_info.py", line 75, in __init__
    raise TypeError("UIAElementInfo object can be initialized " + \
TypeError: UIAElementInfo object can be initialized with integer or IUIAutomationElement instance only!

Process finished with exit code 1

**Comment by vasily-v-ryabov** [comment]
@bharatrajs sorry for long waiting but I see that the error message is NOT from my branch. Can you please try with my branch again?
```
pip uninstall -y pywinauto
pip install https://github.com/vasily-v-ryabov/pywinauto/archive/refs/heads/uia_elem_init_crash.zip
```
