### ISSUE TITLE
set_window_text doesn't work

### ISSUE THREAD

**Issue by wkingnet** [pywinauto/pywinauto#1100]
## Expected Behavior
set_window_text(text, append=False) can set program window title text

## Actual Behavior
python return ctypes.ArgumentError: argument 4: <class 'TypeError'>: wrong type

## Steps to Reproduce the Problem
Use set_window_text() anywhere

## Short Example of Code to Demonstrate the Problem
```
Traceback (most recent call last):
>>>pywinauto.controls.hwndwrapper.set_window_text('aaa')
  File "<input>", line 1, in <module>
  File "D:\soft\Anaconda\envs\game\lib\site-packages\pywinauto\controls\hwndwrapper.py", line 896, in set_window_text
    self.post_message(win32defines.WM_SETTEXT, 0, text)
  File "D:\soft\Anaconda\envs\game\lib\site-packages\pywinauto\controls\hwndwrapper.py", line 686, in post_message
    return win32functions.PostMessage(self, message, wparam, lparam)
ctypes.ArgumentError: argument 4: <class 'TypeError'>: wrong type
```

## Specifications

  - Pywinauto version:0.6.8
  - Python version and bitness: 3.9.5 x32
  - Platform and OS: win10

**Comment by wkingnet** [comment]
I use
```
auto.send_message(0x000C, wparam=None, lparam='aaaa')
```
instand of it temporary.

**Comment by k1m190r** [comment]
```python
import pywinauto.win32functions as win32functions
import win32con

....
handle = <a handle for a control to receive the message>
....

text = "new value for string"
win32functions.SendMessage(handle, win32con.WM_SETTEXT, 0, text)

```
As error above states: `set_window_text()` calls `win32functions.PostMessage()` which returns error 0x487 which is '_The message can be used only with synchronous operations_' which means have to use `win32functions.SendMessage()`.
