### ISSUE TITLE
Check selection of an item within a ListBox did not works

### ISSUE THREAD

**Issue by EricaRCA** [pywinauto/pywinauto#1120]
## Expected Behavior
I have a series of items in a ListBox presented in the following picture:
![image](https://user-images.githubusercontent.com/90624475/134905759-ec5c7ff0-11b4-48c7-b673-3b9b73bc416c.png)

The following is a snippet of the related control identifiers using uia backend:
   | ListBox - ''    (L828, T305, R989, B466)
   | ['ListBox']
   | child_window(auto_id="788838", control_type="List")
   |    |
   |    | ListItem - '#IS_VISIBLE#'    (L830, T307, R987, B320)
   |    | ['#IS_VISIBLE#', 'ListItem', '#IS_VISIBLE#ListItem', 'ListItem0', 'ListItem1']
   |    | child_window(title="#IS_VISIBLE#", control_type="ListItem")
   |    |
   |    | ListItem - '#NOT_VISIBLE#'    (L830, T320, R987, B333)
   |    | ['#NOT_VISIBLE#ListItem', '#NOT_VISIBLE#', 'ListItem2']
   |    | child_window(title="#NOT_VISIBLE#", control_type="ListItem")
   |    |
   |    | ListItem - '#IS_ENABLED#'    (L830, T333, R987, B346)
   |    | ['#IS_ENABLED#', '#IS_ENABLED#ListItem', 'ListItem3']
   |    | child_window(title="#IS_ENABLED#", control_type="ListItem")
   |    |
   |    | ListItem - '#NOT_ENABLED#'    (L830, T346, R987, B359)
   |    | ['#NOT_ENABLED#ListItem', '#NOT_ENABLED#', 'ListItem4']
   |    | child_window(title="#NOT_ENABLED#", control_type="ListItem")
   |    |
   |    | ListItem - '#HAS_TEXT#'    (L830, T359, R987, B372)
   |    | ['#HAS_TEXT#ListItem', 'ListItem5', '#HAS_TEXT#']
   |    | child_window(title="#HAS_TEXT#", control_type="ListItem")
   |    |
   |    | ListItem - '#HAS_NO_TEXT#'    (L830, T372, R987, B385)
   |    | ['#HAS_NO_TEXT#', '#HAS_NO_TEXT#ListItem', 'ListItem6']
   |    | child_window(title="#HAS_NO_TEXT#", control_type="ListItem")
   |    |
   |    | ListItem - '#NOT_FOUND#'    (L830, T385, R987, B398)
   |    | ['#NOT_FOUND#', '#NOT_FOUND#ListItem', 'ListItem7']
   |    | child_window(title="#NOT_FOUND#", control_type="ListItem")
   |    |
   |    | ListItem - '#CHECK COLOR#'    (L830, T398, R987, B411)
   |    | ['#CHECK COLOR#ListItem', '#CHECK COLOR#', 'ListItem8']
   |    | child_window(title="#CHECK COLOR#", control_type="ListItem")
   |    |
   |    | ListItem - '#TEXT#'    (L830, T411, R987, B424)
   |    | ['#TEXT#', '#TEXT#ListItem', 'ListItem9']
   |    | child_window(title="#TEXT#", control_type="ListItem")

I would like to be able to check if an item is checked. 
## Actual Behavior
**Code:**
w = appuia.top_window().child_window(best_match='#IS_ENABLED#', control_type='ListItem', title='#IS_ENABLED#').wrapper_object()
w.is_checked()

**Exception:**
Traceback (most recent call last):
  File "C:\Python39-32\lib\site-packages\pywinauto\uia_defines.py", line 234, in get_elem_interface
    iface = cur_ptrn.QueryInterface(cls_name)
  File "C:\Python39-32\lib\site-packages\comtypes\__init__.py", line 1158, in QueryInterface
    self.__com_QueryInterface(byref(iid), byref(p))
ValueError: NULL COM pointer access

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python39-32\lib\site-packages\pywinauto\controls\uia_controls.py", line 659, in is_checked
    return self.iface_toggle.ToggleState_On == toggle_state_on
  File "C:\Python39-32\lib\site-packages\pywinauto\controls\uiawrapper.py", line 132, in __get__
    value = self.fget(obj)
  File "C:\Python39-32\lib\site-packages\pywinauto\controls\uiawrapper.py", line 238, in iface_toggle
    return uia_defs.get_elem_interface(elem, "Toggle")
  File "C:\Python39-32\lib\site-packages\pywinauto\uia_defines.py", line 236, in get_elem_interface
    raise NoPatternInterfaceError()
pywinauto.uia_defines.NoPatternInterfaceError

## Steps to Reproduce the Problem
Element found: <uia_controls.ListItemWrapper - '#IS_ENABLED#', ListItem, 846907961>
  1. Find an application which has a ListBox similar to the one presented in the issue description
  2. Try to evaluate if the item is checked

## Short Example of Code to Demonstrate the Problem
w = appuia.top_window().child_window(best_match='#IS_ENABLED#', control_type='ListItem', title='#IS_ENABLED#').wrapper_object()
w.is_checked()

## Specifications

  - Pywinauto version: 0.6.8
  - Python version and bitness: 3.9.2
  - Platform and OS: Windows 10

**Comment by vasily-v-ryabov** [comment]
Please re-take Inspect.exe screenshot in "UI Automation" mode instead of default "MS AA".
If NativeWindowHandle property is visible in Inspect.exe, I suggest to try "win32" backend.
