### ISSUE TITLE
Multiple ComboBox inside pane flicker. Wrapper error

### ISSUE THREAD

**Issue by marcoccio** [pywinauto/pywinauto#1161]
## Expected Behavior
When creating a handle for a ComboBox objetc the hwwrapper should respect the ComboBox name given. For example: 

`comboBox1 = dlg.WindowName.ComboBox1.select(0)`

Should search for a ComboBox with name "1" an select the index 0. 

## Actual Behavior

When `comboBox1 = dlg.WindowName.ComboBox1.select(0)` gets called, the library checks the window, during this process all the comboBoxes present in the window opens and closes for some time, then item 0 gets correctly selected but the call exits with code: 

`Traceback (most recent call last):
  File "C:\python38\lib\site-packages\pywinauto\uia_defines.py", line 234, in get_elem_interface
    iface = cur_ptrn.QueryInterface(cls_name)
  File "C:\python38\lib\site-packages\comtypes\__init__.py", line 1152, in QueryInterface
    self.__com_QueryInterface(byref(iid), byref(p))
ValueError: NULL COM pointer access

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\python38\lib\site-packages\pywinauto\controls\uia_controls.py", line 238, in select
    self._select(item)
  File "C:\python38\lib\site-packages\pywinauto\controls\uiawrapper.py", line 676, in _select
    wrp.iface_selection_item.Select()
  File "C:\python38\lib\site-packages\pywinauto\controls\uiawrapper.py", line 132, in __get__
    value = self.fget(obj)
  File "C:\python38\lib\site-packages\pywinauto\controls\uiawrapper.py", line 224, in iface_selection_item
    return uia_defs.get_elem_interface(elem, "SelectionItem")
  File "C:\python38\lib\site-packages\pywinauto\uia_defines.py", line 236, in get_elem_interface
    raise NoPatternInterfaceError()
pywinauto.uia_defines.NoPatternInterfaceError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\python38\lib\site-packages\pywinauto\uia_defines.py", line 234, in get_elem_interface
    iface = cur_ptrn.QueryInterface(cls_name)
  File "C:\python38\lib\site-packages\comtypes\__init__.py", line 1152, in QueryInterface
    self.__com_QueryInterface(byref(iid), byref(p))
ValueError: NULL COM pointer access

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\python38\lib\site-packages\pywinauto\controls\uia_controls.py", line 293, in selected_index
    return self.selected_item_index()
  File "C:\python38\lib\site-packages\pywinauto\controls\uiawrapper.py", line 588, in selected_item_index
    selection = self.get_selection()
  File "C:\python38\lib\site-packages\pywinauto\controls\uiawrapper.py", line 579, in get_selection
    ptrs_array = self.iface_selection.GetCurrentSelection()
  File "C:\python38\lib\site-packages\pywinauto\controls\uiawrapper.py", line 132, in __get__
    value = self.fget(obj)
  File "C:\python38\lib\site-packages\pywinauto\controls\uiawrapper.py", line 217, in iface_selection
    return uia_defs.get_elem_interface(elem, "Selection")
  File "C:\python38\lib\site-packages\pywinauto\uia_defines.py", line 236, in get_elem_interface
    raise NoPatternInterfaceError()
pywinauto.uia_defines.NoPatternInterfaceError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/Cega/Desktop/gitlab/pcanview-controller/source/temporary_tests/pruebas_connect.py",
line 104, in <module>
    dlg.Connect.ComboBox1.select(0)
  File "C:\python38\lib\site-packages\pywinauto\controls\uia_controls.py", line 255, in select
    elif self.selected_index() != item:
  File "C:\python38\lib\site-packages\pywinauto\controls\uia_controls.py", line 296, in selected_index
    return self.texts().index(self.selected_text())
ValueError: '20 MHz' is not in list`

## Steps to Reproduce the Problem

See code below.  

## Short Example of Code to Demonstrate the Problem

`app = Application(backend="uia").start(r"C:\Users\Cega\Desktop\gitlab\pcanview-controller\source\PcanView.exe")
dlg = app.top_window()
dlg.Connect.ComboBox1.draw_outline() <== This works without any errors
time.sleep(1)
dlg.Connect.ComboBox1.select(0) <== This gives the error mentioned above. 
`
"Connect" is a popup window given by PcanView.exe at startup. 

[Here is a short video of this behavior ](https://1drv.ms/v/s!AifPFXqjPaa5koUT1DafTNt72jn8aw?e=dMwX0X) 

## Specifications

  - Pywinauto version: 0.6.8
  - Python version and bitness: 3.8
  - Platform and OS: windows 7

**Comment by marcoccio** [comment]
Here is the control tree of the "Connect" window: 
`Control Identifiers:

Dialog - 'Connect'    (L449, T103, R887, B635)
['Connect', 'ConnectDialog', 'Dialog']
child_window(title="Connect", control_type="Window")
   |
   | Button - ''    (L842, T480, R867, B505)
   | ['Button', 'Button0', 'Button1']
   | child_window(auto_id="197448", control_type="Button")
   |
   | ComboBox - ''    (L465, T481, R565, B504)
   | ['ComboBoxClose', 'ComboBox', 'ComboBox0', 'ComboBox1']
   | child_window(auto_id="197462", control_type="ComboBox")
   |    |
   |    | Static - ''    (L3, T3, R80, B20)
   |    | ['Static', 'Static0', 'Static1']
   |    |
   |    | Button - 'Open'    (L549, T482, R564, B503)
   |    | ['Open', 'OpenButton', 'Button2', 'Open0', 'Open1', 'OpenButton0', 'OpenButton1']
   |    | child_window(title="Open", auto_id="DropDown", control_type="Button")
   |
   | CheckBox - 'CAN FD'    (L465, T438, R562, B455)
   | ['CAN FDCheckBox', 'CheckBox', 'CAN FD', 'CheckBox0', 'CheckBox1']
   | child_window(title="CAN FD", auto_id="394022", control_type="CheckBox")
   |
   | CheckBox - 'Listen-only mode'    (L481, T593, R618, B610)
   | ['Listen-only mode', 'CheckBox2', 'Listen-only modeCheckBox']
   | child_window(title="Listen-only mode", auto_id="262962", control_type="CheckBox")
   |
   | Pane - ''    (L571, T455, R840, B512)
   | ['Pane', 'Pane0', 'Pane1']
   | child_window(auto_id="197442", control_type="Pane")
   |    |
   |    | Pane - 'CAN'    (L571, T455, R840, B512)
   |    | ['Pane2', 'CAN', 'CANPane']
   |    | child_window(title="CAN", auto_id="197450", control_type="Pane")
   |    |    |
   |    |    | Edit - ''    (L707, T481, R837, B504)
   |    |    | ['Edit', 'Edit0', 'Edit1']
   |    |    | child_window(auto_id="459616", control_type="Edit")
   |    |    |
   |    |    | ComboBox - ''    (L571, T481, R701, B504)
   |    |    | ['ComboBox2']
   |    |    | child_window(auto_id="197452", control_type="ComboBox")
   |    |    |    |
   |    |    |    | Static - ''    (L3, T3, R110, B20)
   |    |    |    | ['Static2']
   |    |    |    |
   |    |    |    | Button - 'Open'    (L685, T482, R700, B503)
   |    |    |    | ['Open2', 'OpenButton2', 'Button3']
   |    |    |    | child_window(title="Open", auto_id="DropDown", control_type="Button")
   |
   | Pane - ''    (L457, T133, R862, B180)
   | ['Pane3']
   | child_window(auto_id="197440", control_type="Pane")
   |
   | Pane - 'Filter settings'    (L465, T518, R870, B583)
   | ['Filter settings', 'Pane4', 'Filter settingsPane']
   | child_window(title="Filter settings", auto_id="394032", control_type="Pane")
   |    |
   |    | RadioButton - 'Extended'    (L481, T557, R558, B574)
   |    | ['Extended', 'RadioButton', 'ExtendedRadioButton', 'RadioButton0', 'RadioButton1']
   |    | child_window(title="Extended", auto_id="197438", control_type="RadioButton")
   |    |
   |    | RadioButton - 'Standard'    (L481, T538, R558, B555)
   |    | ['Standard', 'StandardRadioButton', 'RadioButton2']
   |    | child_window(title="Standard", auto_id="197436", control_type="RadioButton")
   |    |
   |    | Edit - ''    (L729, T543, R794, B566)
   |    | ['Edit2']
   |    | child_window(auto_id="328500", control_type="Edit")
   |    |
   |    | Edit - ''    (L601, T543, R666, B566)
   |    | ['Edit3']
   |    | child_window(auto_id="328476", control_type="Edit")
   |
   | Button - 'Help'    (L796, T593, R871, B618)
   | ['Help', 'HelpButton', 'Button4']
   | child_window(title="Help", auto_id="394014", control_type="Button")
   |
   | Button - 'Cancel'    (L716, T593, R791, B618)
   | ['Cancel', 'Button5', 'CancelButton']
   | child_window(title="Cancel", auto_id="394016", control_type="Button")
   |
   | Button - 'OK'    (L636, T593, R711, B618)
   | ['Button6', 'OK', 'OKButton']
   | child_window(title="OK", auto_id="394030", control_type="Button")
   |
   | TreeView - ''    (L465, T214, R870, B432)
   | ['TreeView']
   | child_window(auto_id="262968", control_type="Tree")
   |
   | TitleBar - ''    (L473, T106, R879, B133)
   | ['TitleBar']
   |    |
   |    | Menu - 'System'    (L457, T111, R478, B132)
   |    | ['System', 'Menu', 'SystemMenu', 'System0', 'System1']
   |    | child_window(title="System", auto_id="MenuBar", control_type="MenuBar")
   |    |    |
   |    |    | MenuItem - 'System'    (L457, T111, R478, B132)
   |    |    | ['System2', 'MenuItem', 'SystemMenuItem']
   |    |    | child_window(title="System", control_type="MenuItem")
   |    |
   |    | Button - 'Close'    (L832, T104, R881, B124)
   |    | ['Button7', 'CloseButton', 'Close']
   |    | child_window(title="Close", control_type="Button")`

**Comment by marcoccio** [comment]
After some experimentation I made this: 

```
app = Application(backend="uia").start(r"C:\Users\Cega\Desktop\gitlab\pcanview-controller\source\PcanView.exe")
dlg = app.top_window()

time.sleep(1)

try:
    dlg.Connect.ComboBox1.draw_outline()

    dlg.Connect.ComboBox1.select(1)
except:
    print("")
try: 
    dlg.Connect.ComboBox3.draw_outline()

    dlg.Connect.ComboBox3.select(1)
except:
    print("")
```
This works because I'm basically encapsulating the exception to avoid halting my script. The behavior is even weirder than before:

[Test video](https://1drv.ms/v/s!AifPFXqjPaa5koUUWiwyVdc1D-YYMA?e=OABPxe)
