### ISSUE TITLE
Getting ValueError: NULL COM pointer access followed by _ctypes.COMError: -2147220991

### ISSUE THREAD

**Issue by amittendulkar** [pywinauto/pywinauto#1172]
Trying to automate a proprietary application and getting the `ValueError: NULL COM pointer access` while calling menu_select() with File->Open File. This is followed by `_ctypes.COMError: -2147220991` error.

I can see that the "Open File" dialog is opened. However the python interpreter gets hung and finally exception is raised.

Here is a code sample,
```
>>> from pywinauto.application import Application
>>> app = Application(backend='uia').start('software.exe')
>>> main_window = app.window(title_re='.*My App Title.*')
>>> main_window_actionable = main_window.wait('visible', timeout=30) 
>>> windows = main_window_actionable.children() 
>>> [print(w.window_text()) for w in windows] 

panelContainer1

Dock Bottom
Dock Top

[None, None, None, None, None, None]

>>> children = main_window_actionable.children()
>>> dock_top = None
>>> for child in children:
...     if child.window_text() == 'Dock Top':
...         dock_top = child
...         break
...

>>> dock_top
<uiawrapper.UIAWrapper - 'Dock Top', GroupBox, -5332403040449452796>
>>> dock_top.menu_select("File->OpenFile")
Traceback (most recent call last):
  File "D:\venv\personal\lib\site-packages\pywinauto\uia_defines.py", line 234, in get_elem_interface
    iface = cur_ptrn.QueryInterface(cls_name)
  File "D:\venv\personal\lib\site-packages\comtypes\__init__.py", line 1152, in QueryInterface
    self.__com_QueryInterface(byref(iid), byref(p))
ValueError: NULL COM pointer access

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\venv\personal\lib\site-packages\pywinauto\controls\uia_controls.py", line 949, in select
    self.iface_selection_item.Select()
  File "D:\venv\personal\lib\site-packages\pywinauto\controls\uiawrapper.py", line 132, in __get__
    value = self.fget(obj)
  File "D:\venv\personal\lib\site-packages\pywinauto\controls\uiawrapper.py", line 224, in iface_selection_item
    return uia_defs.get_elem_interface(elem, "SelectionItem")
  File "D:\venv\personal\lib\site-packages\pywinauto\uia_defines.py", line 236, in get_elem_interface
    raise NoPatternInterfaceError()
pywinauto.uia_defines.NoPatternInterfaceError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\venv\personal\lib\site-packages\pywinauto\controls\uiawrapper.py", line 723, in menu_select
    menu.item_by_path(path, exact).select()
  File "D:\venv\personal\lib\site-packages\pywinauto\controls\uia_controls.py", line 952, in select
    self.iface_invoke.Invoke()
_ctypes.COMError: (-2147220991, 'An event was unable to invoke any of the subscribers', (None, None, None, 0, None))       
```

I can see the open file dialog is opened successfully but the control is not returned.

## Specifications

  - Pywinauto version: 0.6.8
  - Python version and bitness: Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)] on win32
  - Platform and OS: Windows 10

**Comment by amittendulkar** [comment]
Additional info: If I click "Cancel" manually on the open file dialog box, the interpreter control returns immediately without any exception.

**Comment by kaigetrost** [comment]
Also getting same issue with this code:
```
import pywinauto, datetime, sys

appPath = r"app.exe"
mainWinRe = "menu regex"
buttonText = "Button Title"
subWinRe = r"Window Title"

print(f"Python version:    {sys.version}")
print(f"Pywinauto version: {pywinauto.__version__}")
print(f"{datetime.datetime.now()} Starting app")
app = pywinauto.application.Application(backend="uia").start(appPath)

mainWin = app.window(title_re=mainWinRe)
button = mainWin[buttonText]
print(f"{datetime.datetime.now()} Clicking button {button}")
button.click()

listDispWin = app.window(title_re=subWinRe)
print(f"{datetime.datetime.now()} Begin menu select on window {listDispWin}")
try:
    x = listDispWin.menu_select("File -> Open")
except Exception as e:
    print(f"{datetime.datetime.now()} Exception in menu_select")
    raise e
else:
    print(f"{datetime.datetime.now()} End menu_select")
```

Gives this:
```
Python version:    3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)]
Pywinauto version: 0.6.8
2023-11-12 14:17:28.085878 Starting app
2023-11-12 14:17:28.289923 Clicking button <pywinauto.application.WindowSpecification object at 0x00000263A5DF5F10>
2023-11-12 14:17:32.330806 Begin menu select on window <pywinauto.application.WindowSpecification object at 0x00000263A86AAF40>
2023-11-12 14:18:35.059771 Exception in menu_select
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\pywinauto\uia_defines.py", line 234, in get_elem_interface
    iface = cur_ptrn.QueryInterface(cls_name)
  File "C:\Anaconda3\lib\site-packages\comtypes\__init__.py", line 1152, in QueryInterface
    self.__com_QueryInterface(byref(iid), byref(p))
ValueError: NULL COM pointer access

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\pywinauto\controls\uia_controls.py", line 949, in select
    self.iface_selection_item.Select()
  File "C:\Anaconda3\lib\site-packages\pywinauto\controls\uiawrapper.py", line 132, in __get__
    value = self.fget(obj)
  File "C:\Anaconda3\lib\site-packages\pywinauto\controls\uiawrapper.py", line 224, in iface_selection_item
    return uia_defs.get_elem_interface(elem, "SelectionItem")
  File "C:\Anaconda3\lib\site-packages\pywinauto\uia_defines.py", line 236, in get_elem_interface
    raise NoPatternInterfaceError()
pywinauto.uia_defines.NoPatternInterfaceError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:/Downloads/foo.py", line 24, in <module>
    raise e
  File "e:/Downloads/foo.py", line 21, in <module>
    x = listDispWin.menu_select("File -> Open")
  File "C:\Anaconda3\lib\site-packages\pywinauto\controls\uiawrapper.py", line 723, in menu_select
    menu.item_by_path(path, exact).select()
  File "C:\Anaconda3\lib\site-packages\pywinauto\controls\uia_controls.py", line 952, in select
    self.iface_invoke.Invoke()
_ctypes.COMError: (-2147220991, 'An event was unable to invoke any of the subscribers', (None, None, None, 0, None))
```

The File -> Open dialog does appear.  If Cancelled manually, menu_select() returns (without exception).  This is Anaconda under Windows 10.

**Comment by meelad2** [comment]
Any solutions?
