### ISSUE TITLE
Repeat select a tab(twice) will cause an exception

### ISSUE THREAD

**Issue by saimadao** [pywinauto/pywinauto#1198]
## Expected Behavior
keep select the tab

## Actual Behavior
exception occurs

## Steps to Reproduce the Problem

  1. backend='uia'
  2. tabframe.select('tabPage1') # once
  3. tabframe.select('tabPage1') # twice
  4. excpetion display:
      Traceback (most recent call last):
        File "C:\Users\z003v11s\AppData\Roaming\Python\Python38\site-packages\pywinauto\uia_defines.py", line 234, in get_elem_interface
          iface = cur_ptrn.QueryInterface(cls_name)
        File "C:\Users\z003v11s\AppData\Roaming\Python\Python38\site-packages\comtypes\__init__.py", line 1198, in QueryInterface  
          self.__com_QueryInterface(byref(iid), byref(p))
      ValueError: NULL COM pointer access
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "d:/WorkSpace/winUIA/try_uia.py", line 262, in <module>
          tabframe.select('tabPage1')
        File "C:\Users\z003v11s\AppData\Roaming\Python\Python38\site-packages\pywinauto\controls\uia_controls.py", line 531, in select
          self._select(item)
        File "C:\Users\z003v11s\AppData\Roaming\Python\Python38\site-packages\pywinauto\controls\uiawrapper.py", line 676, in _select
          wrp.iface_selection_item.Select()
        File "C:\Users\z003v11s\AppData\Roaming\Python\Python38\site-packages\pywinauto\controls\uiawrapper.py", line 132, in __get__
          value = self.fget(obj)
        File "C:\Users\z003v11s\AppData\Roaming\Python\Python38\site-packages\pywinauto\controls\uiawrapper.py", line 224, in iface_selection_item
          return uia_defs.get_elem_interface(elem, "SelectionItem")
        File "C:\Users\z003v11s\AppData\Roaming\Python\Python38\site-packages\pywinauto\uia_defines.py", line 236, in get_elem_interface
          raise NoPatternInterfaceError()
      pywinauto.uia_defines.NoPatternInterfaceError
## Specifications

  - Pywinauto version: 0.6.8
  - Python version and bitness: python 3.8
  - Platform and OS: Windows, a C# Winform application

**Comment by junkmd** [comment]
I was considering a solution to this.

Adding `if not wrp.is_selected():` as a condition for `wrp.iface_selection_item.Select()` in `UIAWrapper._select` seemed like a solution. However, there's an problem with this approach.

The problem is that `is_selected()` assumes that `iface_selection_item` is available, which means that `uia_defs.get_elem_interface(elem, "SelectionItem")` does not raise an error.
If `NoPatternInterfaceError` is raised on the line where `wrp.iface_selection_item.Select()` is called, it's highly likely that calling `iface_selection_item.CurrentIsSelected()` would also result in an error.

Any opinions would be appreciated.
