### ISSUE TITLE
pywinauto is not a package

### ISSUE THREAD

**Issue by ghost** [pywinauto/pywinauto#1227]
## Expected Behavior
I'm trying to run a very basic script to launch notepad.exe

## Actual Behavior
When I run the script to launch notepad, it provides me with error `PS C:\Users\JamesIocco\hello> & C:/Users/JamesIocco/AppData/Local/Microsoft/WindowsApps/python3.7.exe c:/Users/JamesIocco/hello/pywinauto.py
Traceback (most recent call last):
  File "c:/Users/JamesIocco/hello/pywinauto.py", line 1, in <module>
    from pywinauto.application import Application
  File "c:\Users\JamesIocco\hello\pywinauto.py", line 1, in <module>
    from pywinauto.application import Application
ModuleNotFoundError: No module named 'pywinauto.application'; 'pywinauto' is not a package`

## Short Example of Code to Demonstrate the Problem
`from pywinauto.application import Application
app = Application().start("notepad.exe")`

## Specifications

  - Pywinauto version: idk how to find the version
  - Python version and bitness: python 3.7
  - Platform and OS: windows

**Comment by vasily-v-ryabov** [comment]
Script name is `pywinauto.py`. When you're importing module `pywinauto`, it tries to find it in current directory first and gets your script instead of the correct package.
