### ISSUE TITLE
pywinauto can't get items from MSFLexGrid

### ISSUE THREAD

**Issue by EduardoP777** [pywinauto/pywinauto#1242]
Hi
I've tried getting the info inside this table "MSFlexGrid" to copy paste in an excel
The win32 backend show the class and title in "print_control_identifiers) as:
MSFlexGrid - ''    (L193, T350, R1170, B703)
   | ['MSFlexGrid', 'Consulta LotesMSFlexGrid']
   | child_window(class_name="MSFlexGridWndClass")
I can use "click_input" on it
I followed and quick fix adding like a listview wrapper in my common_controls.py , with this class name: 
                                      friendlyclassname = "MSFlexGrid"
                                      windowclasses = [
                                          ".*MSFlexGrid.*",
                                          "MSFlexGridWndClass.*",
                                          ]
With this I'm supposed to be able to use the listview wrapper to get info from my "MSFlexGrid"
But the method : item_count, data, cols ...  all shows as output:    [] or 0  column,  0 items

I've read that it could happens because it's not an unicode app (i don't know if this refers to my python script running pywinauto or the ERP written in VC6 that I'm trying to get the data)
I'm stucked in this step!

I've changed to "uia" backend
it can detect the "MSFlexGrid"  control, just the "scrollbars" of the "Pane"
but if I use the command : ctrl3 = dlg4.child_window(class_name="MSFlexGridWndClass").click_input()
it can click inside the Grid as well

My ERP is in portuguese Brazil (PT_BR) language and I've faced other problems with this unicode characters
I've used the command   is_unicode  (similar to this) and it returns : False

I'm trying to get info inside this control!
I've searched a lot and  nothing worked!

![image](https://user-images.githubusercontent.com/110677949/189143248-2ccd6eda-3d0b-482a-ac41-06702b6f5cf6.png)

**Comment by vasily-v-ryabov** [comment]
Hi @EduardoP777 is it WinForms application? To check this, you can run Inspect.exe, switch it to "UI Automation" mode instead of "MSAA" and look for FrameworkId property.

Inspect.exe is part of Windows SDK.

**Comment by EduardoP777** [comment]
Hi Vasily thanks for your help
it's 
FrameworkId:	"Win32"
ClassName:	"MSFlexGridWndClass"

Inside  win32 backend using my_wrapper(it's a listview clone wrapper in common controls.py) I get item count, col count, data as 0, [ ] , empty, but it shows object handle.
Waiting for your feedback to proceed...

**Comment by vasily-v-ryabov** [comment]
Well, `backend="uia"` seems useless here. The only working way I could find is using DLL injection approach:
https://social.msdn.microsoft.com/Forums/en-US/e0406017-7473-4267-9702-94dd96430845/msflexgrid-uiautomation-c-api?forum=windowsaccessibilityandautomation

It is technically doable using module [pywinauto/injected](https://github.com/pywinauto/injected) which is not part of pywinauto currently. We plan to make it separate Python package with wheels on PyPI. But it will take unpredictable time.

**Comment by vasily-v-ryabov** [comment]
I see MSFlexGrid is a IDispatch COM component. And this code works for me:
```python
import win32com.client as com
grid = com.Dispatch("MSFlexGridLib.MSFlexGrid")
print(grid.hWnd) # prints 0
```
I would suggest to try `grid.hWnd = your_wrapper.handle` and play with other properties and methods of `grid` object. If it magically helps, it could be implemented as MSFlexGridWrapper for `backend="win32"` without any "uia" things.

**Comment by vasily-v-ryabov** [comment]
No, setting `grid.hWnd` seems wrong way. We need to figure out how to connect to existing instance of MSFlexGrid.
Something like `AtlAxGetDispatch(hContainer)` from here: https://cplusplus.com/forum/windows/46242/ but I couldn't quickly find a Python analogue of `AtlAxGetDispatch`, maybe `com.Dispatch(...)` additional params would be enough.

**Comment by vasily-v-ryabov** [comment]
It also depends if MSFlexGrid is implemented as in-proc or out-of-proc COM server on the application side. For the out-of-proc (out-of-process) server it should be easy to automate it from separate Python process like pywinauto script. Otherwise it may require DLL injection which is more complicated.

**Comment by vasily-v-ryabov** [comment]
I've tried the way similar to Excel.Application object: http://timgolden.me.uk/python/win32_how_do_i/attach-to-a-com-instance.html
But it fails:
```python
grid = com.GetObject(Class="MSFlexGridLib.MSFlexGrid")
Traceback (most recent call last):
  File "<interactive input>", line 1, in <module>
  File "C:\Python27\lib\site-packages\win32com\client\__init__.py", line 70, in GetObject
    return GetActiveObject(Class, clsctx)
  File "C:\Python27\lib\site-packages\win32com\client\__init__.py", line 79, in GetActiveObject
    dispatch = pythoncom.GetActiveObject(resultCLSID)
com_error: (-2147221021, 'Operation unavailable', None, None)
```
But maybe I don't have any instances of flex grid on my desktop. @EduardoP777 please try it on your side.

**Comment by MohammedEsamaldin** [comment]
is there any available solution for the issue ?

**Comment by MohammedEsamaldin** [comment]
hey @vasily-v-ryabov how I can reach to you, I have the same issue but I couldn't find a proper solution for it, and I have been searching for a solution for days without any hope.

**Comment by junkmd** [comment]
There are reports in https://github.com/pywinauto/pywinauto/issues/1293 https://github.com/pywinauto/pywinauto/issues/1170 https://github.com/pywinauto/pywinauto/issues/1030 about "cells" and "grids".
I think it is certainly more difficult for UIAutomation to manipulate such elements than others.

Have you read those reports?

**Comment by MohammedEsamaldin** [comment]
yes I have went through all the mentioned reports. However, there are no potential solution to be used. 

I am open to use alternative solutions
