### ISSUE TITLE
UWP apps can't be set as foreground because they "don't have an active window". Perhaps, they need a PID instead of the program executable to be found.

### ISSUE THREAD

**Issue by Illegal-Services** [pywinauto/pywinauto#1272]
## Expected Behavior
Set Minecraft UWP app ((Windows store app) on the foreground

## Actual Behavior
D:\Téléchargements>py test.py
Traceback (most recent call last):
  File "D:\Téléchargements\test.py", line 4, in <module>
    app.top_window().set_focus()
    ^^^^^^^^^^^^^^^^
  File "C:\Users\BUZZARD\AppData\Local\Programs\Python\Python311\Lib\site-packages\pywinauto\application.py", line 1156, in top_window
    raise RuntimeError("No windows for that process could be found")
RuntimeError: No windows for that process could be found

## Short Example of Code to Demonstrate the Problem
from pywinauto import application

app = application.Application().connect(process=14176)
app.top_window().set_focus()

## Specifications

  - Pywinauto version: pywinauto-0.6.8
  - Python version and bitness: Python 3.11.1
  - Platform and OS: Windows 10 (x64)

**Comment by Illegal-Services** [comment]
You don't necessarly need to reproduce the bug using Minecarft UWP, you can just use Calculator app or any other ones that are from the Windows Store or UWP in general.
