### ISSUE TITLE
This module of yours is very difficult to use, and it cannot be run by running a simple example on the official website. Please give the developers some help, otherwise don't do it

### ISSUE THREAD

**Issue by haisheng666** [pywinauto/pywinauto#1292]
from pywinauto.application import Application
app = Application(backend="win32").start('notepad.exe')
print(app.Properties.print_control_identifiers())
output：

Traceback (most recent call last):
  File "C:\Users\sheng\PycharmVenv\quantitative_transaction\lib\site-packages\pywinauto\application.py", line 248, in __resolve_control
    ctrl = wait_until_passes(
  File "C:\Users\sheng\PycharmVenv\quantitative_transaction\lib\site-packages\pywinauto\timings.py", line 458, in wait_until_passes
    raise err
pywinauto.timings.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sheng\PycharmProjects\quantitative_transaction\pywinauto_api\pa_2.py", line 20, in <module>
    print(app.Properties.print_control_identifiers())
  File "C:\Users\sheng\PycharmVenv\quantitative_transaction\lib\site-packages\pywinauto\application.py", line 585, in print_control_identifiers
    this_ctrl = self.__resolve_control(self.criteria)[-1]
  File "C:\Users\sheng\PycharmVenv\quantitative_transaction\lib\site-packages\pywinauto\application.py", line 259, in __resolve_control
    raise e.original_exception
  File "C:\Users\sheng\PycharmVenv\quantitative_transaction\lib\site-packages\pywinauto\timings.py", line 436, in wait_until_passes
    func_val = func(*args, **kwargs)
  File "C:\Users\sheng\PycharmVenv\quantitative_transaction\lib\site-packages\pywinauto\application.py", line 201, in __get_ctrl
    dialog = self.backend.generic_wrapper_class(findwindows.find_element(**criteria[0]))
  File "C:\Users\sheng\PycharmVenv\quantitative_transaction\lib\site-packages\pywinauto\findwindows.py", line 84, in find_element
    elements = find_elements(**kwargs)
  File "C:\Users\sheng\PycharmVenv\quantitative_transaction\lib\site-packages\pywinauto\findwindows.py", line 303, in find_elements
    elements = findbestmatch.find_best_control_matches(best_match, wrapped_elems)
  File "C:\Users\sheng\PycharmVenv\quantitative_transaction\lib\site-packages\pywinauto\findbestmatch.py", line 533, in find_best_control_matches
    raise MatchError(items = name_control_map.keys(), tofind = search_text)
pywinauto.findbestmatch.MatchError: Could not find 'Properties' in 'dict_keys(['Notepad', '无标题 - 记事本', '无标题 - 记事本Notepad'])'

**Comment by lukjak** [comment]
If you cannot determine the "problem" here, you really shouldn't dabble with programming.

**Comment by haisheng666** [comment]
I have successfully run the program through other methods, and have viewed various types of information, not your garbage sample code! Could you please update it locally? You can write several pages of bugs in this module, okay?

**Comment by haisheng666** [comment]
You should solve the 421 problem first, and then talk about other things

**Comment by CJ-Hadley** [comment]
https://www.youtube.com/watch?v=uTLsI2asox4

**Comment by vrnvorona** [comment]
> If you cannot determine the "problem" here, you really shouldn't dabble with programming.

While I don't agree with author, your approach (basically gatekeeping) doesn't really help. You weren't born genius to understand programming and how-to debug code from young age. There is never a place for comment like this in open source community.

**Comment by vasily-v-ryabov** [comment]
@haisheng666 First the code you've tried is not exactly the same as in README examples. It's a combination of codes from 2 different code samples. Copy-pasting any piece of code without understanding is not always a good idea.

Second the error message is pretty clear: `Could not find 'Properties' in 'dict_keys(['Notepad', '无标题 - 记事本', '无标题 - 记事本Notepad'])'` which means that the caption of main window is `'无标题 - 记事本', '无标题 - 记事本Notepad'` while you expect `"Properties"` or something similar to it. Of course, it's not equal to the real window title. Reading Python traceback **carefully** is not very hard skill. If you're new to Python, maybe it's worth learning some basic Python course.

Also the Getting Started Guide is among recommended links to read first. Maybe this guide is not the easiest guide in the world, but GUI automation is also not the easiest area to learn as timing issues are pretty common, for example. pywinauto provides many APIs for handling such issues, and we work on simplifying it during our free time.

All, please be more patient and calm. I'd prefer to see only technical and professional discussions.
