### ISSUE TITLE
ModuleNotFoundError: No module named 'win32process' (Linux)

### ISSUE THREAD

**Issue by tct123** [pywinauto/pywinauto#1301]
Hello,
I have some Problems with this code.
`from pywinauto.application import Application`
`app = Application()`
`app.start("APPNAME")`
I am using a Debian based Linux (64 Bit).
Here is my terminal output:
``Traceback (most recent call last):
  File "/home/anonym/windowswitcher/windowswitcher.py", line 1, in <module>
    from pywinauto.application import Application
  File "/home/anonym/.local/lib/python3.11/site-packages/pywinauto/application.py", line 76, in <module>
    import win32process
ModuleNotFoundError: No module named 'win32process'``

Is there any way to fix?

**Comment by junkmd** [comment]
[The version currently available for download from pypi](https://pypi.org/project/pywinauto/0.6.8/)([0.6.8](https://github.com/pywinauto/pywinauto/releases/tag/0.6.8)) does not support Linux.

There are plans for implementation as noted in #328.

**Comment by junkmd** [comment]
@tct123 

My previous comment was misleading. I apologize.

The `Application` is trying to find win32 dependencies because it has a default argument of 'win32', but your environment is Linux, which is causing the error.
Version `0.6.8` should work on Linux, but you need to import `clipboard` and `keyboard` from `pywinauto.linux` instead of using the `Application` class.

https://github.com/pywinauto/pywinauto/tree/0.6.8/pywinauto/linux

To use `Application(backend='atspi')`, you need to use the codebase from the `atspi` branch.

https://github.com/pywinauto/pywinauto/blob/bf7f789d01b7c66ccd0c213db0a029da7e588c9e/pywinauto/linux/application.py#L45-L54

**Comment by sasananas1** [comment]
I'm sorry, I can't figure out how to do this in practice. You can describe an example by completing which the connection to firefox will be made

**Comment by junkmd** [comment]
With the `atspi` branch codebase, you may be able to launch Firefox using the following code.

```py
from pywinauto.application import Application
app = Application(backend="atspi")
app.start("/your/env/firefox")
```

**Comment by sasananas1** [comment]
A similar problem has arisen. I found the solution on this branch https://github.com/pywinauto/pywinauto/issues/951
