### ISSUE TITLE
This library in windows11 is completely unable to use, many people around me have encountered this problem, it even simple cases can not run.

### ISSUE THREAD

**Issue by chenxurui19** [pywinauto/pywinauto#1305]
## Actual Behavior
<img width="1336" alt="截屏2023-06-11 00 21 15" src="https://github.com/pywinauto/pywinauto/assets/125239070/ed36e354-a2df-4377-acb1-f3657dae629f">
Traceback (most recent call last):
  File "C:\Users\chenxurui\PycharmProjects\pywinauto_project\venv\lib\site-packages\pywinauto\application.py", line 250, in __resolve_control
    ctrl = wait_until_passes(
  File "C:\Users\chenxurui\PycharmProjects\pywinauto_project\venv\lib\site-packages\pywinauto\timings.py", line 458, in wait_until_passes
    raise err
pywinauto.timings.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\chenxurui\PycharmProjects\pywinauto_project\pc_test10.py", line 9, in <module>
    window.print_control_identifiers()
  File "C:\Users\chenxurui\PycharmProjects\pywinauto_project\venv\lib\site-packages\pywinauto\application.py", line 613, in print_control_identifiers
    this_ctrl = self.__resolve_control(self.criteria)[-1]
  File "C:\Users\chenxurui\PycharmProjects\pywinauto_project\venv\lib\site-packages\pywinauto\application.py", line 261, in __resolve_control
    raise e.original_exception
  File "C:\Users\chenxurui\PycharmProjects\pywinauto_project\venv\lib\site-packages\pywinauto\timings.py", line 436, in wait_until_passes
    func_val = func(*args, **kwargs)
  File "C:\Users\chenxurui\PycharmProjects\pywinauto_project\venv\lib\site-packages\pywinauto\application.py", line 203, in __get_ctrl
    dialog = self.backend.generic_wrapper_class(findwindows.find_element(**criteria[0]))
  File "C:\Users\chenxurui\PycharmProjects\pywinauto_project\venv\lib\site-packages\pywinauto\findwindows.py", line 87, in find_element
    raise ElementNotFoundError(kwargs)
pywinauto.findwindows.ElementNotFoundError: {'title_re': '无标题 - Notepad', 'backend': 'uia', 'process': 9104}

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Short Example of Code to Demonstrate the Problem
import time
from pywinauto.application import Application

app = Application(backend="uia").start('notepad.exe')
time.sleep(5)
window = app.window(title_re='无标题 - Notepad')
window.print_control_identifiers()

## Specifications

  - Pywinauto version: 0.6.8
  - Python version and bitness: Python 3.9.13
  - Platform and OS: windows11

**Comment by chenxurui19** [comment]
Windows 10 is running normally, please see how to solve?

**Comment by junkmd** [comment]
I am not familiar with the specific library you are using, `..w Wizard 2.8.0`, but I believe it is something similar to the Inspect.exe tool that comes with the Windows SDK.

The displaying process ID(进程ID) is `2600`. On the other hand, the error you encountered:

> pywinauto.findwindows.ElementNotFoundError: {'title_re': '无标题 - Notepad', 'backend': 'uia', 'process': 9104}

I thought that the error occurred because it was trying to retrieve a window with a process ID of `9104` and couldn't find it.

You may need to retrieve root window object and pass different parameters to `root.children` or `root.descendants` to find the notepad window object in your Windows 11 env.

**Comment by chenxurui19** [comment]
> 我不熟悉您使用的工具，`..w Wizard 2.8.0`但我相信它类似于 Windows SDK 附带的 Inspect.exe 工具。
> 
> 显示的进程 ID(进程 ID) 是`2600`。另一方面，您遇到的错误：
> 
> > pywinauto.findwindows.ElementNotFoundError: {'title_re': '无标题 - 记事本', 'backend': 'uia', 'process': 9104}
> 
> 我认为错误发生是因为它试图检索进程 ID 为 的窗口，`9104`但找不到它。
> 
> 您可能需要检索根窗口对象并将不同的参数传递给`root.children`或`root.descendants`在 Windows 11 环境中查找记事本窗口对象。

This happens when you do any software gui automation in windows11, does it happen on your computer?

**Comment by junkmd** [comment]
I do not have Windows 11.

However, in the case of a software I use, I have noticed that the process ID of the `.exe` file that I run and the process ID of the window that comes up are the same in one version, but different in another version, in a Windows 10 environment.

I do not use `Application` for that software, but I search the window from the root window using `children` and `descendants` methods.

By removing the process ID from the window search criteria, I was able to automate GUI even if there are different versions of that software.

I think a similar workaround is needed.

**Comment by QuarTerll** [comment]
> I do not have Windows 11.
> 
> However, in the case of a software I use, I have noticed that the process ID of the `.exe` file that I run and the process ID of the window that comes up are the same in one version, but different in another version, in a Windows 10 environment.
> 
> I do not use `Application` for that software, but I search the window from the root window using `children` and `descendants` methods.
> 
> By removing the process ID from the window search criteria, I was able to automate GUI even if there are different versions of that software.
> 
> I think a similar workaround is needed.

don't understand.

Can you please provide some sample code you tested ? Or pseudocode

**Comment by QuarTerll** [comment]
@chenxurui19 What's up now? Same questions to u

**Comment by junkmd** [comment]
Please see also #1373
