### ISSUE TITLE
Win10_ Calculator.py, running this example code has reported an error, what kind of garbage

### ISSUE THREAD

**Issue by haisheng666** [pywinauto/pywinauto#1317]
## Actual Behavior
Traceback (most recent call last):
  File "C:\Users\sheng\PycharmVenv\quantitative_transaction\lib\site-packages\pywinauto\application.py", line 248, in __resolve_control
    ctrl = wait_until_passes(
  File "C:\Users\sheng\PycharmVenv\quantitative_transaction\lib\site-packages\pywinauto\timings.py", line 458, in wait_until_passes
    raise err
pywinauto.timings.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sheng\PycharmProjects\quantitative_transaction\pywinauto-master\examples\win10_calculator.py", line 21, in <module>
    dlg.type_keys('2*3=')
  File "C:\Users\sheng\PycharmVenv\quantitative_transaction\lib\site-packages\pywinauto\application.py", line 378, in __getattribute__
    ctrls = self.__resolve_control(self.criteria)
  File "C:\Users\sheng\PycharmVenv\quantitative_transaction\lib\site-packages\pywinauto\application.py", line 259, in __resolve_control
    raise e.original_exception
  File "C:\Users\sheng\PycharmVenv\quantitative_transaction\lib\site-packages\pywinauto\timings.py", line 436, in wait_until_passes
    func_val = func(*args, **kwargs)
  File "C:\Users\sheng\PycharmVenv\quantitative_transaction\lib\site-packages\pywinauto\application.py", line 201, in __get_ctrl
    dialog = self.backend.generic_wrapper_class(findwindows.find_element(**criteria[0]))
  File "C:\Users\sheng\PycharmVenv\quantitative_transaction\lib\site-packages\pywinauto\findwindows.py", line 84, in find_element
    elements = find_elements(**kwargs)
  File "C:\Users\sheng\PycharmVenv\quantitative_transaction\lib\site-packages\pywinauto\findwindows.py", line 303, in find_elements
    elements = findbestmatch.find_best_control_matches(best_match, wrapped_elems)
  File "C:\Users\sheng\PycharmVenv\quantitative_transaction\lib\site-packages\pywinauto\findbestmatch.py", line 533, in find_best_control_matches
    raise MatchError(items = name_control_map.keys(), tofind = search_text)
pywinauto.findbestmatch.MatchError: Could not find 'Calculator' in 'dict_keys(['Pane', '任务栏', '任务栏Pane', '计算器', 'Dialog', '计算器Dialog', 'quantitative_transaction – win10_calculator.pyDialog', 'Dialog0', 'Dialog1', 'Dialog2', 'quantitative_transaction – win10_calculator.py', 'C:\\Users\\sheng\\PycharmVenv\\quantitative_transaction\\Lib\\site-packages\\easytraderDialog', 'C:\\Users\\sheng\\PycharmVenv\\quantitative_transaction\\Lib\\site-packages\\easytrader', 'Dialog3', 'pywinauto官网_百度搜索 - 360极速浏览器 13.5', 'Dialog4', 'pywinauto官网_百度搜索 - 360极速浏览器 13.5Dialog', '', 'Pane0', 'Pane1', 'Pane2', 'D:\\Program Files\\JetBrains\\PyCharm 2022.2.3\\projects', 'D:\\Program Files\\JetBrains\\PyCharm 2022.2.3\\projectsDialog', 'Dialog5', 'Demo1_20210911.zip - 360压缩Dialog', 'Dialog6', 'Demo1_20210911.zip - 360压缩', 'hexin_UserEnumDialog', 'Dialog7', 'hexin_UserEnum', 'C:\\Users\\sheng\\Desktop\\金融', 'Dialog8', 'C:\\Users\\sheng\\Desktop\\金融Dialog', 'Pane3', '向日葵远程控制Pane', '向日葵远程控制', 'lhs-Jijia-U2204', 'Pane4', 'lhs-Jijia-U2204Pane', '网上股票交易系统5.0', 'Dialog9', '网上股票交易系统5.0Dialog', 'Pane5', '360DTFenceLite', '360DTFenceLitePane', '0', '1', '2', 'ListBox', 'Program ManagerPane', 'Pane6', 'Program Manager'])'

## Short Example of Code to Demonstrate the Problem

Win10_ Calculator.py, running this example code has reported an error, what kind of garbage

## Specifications

  - Pywinauto version:0.6.6
  - Python version and bitness:3.9
  - Platform and OS:windows

**Comment by johnyCZS** [comment]
Could you provide more information about the exact issue you are facing?

 I can see you are trying to run Win10_ Calculator.py but you get an error: Could not find 'Calculator' in 'dict_keys
You can see that there is an object quantitative_transaction – win10_calculator.py. From the limited information you gave I can only think of syntax error as it seems you have a " " between Win10_ and Calculator.py. Also the upper cases doesnt seem to appear in dict_keys
