### ISSUE TITLE
Regression in atspi branch causes call to Application.windows() to raise RuntimeError

### ISSUE THREAD

**Issue by logkirkland** [pywinauto/pywinauto#1338]
There seems to be a regression in the `atspi` branch which causes a call to `Application.windows()` to raise a `RuntimeError`. The example code works as expected on 0.6.8.

## Expected Behavior

`[<hwndwrapper.DialogWrapper - 'Untitled - Notepad', Notepad, 1050764>]`

## Actual Behavior

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\[redacted]\Downloads\venv\lib\site-packages\pywinauto\base_application.py", line 959, in windows
    windows = findwindows.find_elements(**kwargs)
  File "C:\Users\[redacted]\Downloads\venv\lib\site-packages\pywinauto\findwindows.py", line 155, in find_elements
    for key, value in kwargs.items():
RuntimeError: dictionary keys changed during iteration
```

## Steps to Reproduce the Problem

Run the example code in the specified environment.

## Short Example of Code to Demonstrate the Problem

```python
import pywinauto
app = pywinauto.Application(backend="win32").start(cmd_line=r"C:\WINDOWS\system32\notepad.exe")
print(app.windows(title_re=".*Notepad.*"))
```

## Specifications

  - Pywinauto version: `atspi@bf7f789`
  - Python version and bitness: Python 3.8.2, 32-bit
  - Platform and OS:
  
    Windows info:
64-bit version
Edition: Windows 10 Enterprise
Version: 22H2
OS build: 19045.3324
Experience: Windows Feature Experience Pack 1000.19041.1000.0

**Comment by junkmd** [comment]
This is similar to #1304.

I don't much use `Application` or `Desktop`, so I didn't notice that this could be a regression.
Good point.

Can you create a test in `.../pywinauto/unittests/test_application.py` that passes in `0.6.8` and fails in `atspi@bf7f789`?

If possible, it would be desirable to use a test GUI from `.../apps` instead of notepad.exe, as the names may change depending on the language of the execution environment.

**Comment by junkmd** [comment]
I plan to investigate this next week during weekdays and make any necessary changes to the production code or add test code if needed.

However, those who frequently use `Application` or `Desktop` might come up with more suitable use cases for testing.

Any opinions would be appreciated.

**Comment by junkmd** [comment]
This is not a situation where `Application.window` "became uncallable" or "lost the ability to take any keyword arguments". Rather, it should be viewed as a situation where "the acceptable keyword arguments have changed".

In #848, significant changes were made where `title_re` and `title` were replaced with `name_re` and `name`, and tests were also updated in 22ba132.

- For example...
  - `0.6.8` https://github.com/pywinauto/pywinauto/blob/ff95296e42c16beaf1f8b94252276cb664a4e47e/pywinauto/unittests/test_application.py#L641-L667
  - `atspi@bf7f789` https://github.com/pywinauto/pywinauto/blob/bf7f789d01b7c66ccd0c213db0a029da7e588c9e/pywinauto/unittests/test_application.py#L640-L666

@vasily-v-ryabov
Should we consider adding a workaround for developers who were previously using `title_re` or `title`?

**Comment by junkmd** [comment]
It might be necessary to have a warning message conveying that "argument names should be updated to the new ones" as well.

**Comment by junkmd** [comment]
I didn't notice it just by looking at `Application`, but while looking at the `findwindows` side, I think I found the possible cause of the problem.

There is an implementation in `find_windows` that swaps keywords based on `*ElementInfo.renamed_props`, but it seems to not be working correctly.

I'm considering making changes to the production code and adding tests, and if it seems to work well, I'll submit a PR.

**Comment by junkmd** [comment]
I'd also like to mention that backward compatibility was restored in #1253.

**Comment by logkirk** [comment]
@junkmd I appreciate all your work on this issue!
