### ISSUE TITLE
Tutorials but Not Work at All !

### ISSUE THREAD

**Issue by QuarTerll** [pywinauto/pywinauto#1373]
## Expected Behavior
print_control_identifiers
## Actual Behavior
``` cmd
PS E:\code> python E:\code\win-auto.py
Traceback (most recent call last):
  File "C:\Users\ZJ\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pywinauto\application.py", line 250, in __resolve_control
    ctrl = wait_until_passes(
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZJ\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pywinauto\timings.py", line 458, in wait_until_passes
    raise err
pywinauto.timings.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\code\win-auto.py", line 7, in <module>
    dlg_spec.print_control_identifiers()
  File "C:\Users\ZJ\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pywinauto\application.py", line 613, in print_control_identifiers
    this_ctrl = self.__resolve_control(self.criteria)[-1]
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZJ\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pywinauto\application.py", line 261, in __resolve_control
    raise e.original_exception
  File "C:\Users\ZJ\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pywinauto\timings.py", line 436, in wait_until_passes
    func_val = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZJ\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pywinauto\application.py", line 203, in __get_ctrl
    dialog = self.backend.generic_wrapper_class(findwindows.find_element(**criteria[0]))
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZJ\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pywinauto\findwindows.py", line 87, in find_element
    raise ElementNotFoundError(kwargs)
pywinauto.findwindows.ElementNotFoundError: {'best_match': '无标题 - 记事本', 'backend': 'uia', 'process': 26536}
```

## Steps to Reproduce the Problem
See code on next section

## Short Example of Code to Demonstrate the Problem
``` python3
from pywinauto.application import Application
import time
app = Application(backend="uia").start('notepad.exe')
# 查到这个记事本的控件树
time.sleep(5)
dlg_spec = app[u'无标题 - 记事本']
dlg_spec.print_control_identifiers()
```

## Specifications

  - Pywinauto version: 0.6.8
  - Python version and bitness: 3.12.1
  - Platform and OS: Microsoft Windows 11 家庭中文版

**Comment by QuarTerll** [comment]
![image](https://github.com/pywinauto/pywinauto/assets/49419815/41971ea9-cc02-45f7-9d1d-055b2dc5c393)

**Comment by QuarTerll** [comment]
@junkmd Can u help me

**Comment by junkmd** [comment]
Hi,

I don't have Windows 11, so please keep in mind that this is speculative.

It seems that the reason for the problem may be due to the Notepad GUI modifications made from Windows 11.
https://blogs.windows.com/windows-insider/2023/01/19/tabs-in-notepad-begins-rolling-out-to-windows-insiders/

From what I googled, there also appears to be a way to revert to the "classic version."
https://www.thewindowsclub.com/how-to-restore-the-classic-notepad-in-windows

For now, try changing your Notepad to the classic version in your environment and see if that works.

**Comment by juharris** [comment]
I just tried some stuff to manipulate Microsoft Teams in Windows 11 and it worked for me. You can see some examples in https://github.com/onhello-automation/otto/blob/py/python/experiments.ipynb

**Comment by junkmd** [comment]
@juharris 
Your information seems very helpful.
Pywinauto can work on Windows 11, but I suspect that the codebase that works on Windows 10 (such as examples in tutorials) may not work on Windows 11.

I suspect that the changes in functionality in the notepad application for Windows 11, as compared to Windows 10, may have changes in GUI components and accessibility.
Do you have any information about this?
