### ISSUE TITLE
could you give a example about windows 11, or pywinauto doesn't work with windows 11?

### ISSUE THREAD

**Issue by yllgl** [pywinauto/pywinauto#1375]
## Expected Behavior
run successfully

## Actual Behavior
```
Traceback (most recent call last):
  File "c:\Users\lgl\Desktop\tempCodeRunnerFile.python", line 23, in <module>
    common_files = app.ProgramFiles.ItemsView.get_item('Common Files')
  File "D:\Python38\lib\site-packages\pywinauto\controls\uia_controls.py", line 1344, in get_item
    raise RuntimeError(
RuntimeError: Only absolute paths allowed - please start the path with \
```

## Short Example of Code to Demonstrate the Problem
```python
from pywinauto import Desktop, Application

Application().start('explorer.exe "C:\\Program Files"')

# connect to another process spawned by explorer.exe
# Note: make sure the script is running as Administrator!
app = Application(backend="uia").connect(path="explorer.exe", title="Program Files")

app.ProgramFiles.set_focus()
common_files = app.ProgramFiles.ItemsView.get_item('Common Files')
common_files.right_click_input()
app.ContextMenu.Properties.invoke()

# this dialog is open in another process (Desktop object doesn't rely on any process id)
Properties = Desktop(backend='uia').Common_Files_Properties
Properties.print_control_identifiers()
Properties.Cancel.click()
Properties.wait_not('visible') # make sure the dialog is closed
```

## Specifications

  - Pywinauto version:0.6.8
  - Python version and bitness:3.8
  - Platform and OS:windows 11

**Comment by BadrinathMJ** [comment]
Hi @cassini1010 ,
Is pywinauto consitently work with all kinds of apps?
