### ISSUE TITLE
support for .appref-ms apps?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pywinauto/pywinauto#15]
```
What steps will reproduce the problem?
1. Attempt to start an app using start_ command, like 
app.start_('c:\foo\foo.appref-ms')

What is the expected output? What do you see instead?
app starts and app object references to Application's main window.

What version of the product are you using? On what operating system?
latest, on winXP

Please provide any additional information below.

command:

>>> app.start_ ('c:\Documents and 
Settings\navaoma\Desktop\Automation\Foo.appref-ms')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python25\lib\site-packages\pywinauto\application.py", line 876, in st
art_
    raise AppStartError(message)
pywinauto.application.AppStartError: Could not create the process "c:\Documents
and Settings
avaoma\Desktop\Automation\Foo.appref-ms"
Error returned by CreateProcess: [Error 2] The system cannot find the file speci
fied.
>>>


```

Original issue reported on code.google.com by `jomarnav...@gmail.com` on 26 Nov 2012 at 7:10

**Comment by Isaac-Pollack** [comment]
Is there any intention to implement this? I may be blind but no other library allows for an easy solution to this problem

**Comment by vasily-v-ryabov** [comment]
This is working code example to workaround it: https://stackoverflow.com/a/29799907/3648361
