### ISSUE TITLE
_iuia.GetRootElement() fails on Win8.1 somehow (it doesn't fail while _iuia just created)

### ISSUE THREAD

**Issue by vasily-v-ryabov** [pywinauto/pywinauto#158]
I faced with this strange behavior on my Win8.1 desktop using 64-bit Python 3.4. Just ran `test_UIAWrapper.py` and got bunch of errors like the following one:

```
Traceback (most recent call last):
  File ".\pywinauto\unittests\test_UIAWrapper.py", line 51, in setUp
    self.button = UIAWrapper(self.dlg.OK.element_info)
  File ".\pywinauto\application.py", line 323, in __getattribute__
    ctrls = self.__resolve_control(self.criteria)
  File ".\pywinauto\application.py", line 213, in __resolve_control
    criteria)
  File ".\pywinauto\timings.py", line 366, in WaitUntilPasses
    func_val = func(*args)
  File ".\pywinauto\application.py", line 162, in __get_ctrl
    dialog = self.backend.generic_wrapper_class(findwindows.find_element(**criteria[0]))
  File ".\pywinauto\findwindows.py", line 61, in find_element
    elements = find_elements(**kwargs)
  File ".\pywinauto\findwindows.py", line 141, in find_elements
    element = backend_obj.element_info_class()
  File ".\pywinauto\UIAElementInfo.py", line 132, in __init__
    self._element = _iuia.GetRootElement()
OSError: exception: access violation writing 0x00000000008B0000
```

Caching root element doesn't help as a workaround. I see the following error while building condition:

```
Traceback (most recent call last):
  File ".\pywinauto\unittests\test_UIAWrapper.py", line 51, in setUp
    self.button = UIAWrapper(self.dlg.OK.element_info)
  File ".\pywinauto\application.py", line 323, in __getattribute__
    ctrls = self.__resolve_control(self.criteria)
  File ".\pywinauto\application.py", line 213, in __resolve_control
    criteria)
  File ".\pywinauto\timings.py", line 366, in WaitUntilPasses
    func_val = func(*args)
  File ".\pywinauto\application.py", line 162, in __get_ctrl
    dialog = self.backend.generic_wrapper_class(findwindows.find_element(**criteria[0]))
  File ".\pywinauto\findwindows.py", line 61, in find_element
    elements = find_elements(**kwargs)
  File ".\pywinauto\findwindows.py", line 144, in find_elements
    title = title) # root.children == enum_windows()
  File ".\pywinauto\UIAElementInfo.py", line 210, in children
    cond = _build_condition(**kwargs)
  File ".\pywinauto\UIAElementInfo.py", line 96, in _build_condition
    _UIA_dll.UIA_ProcessIdPropertyId, process)
ctypes.ArgumentError: argument 2: <class 'OSError'>: exception: access violation writing 0x00000000005E0000
```

**Comment by vasily-v-ryabov** [comment]
[This example](http://stackoverflow.com/questions/15660778/net-uiautomation-simple-example-in-c) might be useful.

**Comment by vasily-v-ryabov** [comment]
After long debugging it looks like comtypes 1.1.1 bug. Everything works fine with comtypes 1.1.2.

**Comment by vasily-v-ryabov** [comment]
[Related issue](https://github.com/enthought/comtypes/issues/98) for comtypes. Still reproduced for comtypes 1.1.2 on Win8.1 x64.
