### ISSUE TITLE
Cannot get descendants() for the dialog (notepad.exe) + incorrect application menu name

### ISSUE THREAD

**Issue by vasily-v-ryabov** [pywinauto/pywinauto#173]
Running the following code:
```python
import pywinauto

app = pywinauto.Application(backend='uia').start(r'notepad.exe')
dlg = app.UntitledNotepad

dlg.WrapperObject().descendants()
```

Output:
```
>>> dlg.WrapperObject().descendants()
Traceback (most recent call last):
  File "<interactive input>", line 1, in <module>
  File "C:\OneDrive\python_students\pywinauto-64_github\pywinauto_fork\pywinauto\base_wrapper.py", line 384, in descendants
    desc_elements = self.element_info.descendants(proc_id=self.process_id())
  File "C:\OneDrive\python_students\pywinauto-64_github\pywinauto_fork\pywinauto\UIAElementInfo.py", line 250, in descendants
    cond = IUIA().build_condition(**kwargs)
TypeError: build_condition() got an unexpected keyword argument 'proc_id'
```

Also `dlg.MenuBar.WrapperObject().element_info.name` returns `"System"` instead of `"Application"`.

**Comment by vasily-v-ryabov** [comment]
BTW, `dlg.WrapperObject().children()[-1].element_info.name` returns `"Application"`.
