### ISSUE TITLE
Improve WindowSpecification.__call__ to handle calling method of the control for 3+ access levels

### ISSUE THREAD

**Issue by vasily-v-ryabov** [pywinauto/pywinauto#220]
These 2 code snippets must work the same way, but both are failing:
```python
>>> app.pywinauto.ItemsView.get_item('appveyor.yml')

Traceback (most recent call last):
  File "<interactive input>", line 1, in <module>
  File "C:\###\pywinauto\application.py", line 148, in __call__
    format(self.criteria[-1]['best_match']) )
AttributeError: WindowSpecification class has no 'get_item' method

>>> app.pywinauto.ItemsView.wrapper_object().get_item('appveyor.yml')

Traceback (most recent call last):
  File "<interactive input>", line 1, in <module>
AttributeError: 'UIAWrapper' object has no attribute 'get_item'

>>> app.pywinauto.ItemsView.wrapper_object()
<pywinauto.controls.uia_controls.ListViewWrapper object at 0x08BEE3F0>
```

**Comment by vasily-v-ryabov** [comment]
The issue happens when `explorer.exe` window is minimized. `app.pywinauto.print_control_identifiers(depth=7)` shows there are no `Items View` in the hierarchy. :)
