### ISSUE TITLE
ctypes.ArgumentError: argument 2: <type 'exceptions.TypeError'>: object of type 'Application' has no len()

### ISSUE THREAD

**Issue by nimuston** [pywinauto/pywinauto#254]
Hi, for some reason my script causes `ctypes.ArgumentError`. Do you have any idea what might be wrong here?

```
Traceback (most recent call last):
  File "test_case1.py", line 25, in <module>
    press_button('apptitle', '_buttonName_1')
  File "test_case1.py", line 23, in press_button
    button = window.child_window(auto_id=button).set_focus().type_keys("{ENTER}")
  File "build\bdist.win-amd64\egg\pywinauto\application.py", line 346, in __getattribute__
  File "build\bdist.win-amd64\egg\pywinauto\application.py", line 228, in __resolve_control
  File "build\bdist.win-amd64\egg\pywinauto\timings.py", line 405, in wait_until_passes
  File "build\bdist.win-amd64\egg\pywinauto\application.py", line 175, in __get_ctrl
  File "build\bdist.win-amd64\egg\pywinauto\findwindows.py", line 81, in find_element
  File "build\bdist.win-amd64\egg\pywinauto\findwindows.py", line 181, in find_elements
  File "build\bdist.win-amd64\egg\pywinauto\uia_element_info.py", line 247, in children
  File "build\bdist.win-amd64\egg\pywinauto\uia_defines.py", line 113, in build_condition
ctypes.ArgumentError: argument 2: <type 'exceptions.TypeError'>: object of type 'Application' has no len()
```

code below

```
def press_button(app_title, button):
    app = Application(backend='uia')
    connectapp = app.Connect(title=app_title)
    window = app.window_(title=app_title)
    button = window.child_window(auto_id=button).set_focus().type_keys("{ENTER}")

press_button('apptitle', '_buttonName_1')
```

also if i break this button variable into two lines i get different type of error, like this

```
button = window.child_window(auto_id=button).set_focus()
button.type_keys("{ENTER}")
```

```
Traceback (most recent call last):
  File "<pyshell#26>", line 1, in <module>
    button.type_keys("{ENTER}")
  File "build\bdist.win-amd64\egg\pywinauto\base_wrapper.py", line 811, in type_keys
    self.verify_actionable()
  File "build\bdist.win-amd64\egg\pywinauto\base_wrapper.py", line 557, in verify_actionable
    win32functions.WaitGuiThreadIdle(self)
  File "build\bdist.win-amd64\egg\pywinauto\win32functions.py", line 283, in WaitGuiThreadIdle
    GetWindowThreadProcessId(handle, ctypes.byref(process_id))
ArgumentError: argument 1: <type 'exceptions.OverflowError'>: long int too long to convert
```

**Comment by vasily-v-ryabov** [comment]
Hi @nimuston, thanks for reporting that. I've just fixed it in the fork. Will be included into the coming release.

**Comment by vasily-v-ryabov** [comment]
@nimuston please re-check for the updated master branch. The issue should gone.

**Comment by nimuston** [comment]
so far not able reproduce this error, I will close this issue tomorrow when I see the results from my tests

**Comment by nimuston** [comment]
Not able to reproduce this issue, i will close it. Thanks for the fix
