### ISSUE TITLE
Can't install pywinauto on Windows 10 64-bit

### ISSUE THREAD

**Issue by nxz91** [pywinauto/pywinauto#263]
I have been spending the past 2 hours trying to install pywinauto on a brand new Windows 10 installation. Tested with the following approaches:

- Python 2.7 + pip install pywinauto
- Python 3.5 + pip install pywinauto
- Python 2.7 + pip install pypiwinauto + python setup.py install (using the most recent commit on the UIA branch)
- Python 3.5 + pip install pypiwinauto + python setup.py install (using the most recent commit on the UIA branch)

pip install pywinauto / python setup.py install is failing with:

`C:\Users\Leonard\Desktop\pywinauto-UIA\pywinauto-UIA>pip install pywinauto
Collecting pywinauto
  Using cached pywinauto-0.6.0.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Leonard\AppData\Local\Temp\pip-build-mro11dft\pywinauto\setup.py", line 110, in <module>
        setup_requires=['setuptools-scm'],
      File "c:\users\leonard\appdata\local\programs\python\python35-32\lib\distutils\core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "c:\users\leonard\appdata\local\programs\python\python35-32\lib\site-packages\setuptools\dist.py", line 269, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "c:\users\leonard\appdata\local\programs\python\python35-32\lib\site-packages\setuptools\dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "c:\users\leonard\appdata\local\programs\python\python35-32\lib\site-packages\pkg_resources\__init__.py", line 826, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "c:\users\leonard\appdata\local\programs\python\python35-32\lib\site-packages\pkg_resources\__init__.py", line 1092, in best_match
        return self.obtain(req, installer)
      File "c:\users\leonard\appdata\local\programs\python\python35-32\lib\site-packages\pkg_resources\__init__.py", line 1104, in obtain
        return installer(requirement)
      File "c:\users\leonard\appdata\local\programs\python\python35-32\lib\site-packages\setuptools\dist.py", line 380, in fetch_build_egg
        return cmd.easy_install(req)
      File "c:\users\leonard\appdata\local\programs\python\python35-32\lib\site-packages\setuptools\command\easy_install.py", line 628, in easy_install
        not self.always_copy, self.local_index
      File "c:\users\leonard\appdata\local\programs\python\python35-32\lib\site-packages\setuptools\package_index.py", line 604, in fetch_distribution
        self.find_packages(requirement)
      File "c:\users\leonard\appdata\local\programs\python\python35-32\lib\site-packages\setuptools\package_index.py", line 441, in find_packages
        self.scan_url(self.index_url + requirement.unsafe_name+'/')
      File "c:\users\leonard\appdata\local\programs\python\python35-32\lib\site-packages\setuptools\package_index.py", line 775, in scan_url
        self.process_url(url, True)
      File "c:\users\leonard\appdata\local\programs\python\python35-32\lib\site-packages\setuptools\package_index.py", line 316, in process_url
        page = f.read()
      File "c:\users\leonard\appdata\local\programs\python\python35-32\lib\http\client.py", line 461, in read
        s = self._safe_read(self.length)
      File "c:\users\leonard\appdata\local\programs\python\python35-32\lib\http\client.py", line 607, in _safe_read
        chunk = self.fp.read(min(amt, MAXAMOUNT))
      File "c:\users\leonard\appdata\local\programs\python\python35-32\lib\socket.py", line 575, in readinto
        return self._sock.recv_into(b)
      File "c:\users\leonard\appdata\local\programs\python\python35-32\lib\ssl.py", line 929, in recv_into
        return self.read(nbytes, buffer)
      File "c:\users\leonard\appdata\local\programs\python\python35-32\lib\ssl.py", line 791, in read
        return self._sslobj.read(len, buffer)
      File "c:\users\leonard\appdata\local\programs\python\python35-32\lib\ssl.py", line 575, in read
        v = self._sslobj.read(len, buffer)
    ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Leonard\AppData\Local\Temp\pip-build-mro11dft\pywinauto\
You are using pip version 8.1.1, however version 9.0.0 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.`

Any ideas?

**Comment by vasily-v-ryabov** [comment]
Hi @nxz91, are you able to install other packages from PyPI?
Say `pip install -U comtypes`.

**Comment by nimuston** [comment]
@nxz91 it seems that you need to first install setuptools. Download .whl file and install it `pip install filename.whl`
[https://pypi.python.org/pypi/setuptools#downloads](https://pypi.python.org/pypi/setuptools#downloads)

**Comment by nxz91** [comment]
Hello @vasily-v-ryabov, yes, I am! Works like a charm...

Hello @nimuston, just tried that... Installed setuptools, then pip install pywinauto – same error. WinError 10054. :-/

**Comment by nxz91** [comment]
Or let me put the question differently: I am quite indifferent about the OS I have to use to be able to use pywinauto. Which one is most stable? 7/8/XP?

**Comment by nxz91** [comment]
Guys! I just resolved the problem! It was probably a problem with the firewall. (After switching to Windows 7), I manually installed the dependencies and everything works just fine now :-)
