### ISSUE TITLE
Unit test test_application.py did not pass on pywinauto-0.4.0 (Japanese Windows)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pywinauto/pywinauto#28]
```
What steps will reproduce the problem?
1. Set up (install Python 3.4, pywinauto-0.4.0 on Windows 7; fix source code to 
let the code be Python 3.4 compatible; set PYTHONPATH)
2. Browse to pywinauto-0.4.0\pywinauto\unittests
3. Run "python test_application.py"


What is the expected output? What do you see instead?

The unit tests passed.  However, the test didn't seem to let the application 
menu recognize menu selection, such as (MenuSelect("File->Exit")).  Below shows 
a part of the unit test log messages

======================================================================
ERROR: test__init__ (__main__.WindowSpecificationTestCases)
Test creating a new spec by hand
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_application.py", line 417, in tearDown
    self.app.UntitledNotepad.MenuSelect("File->Exit")
  File "C:\pywinauto-0.4.0\pywinauto\controls\HwndWrapper.py", line 1195, in MenuSelect
    self.MenuItem(path).Select()
  File "C:\pywinauto-0.4.0\pywinauto\controls\HwndWrapper.py", line 1145, in MenuItem
    return self.Menu().GetMenuPath(path, appdata = menu_appdata)[-1]
  File "C:\pywinauto-0.4.0\pywinauto\controls\menuwrapper.py", line 418, in GetMenuPath
    item_texts = [item.Text() for item in self.Items()]
  File "C:\pywinauto-0.4.0\pywinauto\controls\menuwrapper.py", line 418, in <listcomp>
    item_texts = [item.Text() for item in self.Items()]
  File "C:\pywinauto-0.4.0\pywinauto\controls\menuwrapper.py", line 138, in Text
    info = self._read_item()
  File "C:\pywinauto-0.4.0\pywinauto\controls\menuwrapper.py", line 90, in _read_item
    raise ctypes.WinError()
OSError: [WinError 87] パラメーターが間違っています。


What version of the product are you using? On what operating system?

pywinauto-0.4.0, Windows 7


Please provide any additional information below.

The OS was Japanese (64-bit) one, so part of the error messages contained 
Japanese characters.
```

Original issue reported on code.google.com by `chanpato...@gmail.com` on 23 May 2014 at 4:34

**Comment by junkmd** [comment]
I was investigating to see if there are any remaining issues, and I came across this issue.

This issue is one of the oldest and has not been updated for a long time.

this test failed because the names of menus differ depending on the language of the execution environment.
Even when running in my Japanese Windows environment with the current development branch(`atspi@bf7f789`), the same problem occurs.
The following is the result demonstrated in Python 3.10 interactive mode.

```py
>>> from pywinauto.application import Application
>>> app = Application().start("notepad.exe")
>>> app.UntitledNotepad.MenuSelect("File->Exit")
<stdin>:1: DeprecationWarning: Method .MenuSelect() is deprecated, use .menu_select() instead.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...\pywinauto\pywinauto\__init__.py", line 50, in wrap
    return method(*args, **kwargs)
  File "...\pywinauto\pywinauto\controls\hwndwrapper.py", line 1080, in menu_select
    self.menu_item(path, exact=exact).select()
  File "...\pywinauto\pywinauto\controls\hwndwrapper.py", line 1024, in menu_item
    return self.menu().get_menu_path(path, appdata = menu_appdata, exact=exact)[-1]
  File "...\pywinauto\pywinauto\controls\menuwrapper.py", line 108, in check
    return method(instance, *args, **kwargs)
  File "...\pywinauto\pywinauto\controls\menuwrapper.py", line 567, in get_menu_path
    best_item = findbestmatch.find_best_match(
  File "...\pywinauto\pywinauto\findbestmatch.py", line 133, in find_best_match
    raise MatchError(items = text_item_map.keys(), tofind = search_text)
pywinauto.findbestmatch.MatchError: Could not find 'File' in 'dict_keys(['ファイル(&F)', '編集(&E)', '書式(&O)', '表示(&V)', 'ヘルプ(&H)'])'
>>> app.UntitledNotepad.MenuSelect("ファイル->Exit") 
<stdin>:1: DeprecationWarning: Method .MenuSelect() is deprecated, use .menu_select() instead.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...\pywinauto\pywinauto\__init__.py", line 50, in wrap
    return method(*args, **kwargs)
  File "...\pywinauto\pywinauto\controls\hwndwrapper.py", line 1080, in menu_select
    self.menu_item(path, exact=exact).select()
  File "...\pywinauto\pywinauto\controls\hwndwrapper.py", line 1024, in menu_item
    return self.menu().get_menu_path(path, appdata = menu_appdata, exact=exact)[-1]
  File "...\pywinauto\pywinauto\controls\menuwrapper.py", line 108, in check
    return method(instance, *args, **kwargs)
  File "...\pywinauto\pywinauto\controls\menuwrapper.py", line 579, in get_menu_path
    best_item.sub_menu().get_menu_path(
  File "...\pywinauto\pywinauto\controls\menuwrapper.py", line 108, in check
    return method(instance, *args, **kwargs)
  File "...\pywinauto\pywinauto\controls\menuwrapper.py", line 567, in get_menu_path
    best_item = findbestmatch.find_best_match(
  File "...\pywinauto\pywinauto\findbestmatch.py", line 133, in find_best_match
    raise MatchError(items = text_item_map.keys(), tofind = search_text)
pywinauto.findbestmatch.MatchError: Could not find 'Exit' in 'dict_keys(['新規(&N)', '新しいウィンドウ(&W)', '開く(&O)...', '上書き保存(&S)', '名前を付けて保存(&A)...', '', 'ページ設定(&U)...', '印刷(&P)...', '0', '1', '2', 'メモ帳の終了
(&X)'])'
>>> app.UntitledNotepad.MenuSelect("ファイル->メモ帳の終了") 
<stdin>:1: DeprecationWarning: Method .MenuSelect() is deprecated, use .menu_select() instead.
```

If the script is expected to run in multiple language environments, it's necessary to create branching for each locale.

```py
>>> from pywinauto.application import Application
>>> import locale
>>> locale_name, _ = locale.getlocale()
>>> if locale_name == 'Japanese_Japan':
...     menu_path = "ファイル->メモ帳の終了"
... else:
...     menu_path = "File->Exit"
... 
>>> app = Application().start("notepad.exe")
>>> app.UntitledNotepad.MenuSelect(menu_path)                                               
<stdin>:1: DeprecationWarning: Method .MenuSelect() is deprecated, use .menu_select() instead.
```

The fact that the current tests are setting the execution environment's language is a known issue and has been escalated to the wiki documentation.
https://github.com/pywinauto/pywinauto/wiki/Contribution-Guide-(draft)#known-problems

Therefore, I will close this issue.

**Comment by junkmd** [comment]
see also https://github.com/pywinauto/pywinauto/discussions/1340
