### ISSUE TITLE
DebugMessage throws exception

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pywinauto/pywinauto#29]
```
What steps will reproduce the problem?
1. np = Application().start_("notepad.exe").Notepad
2. np.DebugMessage("Hello, world!") 

What is the expected output? What do you see instead?
Expected output: "Hello, world!" written over the window
Actual output:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\pywinauto\controls\HwndWrapper.py", line 9
83, in DebugMessage
    ctypes.byref(rect),
TypeError: byref() argument must be a ctypes instance, not 'instancemethod'

What version of the product are you using? On what operating system?
0.4.2, Windows Server 2008 R2

Please provide any additional information below.
I've tried this for a few different windows on a couple different machines.  
Results do not vary.

```

Original issue reported on code.google.com by `Will...@gmail.com` on 27 Jun 2014 at 3:10

**Comment by vasily-v-ryabov** [comment]
Fixed in 0.5.1.
