### ISSUE TITLE
UnicodeDecodeError on installation

### ISSUE THREAD

**Issue by chrono-meter** [pywinauto/pywinauto#324]
`setup.py install` gets the error:

```python
Traceback (most recent call last):
  File "setup.py", line 107, in <module>
    install_requires=install_requires,
  File "C:\Program Files (x86)\Python36-32\lib\distutils\core.py", line 121, in setup
    dist.parse_config_files()
  File "C:\Program Files (x86)\Python36-32\lib\distutils\dist.py", line 395, in parse_config_files
    parser.read(filename)
  File "C:\Program Files (x86)\Python36-32\lib\configparser.py", line 696, in read
    self._read(fp, filename)
  File "C:\Program Files (x86)\Python36-32\lib\configparser.py", line 1012, in _read
    for lineno, line in enumerate(fp, start=1):
UnicodeDecodeError: 'cp932' codec can't decode byte 0x98 in position 87: illegal multibyte sequence
```

This is caused by `setup.cfg`'s this line, LEFT SINGLE QUOTATION MARK is only in unicode characters:
```
    # E265: block comment should start with ‘# ‘...
```

Fix example:
```
    # E265: block comment should start with '# '...
````

**Comment by vasily-v-ryabov** [comment]
Thanks! Should be fixed on PyPI. Can you re-check please?

**Comment by chrono-meter** [comment]
It's OK. Thank you.
```
C:\>py -m pip install --upgrade pywinauto
Collecting pywinauto
  Downloading pywinauto-0.6.2-1.zip (505kB)
    100% |████████████████████████████████| 512kB 728kB/s
Requirement already up-to-date: six in c:\program files (x86)\python36-32\lib\site-packages (from pywinauto)
Collecting comtypes (from pywinauto)
  Using cached comtypes-1.1.3-2.zip
Installing collected packages: comtypes, pywinauto
  Found existing installation: comtypes 1.1.3
    Uninstalling comtypes-1.1.3:
      Successfully uninstalled comtypes-1.1.3
  Running setup.py install for comtypes ... done
  Running setup.py install for pywinauto ... done
Successfully installed comtypes-1.1.3 pywinauto-0.6.2
```
