### ISSUE TITLE
TypeError in ctypes\__init__.py

### ISSUE THREAD

**Issue by jduncan8142** [pywinauto/pywinauto#346]
when doing import for pywinauto as - `from pywinauto.application import Application` is get the below. This is on Windows 7 64 bit system. I am able to get this to load on a fresh system but I'm not sure what is making the difference.  
```python
Traceback (most recent call last):
  File "C:/Users/jmduncan/PythonCode/PureFishing/helpers/PtlPicking.py", line 79, in <module>
    from pywinauto.application import Application
  File "C:\Python271232\lib\site-packages\pywinauto\__init__.py", line 40, in <module>
    from . import findwindows
  File "C:\Python271232\lib\site-packages\pywinauto\findwindows.py", line 39, in <module>
    from . import win32functions
  File "C:\Python271232\lib\site-packages\pywinauto\win32functions.py", line 36, in <module>
    from .actionlogger import ActionLogger
  File "C:\Python271232\lib\site-packages\pywinauto\actionlogger.py", line 35, in <module>
    import logger
  File "C:\Python27\logger.py", line 1, in <module>
    import keylogger
  File "C:\Python27\keylogger.py", line 37, in <module>
    x11 = ct.cdll.LoadLibrary(find_library("X11"))
  File "C:\Python27\Lib\ctypes\__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python27\Lib\ctypes\__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
TypeError: expected string or Unicode object, NoneType found
```

**Comment by vasily-v-ryabov** [comment]
As I can see in the traceback, some 3rd party module mixed the code from different Python installations (`C:\Python271232` and `C:\Python27`). Or you have your own module named `logger.py` which re-defines built-in Python module `logger`. This re-definition could happen if you were modified `sys.path` in your Python scripts or `PATH` variable in Windows environment.

Can you re-check your `PATH` variable and make sure you don't have 2 Pythons here?

**Comment by jduncan8142** [comment]
Resolved - I did have multiple version listed in PATH. That is corrected and also had logger.py in C:\Python27 directly which was finding first before the pywinauto version. Renaming my logger.py fixed. Thanks for the help.
