### ISSUE TITLE
Sub menu query fails: [Error 299] Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

### ISSUE THREAD

**Issue by Ruin0x11** [pywinauto/pywinauto#351]
When I try accessing items from a submenu, the query fails. I've tried the following on both 32-bit and 64-bit Python versions.

```python
import time 
from pywinauto.application import Application

app = Application().connect(path="rpg2000.exe")
menu= app.TFormLcfMain.menu_item("Project")
time.sleep(1)
smenu = menu.sub_menu()
time.sleep(1)
print(smenu.items())

```

```
Traceback (most recent call last):
  File "rpg.py", line 14, in <module>
    print(smenu.items())
  File "C:\Program Files\Python36\lib\site-packages\pywinauto\controls\menuwrapper.py", line 366, in __repr__
    return "<MenuItem " + self.text() + ">"
  File "C:\Program Files\Python36\lib\site-packages\pywinauto\controls\menuwrapper.py", line 223, in text
    mem.Read(s, address)
  File "C:\Program Files\Python36\lib\site-packages\pywinauto\remote_memory_block.py", line 263, in Read
    raise ctypes.WinError()
OSError: [WinError 299] Only part of a ReadProcessMemory or WriteProcessMemory request was completed.
> python
Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)] on win32
```

**Comment by vasily-v-ryabov** [comment]
Hmm... Probably this menu can't be automated using Win32 API.
Did you try `Application(backend='uia')`? MS UI Automation should be more reliable for such a menu.
