### ISSUE TITLE
Cannot run pywinauto

### ISSUE THREAD

**Issue by grego1981** [pywinauto/pywinauto#356]
Hello I've installed pywinauto through pip but when I run `from pywinauto.application import Application`
I get the following error, how can I fix it?
```python
Traceback (most recent call last):
  File "<pyshell#7>", line 1, in <module>
    from pywinauto.application import Application
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\pywinauto\__init__.py", line 40, in <module>
    from . import findwindows
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\pywinauto\findwindows.py", line 42, in <module>
    from . import controls
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\pywinauto\controls\__init__.py", line 36, in <module>
    from . import uiawrapper # register "uia" back-end (at the end of uiawrapper module)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\pywinauto\controls\uiawrapper.py", line 40, in <module>
    from .. import backend
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\pywinauto\backend.py", line 35, in <module>
    from .base_wrapper import BaseWrapper
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\pywinauto\base_wrapper.py", line 41, in <module>
    import win32process
ModuleNotFoundError: No module named 'win32process'
```

**Comment by vasily-v-ryabov** [comment]
Hi @grego1981, it seems pyWin32 package was installed incorrectly. You can try to re-install it by `pip install -U pypiwin32` or install it manually [from here](https://sourceforge.net/projects/pywin32/files/pywin32/).

**Comment by vasily-v-ryabov** [comment]
This is not a pywinauto problem. Closing since no reply for a long time.
