### ISSUE TITLE
NoPatternInterfaceError when setting option in ComboBox

### ISSUE THREAD

**Issue by ripdog** [pywinauto/pywinauto#363]
Hello,

I have a login form for an ancient Visual Foxpro app which I am trying to automate. Here are the relevant field definitions for the username and password entry:

      | ComboBox - 'cboCuoption'    (L707, T439, R767, B460)
      | ['cboCuoptionComboBox', 'ComboBox', 'cboCuoption']
      | child_window(title="cboCuoption", control_type="ComboBox")
      | 
      | Edit - 'txtCpassword'    (L707, T469, R791, B490)
      | ['2', 'Edit']
      | child_window(title="txtCpassword", control_type="Edit")

And here's my code: 

````python
mainwindow = app.window(title_re="AppTitle.*")
loginwindow = mainwindow.child_window(title="Login", class_name="app9c000000")
loginwindow.cboCuoption.select(89) #same result with the text equivalent of this
````

In return, I get:

````
pywinauto.uia_defines.NoPatternInterfaceError
````

Trying to look up 'ExpandCollapse', Is this related to the downarrow button beside the form which opens the list?

If you need any more info, I'd be happy to email/pm you details, I just don't want anything specific in public. Thank you very much!

**Comment by airelil** [comment]
We have a fix for UIA combo box recently. See #361, you can give it a try if you want. Frankly, I'm not sure that even with this fix it will work. Seems that you are trying to select a user name from a list, but it fails because this action can't be accomplished through UI automation interface. If the list can't be expanded the script won't be able to select an item from the list. Did you try to work with another "win32" backend ?

**Comment by airelil** [comment]
@ripdog, any updates on the issue ?

**Comment by ripdog** [comment]
Hi, really sorry for the slowness replying. I tried with the latest master and the error was the same. I did notice a second traceback which I haven't posted here:

````
Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pywinauto\uia_defines.py", line 217, in get_elem_interface
    iface = cur_ptrn.QueryInterface(cls_name)
  File "C:\Users\username\AppData\Local\Programs\Python\Python36-32\lib\site-packages\comtypes\__init__.py", line 1156, in QueryInterface
    self.__com_QueryInterface(byref(iid), byref(p))
ValueError: NULL COM pointer access
````

Which sounds to my uneducated ears like it just can't access the list item. I wonder why it appears in the print_control_identifiers() output but can't subsequently be accessed?

I'm not really surprised that this app does weird shit. It's a 20 year old proprietary foxpro app, after all. 

Oh, I did try the win32 backend, and it couldn't see anything inside the login window at all.

**Comment by vasily-v-ryabov** [comment]
Sometimes even not so ancient apps don't properly support action patterns. The very recent example is iTunes. So I can suggest you similar workaround for combo box:
```python
loginwindow.cboCuoption.type_keys('{HOME}{DOWN 89}{ENTER}')
```
See [original iTunes workaround](https://github.com/pywinauto/pywinauto/issues/307#issuecomment-302533404).

**Comment by vasily-v-ryabov** [comment]
I'd suggest to have no `iface_*` attributes and related methods if the patterns are not actually supported. Still thinking how to implement it better.

**Comment by coolalexhuang** [comment]
@vasily-v-ryabov I have got the same problem, any long term solution for this "pywinauto.uia_defines.NoPatternInterfaceError" issue?

**Comment by vasily-v-ryabov** [comment]
If there is no pattern supported, it's nothing to do on pywinauto side. Maybe some workarounds like creating "win32" ComboBoxWrapper if the control has native handle. This may work for ancient software. Otherwise it's an app side problem not implementing pattern support.

So I keep this thread open to think about workarounds for some cases, not for all.

**Comment by bkk003** [comment]
[app = pywinauto.Application(backend="uia")
    app.connect(path="C:\Tecnai\Exe\Service\PPHSControl.exe")
    app.window_(title=u'PPHSControl', visible_only=False).restore()
    window = app.window_(title=u'PPHSControl')
    # window.print_control_identifiers()
    radioButton = window.child_window(auto_id="powerModeRadioButton", control_type="RadioButton")
    radioButton.get_toggle_state()](url)


Traceback (most recent call last):
  File "C:/Projects/TestAutomation/TBricks/Interface/UI/TBrickUIApp.py", line 119, in <module>
    radioButton.get_toggle_state()
  File "C:\Python27\lib\site-packages\pywinauto\controls\uia_controls.py", line 106, in get_toggle_state
    return self.iface_toggle.CurrentToggleState
  File "C:\Python27\lib\site-packages\pywinauto\controls\uiawrapper.py", line 131, in __get__
    value = self.fget(obj)
  File "C:\Python27\lib\site-packages\pywinauto\controls\uiawrapper.py", line 237, in iface_toggle
    return uia_defs.get_elem_interface(elem, "Toggle")
  File "C:\Python27\lib\site-packages\pywinauto\uia_defines.py", line 234, in get_elem_interface
    raise NoPatternInterfaceError()
pywinauto.uia_defines.NoPatternInterfaceError

I am getting similar "pywinauto.uia_defines.NoPatternInterfaceError"
would it be same open issue or is it something wrong i am doing :(

**Comment by vasily-v-ryabov** [comment]
Hi @bkk003 could you please provide `Inspect.exe` screenshot with all properties for this radio button?
