### ISSUE TITLE
Error when trying to select a ListBox item

### ISSUE THREAD

**Issue by mwsluis** [pywinauto/pywinauto#365]
I'm having an issue with something simple which I'm pulling my hair out over. I'm simply trying to select the item '(All Round) Runtime' in a ListBox:
```
inq_automation_handle = Application(backend='uia').start('my.exe'))
dlg_license = inq_automation_handle.LicenseProfiles
dlg_license.wait('ready')
license_name = '(All Round) Runtime'
dlg_license.TopPanel.ListBox[license_name].select()
```
```
Traceback (most recent call last):
  File "test.py", line 33, in <module>
    dlg_license.TopPanel.ListBox[license_name].select()
  File "build\bdist.win32\egg\pywinauto\application.py", line 310, in __getitem__
AttributeError: The control does not have a __getitem__ method for item access (i.e. ctrl[key]) so maybe you have requested this in error?
```

This however, works perfectly:
`dlg_license.TopPanel.ListBox.AllRoundRuntime.select()`
But I need the license name to be variable. What am I doing wrong?
Here is the output of dlg_license.TopPanel.print_control_identifiers():

```
Pane - 'TopPanel'    (L664, T382, R1255, B606)
[u'TopPanel', 'Pane', u'TopPanelPane']
child_window(title="TopPanel", auto_id="985044", control_type="Pane")
   | 
   | ListBox - ''    (L672, T390, R1135, B606)
   | [u'', u'1', u'0', u'ListBox']
   | child_window(auto_id="985032", control_type="List")
   |    | 
   |    | Header - ''    (L674, T392, R1133, B409)
   |    | [u'2', 'Header']
   |    | child_window(auto_id="Header", control_type="Header")
   |    |    | 
   |    |    | HeaderItem - 'Name'    (L674, T392, R774, B409)
   |    |    | [u'NameHeaderItem', u'Name', u'HeaderItem1', u'HeaderItem0', 'HeaderItem']
   |    |    | child_window(title="Name", control_type="HeaderItem")
   |    |    | 
   |    |    | HeaderItem - 'Status'    (L774, T392, R874, B409)
   |    |    | [u'Status', u'StatusHeaderItem', 'HeaderItem2']
   |    |    | child_window(title="Status", control_type="HeaderItem")
   |    |    | 
   |    |    | HeaderItem - 'Source'    (L874, T392, R1133, B409)
   |    |    | [u'Source', 'HeaderItem3', u'SourceHeaderItem']
   |    |    | child_window(title="Source", control_type="HeaderItem")
   |    | 
   |    | ListItem - '(All Round) Development'    (L674, T411, R1133, B425)
   |    | [u'ListItem0', u'(All Round) DevelopmentListItem', u'(All Round) Development', u'ListItem', u'ListItem1']
   |    | child_window(title="(All Round) Development", control_type="ListItem")
   |    | 
   |    | ListItem - '(All Round) Runtime'    (L674, T425, R1133, B439)
   |    | [u'ListItem2', u'(All Round) Runtime', u'(All Round) RuntimeListItem']
   |    | child_window(title="(All Round) Runtime", control_type="ListItem")
[...]
```

**Comment by vasily-v-ryabov** [comment]
The following statement should work:
```python
dlg_license.TopPanel.ListBox.child_window(title=license_name, control_type="ListItem").select()
```
We'll take a look for item access a bit later. Thanks for reporting it.

**Comment by mwsluis** [comment]
Indeed it does! Thanks for the quick response.

**Comment by longk15t** [comment]
Hi @vasily-v-ryabov , how can I select a hidden ListItem ? That item is on the list but not visible, I see it is listed on print_control_identifiers() but I cannot select() or click() or click_input() it. It throws ElementNotFoundError

`ElementNotFoundError: {'control_type': 'ListItem', 'title': u'Cooper', 'top_level_only': False, 'parent': <uia_element_info.UIAElementInfo - 'Font', #32770, 1640126>, 'backend': u'uia'}`

**Comment by longk15t** [comment]
Nvm, I found you suggested to use `visible_only=False` on another issue. Thanks

**Comment by vasily-v-ryabov** [comment]
Fixed in master branch.

**Comment by virt12** [comment]
Hello,
How select item from this?
![image](https://user-images.githubusercontent.com/34688963/167099829-17530b96-6cad-42fb-b011-e6917ea69a5d.png)

I can't select item.
Code here: https://github.com/pywinauto/pywinauto/discussions/1209.

**Comment by vijay2249** [comment]
@longk15t can you mention the issue number in here

**Comment by vijay2249** [comment]
@virt12 
Have you checked whether the items you showed are list items or not?
