### ISSUE TITLE
ValueError: NULL COM pointer access

### ISSUE THREAD

**Issue by nimuston** [pywinauto/pywinauto#379]
Hi,

I got this NULL com pointer access error message, it is really strange because it happens so randomly. Button i'm trying to press is visible and should have access to it, but still my script fails, any ideas? Anyone else noticed this kind of behavior?

```
Traceback (most recent call last):
  File "C:\temp\Test.py", line 803, in press_button
    if button.exists(timeout=5):
  File "build\bdist.win-amd64\egg\pywinauto\application.py", line 397, in exists
    self.__resolve_control(exists_criteria, timeout, retry_interval)
  File "build\bdist.win-amd64\egg\pywinauto\application.py", line 244, in __resolve_control
    criteria)
  File "build\bdist.win-amd64\egg\pywinauto\timings.py", line 402, in wait_until_passes
    func_val = func(*args)
  File "build\bdist.win-amd64\egg\pywinauto\application.py", line 208, in __get_ctrl
    ctrl = self.backend.generic_wrapper_class(findwindows.find_element(**ctrl_criteria))
  File "build\bdist.win-amd64\egg\pywinauto\findwindows.py", line 84, in find_element
    elements = find_elements(**kwargs)
  File "build\bdist.win-amd64\egg\pywinauto\findwindows.py", line 214, in find_elements
    depth=depth)
  File "build\bdist.win-amd64\egg\pywinauto\uia_element_info.py", line 277, in descendants
    elements = self._get_elements(IUIA().tree_scope["descendants"], cond, cache_enable)
  File "build\bdist.win-amd64\egg\pywinauto\uia_element_info.py", line 256, in _get_elements
    return elements_from_uia_array(ptrs_array, cache_enable)
  File "build\bdist.win-amd64\egg\pywinauto\uia_element_info.py", line 47, in elements_from_uia_array
    return [UIAElementInfo(ptrs.GetElement(n), cache_enable) for n in range(ptrs.Length)]
```

**Comment by airelil** [comment]
Probably we could just ignore wile building the array of elements

**Comment by vasily-v-ryabov** [comment]
Should be fixed in master branch now. Could you please also check on your side? I'm planning to publish 0.6.3 tomorrow. Not sure you will have time to re-check it since it's sporadic. Just want to know if it's `ValueError` or `COMError`? I assume it's `COMError`.

**Comment by nimuston** [comment]
@vasily-v-ryabov i ran my tests few times and i did not get any errors, it seems that your fix fixed the problem, thanks

**Comment by maggu2810** [comment]
Hm, I don't think it is closed completely.
0.6.3 uses `COMError` but I get a `ValueError`

See:

```text
Error
Traceback (most recent call last):
  File "C:\Python27\Lib\unittest\case.py", line 320, in run
    self.setUp()
  File "C:\Users\markus\my-project\test\test_bar.py", line 12, in setUp
    self._project = self._foo.open_project(os.path.join(self.RES_DIR, "projects", "TestProject.foo"))
  File "C:\Users\markus\my-project\src\test\foo.py", line 38, in open_project
    return self._internal.open_project(path_to_project)
  File "C:\Users\markus\my-project\src\test\internal\foo.py", line 87, in open_project
    my_open_dialog.wait_not("exists")
  File "C:\Users\markus\my-project\venv\lib\site-packages\pywinauto\application.py", line 538, in wait_not
    lambda: not self.__check_all_conditions(check_method_names, retry_interval))
  File "C:\Users\markus\my-project\venv\lib\site-packages\pywinauto\timings.py", line 349, in wait_until
    func_val = func(*args)
  File "C:\Users\markus\my-project\venv\lib\site-packages\pywinauto\application.py", line 538, in <lambda>
    lambda: not self.__check_all_conditions(check_method_names, retry_interval))
  File "C:\Users\markus\my-project\venv\lib\site-packages\pywinauto\application.py", line 447, in __check_all_conditions
    if not check(retry_interval, float(retry_interval) // 2):
  File "C:\Users\markus\my-project\venv\lib\site-packages\pywinauto\application.py", line 398, in exists
    self.__resolve_control(exists_criteria, timeout, retry_interval)
  File "C:\Users\markus\my-project\venv\lib\site-packages\pywinauto\application.py", line 245, in __resolve_control
    criteria)
  File "C:\Users\markus\my-project\venv\lib\site-packages\pywinauto\timings.py", line 425, in wait_until_passes
    func_val = func(*args)
  File "C:\Users\markus\my-project\venv\lib\site-packages\pywinauto\application.py", line 209, in __get_ctrl
    ctrl = self.backend.generic_wrapper_class(findwindows.find_element(**ctrl_criteria))
  File "C:\Users\markus\my-project\venv\lib\site-packages\pywinauto\findwindows.py", line 84, in find_element
    elements = find_elements(**kwargs)
  File "C:\Users\markus\my-project\venv\lib\site-packages\pywinauto\findwindows.py", line 214, in find_elements
    depth=depth)
  File "C:\Users\markus\my-project\venv\lib\site-packages\pywinauto\uia_element_info.py", line 283, in descendants
    elements = self._get_elements(IUIA().tree_scope["descendants"], cond, cache_enable)
  File "C:\Users\markus\my-project\venv\lib\site-packages\pywinauto\uia_element_info.py", line 262, in _get_elements
    return elements_from_uia_array(ptrs_array, cache_enable)
  File "C:\Users\markus\my-project\venv\lib\site-packages\pywinauto\uia_element_info.py", line 48, in elements_from_uia_array
    for n in range(ptrs.Length):
ValueError: NULL COM pointer access
```

**Comment by vasily-v-ryabov** [comment]
Hi @maggu2810 It's already fixed in master branch. Just had no chance to post 0.6.4 release because I was very busy last 2 months. Hope to post it soon.

**Comment by maggu2810** [comment]
> Hope to post it soon.

Would be great, as my tests are not working with an official pip installed pywinauto caused by this exception.

**Comment by vasily-v-ryabov** [comment]
This is not fully fixed in 0.6.3, exactly for `ptrs.Length` access.

**Comment by maggu2810** [comment]
You are right, I received this error because of `ptrs.Length`.
Do you know why a `ValueError` is raised by this error at all?

I tried to repeat

```python
ptrs_array = self._element.FindAll(tree_scope, cond)
return elements_from_uia_array(ptrs_array, cache_enable)
```

as long as there `ptrs.Length` does not raise any error, but it never succeeded.

**Comment by vasily-v-ryabov** [comment]
This might happen when `AutomationElement` doesn't exist any more. In this case we have to re-walk the elements hierarchy from the very top. pywinauto==0.6.4 handles this automatically because we added the exception handler in the right place. :)
