### ISSUE TITLE
Issue when using pywinauto and cxfreeze

### ISSUE THREAD

**Issue by seancallahan88** [pywinauto/pywinauto#38]
Hi,

I'm trying to make my pywinauto script into an .exe. I recieved this error even though "pywinauto.tests.allcontrols" is included in my setup.py packages.

    Traceback (most recent call last):
      File "C:\WinPython-64bit-3.4.2.3\python-3.4.2.amd64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
        exec(code, m.__dict__)
      File "backup.py", line 2, in <module>
      File "X:\Python34\lib\importlib\_bootstrap.py", line 2237, in _find_and_load
      File "X:\Python34\lib\importlib\_bootstrap.py", line 2226, in _find_and_load_unlocked
      File "X:\Python34\lib\importlib\_bootstrap.py", line 1191, in _load_unlocked
      File "X:\Python34\lib\importlib\_bootstrap.py", line 1161, in _load_backward_compatible
      File "C:\WinPython-64bit-3.4.2.3\python-3.4.2.amd64\lib\site-packages\pywinauto\__init__.py", line 30, in <module>
        from . import findwindows
      File "X:\Python34\lib\importlib\_bootstrap.py", line 2284, in _handle_fromlist
      File "X:\Python34\lib\importlib\_bootstrap.py", line 321, in _call_with_frames_removed
      File "X:\Python34\lib\importlib\_bootstrap.py", line 2237, in _find_and_load
      File "X:\Python34\lib\importlib\_bootstrap.py", line 2226, in _find_and_load_unlocked
      File "X:\Python34\lib\importlib\_bootstrap.py", line 1191, in _load_unlocked
      File "X:\Python34\lib\importlib\_bootstrap.py", line 1161, in _load_backward_compatible
      File "C:\WinPython-64bit-3.4.2.3\python-3.4.2.amd64\lib\site-packages\pywinauto\findwindows.py", line 38, in <module>
        from . import controls
      File "X:\Python34\lib\importlib\_bootstrap.py", line 2284, in _handle_fromlist
      File "X:\Python34\lib\importlib\_bootstrap.py", line 321, in _call_with_frames_removed
      File "X:\Python34\lib\importlib\_bootstrap.py", line 2237, in _find_and_load
      File "X:\Python34\lib\importlib\_bootstrap.py", line 2226, in _find_and_load_unlocked
      File "X:\Python34\lib\importlib\_bootstrap.py", line 1191, in _load_unlocked
      File "X:\Python34\lib\importlib\_bootstrap.py", line 1161, in _load_backward_compatible
      File "C:\WinPython-64bit-3.4.2.3\python-3.4.2.amd64\lib\site-packages\pywinauto\controls\__init__.py", line 34, in <module>
        from . import win32_controls
      File "X:\Python34\lib\importlib\_bootstrap.py", line 2284, in _handle_fromlist
      File "X:\Python34\lib\importlib\_bootstrap.py", line 321, in _call_with_frames_removed
      File "X:\Python34\lib\importlib\_bootstrap.py", line 2237, in _find_and_load
      File "X:\Python34\lib\importlib\_bootstrap.py", line 2226, in _find_and_load_unlocked
      File "X:\Python34\lib\importlib\_bootstrap.py", line 1191, in _load_unlocked
      File "X:\Python34\lib\importlib\_bootstrap.py", line 1161, in _load_backward_compatible
      File "C:\WinPython-64bit-3.4.2.3\python-3.4.2.amd64\lib\site-packages\pywinauto\controls\win32_controls.py", line 43, in <module>
        from .. import tests
      File "X:\Python34\lib\importlib\_bootstrap.py", line 2284, in _handle_fromlist
      File "X:\Python34\lib\importlib\_bootstrap.py", line 321, in _call_with_frames_removed
      File "X:\Python34\lib\importlib\_bootstrap.py", line 2237, in _find_and_load
      File "X:\Python34\lib\importlib\_bootstrap.py", line 2226, in _find_and_load_unlocked
      File "X:\Python34\lib\importlib\_bootstrap.py", line 1191, in _load_unlocked
      File "X:\Python34\lib\importlib\_bootstrap.py", line 1161, in _load_backward_compatible
      File "C:\WinPython-64bit-3.4.2.3\python-3.4.2.amd64\lib\site-packages\pywinauto\tests\__init__.py", line 157, in <module>
        __init_tests()
      File "C:\WinPython-64bit-3.4.2.3\python-3.4.2.amd64\lib\site-packages\pywinauto\tests\__init__.py", line 141, in __init_tests
        test_module = __import__(test_name.lower(), globals(), locals(), level=1)
      File "X:\Python34\lib\importlib\_bootstrap.py", line 2237, in _find_and_load
      File "X:\Python34\lib\importlib\_bootstrap.py", line 2224, in _find_and_load_unlocked
    ImportError: No module named 'pywinauto.tests.allcontrols'

**Comment by airelil** [comment]
Can you show us your setup.py?

**Comment by seancallahan88** [comment]
from distutils.core import setup
import pywinauto
setup(
    name='Backup',
    version='1',
    packages=['pywinauto',
				'pywinauto.tests.allcontrols',
				"pywinauto.tests.truncation",
                "pywinauto.tests.translation",
                "pywinauto.tests.repeatedhotkey",
                "pywinauto.tests.overlapping",
                "pywinauto.tests.missingextrastring",
                "pywinauto.tests.missalignment",
                "pywinauto.tests.miscvalues",
                "pywinauto.tests.leadtrailspaces",
                "pywinauto.tests.comparetoreffont",
                "pywinauto.tests.comboboxdroppedheight",
                "pywinauto.tests.asianhotkey",
                "pywinauto.tests.allcontrols",], 
    url='',
    license='',
    author='',
    author_email='',
    description='',
    console=['backup.py']
)

**Comment by airelil** [comment]
Hi @seancallahan88 
The following steps worked for me. I took as a base an example from the cx_freeze site and modified it:
https://bitbucket.org/anthony_tuininga/cx_freeze/src/1282b6b6ee637738210113dd88c3c198d475340f/cx_Freeze/samples/advanced/setup.py?at=default

```python
import sys
from cx_Freeze import setup, Executable

options = {
    'build_exe': {
        'compressed': True,
        'packages': 'pywinauto',
        'includes': [
            "pywinauto.tests.allcontrols",
            "pywinauto.tests.truncation",
            "pywinauto.tests.translation",
            "pywinauto.tests.repeatedhotkey",
            "pywinauto.tests.overlapping",
            "pywinauto.tests.missingextrastring",
            "pywinauto.tests.missalignment",
            "pywinauto.tests.miscvalues",
            "pywinauto.tests.leadtrailspaces",
            "pywinauto.tests.comparetoreffont",
            "pywinauto.tests.comboboxdroppedheight",
            "pywinauto.tests.asianhotkey",
            "pywinauto.tests.allcontrols",
        ],
        'path': sys.path + ['modules']
    }
}

executables = [
    Executable('test_wait.py'),
]

setup(name='advanced_cx_Freeze_sample',
      version='0.1',
      description='Advanced sample cx_Freeze script',
      options=options,
      executables=executables
      )
```
This is my simple test_wait.py:
``` python
from pywinauto.application import Application
import time

app = Application().start_("Notepad")
dlg = app.Window_(title='Untitled - Notepad', class_name='Notepad')
dlg.edit.SetEditText("Here is some text\r\n and some more")
time.sleep(10)
app.kill_()
```

I put both files, *test_wait.py and  *setup_freeze.py* in the *pywinauto* root directory. Notice that I had to make a different name for *setup_freeze.py* because the root dir already has a *setup.py* file. I used the next command to freeze the script into an exe:
```
python setup_freeze.py build
```

**Comment by vasily-v-ryabov** [comment]
Probably we will make it easier any way. There are too many actions required from user.

**Comment by seancallahan88** [comment]
Hi @airelil ,
I followed this example but with my own backup.py and got this:

	running build
	running build_exe
	creating directory build\exe.win-amd64-3.4
	copying C:\WinPython-64bit-3.4.2.3\python-3.4.2.amd64\lib\site-packages\cx_Freez
	e\bases\Console.exe -> build\exe.win-amd64-3.4\backup.exe
	copying C:\WinPython-64bit-3.4.2.3\python-3.4.2.amd64\python34.dll -> build\exe.
	win-amd64-3.4\python34.dll
	Traceback (most recent call last):
	  File "setup_freeze.py", line 35, in <module>
		executables=executables
	  File "C:\WinPython-64bit-3.4.2.3\python-3.4.2.amd64\lib\site-packages\cx_Freez
	e\dist.py", line 362, in setup
		distutils.core.setup(**attrs)
	  File "C:\WinPython-64bit-3.4.2.3\python-3.4.2.amd64\lib\distutils\core.py", li
	ne 148, in setup
		dist.run_commands()
	  File "C:\WinPython-64bit-3.4.2.3\python-3.4.2.amd64\lib\distutils\dist.py", li
	ne 955, in run_commands
		self.run_command(cmd)
	  File "C:\WinPython-64bit-3.4.2.3\python-3.4.2.amd64\lib\distutils\dist.py", li
	ne 974, in run_command
		cmd_obj.run()
	  File "C:\WinPython-64bit-3.4.2.3\python-3.4.2.amd64\lib\distutils\command\buil
	d.py", line 126, in run
		self.run_command(cmd_name)
	  File "C:\WinPython-64bit-3.4.2.3\python-3.4.2.amd64\lib\distutils\cmd.py", lin
	e 313, in run_command
		self.distribution.run_command(command)
	  File "C:\WinPython-64bit-3.4.2.3\python-3.4.2.amd64\lib\distutils\dist.py", li
	ne 974, in run_command
		cmd_obj.run()
	  File "C:\WinPython-64bit-3.4.2.3\python-3.4.2.amd64\lib\site-packages\cx_Freez
	e\dist.py", line 232, in run
		freezer.Freeze()
	  File "C:\WinPython-64bit-3.4.2.3\python-3.4.2.amd64\lib\site-packages\cx_Freez
	e\freezer.py", line 616, in Freeze
		self._FreezeExecutable(executable)
	  File "C:\WinPython-64bit-3.4.2.3\python-3.4.2.amd64\lib\site-packages\cx_Freez
	e\freezer.py", line 211, in _FreezeExecutable
		self._AddVersionResource(exe.targetName)
	  File "C:\WinPython-64bit-3.4.2.3\python-3.4.2.amd64\lib\site-packages\cx_Freez
	e\freezer.py", line 150, in _AddVersionResource
		stamp(fileName, versionInfo)
	  File "C:\WinPython-64bit-3.4.2.3\python-3.4.2.amd64\lib\site-packages\win32\li
	b\win32verstamp.py", line 159, in stamp
		h = BeginUpdateResource(pathname, 0)
	pywintypes.error: (2, 'BeginUpdateResource', 'The system cannot find the file sp
	ecified.')

**Comment by vasily-v-ryabov** [comment]
Please try to re-install pyWin32 package from here: http://sourceforge.net/projects/pywin32/files/pywin32/Build%20219/

File `win32\lib\win32verstamp.py` exists in my Py3.4.amd64+pyWin32.

**Comment by seancallahan88** [comment]
Reinstalled build 219 and have same issue. I also have the win32verstamp.py.

I will repeat these steps on my desktop and see if there is any difference.

**Comment by airelil** [comment]
@seancallahan88, IMHO, the problem not in *win32verstamp.py*, in fact it just complains about a missing file. Unfortunately it's not clear which file is not found. I have a couple of ideas. Have you been able to "freeze" my simple example ? I think it is worth trying to start from a basic script. Also you can get more info with running python in a "verbose" mode as following:
```
python -v setup_freeze.py build
```
@vasily-v-ryabov did my example worked on your machine ?

**Comment by vasily-v-ryabov** [comment]
Now it works for

    C:\Python34_x64\python.exe C:\Python34_x64\Scripts\cxfreeze test_wait.py --target-dir build_exe

But setup_freeze.py doesn't work (it's not even built):

    C:\Python34_x64\python.exe setup_freeze.py build
    running build
    running build_exe
    Traceback (most recent call last):
      File "setup_freeze.py", line 35, in <module>
        executables=executables
      File "C:\Python34_x64\lib\site-packages\cx_Freeze\dist.py", line 362, in setup

        distutils.core.setup(**attrs)
      File "C:\Python34_x64\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Python34_x64\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "C:\Python34_x64\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Python34_x64\lib\distutils\command\build.py", line 126, in run
        self.run_command(cmd_name)
      File "C:\Python34_x64\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Python34_x64\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Python34_x64\lib\site-packages\cx_Freeze\dist.py", line 232, in run
        freezer.Freeze()
      File "C:\Python34_x64\lib\site-packages\cx_Freeze\freezer.py", line 619, in Fr
    eeze
        self.finder = self._GetModuleFinder()
      File "C:\Python34_x64\lib\site-packages\cx_Freeze\freezer.py", line 378, in _G
    etModuleFinder
        finder.IncludePackage(name)
      File "C:\Python34_x64\lib\site-packages\cx_Freeze\finder.py", line 688, in Inc
    ludePackage
        self._ImportAllSubModules(module, deferredImports)
      File "C:\Python34_x64\lib\site-packages\cx_Freeze\finder.py", line 320, in _Im
    portAllSubModules
        raise ImportError("No module named %r" % subModuleName)
    ImportError: No module named 'pywinauto.elementInfo'

**Comment by vasily-v-ryabov** [comment]
py2exe also works OK on Py34 x64.

setup_py2exe.py

    from distutils.core import setup
    import py2exe

    setup(console=['test_wait.py'])

Build command: `python setup_py2exe.py py2exe`

**Comment by airelil** [comment]
One more remark. My script for cx_freeze can be simplified. I removed the explicit includes for *pywinauto.tests* package and it is still working for me. 
```python
import sys
from cx_Freeze import setup, Executable

options = {
    'build_exe': {
        'compressed': True,
        'packages': 'pywinauto',
        'path': sys.path + ['modules']
    }
}

executables = [
    Executable('test_wait.py'),
]

setup(name='advanced_cx_Freeze_sample',
      version='0.1',
      description='Advanced sample cx_Freeze script',
      options=options,
      executables=executables
      )
```
Also I have recently cleaned up some unused imports. @seancallahan88 try to check your issue with the latest *master* branch of pywinauto. Let me know if your are able to freeze my simple example on your machine.

**Comment by seancallahan88** [comment]
With the latest branch I was able to get it to work  with your setup file. It also works if you import those .tests in your main python file.

**Comment by vasily-v-ryabov** [comment]
I've performed clean-up of all .pyc files and now it works for setup_freeze.py. There was obsolete byte code from experimental branch that was mixed with master somehow.

So closing the issue as resolved. Sean, thank you for reporting that!
