### ISSUE TITLE
Error using HwndWrapper

### ISSUE THREAD

**Issue by 3droj7** [pywinauto/pywinauto#389]
Hey when I'm using HwndWrapper for a specific window I get this error:
```
>>> HwndWrapper(app.windows()[0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\pywinauto\controls\hwndwrapper.py", line 180, in __new__
    return super(HwndWrapper, cls)._create_wrapper(cls, element, HwndWrapper)
  File "C:\Python27\lib\site-packages\pywinauto\base_wrapper.py", line 121, in _create_wrapper
    new_class = cls_spec.find_wrapper(element_info)
  File "C:\Python27\lib\site-packages\pywinauto\controls\hwndwrapper.py", line 137, in find_wrapper
    if regex.match(class_name):
TypeError: expected string or buffer
```

It seems that the line 129 in "pywinauto\controls\hwndwrapper.py" should be this:
`class_name = element.class_name()`
Instead of:
`class_name = element.class_name`

**Comment by vasily-v-ryabov** [comment]
The usage is incorrect because `app.windows()[0]` already returns `HwndWrapper` object or its derivative. To make it more clear we may check if we create a copy of `HwndWrapper` (and hence create it). So thanks for the use case!

Current usage is supposed to get `ElementInfo` derived argument that has a `class_name` property (not a method.
