### ISSUE TITLE
XMLHelpers.py doesn't work on Python 3.3: unknown encoding: bz2

### ISSUE THREAD

**Issue by vasily-v-ryabov** [pywinauto/pywinauto#39]
Traceback (most recent call last):
      File "C:\projects\pywinauto-8b7t7\pywinauto\unittests\test_win32controls.py", line 484, in setUp
        self.app.Calculator.WriteToXML("ref_controls.xml")
      File "C:\projects\pywinauto-8b7t7\pywinauto\controls\win32_controls.py", line 872, in WriteToXML
        XMLHelpers.WriteDialogToFile(filename, props)
      File "C:\projects\pywinauto-8b7t7\pywinauto\XMLHelpers.py", line 171, in WriteDialogToFile
        _SetNodeProps(ctrlelem, name, value)
      File "C:\projects\pywinauto-8b7t7\pywinauto\XMLHelpers.py", line 111, in _SetNodeProps
        image_data = codecs.encode(codecs.encode(value.tobytes(), "bz2"), "base64").decode('utf-8')
    LookupError: unknown encoding: bz2

**Comment by vasily-v-ryabov** [comment]
Module `bz2` exists in Python 3.3 and even in Python 3.1. But `codecs` supports it starting from 3.4.
