### ISSUE TITLE
ModuleNotFoundError: No module named 'win32process'

### ISSUE THREAD

**Issue by alphaQ101** [pywinauto/pywinauto#418]
Hi there,

I ran into a strange issue and was hoping someone could shed some light on it.

I was seeing if the packaged installed which it looks like it did, but immediately ran into a problem.  Here is my code:

```python
from pywinauto.application import Application
#import os
#import timer

app = Application().start("notepad.exe")
```

I get this traceback
```python
> Traceback (most recent call last):
  File "D:/Onedrive/Documents/Programming Projects/Python/hashcatAutoSaveV2.py", line 1, in <module>
    from pywinauto.application import Application
  File "C:\Users\mmoli\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pywinauto\__init__.py", line 40, in <module>
    from . import findwindows
  File "C:\Users\mmoli\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pywinauto\findwindows.py", line 42, in <module>
    from . import controls
  File "C:\Users\mmoli\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pywinauto\controls\__init__.py", line 36, in <module>
    from . import uiawrapper # register "uia" back-end (at the end of uiawrapper module)
  File "C:\Users\mmoli\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pywinauto\controls\uiawrapper.py", line 40, in <module>
    from .. import backend
  File "C:\Users\mmoli\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pywinauto\backend.py", line 35, in <module>
    from .base_wrapper import BaseWrapper
  File "C:\Users\mmoli\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pywinauto\base_wrapper.py", line 41, in <module>
    import win32process
ModuleNotFoundError: No module named 'win32process'
```
I read on [this](https://github.com/pywinauto/pywinauto/issues/356) thread that it is an issue with pypiwin32 and ran the command he recommended which gave me this:
```
> D:\Onedrive\desktop\ITTools\hashcat-0.60>py -m pip install -U pypiwin32
Requirement already up-to-date: pypiwin32 in c:\users\mmoli\appdata\local\programs\python\python36-32\lib\site-packages
```

Unfortunately, it did not fix the issue.  Any help would be very appreciated.

**Comment by BleedingEdgeTech** [comment]
I had the same problem. pip install -U pypiwin32 did not fix the issue for me as well
but he also mentioned that you can manually install it

with that link https://sourceforge.net/projects/pywin32/files/pywin32/
I installed Build 221 and now it works fine

**Comment by alphaQ101** [comment]
Thanks for the suggestion

**Comment by jknguyen621** [comment]
This suggestion didn't work for me on Mac OSX, still getting this error:
import win32process
E   ModuleNotFoundError: No module named 'win32process'

**Comment by vasily-v-ryabov** [comment]
Official PyPI package name is pywin32, not pypiwin32 (outdated name and version which should be deleted first). Of course, this is for Windows OS only. Current pywinauto release works on Windows and have very small functions on Linux. So macOS is not supported yet.

macOS support is ongoing. See this pull request for example: https://github.com/pywinauto/pywinauto/pull/841 It will be next major release with full support for both Linux and macOS. Can't provide exact ETA for 0.7.0, it could be this year or next one.
