### ISSUE TITLE
win32 hook caused OSError: exception: access violation writing 0x00000102

### ISSUE THREAD

**Issue by redstoneleo** [pywinauto/pywinauto#451]
After running the following , the mouse cursor moving speed becomes a bit slow, guess need enchantment ,
```
import win32api
import win32con
from threading import Timer
from pywinauto.win32_hooks import Hook
from pywinauto.win32_hooks import KeyboardEvent
from pywinauto.win32_hooks import MouseEvent


def on_timer():
    """Callback by timer out"""
    win32api.PostThreadMessage(main_thread_id, win32con.WM_QUIT, 0, 0);


def on_event(args):
    """Callback for keyboard and mouse events"""
    if isinstance(args, KeyboardEvent):
        if args.current_key == 'A' and args.event_type == 'key down' and 'Lcontrol' in args.pressed_key:
            print("Ctrl + A was pressed");

        if args.current_key == 'K' and args.event_type == 'key down':
            print("K was pressed");

        if args.current_key == 'M' and args.event_type == 'key down' and 'U' in args.pressed_key:
            hk.unhook_mouse()
            print("Unhook mouse")

        if args.current_key == 'K' and args.event_type == 'key down' and 'U' in args.pressed_key:
            hk.unhook_keyboard()
            print("Unhook keyboard")

    if isinstance(args, MouseEvent):
        print(args.current_key,'--------',args.event_type)
        # if args.current_key == 'RButton' and args.event_type == 'key down':
        #     print ("Right button pressed")

        # if args.current_key == 'WheelButton' and args.event_type == 'key down':
        #     print("Wheel button pressed")

hk = Hook()
hk.handler = on_event
# main_thread_id = win32api.GetCurrentThreadId()
# t = Timer(5.0, on_timer)  # Quit after 5 seconds
# t.start()
hk.hook(keyboard=True, mouse=True)
```

 and after playing around (include moving mouse cursor) for a while ,  got
```
Traceback (most recent call last):
  File "C:\Users\i\Downloads\hook_and_listen.py", line 44, in <module>
    hk.hook(keyboard=True, mouse=True)
  File "C:\Users\i\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pywinauto\win32_hooks.py", line 548, in hook
    self.listen()
  File "C:\Users\i\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pywinauto\win32_hooks.py", line 591, in listen
    self._process_win_msgs()
  File "C:\Users\i\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pywinauto\win32_hooks.py", line 575, in _process_win_msgs
    res = windll.user32.PeekMessageW(pointer(message), 0, 0, 0, win32con.PM_REMOVE)
OSError: exception: access violation writing 0x00000102
```

**Comment by airelil** [comment]
@redstoneleo, I tried your example with the latest code of pywinauto from the master branch, on my win8.1 and py35-x64 and py34-x86. So far it works for me. It looks like you run on py35 x86, please confirm. Which OS version do you use ? How long you run this script ? A couple of minutes or hours? ;-)

**Comment by redstoneleo** [comment]
Tested on: Python 3.5.2, Win7 32bit for a couple of minutes
I got the exception again 
```
Traceback (most recent call last):
  File "C:\Users\i\Downloads\hook_and_listen.py", line 44, in <module>
    hk.hook(keyboard=True, mouse=True)
  File "C:\Users\i\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pywinauto\win32_hooks.py", line 548, in hook
    self.listen()
  File "C:\Users\i\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pywinauto\win32_hooks.py", line 591, in listen
    self._process_win_msgs()
  File "C:\Users\i\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pywinauto\win32_hooks.py", line 575, in _process_win_msgs
    res = windll.user32.PeekMessageW(pointer(message), 0, 0, 0, win32con.PM_REMOVE)
OSError: exception: access violation writing 0x00000102
```

**Comment by airelil** [comment]
@redstoneleo , do you mind trying a small change in pywinauto sources?
```diff
diff --git a/pywinauto/win32_hooks.py b/pywinauto/win32_hooks.py
index 831864f..5531d4c 100644
--- a/pywinauto/win32_hooks.py
+++ b/pywinauto/win32_hooks.py
@@ -570,8 +570,8 @@ class Hook(object):

     def _process_win_msgs(self):
         """Peek and process queued windows messages"""
-        message = wintypes.MSG()
         while True:
+            message = wintypes.MSG()
             res = windll.user32.PeekMessageW(pointer(message), 0, 0, 0, win32con.PM_REMOVE)
             if not res:
                 break
```

**Comment by redstoneleo** [comment]
Thanks for your kind help !
I changed the pywinauto source, tested nearly a minute , then 
```
Traceback (most recent call last):
  File "C:\Users\i\Downloads\hook_and_listen.py", line 44, in <module>
    hk.hook(keyboard=True, mouse=True)
  File "C:\Users\i\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pywinauto\win32_hooks.py", line 548, in hook
    self.listen()
  File "C:\Users\i\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pywinauto\win32_hooks.py", line 592, in listen
    self._process_win_msgs()
  File "C:\Users\i\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pywinauto\win32_hooks.py", line 576, in _process_win_msgs
    res = windll.user32.PeekMessageW(pointer(message), 0, 0, 0, win32con.PM_REMOVE)
OSError: exception: access violation writing 0x00000102
```

**Comment by airelil** [comment]
@redstoneleo, I was able to reproduce this problem on a VM with win7-x86. For me it fails immediately on first key press. The problem happens even when running mouse only hooks - ```hk.hook(keyboard=False, mouse=True)```. It also fails with just running ```win32gui.PumpWaitingMessages```, so it's hard to say the reason... I'll try to look into it later on.

**Comment by redstoneleo** [comment]
CFUNCTYPE should be replaced with WINFUNCTYPE in the project, because [someone says](https://stackoverflow.com/a/31396340/1485853) that 

> Pay attention to the calling convention if you need to support 32-bit Windows. The 32-bit Windows API generally requires stdcall (callee stack cleanup), so the callback needs to be defined via WINFUNCTYPE instead of CFUNCTYPE.

And I did, then I didn't get the following mysterious exception anymore.

BTW, Events should be captured in a separate thread in order to not  block main program.
