### ISSUE TITLE
ElementAmbiguousError when using backend win32

### ISSUE THREAD

**Issue by nimuston** [pywinauto/pywinauto#453]
Hi,

I got and ElementAmbiguousError when i used backend win32. 

full traceback

```
Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    appwindow.print_control_identifiers(filename='identifiers.txt')
  File "build\bdist.win-amd64\egg\pywinauto\application.py", line 584, in print_control_identifiers
    this_ctrl = self.__resolve_control(self.criteria)[-1]
  File "build\bdist.win-amd64\egg\pywinauto\application.py", line 245, in __resolve_control
    criteria)
  File "build\bdist.win-amd64\egg\pywinauto\timings.py", line 419, in wait_until_passes
    func_val = func(*args)
  File "build\bdist.win-amd64\egg\pywinauto\application.py", line 190, in __get_ctrl
    dialog = self.backend.generic_wrapper_class(findwindows.find_element(**criteria[0]))
  File "build\bdist.win-amd64\egg\pywinauto\findwindows.py", line 98, in find_element
    raise exception
ElementAmbiguousError: There are 2 elements that match the criteria {'process': 6232, 'backend': u'win32'}
```
code that causes this error is very simple, it seems that it is the app being tested that causes this. My app that i'm testing is opening winform on top of winform and that's the reason.

```
import pywinauto

app = pywinauto.Application()
appconnect = app.connect(path='TestApp.exe')
appwindow = appconnect.window()
appwindow.print_control_identifiers(filename='identifiers.txt')
```

I was also able to fix this by editing findwindows.py, i commented one if statement out from find_element function. Lines 89 - 98

```
def find_element(**kwargs):
    """
    Call find_elements and ensure that only one element is returned

    Calls find_elements with exactly the same arguments as it is called with
    so please see :py:func:`find_elements` for the full parameters description.
    """
    elements = find_elements(**kwargs)

    if not elements:
        raise ElementNotFoundError(kwargs)

#    if len(elements) > 1:
#        exception = ElementAmbiguousError(
#            "There are {0} elements that match the criteria {1}".format(
#                len(elements),
#                six.text_type(kwargs),
#            )
#        )
#
#        exception.elements = elements
#        raise exception

    return elements[0]
```

so my question is that is this if statement necessary or should we comment this out also from master branch?

**Comment by airelil** [comment]
No we shouldn't comment it out. Usually, to solve the ambiguity we use "[found_index](https://github.com/pywinauto/pywinauto/blob/0c8f04db13ad10c23e5bbc0a4c1b74cb640e4896/pywinauto/findwindows.py#L165)". You can pass this filter as an argument for window method: 
```appconnect.window(found_index=0)```.

**Comment by nimuston** [comment]
Nice thanks, Good that i asked :D
