### ISSUE TITLE
syntax error when import pywinauto

### ISSUE THREAD

**Issue by spectereye** [pywinauto/pywinauto#468]
Hello all, anybody met the same error below?
i met this in my win10 but not in win7 pc - both python 3.6.4,
strange that it seems a obvious syntax error ...

```python
C:\WINDOWS\system32>python
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pywinauto
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python3\lib\site-packages\pywinauto\__init__.py", line 70, in <module>
    from .sysinfo import UIA_support
  File "C:\Python3\lib\site-packages\pywinauto\sysinfo.py", line 44, in <module>
    import comtypes  # noqa: E402
  File "C:\Python3\lib\site-packages\comtypes\__init__.py", line 381
    except COMError, err:
                   ^
SyntaxError: invalid syntax


>>> import comtypes
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python3\lib\site-packages\comtypes\__init__.py", line 381
    except COMError, err:
                   ^
SyntaxError: invalid syntax
>>> exit()


C:\WINDOWS\system32>pip list | grep pywinauto
pywinauto (0.6.4)


```

**Comment by airelil** [comment]
Seems as a problem in comtypes module.

**Comment by spectereye** [comment]
yeah, but no problem in win 7, strange ...

**Comment by airelil** [comment]
BTW, the same problem (or  very similar one) was already reported by @vasily-v-ryabov https://github.com/enthought/comtypes/issues/99

**Comment by vasily-v-ryabov** [comment]
Hi @spectereye maybe you've installed comtypes on Python 2.7 first, then ran the same `setup.py` on Python 3.6. Can you try to remove and make clean install for your Python 3.6?

If `pip install comtypes` has been used (comtypes installer could be cached somehow), I'd suggest to download comtypes as zip package and run `C:\Python3\python.exe setup.py install`

**Comment by spectereye** [comment]
@vasily-v-ryabov thanks a lot for your guide! you are right it's caused by pip cache. i tried below:
```cmd
pip install --upgrade comtypes  # not work
pip uninstall comtpyes && pip install --upgrade comtpyes  # not work
pip uninstall comtypes && pip install --no-cache-dir comtypes  # works
:: i also deleted %appdata%\pip\cache folder - though not sure it's the cache dir...
```
