### ISSUE TITLE
Issues with running simple notepad pywinauto script

### ISSUE THREAD

**Issue by caseysalvador** [pywinauto/pywinauto#500]
Issues running PyWinAuto using simply the basic example script from the pywinauto github welcome page for notepad.

```
from pywinauto.application import Application
app = Application().start("notepad.exe")

app.UntitledNotepad.menu_select("Help->About Notepad")
app.AboutNotepad.OK.click()
app.UntitledNotepad.Edit.type_keys("pywinauto Works!", with_spaces = True)
```

**I'm receiving this error below:**
```
Traceback (most recent call last):
  File "C:/Users/USER_NAME/Documents/Open_Notepad.py", line 1, in <module>
    import pywinauto
  File "C:\Program Files\Python36\lib\site-packages\pywinauto\__init__.py", line 72, in <module>
    from . import findwindows
  File "C:\Program Files\Python36\lib\site-packages\pywinauto\findwindows.py", line 42, in <module>
    from . import controls
  File "C:\Program Files\Python36\lib\site-packages\pywinauto\controls\__init__.py", line 36, in <module>
    from . import uiawrapper # register "uia" back-end (at the end of uiawrapper module)
  File "C:\Program Files\Python36\lib\site-packages\pywinauto\controls\uiawrapper.py", line 46, in <module>
    from ..uia_defines import IUIA
  File "C:\Program Files\Python36\lib\site-packages\pywinauto\uia_defines.py", line 35, in <module>
    import comtypes.client
  File "C:\Program Files\Python36\lib\site-packages\comtypes\client\__init__.py", line 33, in <module>
    gen_dir = _find_gen_dir()
  File "C:\Program Files\Python36\lib\site-packages\comtypes\client\_code_cache.py", line 71, in _find_gen_dir
    result = os.path.abspath(gen_path[-1])
IndexError: list index out of range
```

**Comment by vasily-v-ryabov** [comment]
This is known `comtypes` issue. Please re-install your Python to the non-system folder like `C:\Python36\` or run the script as Administrator. Unfortunately this issue is still not fixed in comtypes repo, though few similar pull requests with fixes were submitted.
