### ISSUE TITLE
how do I use SendKeys? I am using pywinauto 0.6.5 and Python 3.5.1

### ISSUE THREAD

**Issue by volksmania** [pywinauto/pywinauto#533]
I am trying to send the following
####to a terminal window###
from pywinauto import keyboard
keyboard.SendKeys.send('jsmith')
########################

but when I try to run the above, I receive the invalid syntax

 File "demo.py", line 35
    keyboard.SendKeys.send('jsmith')
           ^
SyntaxError: invalid syntax

**Comment by vasily-v-ryabov** [comment]
`SendKeys` is a function, not an object/module. How it works in my Python console:
```python
>>> from pywinauto import keyboard
>>> keyboard.SendKeys.send('jsmith')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'function' object has no attribute 'send'
>>> keyboard.SendKeys('jsmith')
>>> jsmith
```
So the error message is correct for Python 3.6.5 32-bit. It should be the same on all Pythons. Maybe you have something more with indentation or something on previous lines.

Anyway there is nothing to do with pywinauto.
