### ISSUE TITLE
pywinauto 0.6.5 invalid window handle problem

### ISSUE THREAD

**Issue by meshuggahtas** [pywinauto/pywinauto#534]
My scripts got broken after updating from 0.6.4 to 0.6.5. Error thrown when using type_keys on a not focused element while automating an application with focus problems.

> pywintypes.error: (1400, 'GetWindowRect', 'Invalid window handle.').

The program I automate made with Delphi.
The program has a problem of getting focus after not having focus. So clicking a button in this application requires clicking twice if it didn't had focus initially.

**Detailed focus problem:**
When I try to get focus of the Delphi application, there will be no foreground application having focus for a very brief moment until getting focused. Used this program: http://www.happydroid.com/focus

```
1284:C:\Windows\explorer.exe | Thu Aug 09 12:24:18 2018

No foreground application | Thu Aug 09 12:24:19 2018

9840:C:\Program Files (x86)\Intellio Video System\Intellio Client 4\RCClient.exe | Thu Aug 09 12:24:20 2018

```
So I use win32 backend, type_keys (AFAIK SendKeys requires focus) and click (AFAIK click_input requires focus).

The release notes only talks about 

> Fix .set_focus() for "uia" backend including minimized window case
> (issue #443).

while I think I'm having this problem because one of the changes in hwndwrapper (https://github.com/pywinauto/pywinauto/commit/960682d0abd7db4efb8e129e4599fd47a4b5e5bd#diff-03fd5a827c53b158f63e6e8c518d9809)

I'm looking for your answer. And thank you for making pywinauto :)

**Relevant example code** that fails everytime in 0.6.5 and works flawlessly in 0.6.4:
```
import pywinauto
APP = pywinauto.Application(backend="win32").start("RCClient.exe")
elem = APP.MainForm
elem.type_keys("%{TAB}") # everything fine here
elem.type_keys("%{TAB}") # error
```

**Full log:**
```
12:02:20.461 ERROR   scenario          Test                @124 Traceback (most recent call last):
  File "C:\Users\oliver.horvath\PycharmProjects\autoivs\scenario.py", line 113, in Test
    RESULT = func()  # Teszt eset futtatása
  File "C:\Users\oliver.horvath\PycharmProjects\autoivs\scenarios\teszt.py", line 276, in Github2_9988
    log.info(ivs.APP.MainForm.control_type())
  File "C:\Users\oliver.horvath\venv\autoivspackages\lib\site-packages\pywinauto\application.py", line 368, in __getattribute__
    ctrls = self.__resolve_control(self.criteria)
  File "C:\Users\oliver.horvath\venv\autoivspackages\lib\site-packages\pywinauto\application.py", line 246, in __resolve_control
    criteria)
  File "C:\Users\oliver.horvath\venv\autoivspackages\lib\site-packages\pywinauto\timings.py", line 431, in wait_until_passes
    func_val = func(*args, **kwargs)
  File "C:\Users\oliver.horvath\venv\autoivspackages\lib\site-packages\pywinauto\application.py", line 191, in __get_ctrl
    dialog = self.backend.generic_wrapper_class(findwindows.find_element(**criteria[0]))
  File "C:\Users\oliver.horvath\venv\autoivspackages\lib\site-packages\pywinauto\findwindows.py", line 84, in find_element
    elements = find_elements(**kwargs)
  File "C:\Users\oliver.horvath\venv\autoivspackages\lib\site-packages\pywinauto\findwindows.py", line 303, in find_elements
    elements = findbestmatch.find_best_control_matches(best_match, wrapped_elems)
  File "C:\Users\oliver.horvath\venv\autoivspackages\lib\site-packages\pywinauto\findbestmatch.py", line 494, in find_best_control_matches
    name_control_map = build_unique_dict(controls)
  File "C:\Users\oliver.horvath\venv\autoivspackages\lib\site-packages\pywinauto\findbestmatch.py", line 473, in build_unique_dict
    ctrl_names = get_control_names(ctrl, controls, text_ctrls)
  File "C:\Users\oliver.horvath\venv\autoivspackages\lib\site-packages\pywinauto\findbestmatch.py", line 320, in get_control_names
    non_text_names = get_non_text_control_name(control, allcontrols, textcontrols)
  File "C:\Users\oliver.horvath\venv\autoivspackages\lib\site-packages\pywinauto\findbestmatch.py", line 219, in get_non_text_control_name
    ctrl_r = ctrl.rectangle()
  File "C:\Users\oliver.horvath\venv\autoivspackages\lib\site-packages\pywinauto\base_wrapper.py", line 337, in rectangle
    return self.element_info.rectangle
  File "C:\Users\oliver.horvath\venv\autoivspackages\lib\site-packages\pywinauto\win32_element_info.py", line 181, in rectangle
    return handleprops.rectangle(self.handle)
  File "C:\Users\oliver.horvath\venv\autoivspackages\lib\site-packages\pywinauto\handleprops.py", line 207, in rectangle
    return win32structures.RECT(*win32gui.GetWindowRect(handle))
pywintypes.error: (1400, 'GetWindowRect', 'Érvénytelen ablakleíró.')
```

**Comment by vasily-v-ryabov** [comment]
Thanks for such a detailed report. This is interesting case. I can take a look later. By the way method `.type_keys()` has parameter `set_foreground=True`. So it always sets focus by default. Though the problem might be not directly connected with the focus.

**Comment by meshuggahtas** [comment]
Thanks, `.type_keys("something", set_foreground=False)` does solves my problem!

And I can verify that my problem is directly connected with focus using enough `time.sleep()` to have focus on the automated app.

I don't know if I have other problems related to this (focus problem not originating from pywinauto) but will report it back if I found any.

**Comment by NORDCOMPCZ** [comment]
I have the same problem. In my case I do automate some process which opens same application multiple times (runs in a loop over files) and quite often after 2nd iteration this error appears. Unfortunately I can't use `.type_keys()` as almost all internal elements are generated by XML and are not focusable (this is bypassed with `SendKeys()` usage).

**Comment by madhavankumar** [comment]
I get this exact same error while while waiting for a window to appear.

`pywintypes.error: (1400, 'GetWindowRect', 'Invalid window handle.')`

Code that errors - 

`my_app['Please Login'].wait('ready', timeout=30, retry_interval=0.5)`

This worked fine in 0.6.4. I see that this bug is closed. @vasily-v-ryabov  - Is the fix included in the 0.6.6 version? Is there a workaround for this in the current version?

**Comment by vasily-v-ryabov** [comment]
Hi @madhavankumar this bus is not closed yet. 0.6.6 is not released yet as well. Downgrade to 0.6.4 is the only way for now.

Sorry for long waiting. I'm able to work on the project ~2 times a week for recent half a year.

**Comment by meshuggahtas** [comment]
@madhavankumar the referenced issue #557 was closed, not this ticket.

**Comment by vasily-v-ryabov** [comment]
@meshuggahtas please check latest master branch. The problem should gone.

**Comment by meshuggahtas** [comment]
**Test**: 
```
APP = pywinauto.Application(backend="win32").start("RCClient.exe")
APP.MainForm.type_keys("%{TAB}")
```

Result:
- As soon as the application would be ready to accept keys, pywinauto thinks it actually not responding.
- Would be successful using `time.sleep()` or with waiting for a specfic state.
- `set_foreground=True` doesn't affects the result.

Log:

```
  File "C:\Users\oliver.horvath\PycharmProjects\autoivs\scenario.py", line 112, in Test
    RESULT = func()  # Teszt eset futtatása
  File "C:\Users\oliver.horvath\PycharmProjects\autoivs\scenarios\teszt.py", line 315, in github_9534
    elem.type_keys("%{TAB}")  # everything fine here
  File "C:\Users\oliver.horvath\venv\autoivspackages\lib\site-packages\pywinauto\base_wrapper.py", line 845, in type_keys
    self.verify_actionable()
  File "C:\Users\oliver.horvath\venv\autoivspackages\lib\site-packages\pywinauto\base_wrapper.py", line 591, in verify_actionable
    self.wait_for_idle()
  File "C:\Users\oliver.horvath\venv\autoivspackages\lib\site-packages\pywinauto\controls\hwndwrapper.py", line 710, in wait_for_idle
    win32functions.WaitGuiThreadIdle(self)
  File "C:\Users\oliver.horvath\venv\autoivspackages\lib\site-packages\pywinauto\win32functions.py", line 294, in WaitGuiThreadIdle
    raise RuntimeError('Window (hwnd={0}) is not responding!'.format(handle))
RuntimeError: Window (hwnd=hwndwrapper.DialogWrapper - 'None', TMainForm) is not responding!

```

**Comment by vasily-v-ryabov** [comment]
@meshuggahtas it should be asked as separate issue. Usually such error happens when application has a console launcher that spawns GUI subprocess. To handle this you have to say pywinauto it's a console launcher and then use `.connect(...)` by title or title_re with optional timeout param.

In method `start()` you need parameters `create_new_console=True, wait_for_idle=False`.

**Comment by meshuggahtas** [comment]
Okay, I think this issue can be closed, the 0.6.5 master branch fixed this problem.

@vasily-v-ryabov: I'm not sure I understood what you wrote, but the problem is that the application I'm testing has multiple windows and works flawlessly with the tricks I mentioned (time.sleep(), waiting for a window to be idle, etc). 

Using the above mentioned extra parameters which leads to 

`APP = pywinauto.Application(backend="win32").start(r"C:/Program Files (x86)/Intellio Video System/Intellio Client 4/RCClient.exe", create_new_console=True, wait_for_idle=False)` also throws the same log, including the "wait_for_idle" and "WaitGuiThreadIdle(self)" in the traceback

```
12:54:39.269 ERROR   scenario          Test                @147 Traceback (most recent call last):
  File "C:\Users\oliver.horvath\PycharmProjects\autoivs\scenario.py", line 112, in Test
    RESULT = func()  # Teszt eset futtatása
  File "C:\Users\oliver.horvath\PycharmProjects\autoivs\scenarios\teszt.py", line 315, in github_9534
    APP.TMainForm.type_keys("%{TAB}", set_foreground=False) # everything fine here
  File "C:\Users\oliver.horvath\venv\autoivspackages\lib\site-packages\pywinauto\base_wrapper.py", line 845, in type_keys
    self.verify_actionable()
  File "C:\Users\oliver.horvath\venv\autoivspackages\lib\site-packages\pywinauto\base_wrapper.py", line 591, in verify_actionable
    self.wait_for_idle()
  File "C:\Users\oliver.horvath\venv\autoivspackages\lib\site-packages\pywinauto\controls\hwndwrapper.py", line 710, in wait_for_idle
    win32functions.WaitGuiThreadIdle(self)
  File "C:\Users\oliver.horvath\venv\autoivspackages\lib\site-packages\pywinauto\win32functions.py", line 294, in WaitGuiThreadIdle
    raise RuntimeError('Window (hwnd={0}) is not responding!'.format(handle))
RuntimeError: Window (hwnd=hwndwrapper.DialogWrapper - 'None', TMainForm) is not responding!
```

Not sure about is this really a bug (and yes, this should be discussed somewhere else).

**Comment by vasily-v-ryabov** [comment]
This is expected behavior, because this `APP` instance is a console launcher process that has no GUI. Next line `APP.TMainForm.type_keys("%{TAB}", set_foreground=False)` is really failing because you didn't re-connect to the GUI process by title. Please pay more attention to traceback details and which line is failing.

**Comment by vasily-v-ryabov** [comment]
Maybe this example is more clear to understand spawning process problem: https://stackoverflow.com/questions/52853483/print-control-identifiers-for-network-and-sharing-center

**Comment by vasily-v-ryabov** [comment]
Filed #593 for this feature request.
