### ISSUE TITLE
get_button command id problem

### ISSUE THREAD

**Issue by meshuggahtas** [pywinauto/pywinauto#544]
To press a button on a toolbar, I'm using `pywinauto.controls.common_controls.ToolbarWrapper(WindowSpec.ToolBar)` and then ask the texts of all buttons then click the Nth button which is the desired button's index.
However, the app I'm automating (Delphi app with VCL components) has some -1 as command id because they are separators. I also get higher numbers on other applications for example the MMC (Microsoft Management Console) like 21508.
Unfortunately the `.button(index).click()` will execute `get_button`, which throws the `RuntimeError: GetButtonInfo failed for button with command id 21508`

I have plenty workarounds for this but don't really understand the underlying problem and would like a cleaner solution. What I really missed is clicking on a button using it's name like `APP.ToolbarsName.ButtonsName.click()` so I made a wrapper for myself.

**Example code for MMC devmgmt failing:**
```
import pywinauto, time
from pywinauto import actionlogger

actionlogger.enable()

APP = pywinauto.Application(backend="win32").start("mmc devmgmt.msc")
time.sleep(5)
APP = pywinauto.Application(backend="win32").connect(class_name="MMCMainFrame")

elem = pywinauto.controls.common_controls.ToolbarWrapper(APP.MMCMainFrame.ToolBar2)
#elem.button(0).click() #also throws the same error

for i in range (1, elem.button_count()):
    print(elem.get_button(i))
```
**Result of above code:**
```
Traceback (most recent call last):
  File "C:/Users/oliver.horvath/PycharmProjects/pywinautogithub/main4.py", line 18, in <module>
    print(elem.get_button(i))
  File "C:\Users\oliver.horvath\venv\pywinautogithub\lib\site-packages\pywinauto\controls\common_controls.py", line 2571, in get_button
    ' id {0}'.format(button.idCommand))
RuntimeError: GetButtonInfo failed for button with command id 21513
```

**Some workarounds I was using with varying success (app dependent):**
1. making a list of button texts and directly click on the toolbar rect at the desired position with the mouse
2. using .send_messages to get the texts and also to press button. **Example code (missing pressing the button but it's straightforward, used https://docs.microsoft.com/hu-hu/windows/desktop/Controls/tb-getbuttontext):**
 ```
elem = pywinauto.controls.common_controls.ToolbarWrapper(ivs.APP.MainForm.ToolBar)
for i in range(0, elem.button_count()):
        s = "                        "
        ret = bytearray(1000)
        ret = elem.send_message(1099, i, None)
        log.debug("első message a méret: {}".format(ret))
        ret = elem.send_message(1099, i, s)
        log.debug("második message a szöveg: {}".format(ret))
        if ret == 0:
            log.debug(s)

        log.debug(elem.get_button(i).text)
```
**Result of above code:**
```
10:08:03.576 DEBUG   teszt             Github_Toolbar_Szov @277 1st msg is size: 7
10:08:03.613 DEBUG   teszt             Github_Toolbar_Szov @279 2md msg is the text: 0
10:08:03.614 DEBUG   teszt             Github_Toolbar_Szov @281                         
10:08:03.627 DEBUG   teszt             Github_Toolbar_Szov @283 Refresh
10:08:03.627 DEBUG   teszt             Github_Toolbar_Szov @277 1st msg is size: -1
10:08:03.628 DEBUG   teszt             Github_Toolbar_Szov @279 2md msg is the text: -1
10:08:03.641 DEBUG   teszt             Github_Toolbar_Szov @283 
10:08:03.641 DEBUG   teszt             Github_Toolbar_Szov @277 1st msg is size: 14
10:08:03.670 DEBUG   teszt             Github_Toolbar_Szov @279 2md msg is the text: 0
10:08:03.671 DEBUG   teszt             Github_Toolbar_Szov @281                         
10:08:03.688 DEBUG   teszt             Github_Toolbar_Szov @283 Mark as Master
10:08:03.688 DEBUG   teszt             Github_Toolbar_Szov @277 1st msg is size: -1
10:08:03.689 DEBUG   teszt             Github_Toolbar_Szov @279 2md msg is the text: -1
10:08:03.702 DEBUG   teszt             Github_Toolbar_Szov @283 
10:08:03.702 DEBUG   teszt             Github_Toolbar_Szov @277 1st msg is size: 3
10:08:03.734 DEBUG   teszt             Github_Toolbar_Szov @279 2md msg is the text: 0
10:08:03.734 DEBUG   teszt             Github_Toolbar_Szov @281                         
10:08:03.748 DEBUG   teszt             Github_Toolbar_Szov @283 Add
```

edit: I see the docs mentions `button_identifier` but it's actually an index (at least I see `button_index = button_identifier` at line 2494 in common_controls.py, so as I understand, pywinauto doesn't supports pressing buttons on a toolbar by text on the button.

**Comment by vasily-v-ryabov** [comment]
`.press_button(u"Open")` is what you need. I agree that Toolbar implementation is not very clean. And there are a lot of app dependent cases. One of these is covered by known issue #413 for MFC toolbar (`press_button` implementation is possible using both backends only). I've never dealt with VCL toolbar from automation point of view. It would be great if you could prepare sample app that we can add to auto tests. The source code for test apps is stored in [PywinautoTestapps](https://github.com/pywinauto/PywinautoTestapps) repo. The binaries are in the [apps folder](https://github.com/pywinauto/pywinauto/tree/master/apps) of the main repo.

I see you're making good testing efforts. And we really appreciate it.
But we're focusing on new features like "record-replay" for "uia" backend right now. So I have no chances to assign high priority for all the reported issues. You may consider next level of contribution: we also appreciate pull requests. I can guarantee high quality code review from my side.

**Comment by meshuggahtas** [comment]
Since this is my day job and the automated app seems to be impossible to automate with uia (plenty errors that I can't figure out alone or simply empty controls or same generic name for every element), I doubt I will try any uia feature (apart from already automated OBS for recording). On the same note, I doubt I could have opportunity to contribute to this code... I have enough other projects I'm doing at home, sorry.

**Comment by meshuggahtas** [comment]
Made some tests again, `.press_button()` also executes `.get_button()` so in this case this isn't a solution for the problem but an answer to my question.
