### ISSUE TITLE
app.windows() got empty list ???

### ISSUE THREAD

**Issue by Ranxi** [pywinauto/pywinauto#553]
I used the following code to get a app object, and it executed successfully:
```
from pywinauto.application import Application
c_path = 'D:\\Program Files\\THS\\4.8.1.0\\bin\\transaction\\xiadan.exe'
app = Application(backend="uia").connect(path=c_path)
```
I have checked the supported accessibility technologies for this xiadan.exe application with comparing controls shown in the Spy++ and Inspect.exe. Controls shown in the Spy++ are fragmentary while Inspect.exe perfectly showed out the hierarchy structure of the UI, therefore I chose the UIA backend.
Then, `app` has the correct `process` value which is PID. However, when I want to access its window, I got:
```
>>> app.windows()
[]
```
```
>>> app.top_window()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Program Files\python35\lib\site-packages\pywinauto\application.py", line 1124, in top_window
    raise RuntimeError("No windows for that process could be found")
RuntimeError: No windows for that process could be found
```
Surprisingly, if I choose the default backend `win32`, I can access the windows of `app`, but the structure is scrambled with something missing. It's really difficult to find what I want to automate. 
```
 <hwndwrapper.HwndWrapper - '', Afx:400000:843:0:5:0, 657620>,
 <hwndwrapper.DialogWrapper - 'CMyTimerWnd', Afx:400000:0, 11469250>,
 <hwndwrapper.DialogWrapper - '', Dialog, 4326628>,
 <common_controls.ToolTipsWrapper - '', ToolTips, 5178472>,
 <hwndwrapper.DialogWrapper - '', Dialog, 264288>,
 <hwndwrapper.DialogWrapper - '', Dialog, 329730>,
 <common_controls.ToolTipsWrapper - '', ToolTips, 329728>,
 <hwndwrapper.DialogWrapper - '', Dialog, 1836088>,
 <hwndwrapper.DialogWrapper - '', Dialog, 394880>,
 <common_controls.ToolTipsWrapper - '', ToolTips, 264126>,
 <common_controls.ToolTipsWrapper - '', ToolTips, 133624>,
 <common_controls.ToolTipsWrapper - '', ToolTips, 133642>,
 <common_controls.ToolTipsWrapper - '', ToolTips, 133656>,
 <common_controls.ToolTipsWrapper - '', ToolTips, 133670>,
...
```
How to automate this annoying application?

**Comment by vasily-v-ryabov** [comment]
Hi @Ranxi probably this app creates the hierarchy of windows inside another spawning process with the same `path` but window-less process is found first (might be sporadic). I would recommend `.connect(title="Main window title")` to make it more reliable way for UIA backend.

**Comment by vasily-v-ryabov** [comment]
Possible improvement for `.connect(path=...)` could be choosing the first process with existing windows and warn user if there are several such processes. Maybe some additional criteria like `active_only=True` makes sense (need to check if it's already possible).

**Comment by Ranxi** [comment]
您好，您发的邮件已收到，谢谢！
