### ISSUE TITLE
dict_keys() is empty when trying to select a ListBox item

### ISSUE THREAD

**Issue by vnabokit** [pywinauto/pywinauto#555]
I try to select an item in a ListBox (pywinauto 0.6.5).

The initial script just finds the certain drop down menu inside a dialog.
```
from pywinauto.application import Application
app = Application(backend='uia').start(r"app.exe")
dlg = app.window(best_match='Select Rename Device')
dlg.window(best_match='DownComboBox3').print_control_identifiers()
```
The output seems to be good:
```
ComboBox - ' Down'    (L795, T522, R1157, B542)
['ComboBox', ' DownComboBox', ' Down']
child_window(title=" Down", control_type="ComboBox")
   | 
   | ListBox - ''    (L0, T0, R0, B0)
   | ['', 'ListBox']
   |    | 
   |    | ListItem - '00/4i Simulation mode'    (L1, T1, R752, B24)
   |    | ['00/4i Simulation mode', '00/4i Simulation modeListItem', 'ListItem', 'ListItem0', 'ListItem1']
   |    | child_window(title="00/4i Simulation mode", control_type="ListItem")
   |    | 
   |    | ListItem - '00/2i Simulation mode'    (L1, T24, R752, B47)
   |    | ['00/2i Simulation mode', '00/2i Simulation modeListItem', 'ListItem2']
   |    | child_window(title="00/2i Simulation mode", control_type="ListItem")
   |    | 
   |    | ListItem - '00/6i Simulation mode'    (L1, T47, R752, B70)
   |    | ['00/6i Simulation mode', '00/6i Simulation modeListItem', 'ListItem3']
   |    | child_window(title="00/6i Simulation mode", control_type="ListItem")

Process finished with exit code 0
```

Now I try to select '`00/2i Simulation mode`' ListItem:
```
from pywinauto.application import Application
app = Application(backend='uia').start(r"app.exe")
dlg = app.window(best_match='Select Rename Device')
dlg.window(best_match='DownComboBox3').child_window(best_match='00/2i Simulation mode').select()
```
but got an error:
`pywinauto.findbestmatch.MatchError: Could not find '00/2i Simulation mode' in 'dict_keys([])'`

I tried to apply workaround suggested in the issue #365 but the error was the same:
```
from pywinauto.application import Application
app = Application(backend='uia').start(r"app.exe")
dlg = app.window(best_match='Select Rename Device')
dlg.window(best_match='DownComboBox3').ListBox.child_window(title="00/2i Simulation mode", control_type="ListItem").select()
```

Also, I tried to change backend to `win32` (as #467 suggested).

But the dict_keys() was still empty.

I have no idea where I'm wrong. May anybody suggests a way to solve this issue with drop-down menu selection?

**Comment by vnabokit** [comment]
Additional info.
It seems the ListBox element simply is not included to dict_keys() array.

`dlg.print_control_identifiers()` shows full tree of the dialog. `ListBox` element is included.
```
C:\Users\volodymyr.nabok\AppData\Local\Programs\Python\Python36-32\python.exe C:/Users/volodymyr.nabok/PycharmProjects/stydy1/ft.py
Control Identifiers:

Pane - 'Dialog'    (L720, T395, R1200, B644)
['Pane', 'DialogPane', 'Dialog', 'Pane0', 'Pane1']
child_window(title="Dialog", control_type="Pane")
   | 
   | Custom - ''    (L720, T395, R1200, B644)
   | ['', 'Custom', '0', '1', 'Custom0', 'Custom1']
   |    | 
   |    | Custom - ''    (L735, T410, R1185, B439)
   |    | ['2', 'Custom2']
   |    |    | 
   |    |    | Static - 'Select/Rename Device'    (L744, T416, R1176, B433)
   |    |    | ['Select/Rename Device', 'Select/Rename DeviceStatic', 'Static', 'Static0', 'Static1']
   |    |    | child_window(title="Select/Rename Device", control_type="Text")
   |    | 
   |    | Custom - ''    (L735, T439, R1185, B599)
   |    | ['3', 'Custom3', 'Select/Rename DeviceCustom']
   |    |    | 
   |    |    | Custom - ''    (L744, T448, R1176, B590)
   |    |    | ['4', 'Custom4']
   |    |    |    | 
   |    |    |    | TreeView - ''    (L0, T0, R0, B0)
   |    |    |    | ['5', 'TreeView']
   |    |    |    | 
   |    |    |    | Custom - ''    (L753, T457, R1167, B477)
   |    |    |    | ['6', 'Custom5']
   |    |    |    |    | 
   |    |    |    |    | RadioButton - ''    (L773, T459, R795, B475)
   |    |    |    |    | ['RadioButton', '7', 'RadioButton0', 'RadioButton1']
   |    |    |    |    | 
   |    |    |    |    | Pane - ''    (L795, T458, R971, B475)
   |    |    |    |    | ['8', 'Pane2']
   |    |    |    |    |    | 
   |    |    |    |    |    | Custom - ''    (L795, T458, R971, B475)
   |    |    |    |    |    | ['9', 'Custom6']
   |    |    |    |    |    |    | 
   |    |    |    |    |    |    | Static - '2 Simulation mode'    (L795, T458, R971, B475)
   |    |    |    |    |    |    | ['2 Simulation modeStatic', 'Static2', '2 Simulation mode', '2 Simulation modeStatic0', '2 Simulation modeStatic1']
   |    |    |    |    |    |    | child_window(title="2 Simulation mode", control_type="Text")
   |    |    |    |    | 
   |    |    |    |    | Static - ''    (L981, T457, R1157, B477)
   |    |    |    |    | ['10', '2 Simulation modeStatic2', 'Static3']
   |    |    |    | 
   |    |    |    | Custom - ''    (L753, T483, R1167, B503)
   |    |    |    | ['11', 'Custom7']
   |    |    |    |    | 
   |    |    |    |    | RadioButton - ''    (L773, T485, R795, B501)
   |    |    |    |    | ['RadioButton2', '12']
   |    |    |    |    | 
   |    |    |    |    | Pane - ''    (L795, T484, R971, B501)
   |    |    |    |    | ['13', 'Pane3']
   |    |    |    |    |    | 
   |    |    |    |    |    | Custom - ''    (L795, T484, R971, B501)
   |    |    |    |    |    | ['14', 'Custom8']
   |    |    |    |    |    |    | 
   |    |    |    |    |    |    | Static - '6 Simulation mode'    (L795, T484, R971, B501)
   |    |    |    |    |    |    | ['6 Simulation modeStatic', 'Static4', '6 Simulation mode', '6 Simulation modeStatic0', '6 Simulation modeStatic1']
   |    |    |    |    |    |    | child_window(title="6 Simulation mode", control_type="Text")
   |    |    |    |    | 
   |    |    |    |    | Static - ''    (L981, T483, R1157, B503)
   |    |    |    |    | ['15', '6 Simulation modeStatic2', 'Static5']
   |    |    |    | 
   |    |    |    | Custom - ''    (L753, T509, R1167, B529)
   |    |    |    | ['16', 'Custom9']
   |    |    |    |    | 
   |    |    |    |    | RadioButton - ''    (L773, T511, R795, B527)
   |    |    |    |    | ['RadioButton3', '17']
   |    |    |    |    | 
   |    |    |    |    | Pane - ''    (L795, T510, R971, B527)
   |    |    |    |    | ['18', 'Pane4']
   |    |    |    |    |    | 
   |    |    |    |    |    | Custom - ''    (L795, T510, R971, B527)
   |    |    |    |    |    | ['19', 'Custom10']
   |    |    |    |    |    |    | 
   |    |    |    |    |    |    | Static - '8 Simulation mode'    (L795, T510, R971, B527)
   |    |    |    |    |    |    | ['8 Simulation mode', '8 Simulation modeStatic', 'Static6', '8 Simulation modeStatic0', '8 Simulation modeStatic1']
   |    |    |    |    |    |    | child_window(title="8 Simulation mode", control_type="Text")
   |    |    |    |    | 
   |    |    |    |    | Static - ''    (L981, T509, R1157, B529)
   |    |    |    |    | ['8 Simulation modeStatic2', '20', 'Static7']
   |    |    |    | 
   |    |    |    | Custom - ''    (L753, T535, R1167, B555)
   |    |    |    | ['21', 'Custom11']
   |    |    |    |    | 
   |    |    |    |    | RadioButton - ''    (L773, T537, R795, B553)
   |    |    |    |    | ['RadioButton4', '22']
   |    |    |    |    | 
   |    |    |    |    | Pane - ''    (L795, T536, R971, B553)
   |    |    |    |    | ['23', 'Pane5']
   |    |    |    |    |    | 
   |    |    |    |    |    | Custom - ''    (L795, T536, R971, B553)
   |    |    |    |    |    | ['24', 'Custom12']
   |    |    |    |    |    |    | 
   |    |    |    |    |    |    | Static - '18 Simulation mode'    (L795, T536, R971, B553)
   |    |    |    |    |    |    | ['18 Simulation mode', '18 Simulation modeStatic', 'Static8', '18 Simulation modeStatic0', '18 Simulation modeStatic1']
   |    |    |    |    |    |    | child_window(title="18 Simulation mode", control_type="Text")
   |    |    |    |    | 
   |    |    |    |    | Static - ''    (L981, T535, R1157, B555)
   |    |    |    |    | ['25', '18 Simulation modeStatic2', 'Static9']
   |    |    |    | 
   |    |    |    | Custom - ''    (L753, T561, R1167, B581)
   |    |    |    | ['26', 'Custom13']
   |    |    |    |    | 
   |    |    |    |    | RadioButton - ''    (L773, T563, R795, B579)
   |    |    |    |    | ['RadioButton5', '27']
   |    |    |    |    | 
   |    |    |    |    | ComboBox - ' Down'    (L795, T561, R1157, B581)
   |    |    |    |    | [' DownComboBox', ' Down', 'ComboBox']
   |    |    |    |    | child_window(title=" Down", control_type="ComboBox")
   |    |    |    |    |    | 
   |    |    |    |    |    | ListBox - ''    (L0, T0, R0, B0)
   |    |    |    |    |    | ['28', 'ListBox']
   |    |    |    |    |    |    | 
   |    |    |    |    |    |    | ListItem - '00/4i Simulation mode'    (L1, T1, R752, B24)
   |    |    |    |    |    |    | ['00/4i Simulation modeListItem', '00/4i Simulation mode', 'ListItem', 'ListItem0', 'ListItem1']
   |    |    |    |    |    |    | child_window(title="00/4i Simulation mode", control_type="ListItem")
   |    |    |    |    |    |    | 
   |    |    |    |    |    |    | ListItem - '00/2i Simulation mode'    (L1, T24, R752, B47)
   |    |    |    |    |    |    | ['00/2i Simulation mode', '00/2i Simulation modeListItem', 'ListItem2']
   |    |    |    |    |    |    | child_window(title="00/2i Simulation mode", control_type="ListItem")
   |    |    |    |    |    |    | 
   |    |    |    |    |    |    | ListItem - '00/6i Simulation mode'    (L1, T47, R752, B70)
   |    |    |    |    |    |    | ['00/6i Simulation modeListItem', '00/6i Simulation mode', 'ListItem3']
   |    |    |    |    |    |    | child_window(title="00/6i Simulation mode", control_type="ListItem")
   |    |    |    |    |    |    | 
   |    |    |    |    |    |    | ListItem - '00/5i Simulation mode'    (L1, T70, R752, B93)
   |    |    |    |    |    |    | ['00/5i Simulation mode', 'ListItem4', '00/5i Simulation modeListItem']
   |    |    |    |    |    |    | child_window(title="00/5i Simulation mode", control_type="ListItem")
   |    |    |    |    |    |    | 
   |    |    |    |    |    |    | ListItem - '00/8i Simulation mode'    (L1, T93, R752, B116)
   |    |    |    |    |    |    | ['ListItem5', '00/8i Simulation mode', '00/8i Simulation modeListItem']
   |    |    |    |    |    |    | child_window(title="00/8i Simulation mode", control_type="ListItem")
   |    |    |    |    |    |    | 
   |    |    |    |    |    |    | ListItem - '00/5i Simulation mode'    (L1, T116, R752, B139)
   |    |    |    |    |    |    | ['00/5i Simulation mode', 'ListItem6', '00/5i Simulation modeListItem']
   |    |    |    |    |    |    | child_window(title="00/5i Simulation mode", control_type="ListItem")
   |    |    |    |    |    |    | 
   |    |    |    |    |    |    | ListItem - '00/1i Simulation mode'    (L1, T139, R752, B162)
   |    |    |    |    |    |    | ['00/1i Simulation modeListItem', '00/1i Simulation mode', 'ListItem7']
   |    |    |    |    |    |    | child_window(title="00/1i Simulation mode", control_type="ListItem")
   |    |    |    |    |    |    | 
   |    |    |    |    |    |    | ListItem - '00/1i Simulation mode'    (L1, T162, R752, B185)
   |    |    |    |    |    |    | ['00/1i Simulation mode', 'ListItem8', '00/1i Simulation modeListItem']
   |    |    |    |    |    |    | child_window(title="00/1i Simulation mode", control_type="ListItem")
   |    | 
   |    | Custom - ''    (L735, T599, R1185, B629)
   |    | ['29', 'Custom14']
   |    |    | 
   |    |    | Button - 'OK Enter'    (L915, T604, R1006, B624)
   |    |    | ['OK EnterButton', 'OK Enter', 'Button']
   |    |    | child_window(title="OK Enter", control_type="Button")

Process finished with exit code 0
```

I try to select an item via `.ListBox` object:
```
dlg.ListBox.window(title='00/2i Simulation mode').select()
```

but `dict_keys()` does not contain `ListBox`:
```
pywinauto.findbestmatch.MatchError: Could not find 'ListBox' in 'dict_keys(['', 'Custom', '0', '1', '2', 'Custom0', 'Custom1', 'Custom2', 'Static', 'Select/Rename DeviceStatic', 'Select/Rename Device', '3', 'Custom3', 'Select/Rename DeviceCustom', '4', 'Custom4', '5', 'Custom5', '6', 'RadioButton', '7', 'Pane', '8', 'Custom6', 'Static0', 'Static1', 'Static2', 'FiX 82 Simulation modeStatic', 'FiX 82 Simulation mode', '9', 'Static3', 'FiX 82 Simulation modeStatic0', 'FiX 82 Simulation modeStatic1', 'FiX 82 Simulation modeStatic2', '10', 'Custom7', '11', 'RadioButton0', 'RadioButton1', 'RadioButton2', '12', 'Pane0', 'Pane1', 'Pane2', '13', 'Custom8', 'Static4', 'FiX 86 Simulation modeStatic', 'FiX 86 Simulation mode', '14', 'Static5', 'FiX 86 Simulation modeStatic0', 'FiX 86 Simulation modeStatic1', 'FiX 86 Simulation modeStatic2', '15', 'Custom9', '16', 'RadioButton3', '17', 'Pane3', '18', 'Custom10', 'Static6', 'TwK 88 Simulation mode', 'TwK 88 Simulation modeStatic', '19', 'Static7', 'TwK 88 Simulation modeStatic0', 'TwK 88 Simulation modeStatic1', 'TwK 88 Simulation modeStatic2', '20', 'Custom11', '21', 'RadioButton4', '22', 'Pane4', '23', 'Custom12', 'Static8', 'TwK D8 Simulation modeStatic', 'TwK D8 Simulation mode', '24', 'Static9', 'TwK D8 Simulation modeStatic0', 'TwK D8 Simulation modeStatic1', 'TwK D8 Simulation modeStatic2', '25', 'Custom13', '26', 'RadioButton5', ' DownComboBox', 'ComboBox', ' Down', '27', 'Custom14', 'Button', 'OK Enter', 'OK EnterButton'])'
```

When I tried to use
```
dlg.ComboBox.window(title='00/2i Simulation mode').select()
```

then it causes the error:
```
pywinauto.findwindows.ElementNotFoundError: {'title': '00/2i Simulation mode', 'top_level_only': False, 'parent': <uia_element_info.UIAElementInfo - ' Down', , None>, 'backend': 'uia'}
```

I freaked out and tried to access via indexes:

```
dlg[27][1].select()
```

But received an error again:
```
AttributeError: The control does not have a __getitem__ method for item access (i.e. ctrl[key]) so maybe you have requested this in error?
```

Sorry for long description. I will update this issue once smth new would be found.

**Comment by vnabokit** [comment]
Try to use
```
dlg.window(best_match='ComboBox').select('00/2i Simulation mode')
```

but the error rises:
```
Traceback (most recent call last):
  File "C:\Users\volodymyr.nabok\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pywinauto\uia_defines.py", line 232, in get_elem_interface
    iface = cur_ptrn.QueryInterface(cls_name)
  File "C:\Users\volodymyr.nabok\AppData\Local\Programs\Python\Python36-32\lib\site-packages\comtypes\__init__.py", line 1156, in QueryInterface
    self.__com_QueryInterface(byref(iid), byref(p))
ValueError: NULL COM pointer access

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/volodymyr.nabok/PycharmProjects/stydy1/ft.py", line 10, in <module>
    dlg.window(best_match='ComboBox').select('VX600/2i Simulation mode')
  File "C:\Users\volodymyr.nabok\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pywinauto\controls\uia_controls.py", line 158, in select
    self.expand()
  File "C:\Users\volodymyr.nabok\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pywinauto\controls\uiawrapper.py", line 527, in expand
    self.iface_expand_collapse.Expand()
  File "C:\Users\volodymyr.nabok\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pywinauto\controls\uiawrapper.py", line 132, in __get__
    value = self.fget(obj)
  File "C:\Users\volodymyr.nabok\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pywinauto\controls\uiawrapper.py", line 210, in iface_expand_collapse
    return uia_defs.get_elem_interface(elem, "ExpandCollapse")
  File "C:\Users\volodymyr.nabok\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pywinauto\uia_defines.py", line 234, in get_elem_interface
    raise NoPatternInterfaceError()
pywinauto.uia_defines.NoPatternInterfaceError
```

**Comment by vnabokit** [comment]
**Use Case.
Select an item from ComboBox control for an Qt5.6 application.**

App example: https://fex.net/485689299381 (it is standard 'blockingslave.exe' Qt app compiled via QtCreator using MinGW)
_Note: Activate a COM port before using this app (I plugged an USB device, USB type B)_

**Actual Result:**
Such constructions do not work:
```
dlg.child_window(title=' Down').child_window(best_match='ListBox').select('COM12')
```
or
```
dlg.ComboBox.child_window(best_match='ListBox').select('COM12')
```
or
```
dlg.ComboBox.ListBox.select(0)
```

**Expected Result:**
Ability to make selection by any way.

**Full script code:**
```
from pywinauto.application import Application
import time

app_full_path = r'C:\Qt56\Examples\Qt-5.6\serialport\build-blockingslave-Desktop_Qt_5_6_2_MinGW_32bit-Debug\debug\blockingslave.exe'
app = Application(backend='uia').start(app_full_path)
time.sleep(2)
dlg = app.window(best_match='Dialog')
dlg.child_window(title=' Down').child_window(best_match='ListBox').select('COM12')

```

**Screens:**
![screenshot_25](https://user-images.githubusercontent.com/16936389/44902771-83155f80-ad13-11e8-9a2f-136381b46543.png)
![screenshot_24](https://user-images.githubusercontent.com/16936389/44902772-83155f80-ad13-11e8-8ff2-8ed7784baef7.png)
![screenshot_23](https://user-images.githubusercontent.com/16936389/44902773-83adf600-ad13-11e8-8392-d6df8ef9b8c3.png)

**Comment by vasily-v-ryabov** [comment]
I've found tricky workaround for WireShark combo box that I think could be used for your app as well:
```python
combo.invoke()
app.window(title="00/2i Simulation mode", control_type='ListItem', top_level_only=False).click_input()
```
If I use `.select()` or `.invoke()` instead of `.click_input()` it does select the item but doesn't apply it to combo box and doesn't close drop down list.

I need more time to adopt this code for wrapper to handle Qt5 case. Marking as enhancement.

**Comment by vnabokit** [comment]
Really, it works!
But I made one change in your suggestion. I used `combo.child_window()` instead of `app.window()`.
