### ISSUE TITLE
How to navigate

### ISSUE THREAD

**Issue by rajarameshmamidi** [pywinauto/pywinauto#557]
Hi All,

is there a way to navigate / drill down /drill up with the help of pywinauto?  if yes, can you share the details...!

i have a scenario related to this, below is the screenshot where i need to navigate,
![navigate](https://user-images.githubusercontent.com/42936846/44989490-a8bc9600-afab-11e8-9b1e-d87f9d642919.PNG)
 

Thanks,
Rajarameshmamidi

**Comment by vasily-v-ryabov** [comment]
This is not easy to help without details. Read the Getting Started Guide first and provide what you've already tried. This picture looks like `TreeView` control, but how about `Inspect.exe` screenshot? The link to Inspect.exe can be found in the guide as well. Please be prepared to use my time effectively.

**Comment by rajarameshmamidi** [comment]
Hi Vasily,

i am trying to select treeView with below code but not able due to  multiple screens with duplicate names. i have attached the screens of app and inspect.exe

app.CA_Harvest_Software_Change_Manager_Workbench['Package:TreeView'].TreeView.Select('\cdtsapp375p').click_input('double') #not working

app.CA_Harvest_Software_Change_Manager_Workbench['TreeView'].get_item('\cdtsapp375p').ClickInput('right')  #not working
app.CA_Harvest_Software_Change_Manager_Workbench['SWT_Window00'].TreeView.click_input('right') 

![Uploading Har_control.png…]()

 

 

Thanks,
Raja

**Comment by vasily-v-ryabov** [comment]
Any more details? Or we can close this?

**Comment by vasily-v-ryabov** [comment]
@rajarameshmamidi it looks like your reply is not posted here, I can see it in e-mail only. Did you delete it? Or still awaiting my reply?

**Comment by rajarameshmamidi** [comment]
hi vasily,

i ma trying to click the treeview but not able to and error message say's duplicate with same names below are the inspect details.

[Har_control.zip](https://github.com/pywinauto/pywinauto/files/2424413/Har_control.zip)

**Comment by rajarameshmamidi** [comment]
this is the major one for me which contains many conditions and need to compare the values from treeview. i can explore more once i am able to double click above tree view.

**Comment by rajarameshmamidi** [comment]
Hi Vasily,

i am able to achieve to click an item from treeview if i close other windows which has treeview structure . 
below is the code which i used, it works  once or twice but not for multiple times.

app.CA_Harvest_Software_Change_Manager_Workbench.TreeView.get_item('\cdtsapp375p').click_input('left','double')

and when i use as below i am getting an error...
app.CA_Harvest_Software_Change_Manager_Workbench.wait('visible',20)
app.CA_Harvest_Software_Change_Manager_Workbench.TreeView.get_item('\cdtsapp375p').click_input('left','double')
   Traceback (most recent call last):
  File "C:/Users/rrmamidi/Desktop/old Desktop/compress_1/python/basic python scripts/open harvest.py", line 24, in <module>
    app.CA_Harvest_Software_Change_Manager_Workbench.wait('visible',20)
  File "C:\Users\rrmamidi\AppData\Local\Programs\Python\Python36\lib\site-packages\pywinauto-0.6.5-py3.6.egg\pywinauto\application.py", line 502, in wait
    lambda: self.__check_all_conditions(check_method_names, retry_interval))
  File "C:\Users\rrmamidi\AppData\Local\Programs\Python\Python36\lib\site-packages\pywinauto-0.6.5-py3.6.egg\pywinauto\timings.py", line 366, in wait_until
    func_val = func(*args, **kwargs)
  File "C:\Users\rrmamidi\AppData\Local\Programs\Python\Python36\lib\site-packages\pywinauto-0.6.5-py3.6.egg\pywinauto\application.py", line 502, in <lambda>
    lambda: self.__check_all_conditions(check_method_names, retry_interval))
  File "C:\Users\rrmamidi\AppData\Local\Programs\Python\Python36\lib\site-packages\pywinauto-0.6.5-py3.6.egg\pywinauto\application.py", line 461, in __check_all_conditions
    ctrls = self.__resolve_control(self.criteria, retry_interval, float(retry_interval) // 2)
  File "C:\Users\rrmamidi\AppData\Local\Programs\Python\Python36\lib\site-packages\pywinauto-0.6.5-py3.6.egg\pywinauto\application.py", line 249, in __resolve_control
    criteria)
  File "C:\Users\rrmamidi\AppData\Local\Programs\Python\Python36\lib\site-packages\pywinauto-0.6.5-py3.6.egg\pywinauto\timings.py", line 453, in wait_until_passes
    func_val = func(*args, **kwargs)
  File "C:\Users\rrmamidi\AppData\Local\Programs\Python\Python36\lib\site-packages\pywinauto-0.6.5-py3.6.egg\pywinauto\application.py", line 191, in __get_ctrl
    dialog = self.backend.generic_wrapper_class(findwindows.find_element(**criteria[0]))
  File "C:\Users\rrmamidi\AppData\Local\Programs\Python\Python36\lib\site-packages\pywinauto-0.6.5-py3.6.egg\pywinauto\findwindows.py", line 84, in find_element
    elements = find_elements(**kwargs)
  File "C:\Users\rrmamidi\AppData\Local\Programs\Python\Python36\lib\site-packages\pywinauto-0.6.5-py3.6.egg\pywinauto\findwindows.py", line 303, in find_elements
    elements = findbestmatch.find_best_control_matches(best_match, wrapped_elems)
  File "C:\Users\rrmamidi\AppData\Local\Programs\Python\Python36\lib\site-packages\pywinauto-0.6.5-py3.6.egg\pywinauto\findbestmatch.py", line 494, in find_best_control_matches
    name_control_map = build_unique_dict(controls)
  File "C:\Users\rrmamidi\AppData\Local\Programs\Python\Python36\lib\site-packages\pywinauto-0.6.5-py3.6.egg\pywinauto\findbestmatch.py", line 473, in build_unique_dict
    ctrl_names = get_control_names(ctrl, controls, text_ctrls)
  File "C:\Users\rrmamidi\AppData\Local\Programs\Python\Python36\lib\site-packages\pywinauto-0.6.5-py3.6.egg\pywinauto\findbestmatch.py", line 320, in get_control_names
    non_text_names = get_non_text_control_name(control, allcontrols, textcontrols)
  File "C:\Users\rrmamidi\AppData\Local\Programs\Python\Python36\lib\site-packages\pywinauto-0.6.5-py3.6.egg\pywinauto\findbestmatch.py", line 219, in get_non_text_control_name
    ctrl_r = ctrl.rectangle()
  File "C:\Users\rrmamidi\AppData\Local\Programs\Python\Python36\lib\site-packages\pywinauto-0.6.5-py3.6.egg\pywinauto\base_wrapper.py", line 337, in rectangle
    return self.element_info.rectangle
  File "C:\Users\rrmamidi\AppData\Local\Programs\Python\Python36\lib\site-packages\pywinauto-0.6.5-py3.6.egg\pywinauto\win32_element_info.py", line 181, in rectangle
    return handleprops.rectangle(self.handle)
  File "C:\Users\rrmamidi\AppData\Local\Programs\Python\Python36\lib\site-packages\pywinauto-0.6.5-py3.6.egg\pywinauto\handleprops.py", line 207, in rectangle
    return win32structures.RECT(*win32gui.GetWindowRect(handle))
pywintypes.error: (1400, 'GetWindowRect', 'Invalid window handle.')


Thanks,
Raja

**Comment by rajarameshmamidi** [comment]
Also , i tried below code to select an item from popupmenu , after selecting the treeview(with one window) and got error

app.PopupMenuDailog.menu_select(9).click_input() 
below error 
 builtins.AttributeError: 'int' object has no attribute 'split'
app.PopupMenu.menu().get_menu_path("Create Path")[0].click() 

 got below information
C:\Users\rrmamidi\AppData\Local\Programs\Python\Python36\lib\site-packages\win32\lib\win32gui_struct.py:69: DeprecationWarning: unicode_internal codec has been deprecated
data = (text+'\0').encode("unicode-internal")

app.ContextMenu['Create Path'].invoke()
pywinauto.findbestmatch.MatchError: Could not find 'Context' in 'dict_keys(['', 'PopupMenu', '0', '1', '2', 'SysShadow', 'CA Harvest Software Change Manager Workbench', 'CA Harvest Software Change Manager WorkbenchSWT_Window0', 'SWT_Window0'])'

**Comment by vasily-v-ryabov** [comment]
* This one is known issue #534: `pywintypes.error: (1400, 'GetWindowRect', 'Invalid window handle.')` It was introduced in `pywinauto==0.6.5` so temporary downgrade to `pywinauto==0.6.4` would help till `pywinauto==0.6.6` is out.

* `menu_select(9)` is incorrect. It should look so: `app.PopupMenu.menu_item('#9').click()`.

* Warning about `encode("unicode-internal")` relates to `pywin32` package, not to pywinauto.

* `Could not find 'Context'` message looks correct. The code should be `app.PopupMenu.menu_item('Create Path').click()`.

**Comment by rajarameshmamidi** [comment]
Hi Vasily,

1. I have downgrade to 0.6.4

2. Do i need upgrade pywin32 ?
 
3. now i am able to click the popup menu items. i am trying to get the controls of this window. but the app is closing automatically after opening create path window. Any idea why is it happening. i am using below code for controls(with the help of Inspect i got that this window is Dialog ,

app.Create_PathDailog.print_control_identifiers()

![create path screen](https://user-images.githubusercontent.com/42936846/46481337-cc743580-c810-11e8-9e19-a63a567dd9a3.PNG)

Thanks,
Raja

**Comment by vasily-v-ryabov** [comment]
As far as I know, there is no fix in pywin32. Anyway it's just a warning.

The app accidentally disappeared after call to `app.Create_PathDailog.print_control_identifiers()`, right? It might be a bug in the app. Some internal text retrieving handler may crash the app. Did you try touching every element of this dialog by `Inspect.exe`? If the app crashes as well, it's a bug in the app 100%. Otherwise it might be sporadic crash. Probably you will need help from app developers in the issue investigation.

**Comment by vasily-v-ryabov** [comment]
I still don't understand what is crashing: Python or the app.

If the app is crashing, this might be a timing issue or non-finished lazy initialization on app side (need `app.wait_cpu_usage_lower()` then).

If Python script is crashing, please provide traceback of the error.

**Comment by vasily-v-ryabov** [comment]
OK, now the situation looks clear to me. If window "Demote to Handoff to QA" was unexpectedly disappeared, it's definitely an app side problem.
