### ISSUE TITLE
Error message COMError: (-2147220991...) from menu_select

### ISSUE THREAD

**Issue by taiqixp** [pywinauto/pywinauto#563]
Hi there,

Thanks for providing this tool. I ran into one issue today. I am using the latest version of pywinauto on Windows 10 with one app coded on Winform.

After the following script is executed, I got the error message:
COMError: (-2147220991, 'An event was unable to invoke any of the subscribers', (None, None, None, 0, None))
`Application(backend="uia").start(apptorun)
app = Application(backend="uia").connect(path = apptorun)
windowsMain = app['Main Window']
windowsMain.menu_select("Help->About")`

So my question is :
1) Any idea why we have this error? It seems program is waiting for this window closed.
2) Do we have way to set timeout for menu_select?

Thanks,

**Comment by vasily-v-ryabov** [comment]
Hi @taiqixp unfortunately there is no timeout for `menu_select`, though it's possible to use `app.wait_cpu_usage_lower()` to ensure app finished using CPU intensively (so some lazy initialization is done).

But usually such a `COMError` means something goes wrong inside `invoke` handler of the control (on app side). Or the element doesn't exist. Full traceback of the error would be more helpful.

**Comment by taiqixp** [comment]
Hi Vasily,
Thanks for the help.

I attached the full traceback of the error as followings. If you have any idea, just let me know.
I am just guessing the subwindow pops up and blocks my script, but dont know why it happened.

`Traceback (most recent call last):

  File "<ipython-input-8-7b0a693d5dac>", line 1, in <module>
    runfile('C:/Users/steven.yu/.spyder-py3/BugofAboutInvoke.py', wdir='C:/Users/steven.yu/.spyder-py3')

  File "C:\Users\steven.yu\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\steven.yu\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/steven.yu/.spyder-py3/BugofAboutInvoke.py", line 26, in <module>
    windowsMain.menu_select("Help->About")

  File "C:\Users\steven.yu\AppData\Local\Continuum\anaconda3\lib\site-packages\pywinauto\controls\uiawrapper.py", line 723, in menu_select
    menu.item_by_path(path, exact).select()

  File "C:\Users\steven.yu\AppData\Local\Continuum\anaconda3\lib\site-packages\pywinauto\controls\uia_controls.py", line 768, in select
    self.iface_invoke.Invoke()

COMError: (-2147220991, 'An event was unable to invoke any of the subscribers', (None, None, None, 0, None))`

**Comment by vasily-v-ryabov** [comment]
What kind of app do you automate? Is it Qt5? or something more specific?
If it's available for download, please provide a link. I need to take a look.

**Comment by taiqixp** [comment]
Alright. I have one workaround now.
Thanks for your help.
`windowsMain = app['Main Window']
help = windowsMain['Help'].select()
submenu = app['Dialog'] # Dropdown submenu is a top-level window
submenu['About'].click_input() # or .click_input()`

**Comment by codeNameMahi** [comment]
I am having a similar problem and worked around it using a similar method. See: Issue #621 

My problem is that, even with the workaround, I get COMError when I attempt to write text into the application using the .set_edit_text method, even though the text is correctly being input.

**Comment by malathisathya** [comment]
I'm also hitting the same issue when I'm trying to click on a button which looks disabled but actually it is enabled. I'm unable to access that specific button since it is having wrapper 

> *** _ctypes.COMError: (-2147220992, None, (None, None, None, 0, None))

**Comment by pakal** [comment]
I've gotten this error randomly for the past weeks, mostly when trying to input text into a "save as..." combobox (the error came from the automation interface SetValue()).

No idea what it's coming from, it seems to be better now that I focus() the combobox before inputing text.

**Comment by basicAuto** [comment]
I'm also having this problem. Even though I can get past it, now everything I type trips it.
So even doing print("hi") will cause the comerror until I restart my debugger.

`_ctypes.COMError: (-2147220991, 'An event was unable to invoke any of the subscribers', (None, None, None, 0, None))
Unexpected error, recovered safely.`

**Comment by airelil** [comment]
There is a chance that the COM error -2147220991 could be related to pywinauto internal caching of UIA interfaces. @basicAuto , you could try to patch temporarily your pywinauto installation and see if the problem goes away. To disable the caching you need to comment in this line in your pywinauto sources:
https://github.com/pywinauto/pywinauto/blob/5832acf8dd5a92852d3d5b328064f023b5d68e4a/pywinauto/controls/uiawrapper.py#L133

Another way to disable the caching is to remove `@lazy_property` decorator on `UIAWrapper.iface_*` methods.

**Comment by basicAuto** [comment]
This is an ongoing pain point for me as well. It's breaking my scrips... Is there any fix in the works or anything I can do about it myself?

**Comment by basicAuto** [comment]
This also happens when just trying to access the value in the text box:

`Save_As_File_Name_Box.get_value
<bound method EditWrapper.get_value of <uia_controls.EditWrapper - 'File name:', Edit, -4097925828434660645>>
Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\site-packages\pywinauto\application.py", line 250, in __resolve_control
    ctrl = wait_until_passes(
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\site-packages\pywinauto\timings.py", line 458, in wait_until_passes
    raise err
pywinauto.timings.TimeoutError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.3.1\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_xml.py", line 282, in frame_vars_to_xml
    xml += var_to_xml(v, str(k), evaluate_full_value=eval_full_val)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.3.1\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_xml.py", line 369, in var_to_xml
    elif hasattr(v, "__len__") and not is_string(v):
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\site-packages\pywinauto\application.py", line 379, in __getattribute__
    ctrls = self.__resolve_control(self.criteria)
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\site-packages\pywinauto\application.py", line 261, in __resolve_control
    raise e.original_exception
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\site-packages\pywinauto\timings.py", line 436, in wait_until_passes
    func_val = func(*args, **kwargs)
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\site-packages\pywinauto\application.py", line 222, in __get_ctrl
    ctrl = self.backend.generic_wrapper_class(findwindows.find_element(**ctrl_criteria))
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\site-packages\pywinauto\findwindows.py", line 87, in find_element
    raise ElementNotFoundError(kwargs)
pywinauto.findwindows.ElementNotFoundError: {'best_match': 'vset_text', 'top_level_only': False, 'parent': <uia_element_info.UIAElementInfo - 'File name:', Edit, 19273026>, 'backend': 'uia'}
Unexpected error, recovered safely.
`

**Comment by airelil** [comment]
I think, the `print("hi")` error is not exactly related to the problem. You, probably, getting this error because your debugger tries to refresh the values of variables you trace or some other "live inspection" activity. Just look at your trace:  'pydevd_xml.py", line 282, in frame_vars_to_xml...'

@basicAuto , also, could you explain what kind of application you try to automate? Is it regular win32 or something else, like WPF or QT5?

**Comment by basicAuto** [comment]
@airelil 

Thanks for the response, it is definitely WPF

**Comment by iamvkundra** [comment]
I'm also getting same error while printing all the controls of the window using print_control_identifiers(). 
Can anyone help?

**Comment by rajvar2607** [comment]
I too am facing the same issue, while trying to click on sub_menu, under applications file menu.
It waits for a long and then fails. I am able to click on the sub_menu but after that no operations get performed. If some one can help, would be really great for me.

I am using codes as below.
window.menu_select("File->SaveAs->PublicGallery->AlteryxGallery")
window.child_window(title="Save Workflow", auto_id="CefBrowserDialog", control_type="Window").wrapper_object().click_input()


But then getting below error after menus are selected.

    _ctypes.COMError: (-2147220991, 'An event was unable to invoke any of the subscribers', (None, None, None, 0, None))

**Comment by mkq10** [comment]
@rajvar2607 facing same issue as you have mentioned. How did you resolve ?

**Comment by saimadao** [comment]
I think the problem form menu_select() function.
I change the menu.item_by_path(path, exact).**select**() to menu.item_by_path(path, exact).**click_input**() in UIAWrapper.menu_select(), it works.
I am not sure, but the select() function is special

**Comment by saimadao** [comment]
seems select() function run faster than realistic select menu action, 
but the the realistic select menu action will still achieve later.
