### ISSUE TITLE
How to get certain value of cell in a table if the rows are dynamic.

### ISSUE THREAD

**Issue by smitagodbole** [pywinauto/pywinauto#566]
Hi,
I am running into a problem which has a table and it contains columns and rows.  Number of columns are fixed but number of rows are dynamic.  I need to find out certain value of the cell if it is exists.  
---------------------------------------------------------------------------------------------
Name | LastName | OrderID
-- | -- | --
smita1 |   |  
Smita2 |   |  
**Smita3** |   |  

I need to find out  cell value 'Smita3' which some times display at row 3 or row 4 or row 5.  How can I do that.
-------------------------------------------------------------------------------
I tried following code...

cTable = MyApp1.child_window(title="orderTable",control_type="Table").wrapper_object()
dItem = pywinauto.findwindows.find_windows(title_re ="Name.*",control_type = "DataItem",found_index=0)
nName = int(len(cTable.descendants(title="Name",control_type="DataItem")))
print(nName)
for i in range(nName):
	cell = MyApp1.cTable.dItem
	print (cell.iface_value.CurrentValue)

	i += i+1

when I run this I get following  error traceback...
C:\pywinauto065\pywinauto-0.6.5\Scripts>python Scheduling_1.py
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "C:\Python37\lib\site-packages\pywinauto\win32_element_info.py", line 138, in enum_window_proc
    if control_type is not None and control_type != element.control_type:
  File "C:\Python37\lib\site-packages\pywinauto\win32_element_info.py", line 235, in control_type
    return self.__get_control_type(full=False)
  File "C:\Python37\lib\site-packages\pywinauto\win32_element_info.py", line 216, in __get_control_type
    remote_mem = RemoteMemoryBlock(self, size=length*2)
  File "C:\Python37\lib\site-packages\pywinauto\remote_memory_block.py", line 105, in __init__
    if hex(self.mem_address) == '0xffffffff80000000' or hex(self.mem_address).upper() == '0xFFFFFFFF00000000':
TypeError: 'NoneType' object cannot be interpreted as an integer
Exception ignored in: <function RemoteMemoryBlock.__del__ at 0x0000021C61266AE8>
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\pywinauto\remote_memory_block.py", line 163, in __del__
    self.CleanUp()
  File "C:\Python37\lib\site-packages\pywinauto\remote_memory_block.py", line 140, in CleanUp
    self.CheckGuardSignature()
  File "C:\Python37\lib\site-packages\pywinauto\remote_memory_block.py", line 279, in CheckGuardSignature
    ctypes.c_void_p(self.mem_address + self.size),
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "C:\Python37\lib\site-packages\pywinauto\win32_element_info.py", line 138, in enum_window_proc
    if control_type is not None and control_type != element.control_type:
  File "C:\Python37\lib\site-packages\pywinauto\win32_element_info.py", line 235, in control_type
    return self.__get_control_type(full=False)
  File "C:\Python37\lib\site-packages\pywinauto\win32_element_info.py", line 216, in __get_control_type
    remote_mem = RemoteMemoryBlock(self, size=length*2)
  File "C:\Python37\lib\site-packages\pywinauto\remote_memory_block.py", line 105, in __init__
    if hex(self.mem_address) == '0xffffffff80000000' or hex(self.mem_address).upper() == '0xFFFFFFFF00000000':
TypeError: 'NoneType' object cannot be interpreted as an integer
Exception ignored in: <function RemoteMemoryBlock.__del__ at 0x0000021C61266AE8>
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\pywinauto\remote_memory_block.py", line 163, in __del__
    self.CleanUp()
  File "C:\Python37\lib\site-packages\pywinauto\remote_memory_block.py", line 140, in CleanUp
    self.CheckGuardSignature()
  File "C:\Python37\lib\site-packages\pywinauto\remote_memory_block.py", line 279, in CheckGuardSignature
    ctypes.c_void_p(self.mem_address + self.size),
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "C:\Python37\lib\site-packages\pywinauto\win32_element_info.py", line 138, in enum_window_proc
    if control_type is not None and control_type != element.control_type:
  File "C:\Python37\lib\site-packages\pywinauto\win32_element_info.py", line 235, in control_type
    return self.__get_control_type(full=False)
  File "C:\Python37\lib\site-packages\pywinauto\win32_element_info.py", line 216, in __get_control_type
    remote_mem = RemoteMemoryBlock(self, size=length*2)
  File "C:\Python37\lib\site-packages\pywinauto\remote_memory_block.py", line 105, in __init__
    if hex(self.mem_address) == '0xffffffff80000000' or hex(self.mem_address).upper() == '0xFFFFFFFF00000000':
TypeError: 'NoneType' object cannot be interpreted as an integer
Exception ignored in: <function RemoteMemoryBlock.__del__ at 0x0000021C61266AE8>
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\pywinauto\remote_memory_block.py", line 163, in __del__
    self.CleanUp()
  File "C:\Python37\lib\site-packages\pywinauto\remote_memory_block.py", line 140, in CleanUp
    self.CheckGuardSignature()
  File "C:\Python37\lib\site-packages\pywinauto\remote_memory_block.py", line 279, in CheckGuardSignature
    ctypes.c_void_p(self.mem_address + self.size),
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "C:\Python37\lib\site-packages\pywinauto\win32_element_info.py", line 138, in enum_window_proc
    if control_type is not None and control_type != element.control_type:
  File "C:\Python37\lib\site-packages\pywinauto\win32_element_info.py", line 235, in control_type
    return self.__get_control_type(full=False)
  File "C:\Python37\lib\site-packages\pywinauto\win32_element_info.py", line 216, in __get_control_type
    remote_mem = RemoteMemoryBlock(self, size=length*2)
  File "C:\Python37\lib\site-packages\pywinauto\remote_memory_block.py", line 89, in __init__
    process_id)
pywinauto.remote_memory_block.AccessDenied: ('[WinError 5] Access is denied.process: %d', 14884)
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "C:\Python37\lib\site-packages\pywinauto\win32_element_info.py", line 138, in enum_window_proc
    if control_type is not None and control_type != element.control_type:
  File "C:\Python37\lib\site-packages\pywinauto\win32_element_info.py", line 235, in control_type
    return self.__get_control_type(full=False)
  File "C:\Python37\lib\site-packages\pywinauto\win32_element_info.py", line 216, in __get_control_type
    remote_mem = RemoteMemoryBlock(self, size=length*2)
  File "C:\Python37\lib\site-packages\pywinauto\remote_memory_block.py", line 105, in __init__
    if hex(self.mem_address) == '0xffffffff80000000' or hex(self.mem_address).upper() == '0xFFFFFFFF00000000':
TypeError: 'NoneType' object cannot be interpreted as an integer
Exception ignored in: <function RemoteMemoryBlock.__del__ at 0x0000021C61266AE8>
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\pywinauto\remote_memory_block.py", line 163, in __del__
    self.CleanUp()
  File "C:\Python37\lib\site-packages\pywinauto\remote_memory_block.py", line 140, in CleanUp
    self.CheckGuardSignature()
  File "C:\Python37\lib\site-packages\pywinauto\remote_memory_block.py", line 279, in CheckGuardSignature
    ctypes.c_void_p(self.mem_address + self.size),
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "C:\Python37\lib\site-packages\pywinauto\win32_element_info.py", line 138, in enum_window_proc
    if control_type is not None and control_type != element.control_type:
  File "C:\Python37\lib\site-packages\pywinauto\win32_element_info.py", line 235, in control_type
    return self.__get_control_type(full=False)
  File "C:\Python37\lib\site-packages\pywinauto\win32_element_info.py", line 216, in __get_control_type
    remote_mem = RemoteMemoryBlock(self, size=length*2)
  File "C:\Python37\lib\site-packages\pywinauto\remote_memory_block.py", line 105, in __init__
    if hex(self.mem_address) == '0xffffffff80000000' or hex(self.mem_address).upper() == '0xFFFFFFFF00000000':
TypeError: 'NoneType' object cannot be interpreted as an integer
Exception ignored in: <function RemoteMemoryBlock.__del__ at 0x0000021C61266AE8>
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\pywinauto\remote_memory_block.py", line 163, in __del__
    self.CleanUp()
  File "C:\Python37\lib\site-packages\pywinauto\remote_memory_block.py", line 140, in CleanUp
    self.CheckGuardSignature()
  File "C:\Python37\lib\site-packages\pywinauto\remote_memory_block.py", line 279, in CheckGuardSignature
    ctypes.c_void_p(self.mem_address + self.size),
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "C:\Python37\lib\site-packages\pywinauto\win32_element_info.py", line 138, in enum_window_proc
    if control_type is not None and control_type != element.control_type:
  File "C:\Python37\lib\site-packages\pywinauto\win32_element_info.py", line 235, in control_type
    return self.__get_control_type(full=False)
  File "C:\Python37\lib\site-packages\pywinauto\win32_element_info.py", line 216, in __get_control_type
    remote_mem = RemoteMemoryBlock(self, size=length*2)
  File "C:\Python37\lib\site-packages\pywinauto\remote_memory_block.py", line 105, in __init__
    if hex(self.mem_address) == '0xffffffff80000000' or hex(self.mem_address).upper() == '0xFFFFFFFF00000000':
TypeError: 'NoneType' object cannot be interpreted as an integer
3
Smita1
Smita1
Smita1
Exception ignored in: <function RemoteMemoryBlock.__del__ at 0x0000021C61266AE8>
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\pywinauto\remote_memory_block.py", line 163, in __del__
    self.CleanUp()
  File "C:\Python37\lib\site-packages\pywinauto\remote_memory_block.py", line 140, in CleanUp
    self.CheckGuardSignature()
  File "C:\Python37\lib\site-packages\pywinauto\remote_memory_block.py", line 279, in CheckGuardSignature
    ctypes.c_void_p(self.mem_address + self.size),
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

Thanks
Smita

**Comment by vasily-v-ryabov** [comment]
The problem is that you're using internal low level function `find_windows` which is not recommended. This function uses default backend `"win32"` while your high level code uses `backend="uia"` that comes from `Application` object. Technically it's possible to pass `backend="uia"` param to `find_elements` (`find_windows` is a wrapper around `find_elements` for backward compatibility with old "win32" code), but `find_elements` will return internal objects, not a list of wrappers. So I don't recommend it in any case.

How to handle this correctly:
```python
cTableSpec = MyApp1.child_window(title="orderTable",control_type="Table")
cTable = cTableSpec.wrapper_object()
dItemSpec = cTableSpec.child_window(title_re="Name.*", control_type="DataItem", found_index=0)
dItem = dItemSpec.wrapper_object()
```

We're planning to simplify such cases. For example, we want to allow creating `WindowSpecification` from parent wrapper, not necessary only parent `WindowSpecification`.

**Comment by vasily-v-ryabov** [comment]
I've filed issue #570 for tracking this feature.

**Comment by smitagodbole** [comment]
Thank you very much Vasily.  I tried the way you mentioned and exceptions are not showing any more but result is showing same  i.e. 
![image](https://user-images.githubusercontent.com/38377501/45687866-de21c180-bb1d-11e8-8c37-3894610a1f00.png)
where I was expecting it should display...
3
Smita1
Smita2
Smita3


Thanks
Smita

**Comment by vasily-v-ryabov** [comment]
If you're listing `DataItem`s as linear iterator (`.descendants()` returns a plain list), length of row have to be counted. I mean `i = i + 1` should be replaced by `i = i + 3` if there are 3 columns.

**Comment by smitagodbole** [comment]
Hi,
I tried again by i = i +3 and it gives me same results.. i.e.
![image](https://user-images.githubusercontent.com/38377501/45930302-57f5e880-bf2c-11e8-8906-2c1f4704a342.png)
Thanks
Smita

**Comment by vasily-v-ryabov** [comment]
Maybe try this one?
```python
cells = cTable.descendants(title="Name",control_type="DataItem")
for cell in cells[::3]:
    print(cell.get_value())
```
It prints every third cell text. In your code you're using the same cell. It doesn't depend in `i` value.

**Comment by smitagodbole** [comment]
Thank you very much. This for loop was driving me crazy.  I tried so many ways but none of them worked.   I did try before using get_value() and it gave me following error i.e. -------------------------------------------------------------------------------------------
 print(cell.get_value())AttributeError: 'ListItemWrapper' object has no attribute 'get_value'----------------------------------------------------------------------------------------------------
Then I tried following and it worked fine.  I really was not knowing this for loop syntax you used it i.e. [::3].  cell = MyApp1.cTable.dItemscells = cTable.descendants(control_type="DataItem")
for cell in cells[::3]:    print (cell.iface_value.CurrentValue)
Thanks a lot.Smita
    On Wednesday, September 26, 2018, 5:32:28 PM EDT, Vasily Ryabov <notifications@github.com> wrote:  
 
 
Maybe try this one?
cells = cTable.descendants(title="Name",control_type="DataItem")
for cell in cells[::3]:
    print(cell.get_value())
It prints every third cell text. In your code you're using the same cell. It doesn't depend in i value.

**Comment by vasily-v-ryabov** [comment]
`cells[::3]` is a slice of the list. It includes every third element. Common syntax is `cells[start:end:step]` where `start=0`, `end=None` (last index not included) and `step=1` by default. For example, `cells[:]` is just a deep copy of the list (all elements copied because step=1).

Well, `.get_value()` method is missing for this control type. We will think how to make it available depending on available interface, not by a control type.

**Comment by jjbright** [comment]
@vasily-v-ryabov How to handle this
@smitagodbole I've tagged you just that you could provide any quick help
I've a similar reading for the data from specific columns, but unable to do so using the above examples.
![image](https://user-images.githubusercontent.com/55202374/82687253-b2e96100-9c74-11ea-9e53-b12f4aeebaf4.png)
I wanted to get the YELLOW highlighted column data, but unable to.  I tried for the LAST NAME column first like below
`resultsTable = mainPanel.child_window(auto_id="resultsTable",  control_type="Table")    
        cells = resultsTable.descendants(title="Last Name", control_type="DataItem")
        logger.info(len(cells))  
        for cell in cells[::3]:
            logger.info(cell) 
            logger.info(cell.get_value())    `

Here the cell length returns 0, if I remove **title="Last Name"**,  the cell length gives the length but with below exception
`
INFO - uia_controls.ListItemWrapper - 'KIM', DataItem
INFO - Exception :
Traceback (most recent call last):
  File "C:\Users\<user>\workspace\AutomationPrime\src\com\test\prime\Search.py", line 55, in tLnameZipSearch
    Search.openSearchResult(self, mainPanel)
  File "C:\Users\<user>\workspace\AutomationPrime\src\com\test\prime\Search.py", line 163, in openSearchResult
    logger.info(cell.get_value())
AttributeError: 'ListItemWrapper' object has no attribute 'get_value'
`

When I try with this code `logger.info(cell.iface_value.CurrentValue)` 

I get the below error
`
Traceback (most recent call last):
  File "C:\Python\Python37\lib\site-packages\pywinauto\uia_defines.py", line 234, in get_elem_interface
    iface = cur_ptrn.QueryInterface(cls_name)
  File "C:\Python\Python37\lib\site-packages\comtypes\__init__.py", line 1158, in QueryInterface
    self.__com_QueryInterface(byref(iid), byref(p))
ValueError: NULL COM pointer access

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\<user>\workspace\AutomationPrime\src\com\test\prime\MasterSearch.py", line 55, in contactLnameZipSearch
    Search.openSearchResult(self, mainPanel)
  File "C:\Users\<user>\workspace\AutomationPrime\src\com\test\prime\MasterSearch.py", line 163, in openSearchResult
    logger.info(cell.iface_value.CurrentValue)
  File "C:\Python\Python37\lib\site-packages\pywinauto\controls\uiawrapper.py", line 132, in __get__
    value = self.fget(obj)
  File "C:\Python\Python37\lib\site-packages\pywinauto\controls\uiawrapper.py", line 252, in iface_value
    return uia_defs.get_elem_interface(elem, "Value")
  File "C:\Python\Python37\lib\site-packages\pywinauto\uia_defines.py", line 236, in get_elem_interface
    raise NoPatternInterfaceError()
pywinauto.uia_defines.NoPatternInterfaceError
`

**Comment by airelil** [comment]
@jjbright , did you try `texts` method?

A small tip how could you find it. As you can see, pywinauto throws exception about `ListItemWrapper` that doesn't have the `get_value` method. After this, my next step would be having a look at the docs for available methods in this class. Since you're using the uia backend your destination is [`ListItemWrapper`](https://pywinauto.readthedocs.io/en/latest/code/pywinauto.controls.uia_controls.html#pywinauto.controls.uia_controls.ListItemWrapper) class in uia_controls module. You can also dig a bit in the code: https://github.com/pywinauto/pywinauto/blob/5fc0a7f05fa626c1830be5ef32878f76bea08f34/pywinauto/controls/uia_controls.py#L698

**Comment by jjbright** [comment]
Thanks @airelil , the method `texts` prints everything in the cells.  Originally I wanted to fetch the data from that two columns, I was trying to get the data items by the column title.. but no luck.

**Comment by airelil** [comment]
@jjbright, what's the output of the code below?
```python
resultsTable = mainPanel.child_window(auto_id="resultsTable",  control_type="Table")    
cells = resultsTable.descendants( control_type="DataItem")
logger.info(len(cells))  
for cell in cells:
    logger.info(cell.texts())
```

**Comment by jjbright** [comment]
> @jjbright, what's the output of the code below?
> 
> ```python
> resultsTable = mainPanel.child_window(auto_id="resultsTable",  control_type="Table")    
> cells = resultsTable.descendants( control_type="DataItem")
> logger.info(len(cells))  
> for cell in cells:
>     logger.info(cell.texts())
> ```

2020-05-26 16:31:26,073 - PrimeLogger.Search - INFO - ['KIM']
2020-05-26 16:31:26,076 - PrimeLogger.Search - INFO - ['']
2020-05-26 16:31:26,084 - PrimeLogger.Search - INFO - ['BOSS']
2020-05-26 16:31:26,087 - PrimeLogger.Search - INFO - ['']
2020-05-26 16:31:26,090 - PrimeLogger.Search - INFO - ['']
2020-05-26 16:31:26,094 - PrimeLogger.Search - INFO - ['']
2020-05-26 16:31:26,094 - PrimeLogger.Search - INFO - ['23 ROADSIDE']
....and so on, all the cells are getting logged.

@airelil  That's what I replied in my earlier comment that it prints all data in that table, except the headers.  In this search scenario, I wanted to get the data from columns 3 & 10.  I'll use that data to assert.

**Comment by airelil** [comment]
Ok, so why you don't use the slicing for the cells list and indexes to get the values from the column you need?

**Comment by jjbright** [comment]
@airelil Sure that I can do, but while the result table contains more records that would be a big loop to process... hence I see if I can get by column name.

If there is no option left, then let me do the slicing of cell and indexes to do the validations.

**Comment by airelil** [comment]
WRT the column name, you might need to have a closer look to the data grid control with inspect.exe and see what's actually accessible from uia
