### ISSUE TITLE
is it possible to identify a window using next or previous window?

### ISSUE THREAD

**Issue by prathibha-a** [pywinauto/pywinauto#600]
I recently started using pywinauto. I am trying to identify a combo box, unfortunately the combo box doesn't contains much properties to identify it uniquely. (there are many combo box in the application with same name, and i cant use found_index as the location may change).
FYI Application background is UIA.

So i am just curious to know whether identifying a window using its neighbor windows(next/previous) is possible in pywinauto.

**Comment by vasily-v-ryabov** [comment]
There are 5 rules for creating `best_match` names: https://pywinauto.readthedocs.io/en/latest/getting_started.html#how-to-know-magic-attribute-names

Rule number 4 is what you're looking for.

Also `.child_window(..., parent=parent_wrapper)` might be helpful if combo boxes have different well identifiable parents. But window specifications can have more than 2 levels for UIA backend. So param `depth=2` means 1 level below (not the whole subtree). It will be changed in pywinauto==0.7.0 to more intuitive `depth=1`.

**Comment by prathibha-a** [comment]
what do you mean by top-left label and how to use that?

Actually, i have 4 combo box in my application.
Ex:  File Type:  Combo Box1
      Quality:  Combo Box2
      Width:  Combo Box3
      Resolution:  Combo Box4

File Type, Quality, Width and Resolutions static texts are getting identified as Text control type.
Unfortunately all combo box are with same title which is " Down".
So i am searching for a way to identify Combo Box1 using its neighbor/Previous window(which is 'File Type').

**Comment by vasily-v-ryabov** [comment]
When you call `app.MainWindowTitle.dump_tree()`, it prints all best_match names for every control. It can be dumped to file because output is pretty big for rich forms.

To confirm you've matched the right combo box, try something like this:
```python
app.MainWindowTitle.File_Type_ComboBox.draw_outline()
# or
app.MainWindowTitle["File Type:ComboBox"].draw_outline()
```

**Comment by prathibha-a** [comment]
Hi Vasily,

Thank you for the response.
I have tried both the draw_outline() methods. From the first method, other combo box is getting highlight, not the one which is beside 'File Type' static text. And from the second method, i am getting below error,

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\prak\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pywinauto\application.py", line 313, in __getitem__
    raise AttributeError(message)
AttributeError: The control does not have a __getitem__ method for item access (i.e. ctrl[key]) so maybe you have requested this in error?

Below is the result from dump_tree() method:

   |    |    |    | Pane - 'Image'    (L959, T493, R1169, B496)
   |    |    |    | ['Image3', 'ImagePane2', 'Pane4']
   |    |    |    | child_window(title="Image", control_type="Pane")
   |    |    |    |
   |    |    |    | ComboBox - 'Image Down'    (L1014, T466, R1169, B488)
   |    |    |    | ['Image Down', 'Image DownComboBox', 'ComboBox5', 'Image Down0', 'Image Down1', 'Image DownComboBox0', 'Image DownComboBox1']
   |    |    |    | child_window(title="Image Down", control_type="ComboBox")
   |    |    |    |    |
   |    |    |    |    | ListBox - ''    (L0, T0, R0, B0)
   |    |    |    |    | ['4', 'ListBox', 'ListBox0', 'ListBox1']
   |    |    |    |    |    |
   |    |    |    |    |    | ListItem - 'Low'    (L0, T0, R640, B21)
   |    |    |    |    |    | ['ListItem15', 'LowListItem', 'Low']
   |    |    |    |    |    | child_window(title="Low", control_type="ListItem")
   |    |    |    |    |    |
   |    |    |    |    |    | ListItem - 'Medium'    (L0, T21, R640, B42)
   |    |    |    |    |    | ['ListItem2', 'MediumListItem', 'Medium', 'MediumListItem0', 'MediumListItem1', 'Medium0', 'Medium1']
   |    |    |    |    |    | child_window(title="Medium", control_type="ListItem")
   |    |    |    |    |    |
   |    |    |    |    |    | ListItem - 'High'    (L0, T42, R640, B63)
   |    |    |    |    |    | ['ListItem3', 'HighListItem', 'High', 'HighListItem0', 'HighListItem1', 'High0', 'High1']
   |    |    |    |    |    | child_window(title="High", control_type="ListItem")
   |    |    |    |    |    |
   |    |    |    |    |    | ListItem - 'Maximum'    (L0, T63, R640, B84)
   |    |    |    |    |    | ['ListItem18', 'Maximum', 'MaximumListItem']
   |    |    |    |    |    | child_window(title="Maximum", control_type="ListItem")
   |    |    |    |
   |    |    |    | Static - 'Quality:'    (L959, T466, R1009, B488)
   |    |    |    | ['Quality:Static', 'Quality:', 'Static5']
   |    |    |    | child_window(title="Quality:", control_type="Text")
   |    |    |    |
   |    |    |    | ComboBox - 'Image Down'    (L1014, T439, R1169, B461)
   |    |    |    | ['Image Down2', 'Image DownComboBox2', 'ComboBox6']
   |    |    |    | child_window(title="Image Down", control_type="ComboBox")
   |    |    |    |    |
   |    |    |    |    | ListBox - ''    (L0, T0, R0, B0)
   |    |    |    |    | ['4', 'ListBox', 'ListBox0', 'ListBox1']
   |    |    |    |    |    |
   |    |    |    |    |    | ListItem - 'JPEG'    (L0, T0, R640, B21)
   |    |    |    |    |    | ['ListItem19', 'JPEG', 'JPEGListItem']
   |    |    |    |    |    | child_window(title="JPEG", control_type="ListItem")
   |    |    |    |    |    |
   |    |    |    |    |    | ListItem - 'PNG'    (L0, T21, R640, B42)
   |    |    |    |    |    | ['ListItem20', 'PNGListItem', 'PNG']
   |    |    |    |    |    | child_window(title="PNG", control_type="ListItem")
   |    |    |    |    |    |
   |    |    |    |    |    | ListItem - 'TIFF'    (L0, T42, R640, B63)
   |    |    |    |    |    | ['ListItem21', 'TIFF', 'TIFFListItem']
   |    |    |    |    |    | child_window(title="TIFF", control_type="ListItem")
   |    |    |    |
   |    |    |    | Static - 'File Type:'    (L959, T439, R1009, B461)
   |    |    |    | ['File Type:Static', 'File Type:', 'Static6']
   |    |    |    | child_window(title="File Type:", control_type="Text")
   |

**Comment by prathibha-a** [comment]
Thanks for the clarification and quick support.
