### ISSUE TITLE
How to input the "TreeView" method ?

### ISSUE THREAD

**Issue by plazmusca** [pywinauto/pywinauto#602]
444/5000
can someone help me for this case?
I have tried using the `.get_item()` controls,

my Code 
Input

```
from pywinauto.application import Application

app = Application(backend='win32').connect(title=u'Actix Software - [Map1]')
window = app[u'Actix Software']

toolbarwindow = window.ToolbarWindow32
attributes_button = toolbarwindow.button('Attributes')
attributes_button.click() # Open window Attributes

dlgEditAttributes = app.Dialog
treeview = dlgEditAttributes[u'ATL:SysTreeView32']
treeview.get_item(['|Loaded Data Files|Lanta Dasar|Ericsson UMTS Handset (K800i) (1) - MS2|GSM|Serving Cell Parameters|BCCH'])
```

output:
```
Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/Add_Attribute.py", line 14, in <module>
    treeview.get_item(['|Loaded Data Files|Lanta Dasar|Ericsson UMTS Handset (K800i) (1) - MS2|GSM|Serving Cell Parameters|BCCH'])
  File "build\bdist.win-amd64\egg\pywinauto\application.py", line 174, in __call__
AttributeError: Neither GUI element (wrapper) nor wrapper method 'get_item' were found (typo?)
```

![p10](https://user-images.githubusercontent.com/44937451/48311577-5368ba80-e5d4-11e8-983e-2bf1c615d5fa.jpg)

I really appreciate your opinion, please correct any errors in the above method.

**Comment by plazmusca** [comment]
> 
> 
> 444/5000
> can someone help me for this case?
> I have tried using the `.get_item()` controls,
> 
> my Code
> Input
> 
> ```
> from pywinauto.application import Application
> import time
> 
> app = Application(backend='win32').connect(title=u'Actix Software - [Map1]')
> window = app[u'Actix Software']
> 
> toolbarwindow = window.ToolbarWindow32
> attributes_button = toolbarwindow.button('Attributes')
> attributes_button.click() # Open window Attributes
> 
> dlgEditAttributes = app.Dialog
> treeview = dlgEditAttributes[u'ATL:SysTreeView32']
> treeview.get_item(['|Loaded Data Files|Lanta Dasar|Ericsson UMTS Handset (K800i) (1) - MS2|GSM|Serving Cell Parameters|BCCH'])
> ```
> 
> output:
> 
> ```
> Traceback (most recent call last):
>   File "C:/Users/Administrator/Desktop/Add_Attribute.py", line 14, in <module>
>     treeview.get_item(['|Loaded Data Files|Lanta Dasar|Ericsson UMTS Handset (K800i) (1) - MS2|GSM|Serving Cell Parameters|BCCH'])
>   File "build\bdist.win-amd64\egg\pywinauto\application.py", line 174, in __call__
> AttributeError: Neither GUI element (wrapper) nor wrapper method 'get_item' were found (typo?)
> ```
> 
> ![p10](https://user-images.githubusercontent.com/44937451/48311577-5368ba80-e5d4-11e8-983e-2bf1c615d5fa.jpg)

**Comment by vasily-v-ryabov** [comment]
Maybe the docs about this method will help: https://pywinauto.readthedocs.io/en/latest/code/pywinauto.controls.common_controls.html#pywinauto.controls.common_controls.TreeViewWrapper.get_item

The separator in item path should be backslash `\\`.

**Comment by kooki4** [comment]
@vasily-v-ryabov Greetings from Bulgaria ! My team has chosen to use pywinauto for automation and I have hit some weird and not very clear (for me) things:
a = pywinauto.application.Application(backend="win32").connect(process=XXXX)
b = a.window(title_re="XXXX")
c = b.TreeView

c.select("\\Layout Manager")
[Path]\pywinauto\controls\common_controls.py:1522: DeprecationWarning: Method .Next() is deprecated, use .next_item() instead.
  cur_elem = cur_elem.Next()

d = c.get_item("\\Layout Manager")
[Path]pywinauto\controls\common_controls.py:1522: DeprecationWarning: Method .Next() is deprecated, use .next_item() instead.
  cur_elem = cur_elem.Next()

type(d)
<class 'pywinauto.controls.common_controls._treeview_element'>

Q1: Why is this deprecated warning, do I need to disable them ?
Q2: Since I am inexperience do you have an examples somewhere how to work with TreeView except the docs
