### ISSUE TITLE
Listview item index out of range

### ISSUE THREAD

**Issue by iverson-lu** [pywinauto/pywinauto#611]
Hi, i'm using the tool to click each of the items in a listview. It works perfectly in the beginning however it start to throw out index out of range error in the middle. the itemcount can return correctly as 53, which is indeed the number of the items in the listview. However the code stops at 36th tow. And interestingly it will stop at the 41th row if i adjust the scrolling to 10 lines per time.

Really appreciate if anyone can help, thanks!

    print('Total items:', itemcount)
    for i in range (0, itemcount):
        try:
            dlg.child_window(auto_id='AddOnList').item(i).click_input()
        except Exception as e:
            print('Stop at', i)
            print('Error:', e.with_traceback())
            break
==============================================================
Total items: 53
Stop at: 41
Traceback (most recent call last):
  File "C:/Users/luwe/PycharmProjects/HPTUAutomation/start.py", line 26, in main
    dlg.child_window(auto_id='AddOnList').item(i).click_input()
  File "C:\Users\luwe\AppData\Local\Programs\Python\Python37\lib\site-packages\pywinauto\controls\uia_controls.py", line 686, in get_item
    itm = list_items[row]
IndexError: list index out of range

**Comment by airelil** [comment]
Just a quick note. It can be related to "virtualized items". See the code in https://github.com/pywinauto/pywinauto/blob/ca0d2eee18582a5a0e435e4be97e4468450c984f/pywinauto/controls/uia_controls.py#L681
```python
        elif isinstance(row, six.integer_types):
            # Get the item by a row index
            # TODO: Can't get virtualized items that way
            # TODO: See TODO section of item_count() method for details
            list_items = self.children(content_only=True)
            itm = list_items[row]
```
Instead, you may try to access the row by text  as it should handle virtualized items.
```python
       if isinstance(row, six.string_types):
            # Try to find item using FindItemByProperty
            # That way we can get access to virtualized (unloaded) items
            com_elem = self.iface_item_container.FindItemByProperty(0, IUIA().UIA_dll.UIA_NamePropertyId, row)
           
```
