### ISSUE TITLE
Python SendKeys Installation Error Visual Studio

### ISSUE THREAD

**Issue by irajeshr** [pywinauto/pywinauto#616]
I am a newbie to Python. I am using SendKeys Module in Python to perform the SendKeys Operation. when I try to execute the code, I get the below error. I landed up this link but still didn't resolve. can someone pls give me a detailed help on this, please?

Notes: - using Visual Studio 2017 Community Edition with Python 3.6 x32

Error:
```
Traceback (most recent call last):
File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_86\lib\site-packages\cx_Freeze\initscripts__startup__.py", line 14, in run
File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_86\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
File "C:\VisualStudioProjects\PythonLearning\SiebelIncrementalCompile\Published\Src\SiebelIncrementalCompile.py", line 12, in
File "D:\SiebelIncrementalCompile\lib\SendKeys.py", line 419 except (ValueError,AssertionError),e: ^ SyntaxError: invalid syntax
```

**Comment by irajeshr** [comment]
Even when i do import SendKeys i get the error. below is the info... 

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_86>python.exe

Python 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.

>>> import SendKeys
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_86\lib\site-packages\sendkeys-0.3-py3.6-win32.egg\SendKeys.py", line 419
    except (ValueError,AssertionError),e:
                                      ^
SyntaxError: invalid syntax

**Comment by vasily-v-ryabov** [comment]
Hi @irajeshr this module is not a part of pywinauto and not compatible with Python 3.x (because exception handler must contain keyword `as` instead of comma). Correct pywinauto's module is `pywinauto.keyboard`:
```python
from pywinauto import keyboard
keyboard.send_keys("Something{ENTER}next line", with_spaces=True)
```
The docs are here: [Basic User Input Modules » pywinauto.keyboard](https://pywinauto.readthedocs.io/en/latest/code/pywinauto.keyboard.html).

**Comment by irajeshr** [comment]
@vasily-v-ryabov  thanks for the updates! now my utility is working fine. however i am facing a new issue for which i raised another issue #623 

for now i am closing this thread as this issue is resolved.
