### ISSUE TITLE
scroll() method is throwing an error

### ISSUE THREAD

**Issue by prathibha-ashok** [pywinauto/pywinauto#686]
Hi,

I am trying to use scroll() method for one of the scrollBar object in my application.
But i am getting an error when i tried the same as below,

**app.windows()[0].descendants(control_type='Tree')[0].descendants(control_type='ScrollBar')[0].scroll('down','page')**

**And below is the error:**

Traceback (most recent call last):
  File "C:\Users\prak\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pywinauto\uia_defines.py", line 232, in get_elem_interface
    iface = cur_ptrn.QueryInterface(cls_name)
  File "C:\Users\prak\AppData\Local\Programs\Python\Python37-32\lib\site-packages\comtypes\__init__.py", line 1158, in QueryInterface
    self.__com_QueryInterface(byref(iid), byref(p))
ValueError: NULL COM pointer access

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\prak\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pywinauto\controls\uiawrapper.py", line 759, in scroll
    print(msg)
  File "C:\Users\prak\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pywinauto\controls\uiawrapper.py", line 132, in __get__
    value = self.fget(obj)
  File "C:\Users\prak\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pywinauto\controls\uiawrapper.py", line 301, in iface_scroll
    return uia_defs.get_elem_interface(elem, "Scroll")
  File "C:\Users\prak\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pywinauto\uia_defines.py", line 234, in get_elem_interface
    raise NoPatternInterfaceError()
pywinauto.uia_defines.NoPatternInterfaceError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\prak\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pywinauto\controls\uiawrapper.py", line 775, in scroll
    scroll_if.Scroll(h, v)
  File "C:\Users\prak\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pywinauto\controls\uiawrapper.py", line 756, in _raise_attrib_err
    print(name)
AttributeError: scrollbar "" is not scrollable

And when i tried to debug i understood, that scroll() method depends on iface_scroll. And i am facing some issue for iface_scroll as well.

**app.windows()[0].descendants(control_type='Tree')[0].descendants(control_type='ScrollBar')[0].iface_scroll**

**Error:**

Traceback (most recent call last):
  File "C:\Users\prak\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pywinauto\uia_defines.py", line 232, in get_elem_interface
    iface = cur_ptrn.QueryInterface(cls_name)
  File "C:\Users\prak\AppData\Local\Programs\Python\Python37-32\lib\site-packages\comtypes\__init__.py", line 1158, in QueryInterface
    self.__com_QueryInterface(byref(iid), byref(p))
ValueError: NULL COM pointer access

Could you please help me to understand this and solve the issue.

**Comment by airelil** [comment]
As a first step, you should verify with Inspect utility if the control actually has scroll interface

**Comment by vasily-v-ryabov** [comment]
Hi @prathibha-ashok if the element doesn't have ScrollPattern interface, it's possible to use `.wheel_mouse_input()` method to scroll by mouse like a real user.
