### ISSUE TITLE
ctypes.ArgumentError: argument 1: <class 'OverflowError'>: int too long to convert

### ISSUE THREAD

**Issue by frogger72** [pywinauto/pywinauto#691]
Getting the error when calling `is_minimized()`
Using pywinauto 0.6.6 on python 3.6.8 64-bit (Intel channel) to automate 64-bit Excel 2016

```python
Traceback (most recent call last):
  File "C:\proj\proj.py", line 479, in func
    if wnd.is_minimized():
  File "C:\Miniconda3\envs\py3\lib\site-packages\pywinauto\application.py", line 378, in __getattribute__
    ctrls = self.__resolve_control(self.criteria)
  File "C:\Miniconda3\envs\py3\lib\site-packages\pywinauto\application.py", line 256, in __resolve_control
    criteria)
  File "C:\Miniconda3\envs\py3\lib\site-packages\pywinauto\timings.py", line 436, in wait_until_passes
    func_val = func(*args, **kwargs)
  File "C:\Miniconda3\envs\py3\lib\site-packages\pywinauto\application.py", line 201, in __get_ctrl
    dialog = self.backend.generic_wrapper_class(findwindows.find_element(**criteria[0]))
  File "C:\Miniconda3\envs\py3\lib\site-packages\pywinauto\findwindows.py", line 84, in find_element
    elements = find_elements(**kwargs)
  File "C:\Miniconda3\envs\py3\lib\site-packages\pywinauto\findwindows.py", line 281, in find_elements
    elements = [elem for elem in elements if _title_match(elem)]
  File "C:\Miniconda3\envs\py3\lib\site-packages\pywinauto\findwindows.py", line 281, in <listcomp>
    elements = [elem for elem in elements if _title_match(elem)]
  File "C:\Miniconda3\envs\py3\lib\site-packages\pywinauto\findwindows.py", line 277, in _title_match
    t = w.rich_text
  File "C:\Miniconda3\envs\py3\lib\site-packages\pywinauto\win32_element_info.py", line 83, in rich_text
    return handleprops.text(self.handle)
  File "C:\Miniconda3\envs\py3\lib\site-packages\pywinauto\handleprops.py", line 91, in text
    handle, win32defines.WM_GETTEXT, length, ctypes.byref(buffer_))
ctypes.ArgumentError: argument 1: <class 'OverflowError'>: int too long to convert
```

**Comment by airelil** [comment]
Seems to be the same as #641 . Needs additional cleaning in win32functions.py

**Comment by vasily-v-ryabov** [comment]
@frogger72 can you try the fix from master branch?
```
pip uninstall -y pywinauto
pip install https://github.com/pywinauto/pywinauto/archive/master.zip
```

**Comment by frogger72** [comment]
Thanks - maybe that did the trick. I upgraded a couple days ago and the error hasn't re-appeared yet. Will let you know if does.

**Comment by hansonap** [comment]
Not sure if your having a hard time reproducing this issue, but I am able to using CATIA. I can also report that uninstalling master and installing pip install https://github.com/pywinauto/pywinauto/archive/master.zip resolved the issue.

**Comment by GBULLR** [comment]
Wow did it take a long time to find this solution. Reinstall from master worked!
