### ISSUE TITLE
move_window not available on dialog

### ISSUE THREAD

**Issue by alteryx-sezell** [pywinauto/pywinauto#694]
According to the documentation, move_window should be available on all controls and it seems like I have a valid dialog object. But when I try to use this method on the main window of my application, I get an error. I'm assuming that I am actually doing it wrong, rather than a bug, but any help would be appreciated. I was using v 0.6.5 but updated to 0.6.6 to see if that changed anything, both have same results. Thanks!

Here's the code snippet that is running, followed by the error and the stdout for that section:
 ```
print(self.main_window)
print(self.main_window.handle)
print(self.main_window.wrapper_object())
self.main_window.restore()
self.main_window.move_window(x=0,y=0,width=700,height=800)
```

main_window is set with app.window(title_re='Alteryx Designer.*'), I just cached that reference since I was looking it up all the time. Don't think that affects this, I did try getting it again from the application object before calling move_window and got the same result. 

```
Traceback (most recent call last):
  File "c:\git\py-auto\TestFramework\STF\test\explorer_unit_test.py", line 62, in test_drag_and_drop
    designer.position_window()
  File "c:\git\py-auto\testframework\STF\modules\designer.py", line 1090, in position_window
    self.main_window.move_window(x=0,y=0,width=700,height=800)
  File "C:\Users\sezell\AppData\Local\Continuum\anaconda3\lib\site-packages\pywinauto\application.py", line 180, in __call__
    format(self.criteria[-1]['best_match']))
AttributeError: Neither GUI element (wrapper) nor wrapper method 'move_window' were found (typo?)
-------------------- >> begin captured stdout << ---------------------
<pywinauto.application.WindowSpecification object at 0x0000019B593A4748>
985552
uiawrapper.UIAWrapper - 'Alteryx Designer x64 - New Workflow1', Dialog
```

**Comment by vasily-v-ryabov** [comment]
This method is missed for "uia" backend and we already have issue #668 tracking this problem. So I'd suggest to post additional details there and close this thread as duplication.
