### ISSUE TITLE
Win7 Right-Click Systray Item not Hidden select popmenu item using python2.7 32bit 

### ISSUE THREAD

**Issue by pewkodi** [pywinauto/pywinauto#709]
I am trying  to select an item in the pop up from the systray on a Win7 PC. I was able to find the code to right click on the item.

https://stackoverflow.com/questions/50464576/how-to-get-specific-system-tray-icon-using-pywinauto/50560105#50560105

But, I am having trouble selecting one of menu items. The Class it is using is hwndwrapper but I cannot get the mouse to select it.

Here is the code I am tying to use:

app = Application(backend="uia").connect(path="explorer.exe")
st = app.window(class_name="Shell_TrayWnd")
con = st.child_window(title="Micro Focus Connected Backup").click_input(button='right')

ab =  app.window(title="About", class_name="HwndWrapper", control_type="MenuItem").invoke()

The error i get is this:

Traceback (most recent call last):
  File "powername.py", line 60, in <module>
    ab =  app.window(title="About", class_name="HwndWrapper", control_type="MenuItem").invoke()
  File "C:\Python27\lib\site-packages\pywinauto\application.py", line 378, in __getattribute__
    ctrls = self.__resolve_control(self.criteria)
  File "C:\Python27\lib\site-packages\pywinauto\application.py", line 259, in __resolve_control
    raise e.original_exception
pywinauto.findwindows.ElementNotFoundError: {'class_name': 'HwndWrapper', 'process': 5768, 'backend': u'uia', 'control_type': 'MenuItem', 'title': 'About'}

Any help would be great.

Thanks

**Comment by airelil** [comment]
Did you have a chance to go trough pywinauto docs: https://pywinauto.readthedocs.io/en/latest/getting_started.html ? Inspect.exe utility, mentioned in the guide, proved to be extremely useful for investigating the control hierarchy. Also notice the https://pywinauto.readthedocs.io/en/latest/getting_started.html#how-to-know-magic-attribute-names explaining main principles and providing the example with ```print_control_identifiers```. You can always put the call to ```print_control_identifiers``` at your code at places you struggle to resolve your next control and hopefully it'll give you clues

Regarding the error in your code,  ```HwndWrapper``` as a class name looks suspicious for me. This is the name of one of pywinauto internal classes, so I'm not sure that it's a valid class name for a control in the application you try to automate. Try to not specify the c```lass_name``` parameter at all. If the menu item is still not resolved you should try to identify/validate the proper control name with above mentioned "Inspect.exe" or ```print_control_identifiers```.

**Comment by pewkodi** [comment]
Well. I have been trying to get inspect.exe and the print control identifiers to work before I send the first message. I have been readingthe docs extensively. Right now inspect.exe freezes onm the ui automation piece.

**Comment by pewkodi** [comment]
![image](https://user-images.githubusercontent.com/20560418/56047507-8ba32f00-5d13-11e9-9a1d-3871d641960f.png)
![image](https://user-images.githubusercontent.com/20560418/56047549-a5dd0d00-5d13-11e9-96a9-82617b52a8e3.png)

**Comment by pewkodi** [comment]
Trying to get to the about popup menu

**Comment by airelil** [comment]
```ab = app.window(title="About", class_name="HwndWrapper", control_type="MenuItem").invoke()```
It seems that you still refer to explorer process here, but you have to connect to the ""Micro Focus Connected Backup" process.

BTW, is your Inspect.exe in MSAA mode, because 'uia' "UI automation" mode freezes for you?

**Comment by pewkodi** [comment]
Yes. UI mode seems to freeze. I tried to connect to the systray process and got the same result. I know this is a context menu. I still have issues.

**Comment by pewkodi** [comment]
app = Application(backend="uia").connect(path="explorer.exe")
st = app.window(class_name="Shell_TrayWnd")
con = st.child_window(title="Micro Focus Connected Backup").click_input(button='right')
con1 = st.child_window(title="Micro Focus Connected Backup")
app2 = Application(backend="uia").connect(path=r'C:\Program Files (x86)\Iron Mountain\Connected BackupPC\ConnectedAgent.exe')
time.sleep(10)
app2.PopupMenu.Menu().get_menu_path("About")[0].click_input()
con1.print_control_identifiers()

**Comment by airelil** [comment]
I think, we don't have PopupMenu wrapper for 'uia' backend. Did you try to connect to "Backup" process with "win32" backend?
```python
app2 = Application(backend="win32").connect(path=r'C:\Program Files (x86)\Iron Mountain\Connected BackupPC\ConnectedAgent.exe')
app2.PopupMenu.wait('ready').menu().get_menu_path('About')[0].click_input()

```

**Comment by pewkodi** [comment]
Getting this now after the context menu comes up:

Traceback (most recent call last):
  File "powername.py", line 36, in <module>
    app2.PopupMenu.wait('ready').menu().get_menu_path('About')[0].click_input()
  File "c:\Python27_64\lib\site-packages\pywinauto\application.py", line 512, in wait
    lambda: self.__check_all_conditions(check_method_names, retry_interval))
  File "c:\Python27_64\lib\site-packages\pywinauto\timings.py", line 375, in wait_until
    raise err
pywinauto.timings.TimeoutError: timed out

**Comment by airelil** [comment]
@pewkodi, I just noticed several mentions about WPF app idenitfied as "HwndWrapper[applicatio.exe;;GUID]", [here](https://social.msdn.microsoft.com/Forums/en-US/a15d684f-0cf3-4794-9953-326d087279cc/wpf-window-showing-up-as-a-win32-hwndwrapper-class-control) and [here](https://stackoverflow.com/questions/18103738/wpf-and-hwnd-unique-name). So I believe, your app is also WPF based. In that case you should have more luck with 'uia' backend.  Pywinauto, actually has a WPF demo: [WpfSampleApplicaiton.exe](https://github.com/pywinauto/pywinauto/blob/master/apps/WPF_samples/x64/WpfApplication1.exe) We use this sample for unit testing and the output of Inspect.exe for a pop-up menu of a "Rich Text" control is quite similar to the output on your screenshot. Here is a very simple example you may try to run on your machine, so that it'll give you a confidence that your 'uia' path is valid.
```python
app = Application(backend="uia").start(u"WpfApplication1.exe"))
dlg = app.WPFSampleApplication
dlg.RichTextBox.draw_outline("red")  # just a highlight for debug
dlg.RichTextBox.click_input("right")
dlg.Paste.invoke()
```
 Provided the above code works for you, you can make another attempt with "Connected Backup" app. I would just access the your menu item directly. Notice that we switch back to 'uia' mode here:
```python
app2 = Application(backend="uia").connect(path=r'C:\Program Files (x86)\Iron Mountain\Connected BackupPC\ConnectedAgent.exe')
app2.About.invoke()
```

**Comment by pewkodi** [comment]
The connected Agent has a -silent switch for running in the systray. I tried the above code and got this:

Traceback (most recent call last):
  File "powername.py", line 36, in <module>
    app2.About.invoke()
  File "c:\Python27_64\lib\site-packages\pywinauto\application.py", line 378, in __getattribute__
    ctrls = self.__resolve_control(self.criteria)
  File "c:\Python27_64\lib\site-packages\pywinauto\application.py", line 259, in __resolve_control
    raise e.original_exception
pywinauto.findbestmatch.MatchError: Could not find 'About' in '[u'', u'Dialog']'

This is the code:
app = Application(backend="uia").connect(path="explorer.exe")
st = app.window(class_name="Shell_TrayWnd")
con = st.child_window(title="Micro Focus Connected Backup").click_input(button='right')
con1 = st.child_window(title="Micro Focus Connected Backup")
time.sleep(10)
app2 = Application(backend="uia").connect(path=r'C:\Program Files (x86)\Iron Mountain\Connected BackupPC\ConnectedAgent.exe')
app2.About.invoke()

**Comment by airelil** [comment]
I guess, you should try to access  "About" item as a child of the Dialog.

PS: Does the example with the WPF demo work for you?

**Comment by pewkodi** [comment]
Thee sample app runs gives me this error:

Traceback (most recent call last):
  File "powername.py", line 43, in <module>
    dlg.Paste.invoke()
  File "c:\Python27_64\lib\site-packages\pywinauto\controls\uiawrapper.py", line 513, in invoke
    self.iface_invoke.Invoke()
_ctypes.COMError: (-2146233079, None, (None, None, None, 0, None))

But i can see the red debug the right click and trying to paste.

I trying to get to about in the systray for this app. If i try it like the sample it will launch the full app whuch is different from the systray.
