### ISSUE TITLE
Sub-menu not accessible

### ISSUE THREAD

**Issue by moden-py** [pywinauto/pywinauto#75]
Windows 8 64bit
pywinauto 0.5.2
[problem app](http://www.lostpassword.com/downloads/passware-kit-forensic-demo.msi)

User http://habrahabr.ru/users/EvilsInterrupt/ noticed SWAPY works incorrectly with *passware-kit-forensic-demo* main menu.

The problem is in menu items which point to sub-menu. The item has a handle of the sub-menu but the sub-menu does not exist.
test code:
``` python
pwa_app = pywinauto.application.Application()
w_handle = pywinauto.findwindows.find_windows(title=u'Passware Password Recovery Kit Forensic Demo', class_name='ATL:01AC7C30')[0]
window = pwa_app.window_(handle=w_handle)
window.SetFocus()
m = window.MenuItem(u'&File->&Recover')
m.SubMenu()
```
```
Traceback (most recent call last):
  File "C:/swapy/debug.py", line 13, in <module>
    m.SubMenu()
  File "C:\pywinauto\pywinauto\controls\menuwrapper.py", line 186, in SubMenu
    return Menu(self.ctrl, submenu_handle, False, self)
  File "C:\pywinauto\pywinauto\controls\menuwrapper.py", line 374, in __init__
    win32gui.GetMenuInfo(self.handle, buf)
pywintypes.error: (1401, 'GetMenuInfo', 'Invalid menu handle.')
```

Manually the menu works fine.

Increasing the priority in case the problem causes the exception even if `window.Menu().GetProperties()` is performed. `GetProperties()` of the main menu touches the problem while collecting all sub items/menus into a dictionary.

**Comment by moden-py** [comment]
Verified.
