### ISSUE TITLE
type_keys() does not properly sanitize string parameters

### ISSUE THREAD

**Issue by webredraptors** [pywinauto/pywinauto#762]
The `type_keys()` method does not properly sanitize string parameters passed to it.

For example, the following throws a `KeySequenceError`:
```
from pywinauto.application import Application

app = Application(backend='uia').start('notepad.exe')
app['Untitled - Notepad'].Edit.type_keys('(')
```
Traceback:
```
Traceback (most recent call last):
  File "C:/Users/Nick/PycharmProjects/Testing/testing.py", line 30, in <module>
    app['Untitled - Notepad'].Edit.type_keys(')')
  File "C:\Users\Nick\PycharmProjects\Testing\venv\lib\site-packages\pywinauto\base_wrapper.py", line 970, in type_keys
    turn_off_numlock)
  File "C:\Users\Nick\PycharmProjects\Testing\venv\lib\site-packages\pywinauto\keyboard.py", line 672, in send_keys
    keys = parse_keys(keys, with_spaces, with_tabs, with_newlines)
  File "C:\Users\Nick\PycharmProjects\Testing\venv\lib\site-packages\pywinauto\keyboard.py", line 613, in parse_keys
    raise KeySequenceError('`)` should be preceeded by `(`')
pywinauto.keyboard.KeySequenceError: `)` should be preceeded by `(`
```
I have confirmed the following substrings will cause similar behavior, no matter what else is in the string:
`)`
`{`
`}`
`{}`
`{example text}`

Additionally, when passing a substring such as `(example text)` the program will exit successfully, however the output will be `example text` not `(example text)`

  - Pywinauto version: 0.6.6
  - Python version and bitness: 3.7 (32-bit)
  - Platform and OS: Windows 10

**Comment by vasily-v-ryabov** [comment]
The reason of that: all brackets have their own meaning to press special keys like `{ENTER}`. To type a single special bracket as a bracket you have to wrap it this way: `.type_keys("{(}")`. It will type single bracket `(` correctly. This is described in the docs for keyboard module: https://pywinauto.readthedocs.io/en/latest/code/pywinauto.keyboard.html

Of course the error messages can be improved (so marking the issue as enhancement, but low priority).

**Comment by webredraptors** [comment]
Well. I guess I should have read the docs a bit more closely. Thanks!

**Comment by grantrosse** [comment]
I wrote this little sanitization loop:

```
password = 'ss{)747&FH%4)}'
clean_pass = ''
for c in password:
    if c in ['(', ')', '{', '}', '%']:
        clean_pass += ('{' + c + '}')
    else:
        clean_pass += c
print(clean_pass)
```
