### ISSUE TITLE
_ctypes.COMError: (-2147213310, None, (None, None, None, 0, None))

### ISSUE THREAD

**Issue by Emilymcwu** [pywinauto/pywinauto#778]
## Expected Behavior
want to click this button
![image](https://user-images.githubusercontent.com/30827773/61425731-807f2100-a94a-11e9-969c-450b8983abaf.png)
My code:
app.window(auto_id="MainWindow").window(class_name="PlatformWareController").children()[4].draw_outline
app.window(auto_id="MainWindow").window(class_name="PlatformWareController").children()[4].click()

## Actual Behavior
this button was clicked，but half a minute later, the program went wrong.（uia mode）
Qt version：5.12.2
there is no such problem in the QT version：5.7.0

Traceback (most recent call last):
  File "F:/FinalDemo/TestCase/test.py", line 24, in <module>
    app.window(auto_id="MainWindow").window(class_name="PlatformWareController").children()[4].click()
  File "E:\Python\lib\site-packages\pywinauto\controls\uia_controls.py", line 121, in click
    self.invoke()
  File "E:\Python\lib\site-packages\pywinauto\controls\uiawrapper.py", line 513, in invoke
    self.iface_invoke.Invoke()
_ctypes.COMError: (-2147213310, None, (None, None, None, 0, None))

## Steps to Reproduce the Problem

  1.app.window(auto_id="MainWindow").window(class_name="PlatformWareController").children()[4].click()
  2.
  3.

## Specifications

  - Pywinauto version:0.6.7
  - Python version and bitness:3.5.2 (v3.5.2:4def2a2901a5)
  - Platform and OS:GUI:Qt5.12.2  Win7

**Comment by vasily-v-ryabov** [comment]
What is the number of children for Qt 5.12.2 ? I mean `len(app.window(auto_id="MainWindow").window(class_name="PlatformWareController").children())`. Is it different for 2 Qt versions?

We already noticed that some new Qt versions have problems receiving children through `FindAll` function (currently used in pywinauto), but they are reachable by `RawTreeWalker` object (we're planning to use it in the future).

**Comment by Emilymcwu** [comment]
in qt 5.12.2 and qt5.7,they have 8 childrens,they are same.

**Comment by vasily-v-ryabov** [comment]
Well, it looks an error in Invoke Pattern implementation on app side. But I'd suggest to try both 32-bit Python and 64-bit Python to see if there is any difference. If no difference, then it should be reported to Qt team probably. If you find difference, please let me know. It might be pywinauto issue loading incorrect UIAutomationCore.dll.
