### ISSUE TITLE
UIAWrapperTests.test_scroll failure

### ISSUE THREAD

**Issue by airelil** [pywinauto/pywinauto#790]
## Expected Behavior
UIAWrapperTests.test_scroll should pass for all configurations

## Actual Behavior
Recently the unittest UIAWrapperTests.test_scroll started failing on AppVeyor
```
Traceback (most recent call last):
  File "C:\projects\pywinauto\pywinauto\controls\uia_controls.py", line 812, in cell
    cell_elem = uiawrapper.UIAWrapper(elem_info)
  File "C:\projects\pywinauto\pywinauto\controls\uiawrapper.py", line 186, in __new__
    return super(UIAWrapper, cls)._create_wrapper(cls, element_info, UIAWrapper)
  File "C:\projects\pywinauto\pywinauto\base_wrapper.py", line 126, in _create_wrapper
    new_class = cls_spec.find_wrapper(element_info)
  File "C:\projects\pywinauto\pywinauto\controls\uiawrapper.py", line 159, in find_wrapper
    if element.control_type in UiaMeta.control_type_to_cls:
  File "C:\projects\pywinauto\pywinauto\uia_element_info.py", line 250, in control_type
    return self._get_control_type()
  File "C:\projects\pywinauto\pywinauto\uia_element_info.py", line 112, in _get_current_control_type
    return IUIA().known_control_type_ids[self._element.CurrentControlType]
ValueError: NULL COM pointer access

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python35\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "c:\python35\lib\unittest\case.py", line 605, in run
    testMethod()
  File "C:\projects\pywinauto\pywinauto\unittests\test_uiawrapper.py", line 250, in test_scroll
    cell = listview.cell(3, 0)
  File "C:\projects\pywinauto\pywinauto\controls\uia_controls.py", line 814, in cell
    raise IndexError
IndexError
```
There is also a failure of TreeViewAdditionalTestCases.testCheckBoxes, but it seems to be fixed with:
https://github.com/airelil/pywinauto/commit/cd9967a885219e67e9c65d0071f3fc934f9333e3

## Specifications

  - Pywinauto version: master branch (and same on my atspi branch)
  - Python version and bitness: 2.7, 3.5, 3.6, 3.7 (x86 and x64)

**Comment by airelil** [comment]
I can't reproduce it locally on my win8.1. Might worth trying on win10...

**Comment by airelil** [comment]
Tried to get this error locally, on a Win10 machine. Still can't reproduce it locally...

I also have a debug branch: https://github.com/airelil/pywinauto/commits/issue_790_debug
Saved several AppVeyor screenshots of failed test. All screenshots look fine so far:
![image](https://user-images.githubusercontent.com/795040/63217898-6bdcb580-c1a2-11e9-82ec-b76d41e92930.png)

**Comment by vasily-v-ryabov** [comment]
`.set_focus()` is unreliable for tab switching. So calling `.select()` solves this test problem. I will make a separate fix for `.set_focus()` later in 0.7.0.
