### ISSUE TITLE
pywinauto.findbestmatch.MatchError: Could not find 'FloatActionBar'  

### ISSUE THREAD

**Issue by josewu2008** [pywinauto/pywinauto#791]
## Expected Behavior

app.window(best_match='FloatActionBar') can find the window

## Actual Behavior
raise MatchError(items = name_control_map.keys(), tofind = search_text)
pywinauto.findbestmatch.MatchError: Could not find 'FloatActionBar' in 'dict_keys(['TestWorld Test Meetings', 'Pane', 'TestWorld Test MeetingsPane'])'

## Steps to Reproduce the Problem

1. get the pid by the appname ;
2. get the app by the pid
3. Try find the subwindow  in the app  

## Short Example of Code to Demonstrate the Problem
``` python
import psutil
import pywinauto.application

pids = psutil.pids()
atmgrid=0
for pid in pids:
    p = psutil.Process(pid)
    if p.name().find("atmgr.exe") == 0:
        atmgrid=pid

print("atmgr id is %d" % atmgrid)

app  = pywinauto.application.Application(backend="uia").connect(process=atmgrid)
app.window(best_match='FloatActionBar').print_control_identifiers()`
```
``` python
Traceback (most recent call last):
  File "D:/project/tools/ui-ta/uidemo/demo1.py", line 15, in <module>
    app.window(best_match='FloatActionBar').print_control_identifiers()
  File "C:\Users\nimon\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pywinauto\application.py", line 595, in print_control_identifiers
    this_ctrl = self.__resolve_control(self.criteria)[-1]
  File "C:\Users\nimon\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pywinauto\application.py", line 259, in __resolve_control
    raise e.original_exception
  File "C:\Users\nimon\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pywinauto\timings.py", line 436, in wait_until_passes
    func_val = func(*args, **kwargs)
  File "C:\Users\nimon\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pywinauto\application.py", line 201, in __get_ctrl
    dialog = self.backend.generic_wrapper_class(findwindows.find_element(**criteria[0]))
  File "C:\Users\nimon\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pywinauto\findwindows.py", line 84, in find_element
    elements = find_elements(**kwargs)
  File "C:\Users\nimon\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pywinauto\findwindows.py", line 303, in find_elements
    elements = findbestmatch.find_best_control_matches(best_match, wrapped_elems)
  File "C:\Users\nimon\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pywinauto\findbestmatch.py", line 533, in find_best_control_matches
    raise MatchError(items = name_control_map.keys(), tofind = search_text)
pywinauto.findbestmatch.MatchError: Could not find 'FloatActionBar' in 'dict_keys([TestWorld Test Meetings', 'Pane', 'TestWorld Test  MeetingsPane'])'
```

 **I have dump the all window of the app , the 'FloatActionBar' is existed .**

```
child_window(title="TestWorld Test Meetings", control_type="Pane")
   | 
   | Pane - ''    (L-31357, T-31925, R-31277, B-31897)
   | ['Pane2', '', '0', '1']
   | 
   | Pane - 'FloatActionBar'    (L-31534, T-31306, R-31100, B-31252)
   | ['Pane3', 'FloatActionBar', 'FloatActionBarPane', 'FloatActionBar0', 'FloatActionBar1']
   | child_window(title="FloatActionBar", control_type="Pane")
   |    | 
   |    | Custom - ''    (L-31534, T-31279, R-31533, B-31278)
   |    | ['2', 'Custom', 'Custom0', 'Custom1']
   |    | 
   |    | Custom - ''    (L-31505, T-31306, R-31504, B-31305)
   |    | ['3', 'Custom2']
   |    | 
   |    | Button - 'Connect audio and video'    (L-31530, T-31306, R-31476, B-31252)
   |    | ['Connect audio and videoButton', 'Button', 'Connect audio and video', 'Button0', 'Button1', 'Connect audio and videoButton0', 'Connect audio and videoButton1', 'Connect audio and video0', 'Connect audio and video1']
   |    | child_window(title="Connect audio and video", control_type="Button")
   |    | 
   |    | Button - 'Share content'    (L-31468, T-31306, R-31414, B-31252)
   |    | ['Share contentButton', 'Button2', 'Share content', 'Share contentButton0', 'Share contentButton1', 'Share content0', 'Share content1']
   |    | child_window(title="Share content", control_type="Button")
   |    | 
   |    | Button - 'Recorder'    (L-31406, T-31306, R-31352, B-31252)
   |    | ['Button3', 'Recorder', 'RecorderButton', 'Recorder0', 'Recorder1', 'RecorderButton0', 'RecorderButton1']
   |    | child_window(title="Recorder", control_type="Button")
   |    |    | 
   |    |    | Custom - ''    (L-31381, T-31306, R-31380, B-31305)
   |    |    | ['4', 'Custom3']
   |    | 
   |    | Button - 'Participants'    (L-31344, T-31306, R-31290, B-31252)
   |    | ['Button4', 'ParticipantsButton', 'Participants', 'ParticipantsButton0', 'ParticipantsButton1', 'Participants0', 'Participants1']
   |    | child_window(title="Participants", control_type="Button")
   |    |    | 
   |    |    | Custom - ''    (L-31317, T-31306, R-31316, B-31305)
   |    |    | ['5', 'Custom4']
   |    | 
   |    | Button - 'Chat'    (L-31282, T-31306, R-31228, B-31252)
   |    | ['Button5', 'Chat', 'ChatButton', 'Chat0', 'Chat1', 'ChatButton0', 'ChatButton1']
   |    | child_window(title="Chat", control_type="Button")
   |    |    | 
   |    |    | Custom - ''    (L-31256, T-31306, R-31255, B-31305)
   |    |    | ['6', 'Custom5']
   |    | 
   |    | Button - 'More options'    (L-31220, T-31306, R-31166, B-31252)
   |    | ['More options', 'Button6', 'More optionsButton', 'More options0', 'More options1', 'More optionsButton0', 'More optionsButton1']
   |    | child_window(title="More options", control_type="Button")
   |    |    | 
   |    |    | Custom - ''    (L-31195, T-31306, R-31194, B-31305)
   |    |    | ['7', 'Custom6']
   |    |    | 
   |    |    | Custom - ''    (L-31195, T-31306, R-31194, B-31305)
   |    |    | ['7', 'Custom6']
   |    |    | 
   |    |    | Custom - ''    (L-31195, T-31306, R-31194, B-31305)
   |    |    | ['7', 'Custom6']
   |    | 
   |    | Button - 'End meeting'    (L-31158, T-31306, R-31104, B-31252)
   |    | ['Button7', 'End meetingButton', 'End meeting', 'End meetingButton0', 'End meetingButton1', 'End meeting0', 'End meeting1']
   |    | child_window(title="End meeting", control_type="Button")
   |    | 
   |    | Static - ''    (L-31100, T-31306, R-31099, B-31252)
   |    | ['10', 'Static', 'Static0', 'Static1']
   | 
   | Pane - ''    (L-30882, T-31927, R-30653, B-31893)
   | ['Pane4', '11']
   | 
   | Pane - ''    (L-31981, T-31927, R-31947, B-31893)
   | ['Pane5', '12']
   |    | 
   |    | Button - 'Meeting information'    (L-31981, T-31927, R-31947, B-31893)
   |    | ['Meeting information', 'Button8', 'Meeting informationButton', 'Meeting information0', 'Meeting information1', 'Meeting informationButton0', 'Meeting informationButton1']
   |    | child_window(title="Meeting information", control_type="Button")
   |    |    | 
   |    |    | Custom - ''    (L-31948, T-31910, R-31947, B-31909)
   |    |    | ['13', 'Custom9']
   | 
   | Custom - ''    (L-31996, T-31969, R-30638, B-31939)
   | ['14', 'Custom10']
   |    | 
   |    | Menu - ''    (L-31996, T-31969, R-30734, B-31939)
   |    | ['15', 'Menu']
   |    |    | 
   |    |    | MenuItem - 'File'    (L-31996, T-31969, R-31965, B-31939)
   |    |    | ['MenuItem', 'File', 'FileMenuItem', 'MenuItem0', 'MenuItem1']
   |    |    | child_window(title="File", control_type="MenuItem")
   |    |    | 
   |    |    | MenuItem - 'Edit'    (L-31965, T-31969, R-31931, B-31939)
   |    |    | ['MenuItem2', 'EditMenuItem', 'Edit']
   |    |    | child_window(title="Edit", control_type="MenuItem")
   |    |    | 
   |    |    | MenuItem - 'Share'    (L-31931, T-31969, R-31886, B-31939)
   |    |    | ['MenuItem3', 'Share', 'ShareMenuItem']
   |    |    | child_window(title="Share", control_type="MenuItem")
   |    |    | 
   |    |    | MenuItem - 'View'    (L-31886, T-31969, R-31847, B-31939)
   |    |    | ['View', 'ViewMenuItem', 'MenuItem4']
   |    |    | child_window(title="View", control_type="MenuItem")
   |    |    | 
   |    |    | MenuItem - 'Audio'    (L-31847, T-31969, R-31801, B-31939)
   |    |    | ['Audio', 'MenuItem5', 'AudioMenuItem']
   |    |    | child_window(title="Audio", control_type="MenuItem")
   |    |    | 
   |    |    | MenuItem - 'Participant'    (L-31801, T-31969, R-31728, B-31939)
   |    |    | ['Participant', 'MenuItem6', 'ParticipantMenuItem']
   |    |    | child_window(title="Participant", control_type="MenuItem")
   |    |    | 
   |    |    | MenuItem - 'Meeting'    (L-31728, T-31969, R-31668, B-31939)
   |    |    | ['Meeting', 'MenuItem7', 'MeetingMenuItem']
   |    |    | child_window(title="Meeting", control_type="MenuItem")
   |    |    | 
   |    |    | MenuItem - 'Help'    (L-31668, T-31969, R-31629, B-31939)
   |    |    | ['MenuItem8', 'HelpMenuItem', 'Help']
   |    |    | child_window(title="Help", control_type="MenuItem")
   |    | 
   |    | Custom - ''    (L-30734, T-31969, R-30638, B-31939)
   |    | ['16', 'Custom11']
   |    |    | 
   |    |    | Custom - ''    (L-30734, T-31969, R-30654, B-31939)
   |    |    | ['17', 'Custom12']
   |    |    |    | 
   |    |    |    | Static - 'Connected'    (L-30730, T-31970, R-30672, B-31940)
   |    |    |    | ['ConnectedStatic', 'Static2', 'Connected']
   |    |    |    | child_window(title="Connected", control_type="Text")
   |    |    |    | 
   |    |    |    | Custom - 'Secure connection with SSL'    (L-30664, T-31957, R-30658, B-31951)
   |    |    |    | ['Custom13', 'Secure connection with SSLCustom', 'Secure connection with SSL']
   |    |    |    | child_window(title="Secure connection with SSL", control_type="Custom")
   |    |    |    |    | 
   |    |    |    |    | Custom - ''    (L-30662, T-31952, R-30661, B-31951)
   |    |    |    |    | ['18', 'Custom14']
   | 
   | Custom - ''    (L-31996, T-31939, R-30638, B-31236)
   | ['19', 'Custom15']
   |    | 
   |    | Custom - ''    (L-31996, T-31939, R-30638, B-31236)
   |    | ['19', 'Custom15']
   |    |    | 
   |    |    | Custom - ''    (L-31534, T-31306, R-31100, B-31252)
   |    |    | ['21', 'Custom17']
   |    |    |    | 
   |    |    |    | Custom - 'WndActionBar'    (L-31534, T-31306, R-31100, B-31252)
   |    |    |    | ['WndActionBar', 'Custom18', 'WndActionBarCustom']
   |    |    |    | child_window(title="WndActionBar", control_type="Custom")
   |    |    |    |    | 
   |    |    |    |    | Custom - 'FloatActionBar'    (L-31534, T-31306, R-31100, B-31252)
   |    |    |    |    | ['FloatActionBar2', 'Custom19', 'FloatActionBarCustom']
   |    |    |    |    | child_window(title="FloatActionBar", control_type="Custom")
   |    |    |    |    |    | 
   |    |    |    |    |    | Custom - ''    (L-31534, T-31279, R-31533, B-31278)
   |    |    |    |    |    | ['2', 'Custom', 'Custom0', 'Custom1']
   |    |    |    |    |    | 
   |    |    |    |    |    | Custom - ''    (L-31505, T-31306, R-31504, B-31305)
   |    |    |    |    |    | ['3', 'Custom2']
   |    |    |    |    |    | 
   |    |    |    |    |    | Button - 'Connect audio and video'    (L-31530, T-31306, R-31476, B-31252)
   |    |    |    |    |    | ['Connect audio and videoButton', 'Button', 'Connect audio and video', 'Button0', 'Button1', 'Connect audio and videoButton0', 'Connect audio and videoButton1', 'Connect audio and video0', 'Connect audio and video1']
   |    |    |    |    |    | child_window(title="Connect audio and video", control_type="Button")
   |    |    |    |    |    | 
   |    |    |    |    |    | Button - 'Share content'    (L-31468, T-31306, R-31414, B-31252)
   |    |    |    |    |    | ['Share contentButton', 'Button2', 'Share content', 'Share contentButton0', 'Share contentButton1', 'Share content0', 'Share content1']
   |    |    |    |    |    | child_window(title="Share content", control_type="Button")
   |    |    |    |    |    | 
   |    |    |    |    |    | Button - 'Recorder'    (L-31406, T-31306, R-31352, B-31252)
   |    |    |    |    |    | ['Button3', 'Recorder', 'RecorderButton', 'Recorder0', 'Recorder1', 'RecorderButton0', 'RecorderButton1']
   |    |    |    |    |    | child_window(title="Recorder", control_type="Button")
   |    |    |    |    |    |    | 
   |    |    |    |    |    |    | Custom - ''    (L-31381, T-31306, R-31380, B-31305)
   |    |    |    |    |    |    | ['4', 'Custom3']
   |    |    |    |    |    | 
   |    |    |    |    |    | Button - 'Participants'    (L-31344, T-31306, R-31290, B-31252)
   |    |    |    |    |    | ['Button4', 'ParticipantsButton', 'Participants', 'ParticipantsButton0', 'ParticipantsButton1', 'Participants0', 'Participants1']
   |    |    |    |    |    | child_window(title="Participants", control_type="Button")
   |    |    |    |    |    |    | 
   |    |    |    |    |    |    | Custom - ''    (L-31317, T-31306, R-31316, B-31305)
   |    |    |    |    |    |    | ['5', 'Custom4']
   |    |    |    |    |    | 
   |    |    |    |    |    | Button - 'Chat'    (L-31282, T-31306, R-31228, B-31252)
   |    |    |    |    |    | ['Button5', 'Chat', 'ChatButton', 'Chat0', 'Chat1', 'ChatButton0', 'ChatButton1']
   |    |    |    |    |    | child_window(title="Chat", control_type="Button")
   |    |    |    |    |    |    | 
   |    |    |    |    |    |    | Custom - ''    (L-31256, T-31306, R-31255, B-31305)
   |    |    |    |    |    |    | ['6', 'Custom5']
   |    |    |    |    |    | 
   |    |    |    |    |    | Button - 'More options'    (L-31220, T-31306, R-31166, B-31252)
   |    |    |    |    |    | ['More options', 'Button6', 'More optionsButton', 'More options0', 'More options1', 'More optionsButton0', 'More optionsButton1']
   |    |    |    |    |    | child_window(title="More options", control_type="Button")
   |    |    |    |    |    |    | 
   |    |    |    |    |    |    | Custom - ''    (L-31195, T-31306, R-31194, B-31305)
   |    |    |    |    |    |    | ['7', 'Custom6']
   |    |    |    |    |    |    | 
   |    |    |    |    |    |    | Custom - ''    (L-31195, T-31306, R-31194, B-31305)
   |    |    |    |    |    |    | ['7', 'Custom6']
   |    |    |    |    |    |    | 
   |    |    |    |    |    |    | Custom - ''    (L-31195, T-31306, R-31194, B-31305)
   |    |    |    |    |    |    | ['7', 'Custom6']
   |    |    |    |    |    | 
   |    |    |    |    |    | Button - 'End meeting'    (L-31158, T-31306, R-31104, B-31252)
   |    |    |    |    |    | ['Button7', 'End meetingButton', 'End meeting', 'End meetingButton0', 'End meetingButton1', 'End meeting0', 'End meeting1']
   |    |    |    |    |    | child_window(title="End meeting", control_type="Button")
   |    |    |    |    |    | 
   |    |    |    |    |    | Static - ''    (L-31100, T-31306, R-31099, B-31252)
   |    |    |    |    |    | ['10', 'Static', 'Static0', 'Static1']
   |    |    | 
   |    |    | Custom - ''    (L-31981, T-31927, R-30653, B-31893)
   |    |    | ['31', 'Custom28']
   |    |    |    | 
   |    |    |    | Custom - ''    (L-31981, T-31927, R-30653, B-31893)
   |    |    |    | ['31', 'Custom28']
   |    |    |    |    | 
   |    |    |    |    | Custom - ''    (L-31981, T-31927, R-31947, B-31893)
   |    |    |    |    | ['33', 'Custom30']
   |    |    |    |    |    | 
   |    |    |    |    |    | Button - 'Meeting information'    (L-31981, T-31927, R-31947, B-31893)
   |    |    |    |    |    | ['Meeting information', 'Button8', 'Meeting informationButton', 'Meeting information0', 'Meeting information1', 'Meeting informationButton0', 'Meeting informationButton1']
   |    |    |    |    |    | child_window(title="Meeting information", control_type="Button")
   |    |    |    |    |    |    | 
   |    |    |    |    |    |    | Custom - ''    (L-31948, T-31910, R-31947, B-31909)
   |    |    |    |    |    |    | ['13', 'Custom9']
   |    |    |    |    | 
   |    |    |    |    | Custom - ''    (L-30882, T-31927, R-30653, B-31893)
   |    |    |    |    | ['35', 'Custom32']

Process finished with exit code 0
```

## Specifications

  - Pywinauto version: Version: 0.6.7
  - Python version and bitness: Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 22:20:52) [MSC v.1916 32 bit (Intel)] on win32
  - Platform and OS: win10 64 bit

**Comment by vasily-v-ryabov** [comment]
It should be `app.window(best_match='FloatActionBar', top_level_only=False)` because first level of specification is top level window by default.

**Comment by josewu2008** [comment]
Thanks your great help , work now!
