### ISSUE TITLE
cannot find the popup dialog

### ISSUE THREAD

**Issue by josewu2008** [pywinauto/pywinauto#792]
## Expected Behavior
can find the popup dialog after clicking one  button

## Actual Behavior
cannot  find the popup dialog after clicking one  button

## Steps to Reproduce the Problem

  1.connec the app with the app processID
  2. click the ''callin' button in the dialog, one dialog popup 
  3. try to find the dialog

## Short Example of Code to Demonstrate the Problem
``` python
app = pywinauto.application.Application(backend="uia").connect(process=atmgrid)
# click call in button to popup Audio Connection dialog
app[apptopwindown][callinbutton].click_input()
# search the popup dialog
Audio = app.window(title_re='Audio Connection').print_control_identifiers()
``` 
``` python
Traceback (most recent call last):
  File "C:/ta-projects/uita2/testuita/meetingclient.py", line 21, in <module>
    app[tipwindowname][callin].click_input()
  File "C:\Users\test\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pywinauto\application.py", line 362, in __getattribute__
    ctrls = self.__resolve_control(self.criteria)
  File "C:\Users\test\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pywinauto\application.py", line 259, in __resolve_control
    raise e.original_exception
  File "C:\Users\test\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pywinauto\timings.py", line 436, in wait_until_passes
    func_val = func(*args, **kwargs)
  File "C:\Users\test\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pywinauto\application.py", line 201, in __get_ctrl
    dialog = self.backend.generic_wrapper_class(findwindows.find_element(**criteria[0]))
  File "C:\Users\test\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pywinauto\findwindows.py", line 84, in find_element
    elements = find_elements(**kwargs)
  File "C:\Users\test\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pywinauto\findwindows.py", line 303, in find_elements
    elements = findbestmatch.find_best_control_matches(best_match, wrapped_elems)
  File "C:\Users\test\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pywinauto\findbestmatch.py", line 533, in find_best_control_matches
    raise MatchError(items = name_control_map.keys(), tofind = search_text)
pywinauto.findbestmatch.MatchError: Could not find 'Meetings' in 'dict_keys(['Pane', TestWorld Test Meetings', 'TestWorld Test  MeetingsPane'])'

``` 
the inspect tool can find the dialog

![audio-dia](https://user-images.githubusercontent.com/5562163/62926669-87813e00-bde7-11e9-9e46-f88f7b644c5e.PNG)

## Specifications

  - Pywinauto version: Version: 0.6.7
  - Python version and bitness: Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 22:20:52) [MSC v.1916 32 bit (Intel)] on win32
  - Platform and OS: win10 64 bit

**Comment by vasily-v-ryabov** [comment]
According to provided traceback this line fails: `app[apptopwindown][callinbutton].click_input()` Please read tracebacks carefully.

**Comment by vasily-v-ryabov** [comment]
Also I'd recommend to switch `Inspect.exe` to "UI Automation" mode. It provides more info usually.

**Comment by josewu2008** [comment]
Sorry I modified the code according to  the example ms_paints
'''python
app = pywinauto.application.Application(backend="uia").connect(process=atmgrid)
# click call in button to popup Audio Connection dialog
dlg = app.window(title=tipwindowname)
dlg.print_control_identifiers()
#popup Audio Connection dialog
dlg[callin].click_input()
# search the popup windown
dlg.child_window(title='Audio Connection', found_index=0).invoke()
dlg.AudioConnection.Callme.click_input()
'''

'''python
Traceback (most recent call last):
  File "C:\Users\test\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pywinauto\uia_defines.py", line 234, in get_elem_interface
    iface = cur_ptrn.QueryInterface(cls_name)
  File "C:\Users\test\AppData\Local\Programs\Python\Python37-32\lib\site-packages\comtypes\__init__.py", line 1158, in QueryInterface
    self.__com_QueryInterface(byref(iid), byref(p))
ValueError: NULL COM pointer access

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/ta-projects/uita2/testuita/meetingclient.py", line 27, in <module>
    dlg.child_window(title='Audio Connection', found_index=0).invoke()
  File "C:\Users\test\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pywinauto\controls\uiawrapper.py", line 513, in invoke
    self.iface_invoke.Invoke()
  File "C:\Users\test\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pywinauto\controls\uiawrapper.py", line 132, in __get__
    value = self.fget(obj)
  File "C:\Users\test\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pywinauto\controls\uiawrapper.py", line 231, in iface_invoke
    return uia_defs.get_elem_interface(elem, "Invoke")
  File "C:\Users\test\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pywinauto\uia_defines.py", line 236, in get_elem_interface
    raise NoPatternInterfaceError()
pywinauto.uia_defines.NoPatternInterfaceError
'''

**Comment by josewu2008** [comment]
thanks , now I modified the code according to the example ms_paints, successfully
``` python
app = pywinauto.application.Application(backend="uia").connect(process=atmgrid)
# click call in button to popup Audio Connection dialog
dlg = app.window(title=tipwindowname)
dlg.print_control_identifiers()
#popup Audio Connection dialog
dlg[callin].click_input()
# search the popup windown
#dlg.child_window(title='Audio Connection', found_index=0).print_control_identifiers()
dlg.AudioConnection.Callme.click_input()
```

**Comment by vasily-v-ryabov** [comment]
OK, it seems the issue has been resolved. Closing. Please re-open or submit new one if it's still relevant.
