### ISSUE TITLE
UpDown's control methods are not working

### ISSUE THREAD

**Issue by BorkowskiDominik** [pywinauto/pywinauto#796]
## Expected Behavior
UpDown's methods are invoked correctly.

## Actual Behavior
I can't invoke methods for UpDown control. 
when I run: `app.dlg.UpDown.GetValue()` 
I get: 

> Neither GUI element (wrapper) nor wrapper method 'GetValue' were found.
but when I run
`print(app.dlg.UpDown3.wrapper_object())`
I get 
> uiawrapper.UIAWrapper - '', UpDown

Is there anything I can do about this to make it work? 

## Specifications

  - Pywinauto version: pywinauto==0.6.7
  - Python version and bitness: Python 3.7.4 64bit
  - Platform and OS: Windows 10

**Comment by airelil** [comment]
I think the proper name for the method should be `get_value`. We might need to update the docs.

**Comment by BorkowskiDominik** [comment]
> I think the proper name for the method should be `get_value`. We might need to update the docs.

I tried that, but with the same result:
> AttributeError: Neither GUI element (wrapper) nor wrapper method 'get_value' were found (typo?)

It seems that control is not recognized as UpDown control. Is there a way to force casting? 

I don't know if this is important but in inspect tool exact control type is: 
>UIA_SpinnerControlTypeId (0xC360)

**Comment by airelil** [comment]
Sorry @BorkowskiDominik ,  I didn't notice that you mentioned UIA in your first comment. The UpDown wrapper is implemented only for `win32` backend. If you still want to try working with it through `uia` backend you should use directly `iface_` properties of `UIAWrapper` class. Have a look at implementation of [SliderWrapper](https://github.com/pywinauto/pywinauto/blob/eb4ab91684a2861190da3a55725a67fb8d221789/pywinauto/controls/uia_controls.py#L541) in uia_controls.py as an example. For your code, it would look like
```python
wrp = app.dlg.UpDown3.wrapper_object()

#Get minimum value of the spinner control
print(wrp.iface_range_value.CurrentMinimum)

#Get current value
print(wrp.iface_range_value.CurrentValue)
```
As per Microsoft spec: https://docs.microsoft.com/en-us/windows/win32/winauto/uiauto-supportspinnercontroltype, there are several  UI Automation control patterns that can be supported by the Spinner control. However, all of them are optional and depend on implementation details. As a result, you might see that `iface_rance_value` property throws an exception because `IRangeValueProvider` pattern is not supported by the control in your application. In that case, you may opt out for `IValueProvider` available with `iface_value` property of UIAWrapper.
```python
wrp = app.dlg.UpDown3.wrapper_object()

#Get the value of the spinner control through IValueProvider interface
print(wrp.iface_value.CurrentValue)
```

**Comment by saimadao** [comment]
Hi I have meet the same issue, but when use iface_value I got the below error
Code:
print(mainForm.child_window(auto_id="numericUpDown1").child_window(control_type='Spinner').get_properties())
mainForm.child_window(auto_id="numericUpDown1").child_window(control_type='Spinner').wrapper_object().iface_value.CurrentValue

Error:
{'class_name': 'WindowsForms10.Window.8.app.0.141b42a_r7_ad1', 'friendly_class_name': 'UpDown', 'texts': ['Spinner'], 'control_id': 657394, 'rectangle': <RECT L400, T342, R416, B360>, 'is_visible': True, 'is_enabled': True, 'control_count': 2, 'is_keyboard_focusable': True, 'has_keyboard_focus': False, 'automation_id': '657394'}

Traceback (most recent call last):
  File "C:\Users\z003v11s\AppData\Roaming\Python\Python38\site-packages\pywinauto\uia_defines.py", line 234, in get_elem_interface
    iface = cur_ptrn.QueryInterface(cls_name)
  File "C:\Users\z003v11s\AppData\Roaming\Python\Python38\site-packages\comtypes\__init__.py", line 1198, in QueryInterface
    self.__com_QueryInterface(byref(iid), byref(p))
ValueError: NULL COM pointer access

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:/WorkSpace/winUIA/winFormTest.py", line 130, in <module>
    mainForm.child_window(auto_id="numericUpDown1").child_window(control_type='Spinner').wrapper_object().iface_value.CurrentValue
  File "C:\Users\z003v11s\AppData\Roaming\Python\Python38\site-packages\pywinauto\controls\uiawrapper.py", line 132, in __get__
    value = self.fget(obj)
  File "C:\Users\z003v11s\AppData\Roaming\Python\Python38\site-packages\pywinauto\controls\uiawrapper.py", line 252, in iface_value
    return uia_defs.get_elem_interface(elem, "Value")
  File "C:\Users\z003v11s\AppData\Roaming\Python\Python38\site-packages\pywinauto\uia_defines.py", line 236, in get_elem_interface
    raise NoPatternInterfaceError()
pywinauto.uia_defines.NoPatternInterfaceError
