### ISSUE TITLE
Basic Tutorial Documentation Failing

### ISSUE THREAD

**Issue by theonewolf** [pywinauto/pywinauto#801]
## Expected Behavior

Expected the primary example on http://pywinauto.github.io/ to execute without exception.

## Actual Behavior

```
C:\Users\WolfgangRichter\Desktop>python
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:13:57) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from pywinauto.application import Application
>>> app = Application().start("notepad.exe")
>>> app.UntitledNotepad.menu_select("Help->About Notepad")
Traceback (most recent call last):
  File "C:\Users\WolfgangRichter\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pywinauto\application.py", line 256, in __resolve_control
    criteria)
  File "C:\Users\WolfgangRichter\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pywinauto\timings.py", line 458, in wait_until_passes
    raise err
pywinauto.timings.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\WolfgangRichter\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pywinauto\application.py", line 378, in __getattribute__
    ctrls = self.__resolve_control(self.criteria)
  File "C:\Users\WolfgangRichter\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pywinauto\application.py", line 259, in __resolve_control
    raise e.original_exception
  File "C:\Users\WolfgangRichter\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pywinauto\timings.py", line 436, in wait_until_passes
    func_val = func(*args, **kwargs)
  File "C:\Users\WolfgangRichter\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pywinauto\application.py", line 201, in __get_ctrl
    dialog = self.backend.generic_wrapper_class(findwindows.find_element(**criteria[0]))
  File "C:\Users\WolfgangRichter\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pywinauto\findwindows.py", line 84, in find_element
    elements = find_elements(**kwargs)
  File "C:\Users\WolfgangRichter\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pywinauto\findwindows.py", line 303, in find_elements
    elements = findbestmatch.find_best_control_matches(best_match, wrapped_elems)
  File "C:\Users\WolfgangRichter\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pywinauto\findbestmatch.py", line 533, in find_best_control_matches
    raise MatchError(items = name_control_map.keys(), tofind = search_text)
pywinauto.findbestmatch.MatchError: Could not find 'UntitledNotepad' in 'dict_keys([])'
```

## Steps to Reproduce the Problem

  1. Install `pywinauto` with `pip install pywinauto comtypes==1.1.4`
  2. Run the short code sample below (verbatim from the website)

## Short Example of Code to Demonstrate the Problem

```
>>> from pywinauto.application import Application
>>> app = Application().start("notepad.exe")
>>> app.UntitledNotepad.menu_select("Help->About Notepad")
```

## Specifications

  - Pywinauto version: 0.6.7
  - Python version and bitness: 3.7.4, x86-64
  - Platform and OS: Windows 10, 64-bit

**Comment by airelil** [comment]
Hey @theonewolf , just and idea. Could it be that you run a version of Notepad translated to a local language? Notice, that the localised applications will have translated window titles

**Comment by vasily-v-ryabov** [comment]
If this is Windows localization, we can't recommend something useful except switching to English in OS settings. If we want to support several locales it requires plenty of work. Some old code design takes this opportunity into account, but we had no chance to revive it yet. No real chance for this feature for next 2 years at least. Because there is no much demand for real apps testing and many other bigger plans on Linux and macOS.

Yes, it may confuse for the first use. But if it's for bug report / reputation of project only, this is low priority, sorry. Any ideas on how to improve it another way are welcome.
