### ISSUE TITLE
Checking an item within a ListBox generates exception

### ISSUE THREAD

**Issue by jethro33** [pywinauto/pywinauto#830]
## Expected Behavior

I have a series of items in a ListBox presented in the following picture:

![listbox](https://user-images.githubusercontent.com/20145526/65861705-0701a700-e36d-11e9-8a9f-40a840bff4d4.PNG)

The following is a snippet of the related control identifiers:

```
   |    | ListBox - ''    (L2888, T543, R3185, B709)
   |    | ['0ListBox', 'ListBox', 'ListBox0', 'ListBox1']
   |    | child_window(auto_id="1046", control_type="List")
   |    |    | 
   |    |    | Header - ''    (L2890, T545, R3183, B562)
   |    |    | ['1 Header', 'Header', 'Header0', 'Header1']
   |    |    | child_window(auto_id="Header", control_type="Header")
   |    |    |    | 
   |    |    |    | HeaderItem - 'Index'    (L2890, T545, R2940, B562)
   |    |    |    | ['Index', 'HeaderItem', 'IndexHeaderItem', 'HeaderItem0', 'HeaderItem1', 'Index0', 'Index1', 'IndexHeaderItem0', 'IndexHeaderItem1']
   |    |    |    | child_window(title="Index", control_type="HeaderItem")
   |    |    |    | 
   |    |    |    | HeaderItem - 'Start'    (L2940, T545, R3025, B562)
   |    |    |    | ['StartHeaderItem', 'Start2', 'HeaderItem2', 'StartHeaderItem0', 'StartHeaderItem1']
   |    |    |    | child_window(title="Start", control_type="HeaderItem")
   |    |    |    | 
   |    |    |    | HeaderItem - 'End'    (L3025, T545, R3110, B562)
   |    |    |    | ['EndHeaderItem', 'HeaderItem3', 'End', 'EndHeaderItem0', 'EndHeaderItem1', 'End0', 'End1']
   |    |    |    | child_window(title="End", control_type="HeaderItem")
   |    |    |    | 
   |    |    |    | HeaderItem - 'Size'    (L3110, T545, R3150, B562)
   |    |    |    | ['SizeHeaderItem', 'HeaderItem4', 'Size', 'SizeHeaderItem0', 'SizeHeaderItem1', 'Size0', 'Size1']
   |    |    |    | child_window(title="Size", control_type="HeaderItem")
   |    |    | 
   |    |    | ScrollBar - 'Vertical'    (L3166, T545, R3183, B707)
   |    |    | ['Vertical', 'VerticalScrollBar', 'ScrollBar', 'Vertical0', 'Vertical1', 'VerticalScrollBar0', 'VerticalScrollBar1', 'ScrollBar0', 'ScrollBar1']
   |    |    | child_window(title="Vertical", auto_id="NonClientVerticalScrollBar", control_type="ScrollBar")
   |    |    |    | 
   |    |    |    | Button - 'Line up'    (L3166, T545, R3183, B562)
   |    |    |    | ['Line up', 'Line upButton', 'Button5', 'Line up0', 'Line up1', 'Line upButton0', 'Line upButton1']
   |    |    |    | child_window(title="Line up", auto_id="UpButton", control_type="Button")
   |    |    |    | 
   |    |    |    | Thumb - 'Position'    (L3166, T562, R3183, B607)
   |    |    |    | ['Thumb', 'PositionThumb', 'Position', 'Thumb0', 'Thumb1', 'PositionThumb0', 'PositionThumb1', 'Position0', 'Position1']
   |    |    |    | child_window(title="Position", auto_id="ScrollbarThumb", control_type="Thumb")
   |    |    |    | 
   |    |    |    | Button - 'Page down'    (L3166, T607, R3183, B690)
   |    |    |    | ['Page down', 'Button6', 'Page downButton', 'Page down0', 'Page down1', 'Page downButton0', 'Page downButton1']
   |    |    |    | child_window(title="Page down", auto_id="DownPageButton", control_type="Button")
   |    |    |    | 
   |    |    |    | Button - 'Line down'    (L3166, T690, R3183, B707)
   |    |    |    | ['Line downButton', 'Line down', 'Button7', 'Line downButton0', 'Line downButton1', 'Line down0', 'Line down1']
   |    |    |    | child_window(title="Line down", auto_id="DownButton", control_type="Button")
   |    |    | 
   |    |    | ListItem - '0'    (L2890, T564, R3150, B581)
   |    |    | ['0ListItem', '0', 'ListItem', '00', '01', 'ListItem0', 'ListItem1']
   |    |    | child_window(title="0", control_type="ListItem")
   |    |    |    | 
   |    |    |    | Static - '0'    (L2890, T564, R3150, B581)
   |    |    |    | ['0Static', 'Static', '02', 'Static0', 'Static1']
   |    |    |    | child_window(title="0", control_type="Text")
   |    |    |    | 
   |    |    |    | Static - '0xA0000000'    (L2940, T564, R3025, B581)
   |    |    |    | ['Static2', '0xA0000000Static', '0xA0000000', '0xA0000000Static0', '0xA0000000Static1', '0xA00000000', '0xA00000001']
   |    |    |    | child_window(title="0xA0000000", control_type="Text")
   |    |    |    | 
   |    |    |    | Static - '0xA0003FFF'    (L3025, T564, R3110, B581)
   |    |    |    | ['0xA0003FFFStatic', 'Static3', '0xA0003FFF', '0xA0003FFFStatic0', '0xA0003FFFStatic1', '0xA0003FFF0', '0xA0003FFF1']
   |    |    |    | child_window(title="0xA0003FFF", control_type="Text")
   |    |    |    | 
   |    |    |    | Static - '16K'    (L3110, T564, R3150, B581)
   |    |    |    | ['Static4', '16KStatic', '16K', '16KStatic0', '16KStatic1', '16K0', '16K1']
   |    |    |    | child_window(title="16K", control_type="Text")
   |    |    | 
   |    |    | ListItem - '1'    (L2890, T581, R3150, B598)
   |    |    | ['1ListItem', '1', 'ListItem2', '10', '11', '100', '101', '110', '111']
   |    |    | child_window(title="1", control_type="ListItem")
   |    |    |    | 
   |    |    |    | Static - '1'    (L2890, T581, R3150, B598)
   |    |    |    | ['1Static', 'Static5', '12', '120', '121']
   |    |    |    | child_window(title="1", control_type="Text")
   |    |    |    | 
   |    |    |    | Static - '0xA0004000'    (L2940, T581, R3025, B598)
   |    |    |    | ['0xA0004000Static', 'Static6', '0xA0004000', '0xA0004000Static0', '0xA0004000Static1', '0xA00040000', '0xA00040001']
   |    |    |    | child_window(title="0xA0004000", control_type="Text")
   |    |    |    | 
   |    |    |    | Static - '0xA0007FFF'    (L3025, T581, R3110, B598)
   |    |    |    | ['0xA0007FFFStatic', 'Static7', '0xA0007FFF', '0xA0007FFFStatic0', '0xA0007FFFStatic1', '0xA0007FFF0', '0xA0007FFF1']
   |    |    |    | child_window(title="0xA0007FFF", control_type="Text")
   |    |    |    | 
   |    |    |    | Static - '16K'    (L3110, T581, R3150, B598)
   |    |    |    | ['Static8', '16KStatic2', '16K2']
   |    |    |    | child_window(title="16K", control_type="Text")
```

I would like to be able to check the items within the ListBox in this way:

![listbox_checked](https://user-images.githubusercontent.com/20145526/65861974-898a6680-e36d-11e9-8ba5-74e578d6cc0b.PNG)

In order to do so I tried

```
1 - dlg["ListBox3"].select().get_item(0).select()
2 - dlg["ListBox3"].select().get_item(0).click()
3 - dlg["ListBox3"].select().get_item(0).check()
```

## Actual Behavior

```
I get the following exception in all these cases I tried so far:

Traceback (most recent call last):
  File "C:\Users\ABJ1MI\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pywinauto\uia_defines.py", line 234, in get_elem_interface
    iface = cur_ptrn.QueryInterface(cls_name)
  File "C:\Users\ABJ1MI\AppData\Local\Programs\Python\Python37-32\lib\site-packages\comtypes\__init__.py", line 1158, in QueryInterface
    self.__com_QueryInterface(byref(iid), byref(p))
ValueError: NULL COM pointer access

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ABJ1MI\Desktop\TRAINING\CppBatch\python\dev.py", line 12, in <module>
    lb = dlg["ListBox3"].select().click()
  File "C:\Users\ABJ1MI\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pywinauto\controls\uiawrapper.py", line 605, in select
    self.iface_selection_item.Select()
  File "C:\Users\ABJ1MI\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pywinauto\controls\uiawrapper.py", line 132, in __get__
    value = self.fget(obj)
  File "C:\Users\ABJ1MI\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pywinauto\controls\uiawrapper.py", line 224, in iface_selection_item
    return uia_defs.get_elem_interface(elem, "SelectionItem")
  File "C:\Users\ABJ1MI\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pywinauto\uia_defines.py", line 236, in get_elem_interface
    raise NoPatternInterfaceError()
pywinauto.uia_defines.NoPatternInterfaceError
```

## Steps to Reproduce the Problem

  1. Find an application which has a ListBox similar to the one presented in the issue description
  2. Try to select one of the items and check them out with the methods `click()`, `select()` or `check()`

## Short Example of Code to Demonstrate the Problem

```
app = Application(backend="uia").start("path\to\app\app.exe")
dlg = app.top_window()
dlg["Open ListBox3"].click()

dlg["ListBox3"].select().get_item(0).click()
```

## Specifications

  - Pywinauto version: 0.6.7
  - Python version and bitness: x64
  - Platform and OS: x64, Windows 10

**Comment by vasily-v-ryabov** [comment]
This ListBox probably doesn't support `SelectPattern` which can be checked in `Inspect.exe` in "UI Automation" mode.

What you can do is this:
```python
dlg["ListBox3"].child_window(title="1", control_type="ListItem").child_window(title="1", control_type="Text").click_input()
```

Method `click_input()` doesn't rely on internal UI element implementation. It just performs realistic click with real mouse cursor move.
