### ISSUE TITLE
Accessing the context menus in pywinauto

### ISSUE THREAD

**Issue by Sathis89** [pywinauto/pywinauto#850]
Hello All,

I could not able to select the context menus. Can anyone pls help on this topic ?. I could not able to attach the screen shot because of some issue with the file attachment.

Thanks in Advance !!

**Comment by airelil** [comment]
Any use of the docs below?
https://pywinauto.readthedocs.io/en/latest/getting_started.html
https://pywinauto.readthedocs.io/en/latest/index.html#how-does-it-work

**Comment by Sathis89** [comment]
Yes, I have used already.
I am using python 2.7 and for the below code I am getting error. I could not able to access the menus. Can you pls help on this ?

app = Application().connect(process=11644)
wind = app.top_window_().menu()

Error:
Traceback (most recent call last):
  File "D:\users\sch9cob\python\pywin_check.py", line 61, in <module>
    wind = app.top_window_().menu()
  File "C:\Python27\lib\site-packages\pywinauto-0.5.4-py2.7.egg\pywinauto\application.py", line 131, in __call__
    self.criteria[-1]['best_match'])
AttributeError: WindowSpecification class has no 'menu' method

**Comment by airelil** [comment]
Here is an example from our old issue for the "right-click" pop up menus:
```python
from pywinauto import Application

app_path = r"C:\Users\DELL\Downloads\Sublime Text Build 3176 x64\sublime_text.exe"
file_to_open = r"C:\Users\DELL\Downloads\Sublime Text Build 3176 x64\test.txt"

sublime = Application().start(app_path)

p_sublime = sublime.window(title_re=".*Sublime")

p_sublime.click_input(button='right')

sublime.PopupMenu.wait('ready').menu().get_menu_path('Paste')[0].click_input()
```
For application menus you can refer to examples in our unit tests. 
win32 backend and the famous Notepad app:
https://github.com/pywinauto/pywinauto/blob/bea648b134664f2dc4ce27b30d628f86bd8b5a26/pywinauto/unittests/test_clipboard.py#L62

uia backend:
https://github.com/pywinauto/pywinauto/blob/bea648b134664f2dc4ce27b30d628f86bd8b5a26/pywinauto/unittests/test_uiawrapper.py#L1535

**Comment by Sathis89** [comment]
Hi,
Thank you for the reply.

I can able to access the menus ab above. Now I need to access the menus in the window which appears when I pressed workspace option in the view tab. Menus are like tree view, I could not able to access the menus, I can able to click option in the View tab but I could not able to access the opened window. Please provide a solution. I could not able to attach screen shot here, throwing some error.

Thanks in Advance !!

**Comment by Sathis89** [comment]
Hi,

I can able to select the Menu items but click option throws error as below. How to resolve this issue?
Please help.

Traceback (most recent call last):
  File "D:\Satheesh\Perl\Python\18.11.19\app_auto_win.py", line 108, in <module>
    print(main_list.click())
  File "C:\toolbase\python\3.6.6.2.3\python-3.6.6.amd64\lib\site-packages\pywinauto\controls\hwndwrapper.py", line 750, in click
    self._ensure_enough_privileges('WM_*BUTTONDOWN/UP')
  File "C:\toolbase\python\3.6.6.2.3\python-3.6.6.amd64\lib\site-packages\pywinauto\controls\hwndwrapper.py", line 460, in _ensure_enough_privileges
    '(to resolve it run the script as Administrator)'.format(message_name))
RuntimeError: Not enough rights to use WM_*BUTTONDOWN/UP message/function for target process (to resolve it run the script as Administrator).

Thank you!!

**Comment by airelil** [comment]
The exception is thrown when the Python process exuting the pywinauto script doesn't have "administrator" rights. As suggested by the error message you should try to run the script as Administrator.

Another option would be using `click_input` method instead of the `click`: (https://pywinauto.readthedocs.io/en/latest/code/pywinauto.controls.hwndwrapper.html#pywinauto.controls.hwndwrapper.HwndWrapper.click)
