### ISSUE TITLE
[pytest integration] (Windows fatal exception: code 0x80010108) @ comtypes

### ISSUE THREAD

**Issue by ykangpark** [pywinauto/pywinauto#858]
## Description
Running pytest with pywinauto causes an exception in shutdown of comtypes.
Tests are collected / run correctly, but at the end there's always an exception output.

This breaks test discovery in VSCode, though I can work around it by moving import statements to the inside of fixtures / functions.

I am not sure if this is an issue with how I am using pytest and pywinauto, or its a bug.

I tried python 3.6 (Visual Studio 2017), 3.7 (Anaconda3), and 3.8 (python.org).

## Example code
File test_case.py
```
import pytest
from pywinauto.application import Application

def test_case():
    assert True
```

## Test discovery
In the directory containing test_case.py
`python -m pytest --collect-only`

Output
```
========================================================================================= test session starts ========================================================================================== 
platform win32 -- Python 3.8.0, pytest-5.3.1, py-1.8.0, pluggy-0.13.1
rootdir: C:\Users\Yujin\Desktop\pytest_pywinauto
collected 1 item
<Module test_case.py>
  <Function test_case>

=========================================================================================== warnings summary =========================================================================================== 
C:\Users\Yujin\AppData\Roaming\Python\Python38\site-packages\win32\lib\pywintypes.py:2
  C:\Users\Yujin\AppData\Roaming\Python\Python38\site-packages\win32\lib\pywintypes.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp, sys, os

-- Docs: https://docs.pytest.org/en/latest/warnings.html
========================================================================================== 1 warning in 0.17s ========================================================================================== 
Windows fatal exception: code 0x80010108

Thread 0x0000625c (most recent call first):
  File "C:\Users\Yujin\AppData\Roaming\Python\Python38\site-packages\comtypes\__init__.py", line 185 in shutdown
Windows fatal exception: code 0x80010108

Thread 0x0000625c (most recent call first):
  File "C:\Users\Yujin\AppData\Roaming\Python\Python38\site-packages\comtypes\__init__.py", line 185 in shutdown
```

## Running the test
`python -m pytest`
```
C:\Users\Yujin\Desktop\pytest_pywinauto>"C:/Program Files/Python38/python.exe" -m pytest
========================================================================================= test session starts ========================================================================================== 
platform win32 -- Python 3.8.0, pytest-5.3.1, py-1.8.0, pluggy-0.13.1
rootdir: C:\Users\Yujin\Desktop\pytest_pywinauto
collected 1 item                                                                                                                                                                                         

test_case.py .                                                                                                                                                                                    [100%] 

=========================================================================================== warnings summary =========================================================================================== 
C:\Users\Yujin\AppData\Roaming\Python\Python38\site-packages\win32\lib\pywintypes.py:2
  C:\Users\Yujin\AppData\Roaming\Python\Python38\site-packages\win32\lib\pywintypes.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp, sys, os

-- Docs: https://docs.pytest.org/en/latest/warnings.html
===================================================================================== 1 passed, 1 warning in 0.18s ===================================================================================== 
Windows fatal exception: code 0x80010108

Thread 0x00005e8c (most recent call first):
  File "C:\Users\Yujin\AppData\Roaming\Python\Python38\site-packages\comtypes\__init__.py", line 185 in shutdown
Windows fatal exception: code 0x80010108

Thread 0x00005e8c (most recent call first):
  File "C:\Users\Yujin\AppData\Roaming\Python\Python38\site-packages\comtypes\__init__.py", line 185 in shutdown
```

## Specifications
  - pywin32 version: 227
  - comtypes version: 1.1.7 
  - Pytest version: 5.3.1
  - Pywinauto version: 0.6.8
  - Python version and bitness: 3.8 (64 bit) (also tried 3.6, 3.7)
  - Platform and OS: Win10 x64

**Comment by airelil** [comment]
Seems to be also reported on StackOverflow: https://stackoverflow.com/questions/57523762/pytest-windows-fatal-exception-code-0x8001010d

The error: 0x80010108 - RPC_E_DISCONNECTED reported for many other cases as well. Examples:
https://stackoverflow.com/questions/47429782/rpc-e-disconnected-error0x80010108-while-calling-a-callback-aftre-6-mins
https://stackoverflow.com/questions/38964478/comexception-the-object-invoked-has-disconnected-from-its-clients

For starters, I would try to enable debugs on comtypes and run the simplest test again.
```python
import logging
log = logging.getLogger('comtypes')
log.setLevel('DEBUG')

import pytest
from pywinauto.application import Application

def test_case():
    assert True
```

**Comment by KyleKing** [comment]
I started having this issue as well after upgrading from Windows 7 to Windows 10 64-bit (1903). The 0x80010108 exception causes a Windows pop-up to appear saying that Python crashed (which is probably specific to running pyWinAuto in a separate thread with multiprocessing), but creating a new project with the one test case from the last comment, I get the below error message:

(Note: works with Python 2.7.15, but not Python 3.7.5 - both Python versions are managed with Miniconda)

```
C:\Users\king.kyle\Developer\Packages\PyWinAuto-Win10Error>pytest
============================= test session starts =============================
platform win32 -- Python 2.7.15, pytest-3.6.4, py-1.8.0, pluggy-0.6.0
rootdir: C:\Users\king.kyle\Developer\Packages\PyWinAuto-Win10Error, inifile:
plugins: cov-2.6.1
collected 1 item

tests\test_pywinauto_fatalerror.py .                                     [100%]

========================== 1 passed in 0.65 seconds ===========================

C:\Users\king.kyle\Developer\Packages\PyWinAuto-Win10Error>activate py375

(py375) C:\Users\king.kyle\Developer\Packages\PyWinAuto-Win10Error>pytest
=========================================== test session starts =========================================== 
platform win32 -- Python 3.7.5, pytest-5.3.4, py-1.8.1, pluggy-0.13.1
rootdir: C:\Users\king.kyle\Developer\Packages\PyWinAuto-Win10Error
plugins: dash-1.8.0, cov-2.8.1, html-2.0.1, metadata-1.8.0, timeout-1.3.4
collected 1 item                                                                                            

tests\test_pywinauto_fatalerror.py .                                                                 [100%] 

============================================ 1 passed in 0.36s ============================================ 
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\king.kyle\appdata\local\continuum\anaconda2\envs\py375\lib\logging\__init__.py", line 1028, in emit
    stream.write(msg + self.terminator)
  File "c:\users\king.kyle\appdata\local\continuum\anaconda2\envs\py375\lib\site-packages\_pytest\capture.py", line 427, in write
    self.buffer.write(obj)
ValueError: I/O operation on closed file
Call stack:
  File "c:\users\king.kyle\appdata\local\continuum\anaconda2\envs\py375\lib\site-packages\comtypes\__init__.py", line 183, in shutdown
    _debug("Calling CoUnititialize()")
Message: 'Calling CoUnititialize()'
Arguments: ()
Windows fatal exception: code 0x80010108

Thread 0x00004530 (most recent call first):
  File "c:\users\king.kyle\appdata\local\continuum\anaconda2\envs\py375\lib\site-packages\comtypes\__init__.py", line 185 in shutdown
Windows fatal exception: code 0x80010108

Thread 0x00004530 (most recent call first):
  File "c:\users\king.kyle\appdata\local\continuum\anaconda2\envs\py375\lib\site-packages\comtypes\__init__.py", line 185 in shutdown
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\king.kyle\appdata\local\continuum\anaconda2\envs\py375\lib\logging\__init__.py", line 1028, in emit
    stream.write(msg + self.terminator)
  File "c:\users\king.kyle\appdata\local\continuum\anaconda2\envs\py375\lib\site-packages\_pytest\capture.py", line 427, in write
    self.buffer.write(obj)
ValueError: I/O operation on closed file
Call stack:
  File "c:\users\king.kyle\appdata\local\continuum\anaconda2\envs\py375\lib\site-packages\comtypes\__init__.py", line 193, in shutdown
    _debug("CoUnititialize() done.")
Message: 'CoUnititialize() done.'
Arguments: ()

(py375) C:\Users\king.kyle\Developer\Packages\PyWinAuto-Win10Error>
```

```
comtypes==1.1.7
pywin32==227
pywinauto==0.6.8
six==1.14.0
```

I just started troubleshooting and will update with any progress

**Comment by airelil** [comment]
@KyleKing , you might want to quickly hack `comtypes.__init__` and replace the log calls with simple prints. The originally reported problem was about COM init/deinit error, the logger errors in pytest are less relevant here.

**Comment by KyleKing** [comment]
Thanks, I now think the root cause is due to changes in Ole32.dll for Windows 10 and that the logging ValueError happens after. I'll open a ticket with comtypes and see if they can help

**Comment by KyleKing** [comment]
Ok, so this is the minimum code to reproduce the error:

```py
import comtypes
import comtypes.client

UIA_dll = comtypes.client.GetModule('UIAutomationCore.dll')
ui_automation_client = comtypes.gen.UIAutomationClient
iuia = comtypes.CoCreateInstance(
    ui_automation_client.CUIAutomation().IPersist_GetClassID(),
    interface=ui_automation_client.IUIAutomation,
    clsctx=comtypes.CLSCTX_INPROC_SERVER,
).GetRootElement()


def test_case():
    assert True
```

This above snippet is modified from the below pywinauto code:

https://github.com/pywinauto/pywinauto/blob/4005bff2aacb6e5421a43abdbdd2f4c178ca53b4/pywinauto/windows/uia_defines.py#L43-L64

I'm a little out of my depth here. From what I can piece together, this only occurs when I call the above snippet (the simplified code from pywinauto--no need to import pywinauto) and use pytest. Calling the snippet with Python doesn't throw the fatal exception.

I can't locate what calls the shutdown() method from comtypes that is reporting the Fatal exception on [couninitialize](https://docs.microsoft.com/en-us/windows/win32/api/combaseapi/nf-combaseapi-couninitialize). I tried to call the snippet with multiprocess, but I haven't been able to create an example without pytest

What do you think? What could I try for next steps?

**Comment by KyleKing** [comment]
Hm, using 64-bit Python doesn't cause this error. We have some internal tools that require 32-bit Python, but the projects that use pytest + pywinauto can be run with 64-bit, so I think I can just side-step this issue 🤞

**Comment by airelil** [comment]
Thanks for nailing it down. Might worth opening an issue in pytest project?

**Comment by KyleKing** [comment]
No luck, I tested the 64-bit solution against a local install that had already been hacked. I retested with a clean 64-MiniConda install and saw the same issue.

I tried to dig further but ended up disabling all of the pywinauto-based tests for now. I added a comment to a thread on pytest, but I think this might be a Windows issue? Not sure what I'll do next

**Comment by airelil** [comment]
My guess, it's all about order of unloading imported packages. Apparently, pytest interferes here somehow.

**Comment by vasily-v-ryabov** [comment]
> I'll open a ticket with comtypes and see if they can help

comtypes project is almost not maintained by Enthought. But I have admin rights to merge something and release if we could figure out the root cause and fix it.

I can reproduce the problem with this code:
```python
import pytest
from pywinauto.application import Application

def test_case():
    assert True
```

But this code can't catch the issue:
```python
import pytest
import comtypes
import comtypes.client

UIA_dll = comtypes.client.GetModule('UIAutomationCore.dll')
ui_automation_client = comtypes.gen.UIAutomationClient
iuia = comtypes.CoCreateInstance(
    ui_automation_client.CUIAutomation().IPersist_GetClassID(),
    interface=ui_automation_client.IUIAutomation,
    clsctx=comtypes.CLSCTX_INPROC_SERVER,
).GetRootElement()


def test_case():
    assert True
```

**Comment by vasily-v-ryabov** [comment]
`shutdown` is registered as at-exit function:
```python
import atexit
atexit.register(shutdown)
```
so it runs on Python interpreter exit.

Not sure it can matter, but I'd suggest to try full path to `UIAutomationCore.dll` (both 32-bit and 64-bit versions). Maybe comtypes cache should be cleared as a pre-condition.

**Comment by vasily-v-ryabov** [comment]
We go even further: try to call `CoInitialize` and `CoUninitialize` using only `ctypes.windll` or `ctypes.oledll` without comtypes. This may lead us to ctypes issue probably. :)

We already faced with unsafe fix in Python core that was fortunately reverted (so don't use Python 3.7.6 and 3.8.1 with comtypes). But it's another story.

**Comment by KyleKing** [comment]
Thanks! Interesting that running my simplified example doesn't catch the issue on your computer while importing all of pywinauto does

I have four `UIAutomationCore.dll` on my computer. Seems like two too many? Which should be the correct one for 64 bit?

![dlls](https://user-images.githubusercontent.com/3784339/73346592-21348e80-4254-11ea-929d-e14ed503b48f.png)

Is this the right way to call from windll/oledll directly? This snippet worked without issue:

```py
import atexit
import ctypes
import sys

COINIT_APARTMENTTHREADED = 0x2

_win_ole32 = ctypes.windll.ole32
_ole_ole32 = ctypes.oledll.ole32

flags = getattr(sys, "coinit_flags", COINIT_APARTMENTTHREADED)
_ole_ole32.CoInitializeEx(None, flags)
# _win_ole32.CoInitializeEx(None, flags)  # Should this be called?


def shutdown():
    _win_ole32.CoUninitialize()
    _ole_ole32.CoUninitialize()


atexit.register(shutdown)


def test_case():
    assert True

```

```
(base) C:\Users\king.kyle\Developer\Packages\PyWinAuto-Win10Error>poetry run pytest
================================================ test session starts ================================================ 
platform win32 -- Python 3.6.8, pytest-5.3.4, py-1.8.1, pluggy-0.13.1
rootdir: C:\Users\king.kyle\Developer\Packages\PyWinAuto-Win10Error
collected 1 item                                                                                                      

tests\test_pywinauto_fatalerror.py .                                                                           [100%] 

================================================= 1 passed in 0.09s ================================================= 

(base) C:\Users\king.kyle\Developer\Packages\PyWinAuto-Win10Error>
```

**Comment by harvey-kwok** [comment]
I can reproduce the problem without pytest involved.  It does seem to be related to loading and unloading sequence of modules
```python
import pyad
import pywinauto
```
Here is my result.
```
C:\P4\playpen>python test_winautopy.py
Win32 exception occurred releasing IUnknown at 0x016705d8
Win32 exception occurred releasing IUnknown at 0x016530ec
```
I tried it on
- python 2.7 64-bit
- python 3.7 64-bit
- python 3.8.2 32-bit

All have similar error. Python 2.7 64-bit shows one Win32 exception but the other shows two exceptions.

I am running Windows 10 Professional build 1909.  I debugged it using native debugger. 

![image](https://user-images.githubusercontent.com/42844252/76712021-19309100-66d2-11ea-80e1-1ae20b2ff431.png)

The garbage collector is trying to release something but I don't have the debug symbol for pythoncom.  So, I cannot see what exactly that was.

**Comment by michel117** [comment]
> ~No luck, I tested the 64-bit solution against a local install that had already been hacked. I retested with a clean 64-MiniConda install and saw the same issue.~
> Edit: this is an issue with at least Python 3.6 and 3.7 + comtypes + pytest. Not sure why my initial testing worked with Python 3.6-64, but with a clean 3.6.8 install, the test fails. Doesn't appear to be comtypes initializing twice
> 
> I tried to dig further but ended up disabling all of the pywinauto-based tests for now. I added a comment to a thread on pytest, but I think this might be a Windows issue? Not sure what I'll do next
> 
> Update: I don't know why this fatal error was occurring, but I disabled the pop-ups, which allows me to run through the automated pywinauto test
> 
> ![PreventPopUp](https://user-images.githubusercontent.com/3784339/73077870-08f8f400-3e8f-11ea-9e02-0f60c1213436.png)

Hi, could you reference the ticket in the pytest project?
cheers
Michel

**Comment by michel117** [comment]
I added a comment in the comtypes repo here:
https://github.com/enthought/comtypes/issues/204#issuecomment-599934275

**Comment by KyleKing** [comment]
@michel117 I commented on the Pytest project here: https://github.com/pytest-dev/pytest/issues/5743#issuecomment-577401653, but didn't open a new issue. After disabling the Windows popups, I was able to ship the project and haven't had time to follow up on this

**Comment by czhhua28** [comment]
The issue should not be related to pytest. It looks like comtypes + UIAutomationCore.dll problem

**Comment by zhichaoh** [comment]
> > I'll open a ticket with comtypes and see if they can help
> 
> comtypes project is almost not maintained by Enthought. But I have admin rights to merge something and release if we could figure out the root cause and fix it.
> 
> I can reproduce the problem with this code:
> 
> ```python
> import pytest
> from pywinauto.application import Application
> 
> def test_case():
>     assert True
> ```
> 
> But this code can't catch the issue:
> 
> ```python
> import pytest
> import comtypes
> import comtypes.client
> 
> UIA_dll = comtypes.client.GetModule('UIAutomationCore.dll')
> ui_automation_client = comtypes.gen.UIAutomationClient
> iuia = comtypes.CoCreateInstance(
>     ui_automation_client.CUIAutomation().IPersist_GetClassID(),
>     interface=ui_automation_client.IUIAutomation,
>     clsctx=comtypes.CLSCTX_INPROC_SERVER,
> ).GetRootElement()
> 
> 
> def test_case():
>     assert True
> ```

Cannot reproduce on Python 3.8.2 64 bit (Windows 1809 OS.Build 17763.1098)

**Comment by Fobos23** [comment]
I started pytest with -p no: faulthandler and it helped me. Look at [this](https://docs.pytest.org/en/latest/how-to/failures.html) for more information.
