### ISSUE TITLE
What i am doing wrong?

### ISSUE THREAD

**Issue by raddup** [pywinauto/pywinauto#859]
## Expected Behavior

Trying to get the list of .print_control_identifiers()

## Actual Behavior
Traceback (most recent call last):
  File "C:\Users\melo2\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pywinauto\application.py", line 250, in __resolve_control
    ctrl = wait_until_passes(
  File "C:\Users\melo2\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pywinauto\timings.py", line 458, in wait_until_passes
    raise err
pywinauto.timings.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/automate/autom2.py", line 8, in <module>
    app.WindowsSoftware.print_control_identifiers()
  File "C:\Users\melo2\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pywinauto\application.py", line 613, in print_control_identifiers
    this_ctrl = self.__resolve_control(self.criteria)[-1]
  File "C:\Users\melo2\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pywinauto\application.py", line 261, in __resolve_control
    raise e.original_exception
  File "C:\Users\melo2\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pywinauto\timings.py", line 436, in wait_until_passes
    func_val = func(*args, **kwargs)
  File "C:\Users\melo2\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pywinauto\application.py", line 203, in __get_ctrl
    dialog = self.backend.generic_wrapper_class(findwindows.find_element(**criteria[0]))
  File "C:\Users\melo2\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pywinauto\findwindows.py", line 87, in find_element
    raise ElementNotFoundError(kwargs)
pywinauto.findwindows.ElementNotFoundError: {'best_match': 'WindowsSoftware', 'backend': 'uia', 'process': 1028}

## Short Example of Code to Demonstrate the Problem

```
from pywinauto import Desktop, Application




Application().start(r'C:\Users\melo2\Downloads\Windows Kits\10\WindowsSDK\winsdksetup.exe',  wait_for_idle=False)
app = Application(backend="uia").connect(path="winsdksetup.exe", title_re=".*Windows Software.*")

app.WindowsSoftware.print_control_identifiers()

```

## Specifications

  - Pywinauto version: 0.6.8
  - Python version and bitness: 3.8.0 - 32 bit
  - Platform and OS: Windows 10 64 bit

**Comment by raddup** [comment]
fix it. the corect is ```
"Application(backend="uia").start(r'C:\Users\melo2\Downloads\Windows Kits\10\WindowsSDK\winsdksetup.exe',  wait_for_idle=False)


app = Desktop(backend="uia").window(title_re="Windows Software Development Kit")"
```

**Comment by raddup** [comment]
```
Application(backend="uia").start(r'C:\Users\melo2\Downloads\Windows Kits\10\WindowsSDK\winsdksetup.exe',  wait_for_idle=False)


app = Desktop(backend="uia").window(title_re="Windows Software Development Kit")
```

fix it, this is the corect one

**Comment by vasily-v-ryabov** [comment]
It could be `app.window(title_re="Windows Software Development Kit").print_control_identifiers()` with the same result as for `Desktop` usage probably. `WindowsSoftware` is just not long enough so the "distance" between two texts is too far.

**Comment by rambabu3381** [comment]
it need administration rights,use backend as Win32
