### ISSUE TITLE
For pywinauto.controls.uia_controls.MenuWrapper, the menu_select method throws an AttributeError: 'MenuWrapper' object has no attribute 'visible'

### ISSUE THREAD

**Issue by ajujayapal** [pywinauto/pywinauto#862]
## Expected Behavior
No attribute error when calling the menu_select("menu path") method on the MenuWrapper class.

## Actual Behavior
For pywinauto.controls.uia_controls.MenuWrapper, the menu_select method throws an AttributeError: 'MenuWrapper' object has no attribute 'visible'

## Steps to Reproduce the Problem

`menu = MenuWrapper(app.ContextMenu.wrapper_object())

menu.menu_select("New->Spread")` 

used the code snippet above to select from right click menu (after the menu was made visible in the application by right-clicking)
## Specifications

  - Pywinauto version: 0.6.8
  - Python version and bitness: Python 3.7 64-bit (Application under test is 64-bit as well)
  - Platform and OS: Windows 10

## Output from interactive window
>>> menu = MenuWrapper(app.ContextMenu.wrapper_object())
>>> menu.menu_select("New->Spread")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Aju.jayapalan2\Documents\Beta\px_automation_64\lib\site-packages\pywinauto\controls\uiawrapper.py", line 715, in menu_select
    self.verify_actionable()
  File "C:\Users\Aju.jayapalan2\Documents\Beta\px_automation_64\lib\site-packages\pywinauto\base_wrapper.py", line 680, in verify_actionable
    self.verify_visible()
  File "C:\Users\Aju.jayapalan2\Documents\Beta\px_automation_64\lib\site-packages\pywinauto\base_wrapper.py", line 702, in verify_visible
    if not self.is_visible():
  File "C:\Users\Aju.jayapalan2\Documents\Beta\px_automation_64\lib\site-packages\pywinauto\base_wrapper.py", line 325, in is_visible
    return self.element_info.visible #and self.top_level_parent().element_info.visible
AttributeError: 'MenuWrapper' object has no attribute 'visible'

**Comment by airelil** [comment]
I would try to understand what's the control type returned as the original wrapper from `app.ContextMenu.wrapper_object()` . Maybe it's already the MenuWrapper.

Generally, you have to remember that the popup menu can be implemented by different frameworks in different ways . For example, an MFC application produces the menu dialog as a separate window that can be accessed as a desktop child (not the app's!): 
`from pywinauto import Desktop; menu = Desktop(backend='uia').Menu.draw_outline()`
On the other hand, the WPF can present the context menu as the application child window with 'Pane' type.

**Comment by vasily-v-ryabov** [comment]
Hi @ajujayapal it's wrong usage of `MenuWrapper` constructor. All wrappers from `backend="uia"` expect `UIAElementInfo` object as a constructor parameter. So you have to use this line:
```python
menu = MenuWrapper(app.ContextMenu.wrapper_object().element_info)
```
Is `app.ContextMenu.wrapper_object()` returned object of another class than `MenuWrapper`?

**Comment by ajujayapal** [comment]
> Hi @ajujayapal it's wrong usage of `MenuWrapper` constructor. All wrappers from `backend="uia"` expect `UIAElementInfo` object as a constructor parameter. So you have to use this line:
> 
> ```python
> menu = MenuWrapper(app.ContextMenu.wrapper_object().element_info)
> ```
> 
> Is `app.ContextMenu.wrapper_object()` returned object of another class than `MenuWrapper`?

Using your suggestion, I got an AttributeError (on line 721 in menu_select)

For app.ContextMenu.wrapper_object() I got -> <uia_controls.MenuWrapper - 'Context', Menu, 3713037277417833081>

Screenshot of the python command line interactive screen. [http://bit.ly/35aQ9xH](url)

**Comment by airelil** [comment]
@ajujayapal , there is no point in creating the MenuWrapper manually, as you do in your screenshot. Notice, that pywinauto automatically tries resolve the control type through the "Windows Specification" you defined: `app.ContextMenu`. In your case the MenuWrapper was successfully created.  At this point you can continue using the Window Specification to access the object or you can save the the wrapper in a variable: `menu = app.ContextMenu.wrapper_object()`. Usually re-using the saved wrapper is faster, but then you are risking to have it outdated if the window control is not presented and the script will try to access a non-existing element.
As a next step in the troubleshooting I would try to draw outline on your context menu. This is to confirm that you access the right window:
```python
app.ContextMenu.draw_outline()
```

**Comment by vasily-v-ryabov** [comment]
@airelil is right, but more interesting is what `menu.children()` and `menu.descendants()` returns. And how it's compared with what `Inspect.exe` shows hovering mouse over the menu item (with a hierarchy on screenshot).

Anyway I would say our implementation provided useless error message in this case. I will mark the issue as an enhancement to handle context menus more properly. If `menu.children()` returns `MenuItemWrapper` objects, the fix should be pretty easy.
