### ISSUE TITLE
Problem printing element

### ISSUE THREAD

**Issue by xiyangyang1230** [pywinauto/pywinauto#865]
## Expected Behavior
Print out all elements

## Actual Behavior
 only a small part is printed, an error is thrown;
return bool(IUIA().iuia.CompareElements(self.element, other.element))
_ctypes.COMError: (-2147220991, 'event cannot call any subscribers', (None, None, None, 0, None))

## Steps to Reproduce the Problem

  1.My automation software is WPF type

## Short Example of Code to Demonstrate the Problem
 def test(self):
        wd = self.app[u"放射影像软件"]
        wd.print_ctrl_ids(filename="photograph.txt")
if __name__ == '__main__':
    # app = Application(backend='uia').start(r"E:\fs\fs.exe")
    app = Application(backend="uia").connect(handle=0x20C04)
    ph = Photograph(app)
    ph.test()
## Specifications

  - Pywinauto version:  0.6.7
  - Python version and bitness: 3.7.4
  - Platform and OS: Windows 10 home

**Comment by xiyangyang1230** [comment]
When checking elements with inspect, some elements wait 20 seconds to be detected

**Comment by vasily-v-ryabov** [comment]
Hi @xiyangyang1230 this is very interesting case we have never seen before. If it was possible to download the application to debug it, it would be very helpful. We may try blind fix though.

**Comment by xiyangyang1230** [comment]
Vasily, Hello, this is the company's software. It can't be exported. I'm very sorry.  Our company's software is designed by WPF. When I use inspection to check elements, I need to click the elements with the mouse, and then in sleep (20) seconds, the elements will be checked by inspection

**Comment by DiegoQueiroz** [comment]
I am have the very same error, but not when printing anything.

My code is very simple (I am running it in a terminal):
```
app = Application(backend="uia").start(app_path)
loginButton = app.AppTitle.Login.wrapper_object()
loginButton.click()
```

It raises this error when running the last line:
```
>>> loginButton.click()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\diego.queiroz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pywinauto\controls\uia_controls.py", line 121, in click
    self.invoke()
  File "C:\Users\diego.queiroz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pywinauto\controls\uiawrapper.py", line 513, in invoke
    self.iface_invoke.Invoke()
_ctypes.COMError: (-2147220991, 'Um evento não pôde chamar assinantes', (None, None, None, 0, None))
```
(the error message is in portuguese, but it is basically the same as the op: `event cannot call any subscribers`)

The weird part is that, despite the exception, the button is clicked (so I guess it would be OK to just ignore the exception).
The tested app is not mine, but since it is just a client app, I think I can provide it for investigation if necessary.

**Comment by vasily-v-ryabov** [comment]
Hi @DiegoQueiroz your case is a little bit different. This is a problem of `InvokePattern` implementation on the app side. Use `.click_input()` as a last hope. It requires your PC to be logged in and not locked, but it should work much more reliably.

**Comment by DiegoQueiroz** [comment]
@vasily-v-ryabov I could agree with you, but I still think there's something wrong with pywinauto. The main reason is because the button is clicked as expected. I could use `click_input()` but there is no real reason to do so.

I am running my script with the code bellow and it does not present any instability:

```
app = Application(backend="uia").start(app_path)
try:
  app.AppTitle.Login.click()
except:
  pass

# script continues here
```

The question is, why pywinauto is raising an exception if it is working as expected? I understand that maybe it detected some bad implementation in the invoke method or something, but since the method is fired, what pywinauto is trying to tell me with this exception? Is there something weird happening that I should be handling?

Got my point? Or there is a good explanation for this, or it is a bug since the exception is useless.

At least, it should catch this exception and provide specific information about the problem, instead of raising a generic COM Error.

**Comment by vasily-v-ryabov** [comment]
Sorry, I missed the info that button is really clicked. Well, the exception is raised by `UIAutomationCore.dll` so the right question is "what Microsoft wants to tell us?". But this is not an empty implementation. Of course we can handle this kind of error and convert it to `RuntimeWarning`. But please create separate issue on it. This is completely different to the initial issue.

Sometimes we also face with hang problem when calling `.invoke()` (`.click()` is an alias of `.invoke()` for ButtonWrapper). It means we need to create a separate thread with some timeout and print a warning if it is timed out. This is also separate issue, but we can combine it in one issue since it is all in `.invoke()` method.
