### ISSUE TITLE
Python crashes when the script with Pywinauto imports is executed

### ISSUE THREAD

**Issue by ashwinTheFox** [pywinauto/pywinauto#883]
## Expected Behavior
Code execution & flow without crashes

## Actual Behavior
Python execution crashes with a windows pop screen

## Steps to Reproduce the Problem

  1. Create a simple .py file containing pywinauto imports
  2. Execute the python file from windows cmd --> python filename.py & press Enter
  3. Execution crashes with a pop screen (see screenshot below)

![image](https://user-images.githubusercontent.com/52165455/72883309-5e54ca00-3d04-11ea-8754-2a75d40954d1.png)

## Short Example of Code to Demonstrate the Problem
`import pywinauto
`
## Specifications

  - Pywinauto version: 0.6.8
  - Python version and bitness: 3.7.3 64bit
  - Platform and OS: Windows Server 2012 R2 Standard (runs in EC2 machine)

**Comment by airelil** [comment]
Oh. I didn't notice you created a separate issue and commented on #750. Please try to uninstall comtypes and run your example again

**Comment by vasily-v-ryabov** [comment]
I've tried to reproduce it on clean Python 3.7.3 64-bit, but it works fine:
```python
C:\Python37_3_64\Scripts\pip.exe install six comtypes pywin32 pywinauto

pip version 19.0.3

C:\Python37_3_64\python.exe
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32
>>> import pywinauto
>>>
```

**Comment by Nicceboy** [comment]
I have Python 3.8.1 and pip 19.3.1, fresh install
Getting error when importing:

```
Python 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pywinauto
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\ctypes\__init__.py", line 123, in WINFUNCTYPE
    return _win_functype_cache[(restype, argtypes, flags)]
KeyError: (<class 'ctypes.HRESULT'>, (<class 'ctypes.c_long'>, <class 'comtypes.automation.tagVARIANT'>, <class 'comtypes.LP_POINTER(IUIAutomationCondition)'>), 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\nikla\Documents\GUIAutomation\venv\lib\site-packages\pywinauto\__init__.py", line 89, in <module>          from . import findwindows
  File "C:\Users\nikla\Documents\GUIAutomation\venv\lib\site-packages\pywinauto\findwindows.py", line 42, in <module>       from . import controls
  File "C:\Users\nikla\Documents\GUIAutomation\venv\lib\site-packages\pywinauto\controls\__init__.py", line 36, in <module>
    from . import uiawrapper # register "uia" back-end (at the end of uiawrapper module)
  File "C:\Users\nikla\Documents\GUIAutomation\venv\lib\site-packages\pywinauto\controls\uiawrapper.py", line 47, in <module>
    from ..uia_defines import IUIA
  File "C:\Users\nikla\Documents\GUIAutomation\venv\lib\site-packages\pywinauto\uia_defines.py", line 181, in <module>      pattern_ids = _build_pattern_ids_dic()
tern_ids_dic
  File "C:\Users\nikla\Documents\GUIAutomation\venv\lib\site-packages\pywinauto\uia_defines.py", line 50, in __call__       cls._instances[cls] = super(_Singleton, cls).__call__(*args, **kwargs)
  File "C:\Users\nikla\Documents\GUIAutomation\venv\lib\site-packages\pywinauto\uia_defines.py", line 60, in __init__       self.UIA_dll = comtypes.client.GetModule('UIAutomationCore.dll')
  File "C:\Users\nikla\Documents\GUIAutomation\venv\lib\site-packages\comtypes\client\_generate.py", line 110, in GetModule
    mod = _CreateWrapper(tlib, pathname)
  File "C:\Users\nikla\Documents\GUIAutomation\venv\lib\site-packages\comtypes\client\_generate.py", line 184, in _CreateWrapper
    mod = _my_import(fullname)
  File "C:\Users\nikla\Documents\GUIAutomation\venv\lib\site-packages\comtypes\client\_generate.py", line 24, in _my_import
    return __import__(fullname, globals(), locals(), ['DUMMY'])
  File "C:\Users\nikla\Documents\GUIAutomation\venv\lib\site-packages\comtypes\gen\_944DE083_8FB8_45CF_BCB7_C477ACB2F897_0_1_0.py", line 1599, in <module>
    IUIAutomation._methods_ = [
  File "C:\Users\nikla\Documents\GUIAutomation\venv\lib\site-packages\comtypes\__init__.py", line 329, in __setattr__       self._make_methods(value)
  File "C:\Users\nikla\Documents\GUIAutomation\venv\lib\site-packages\comtypes\__init__.py", line 698, in _make_methods     prototype = WINFUNCTYPE(restype, *argtypes)
  File "C:\Program Files\Python38\lib\ctypes\__init__.py", line 125, in WINFUNCTYPE
    class WinFunctionType(_CFuncPtr):
TypeError: item 2 in _argtypes_ passes a union by value, which is unsupported.
>>> quit()
```

**Comment by vasily-v-ryabov** [comment]
Hi @Nicceboy this is another issue #368 which was already reverted in CPython. So Python 3.8.2 and 3.7.7 will work fine. Just revert to Python 3.8.0 or 3.7.5 for now.

**Comment by vasily-v-ryabov** [comment]
@Nicceboy sorry this issue #868.

**Comment by Nicceboy** [comment]
> 
> 
> Hi @Nicceboy this is another issue #868 which was already reverted in CPython. So Python 3.8.2 and 3.7.7 will work fine. Just revert to Python 3.8.0 or 3.7.5 for now.

Indeed this was a problem. Sorry for responding with such a great delay.
