### ISSUE TITLE
Can not launch SnippingTool 

### ISSUE THREAD

**Issue by FreelanceDev217** [pywinauto/pywinauto#890]
## Expected Behavior
Launch SnippingTool.exe

## Actual Behavior
Error log below
```
(PYWINA~1) f:\PCKLIB_Python\WinAutomation>python main.py
Traceback (most recent call last):
  File "C:\Users\PIAODA~1\Envs\PYWINA~1\lib\site-packages\pywinauto\application.py", line 1047, in start
    start_info)                         # STARTUPINFO structure.
pywintypes.error: (2, 'CreateProcess', 'The system cannot find the file specified.')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 8, in <module>
    app = Application(backend="uia").start('C:\WINDOWS\system32\SnippingTool.exe')
  File "C:\Users\PIAODA~1\Envs\PYWINA~1\lib\site-packages\pywinauto\application.py", line 1052, in start
    raise AppStartError(message)
pywinauto.application.AppStartError: Could not create the process "C:\WINDOWS\system32\SnippingTool.exe"
Error returned by CreateProcess: (2, 'CreateProcess', 'The system cannot find the file specified.')
```

## Short Example of Code to Demonstrate the Problem
```
from pywinauto import Desktop, Application
app = Application(backend="uia").start('C:\WINDOWS\system32\SnippingTool.exe')
```
## Specifications
  - Pywinauto version: ***0.6.8***
  - Python version and bitness: ***Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC v.1916 32 bit (Intel)] on win32***
  - Platform and OS:
***Windows 10 64bit ***

**Comment by vasily-v-ryabov** [comment]
Try `app = Application(backend="uia").start(r'C:\WINDOWS\system32\SnippingTool.exe')` (`r` means "raw string" so that `\s` is interpreted as two symbols, otherwise you should double all back slashes). 

Also try running script as Adminitrator (in `cmd.exe [Adminitrator]`).

**Comment by vasily-v-ryabov** [comment]
Also try typing `C:\WINDOWS\system32\SnippingTool.exe` into command instead of `python main.py` to check it can be started without Python.

**Comment by FreelanceDev217** [comment]
Thank you for your help.
I tried all your suggestions but still failed.
- adding 'r'
- running as an admin
- running directly from cmd works. with python main.py, does not work

**Comment by FreelanceDev217** [comment]
I wonder if this is the problem related to my python bitness cause some articles are saying I might need to install python 64bit. But I am not that willing to install a new instance of Python just to make this run... So hoping there's a workaround,

**Comment by airelil** [comment]
If you're still getting "File not found" error, it shouldn't be related to the bitness of your Python, because it didn't try to interact with the executable itself. The above error almost always comes because of wrong path or insufficient permissions.

**Comment by vasily-v-ryabov** [comment]
Maybe the path contains spaces. Then you need double quotes around the whole path. If you were provided exact error output and path example, the answer could be much faster and simpler.

It's worth trying `subprocess.Popen(...)` as well. If it's successful, method `.connect(...)` can be used for pywinauto's `Application` object.

**Comment by vasily-v-ryabov** [comment]
Well, `Popen` doesn't work as well. It's interesting type of executable which always requires elevation. Even if you're starting it from parent process (running as Administrator), elevation doesn't happen (because for normal executable it's not needed).

I don't recall how it can be solved. There was similar question about Magnifier tool. Maybe `ShellExecuteEx` approach with forced elevation would help. It can be googled easily.

**Comment by myd7349** [comment]
The reason:
You Win10 is 64-bit, and your Python app might be 32-bit.
When you typied `C:\WINDOWS\system32\SnippingTool.exe`, the file system redirector will redirects it to `C:\WINDOWS\SysWOW64\SnippingTool.exe`.

[File System Redirector](https://docs.microsoft.com/en-us/windows/win32/winprog64/file-system-redirector)
[Wow64DisableWow64FsRedirection](https://docs.microsoft.com/en-us/windows/win32/api/wow64apiset/nf-wow64apiset-wow64disablewow64fsredirection)

**Comment by vasily-v-ryabov** [comment]
Hi @myd7349 thanks! This is exactly the root cause. We figured it out some time ago, but I forgot to mention it here because of low priority. And thanks for the references! Really appreciate it.
