### ISSUE TITLE
w.top_level_parent() raises an exception when w is a "list item" of the Windows start menu

### ISSUE THREAD

**Issue by beuaaa** [pywinauto/pywinauto#911]
## Expected Behavior

w.top_level_parent() should not raise a exception when w is a "list item" of the Windows start menu (Like "Google Chrome" or "Notepad++")

Maybe the exception is raised because "semantic zoom" is not a control type known by Pywinauto? 
See the screenshot of inspect.exe in this [link](https://stackoverflow.com/questions/60959635/how-to-get-top-level-parent-of-an-element-in-the-windows-start-menu)

## Actual Behavior

```
Traceback (most recent call last):
  File "C:\Users\d_pra\PycharmProjects\pywinauto_recorder\pywinauto_recorder\recorder.py", line 270, in get_wrapper_path
    wrapper_top_level_parent = wrapper.top_level_parent()
  File "D:\Python\lib\site-packages\pywinauto\base_wrapper.py", line 439, in top_level_parent
    return self.parent().top_level_parent()
  File "D:\Python\lib\site-packages\pywinauto\base_wrapper.py", line 439, in top_level_parent
    return self.parent().top_level_parent()
  File "D:\Python\lib\site-packages\pywinauto\base_wrapper.py", line 433, in top_level_parent
    parent = self.parent()
  File "D:\Python\lib\site-packages\pywinauto\base_wrapper.py", line 409, in parent
    return self.backend.generic_wrapper_class(parent_elem)
  File "D:\Python\lib\site-packages\pywinauto\controls\uiawrapper.py", line 186, in __new__
    return super(UIAWrapper, cls)._create_wrapper(cls, element_info, UIAWrapper)
  File "D:\Python\lib\site-packages\pywinauto\base_wrapper.py", line 126, in _create_wrapper
    new_class = cls_spec.find_wrapper(element_info)
  File "D:\Python\lib\site-packages\pywinauto\controls\uiawrapper.py", line 159, in find_wrapper
    if element.control_type in UiaMeta.control_type_to_cls:
  File "D:\Python\lib\site-packages\pywinauto\uia_element_info.py", line 250, in control_type
    return self._get_control_type()
  File "D:\Python\lib\site-packages\pywinauto\uia_element_info.py", line 112, in _get_current_control_type
    return IUIA().known_control_type_ids[self._element.CurrentControlType]
KeyError: 50039
```

## Steps to Reproduce the Problem

In the following code, top_level_parent() raises an exception if the mouse cursor is over a "list item" of the Windows start menu (Like "Google Chrome" or "Notepad++")

## Short Example of Code to Demonstrate the Problem

```
x, y = win32api.GetCursorPos()
element_from_point = pywinauto.uia_defines.IUIA().iuia.ElementFromPoint(tagPOINT(x, y))
element_info = pywinauto.uia_element_info.UIAElementInfo(element_from_point)
wrapper = pywinauto.controls.uiawrapper.UIAWrapper(element_info)
wrapper_top_level_parent = wrapper.top_level_parent()
```

## Specifications

  - Pywinauto version: 0.6.8
  - Python version and bitness: 2.7 64bit
  - Platform and OS: win 10

**Comment by beuaaa** [comment]
I added this code at the end of __init__ method of class IUIA in uia_defines.py and it fixed the bug:
  
```
        # add some unknown control types
        unknown_control_types_ids = { 50039: 'SemanticZoom' }
        for key in unknown_control_types_ids:
            self.known_control_types[unknown_control_types_ids[key]] = key
            self.known_control_type_ids[key] = unknown_control_types_ids[key]
```

**Comment by airelil** [comment]
That's interesting why the "SemanticZoom" control type wasn't added to the list of known control types automatically. Notice the line that is slightly before in the same function. It populates the list of control types: https://github.com/pywinauto/pywinauto/blob/aea0429b14f9e471974889246b3c4455b93508f3/pywinauto/uia_defines.py#L83
According to https://docs.microsoft.com/en-us/windows/win32/winauto/uiauto-controltype-ids it should have the same name convention as we try to strip "UIA_" and "ControlTypeId"
Could you print the content of `self._controls_types` list and the raw output of UIA attributes on your machine? The raw output probably would be printed with:
```python
print( [attr for attr in dir(self.UIA_dll)] )
```

**Comment by airelil** [comment]
BTW, I printed  the contents of `self.known_control_types` on my x64 Win8 and Python 3.7.5 And I can see the proper control type ID for SemanticZoom:
```
{'InvalidControlType': 0, 'AppBar': 50040, 'Button': 50000, 'Calendar': 50001, 'CheckBox': 50002, 'ComboBox': 50003, 'Custom': 50025, 'DataGrid': 50028, 'DataItem': 50029, 'Document': 50030, 'Edit': 50004, 'Group': 50026, 'Header': 50034, 'HeaderItem': 50035, 'Hyperlink': 50005, 'Image': 50006, 'List': 50008, 'ListItem': 50007, 'MenuBar': 50010, 'Menu': 50009, 'MenuItem': 50011, 'Pane': 50033, 'ProgressBar': 50012, 'RadioButton': 50013, 'ScrollBar': 50014, 'SemanticZoom': 50039, 'Separator': 50038, 'Slider': 50015, 'Spinner': 50016, 'SplitButton': 50031, 'StatusBar': 50017, 'Tab': 50018, 'TabItem': 50019, 'Table': 50036, 'Text': 50020, 'Thumb': 50027, 'TitleBar': 50037, 'ToolBar': 50021, 'ToolTip': 50022, 'Tree': 50023, 'TreeItem': 50024, 'Window': 50032}
```

**Comment by beuaaa** [comment]
It seems that self.UIA_dll is not the same than yours on my PC.
I printed dir(self.UIA_dll) and there is no 'SemanticZoom':

```
000 = {str} 'ARRAY'
001 = {str} 'ArgumentError'
002 = {str} 'Array'
003 = {str} 'AutomationElementMode'
004 = {str} 'AutomationElementMode_Full'
005 = {str} 'AutomationElementMode_None'
006 = {str} 'BSTR'
007 = {str} 'BigEndianStructure'
008 = {str} 'CDLL'
009 = {str} 'CFUNCTYPE'
010 = {str} 'COMMETHOD'
011 = {str} 'CUIAutomation'
012 = {str} 'CoClass'
013 = {str} 'DEFAULT_MODE'
014 = {str} 'DllCanUnloadNow'
015 = {str} 'DllGetClassObject'
016 = {str} 'DockPosition'
017 = {str} 'DockPosition_Bottom'
018 = {str} 'DockPosition_Fill'
019 = {str} 'DockPosition_Left'
020 = {str} 'DockPosition_None'
021 = {str} 'DockPosition_Right'
022 = {str} 'DockPosition_Top'
023 = {str} 'ExpandCollapseState'
024 = {str} 'ExpandCollapseState_Collapsed'
025 = {str} 'ExpandCollapseState_Expanded'
026 = {str} 'ExpandCollapseState_LeafNode'
027 = {str} 'ExpandCollapseState_PartiallyExpanded'
028 = {str} 'FormatError'
029 = {str} 'GUID'
030 = {str} 'GetLastError'
031 = {str} 'HRESULT'
032 = {str} 'IAccessible'
033 = {str} 'IDispatch'
034 = {str} 'IRawElementProviderSimple'
035 = {str} 'IUIAutomation'
036 = {str} 'IUIAutomationAndCondition'
037 = {str} 'IUIAutomationBoolCondition'
038 = {str} 'IUIAutomationCacheRequest'
039 = {str} 'IUIAutomationCondition'
040 = {str} 'IUIAutomationDockPattern'
041 = {str} 'IUIAutomationElement'
042 = {str} 'IUIAutomationElementArray'
043 = {str} 'IUIAutomationEventHandler'
044 = {str} 'IUIAutomationExpandCollapsePattern'
045 = {str} 'IUIAutomationFocusChangedEventHandler'
046 = {str} 'IUIAutomationGridItemPattern'
047 = {str} 'IUIAutomationGridPattern'
048 = {str} 'IUIAutomationInvokePattern'
049 = {str} 'IUIAutomationItemContainerPattern'
050 = {str} 'IUIAutomationLegacyIAccessiblePattern'
051 = {str} 'IUIAutomationMultipleViewPattern'
052 = {str} 'IUIAutomationNotCondition'
053 = {str} 'IUIAutomationOrCondition'
054 = {str} 'IUIAutomationPropertyChangedEventHandler'
055 = {str} 'IUIAutomationPropertyCondition'
056 = {str} 'IUIAutomationProxyFactory'
057 = {str} 'IUIAutomationProxyFactoryEntry'
058 = {str} 'IUIAutomationProxyFactoryMapping'
059 = {str} 'IUIAutomationRangeValuePattern'
060 = {str} 'IUIAutomationScrollItemPattern'
061 = {str} 'IUIAutomationScrollPattern'
062 = {str} 'IUIAutomationSelectionItemPattern'
063 = {str} 'IUIAutomationSelectionPattern'
064 = {str} 'IUIAutomationStructureChangedEventHandler'
065 = {str} 'IUIAutomationSynchronizedInputPattern'
066 = {str} 'IUIAutomationTableItemPattern'
067 = {str} 'IUIAutomationTablePattern'
068 = {str} 'IUIAutomationTextPattern'
069 = {str} 'IUIAutomationTextRange'
070 = {str} 'IUIAutomationTextRangeArray'
071 = {str} 'IUIAutomationTogglePattern'
072 = {str} 'IUIAutomationTransformPattern'
073 = {str} 'IUIAutomationTreeWalker'
074 = {str} 'IUIAutomationValuePattern'
075 = {str} 'IUIAutomationVirtualizedItemPattern'
076 = {str} 'IUIAutomationWindowPattern'
077 = {str} 'IUnknown'
078 = {str} 'Library'
079 = {str} 'LibraryLoader'
080 = {str} 'LittleEndianStructure'
081 = {str} 'OleDLL'
082 = {str} 'OrientationType'
083 = {str} 'OrientationType_Horizontal'
084 = {str} 'OrientationType_None'
085 = {str} 'OrientationType_Vertical'
086 = {str} 'POINTER'
087 = {str} 'PYFUNCTYPE'
088 = {str} 'PropertyConditionFlags'
089 = {str} 'PropertyConditionFlags_IgnoreCase'
090 = {str} 'PropertyConditionFlags_None'
091 = {str} 'ProviderOptions'
092 = {str} 'ProviderOptions_ClientSideProvider'
093 = {str} 'ProviderOptions_NonClientAreaProvider'
094 = {str} 'ProviderOptions_OverrideProvider'
095 = {str} 'ProviderOptions_ProviderOwnsSetFocus'
096 = {str} 'ProviderOptions_ServerSideProvider'
097 = {str} 'ProviderOptions_UseComThreading'
098 = {str} 'PyDLL'
099 = {str} 'RTLD_GLOBAL'
100 = {str} 'RTLD_LOCAL'
101 = {str} 'RowOrColumnMajor'
102 = {str} 'RowOrColumnMajor_ColumnMajor'
103 = {str} 'RowOrColumnMajor_Indeterminate'
104 = {str} 'RowOrColumnMajor_RowMajor'
105 = {str} 'ScrollAmount'
106 = {str} 'ScrollAmount_LargeDecrement'
107 = {str} 'ScrollAmount_LargeIncrement'
108 = {str} 'ScrollAmount_NoAmount'
109 = {str} 'ScrollAmount_SmallDecrement'
110 = {str} 'ScrollAmount_SmallIncrement'
111 = {str} 'SetPointerType'
112 = {str} 'Structure'
113 = {str} 'StructureChangeType'
114 = {str} 'StructureChangeType_ChildAdded'
115 = {str} 'StructureChangeType_ChildRemoved'
116 = {str} 'StructureChangeType_ChildrenBulkAdded'
117 = {str} 'StructureChangeType_ChildrenBulkRemoved'
118 = {str} 'StructureChangeType_ChildrenInvalidated'
119 = {str} 'StructureChangeType_ChildrenReordered'
120 = {str} 'SupportedTextSelection'
121 = {str} 'SupportedTextSelection_Multiple'
122 = {str} 'SupportedTextSelection_None'
123 = {str} 'SupportedTextSelection_Single'
124 = {str} 'SynchronizedInputType'
125 = {str} 'SynchronizedInputType_KeyDown'
126 = {str} 'SynchronizedInputType_KeyUp'
127 = {str} 'SynchronizedInputType_LeftMouseDown'
128 = {str} 'SynchronizedInputType_LeftMouseUp'
129 = {str} 'SynchronizedInputType_RightMouseDown'
130 = {str} 'SynchronizedInputType_RightMouseUp'
131 = {str} 'TextPatternRangeEndpoint'
132 = {str} 'TextPatternRangeEndpoint_End'
133 = {str} 'TextPatternRangeEndpoint_Start'
134 = {str} 'TextUnit'
135 = {str} 'TextUnit_Character'
136 = {str} 'TextUnit_Document'
137 = {str} 'TextUnit_Format'
138 = {str} 'TextUnit_Line'
139 = {str} 'TextUnit_Page'
140 = {str} 'TextUnit_Paragraph'
141 = {str} 'TextUnit_Word'
142 = {str} 'ToggleState'
143 = {str} 'ToggleState_Indeterminate'
144 = {str} 'ToggleState_Off'
145 = {str} 'ToggleState_On'
146 = {str} 'TreeScope'
147 = {str} 'TreeScope_Ancestors'
148 = {str} 'TreeScope_Children'
149 = {str} 'TreeScope_Descendants'
150 = {str} 'TreeScope_Element'
151 = {str} 'TreeScope_Parent'
152 = {str} 'TreeScope_Subtree'
153 = {str} 'UIA_AcceleratorKeyPropertyId'
154 = {str} 'UIA_AccessKeyPropertyId'
155 = {str} 'UIA_AnimationStyleAttributeId'
156 = {str} 'UIA_AriaPropertiesPropertyId'
157 = {str} 'UIA_AriaRolePropertyId'
158 = {str} 'UIA_AsyncContentLoadedEventId'
159 = {str} 'UIA_AutomationFocusChangedEventId'
160 = {str} 'UIA_AutomationIdPropertyId'
161 = {str} 'UIA_AutomationPropertyChangedEventId'
162 = {str} 'UIA_BackgroundColorAttributeId'
163 = {str} 'UIA_BoundingRectanglePropertyId'
164 = {str} 'UIA_BulletStyleAttributeId'
165 = {str} 'UIA_ButtonControlTypeId'
166 = {str} 'UIA_CalendarControlTypeId'
167 = {str} 'UIA_CapStyleAttributeId'
168 = {str} 'UIA_CheckBoxControlTypeId'
169 = {str} 'UIA_ClassNamePropertyId'
170 = {str} 'UIA_ClickablePointPropertyId'
171 = {str} 'UIA_ComboBoxControlTypeId'
172 = {str} 'UIA_ControlTypePropertyId'
173 = {str} 'UIA_ControllerForPropertyId'
174 = {str} 'UIA_CultureAttributeId'
175 = {str} 'UIA_CulturePropertyId'
176 = {str} 'UIA_CustomControlTypeId'
177 = {str} 'UIA_DataGridControlTypeId'
178 = {str} 'UIA_DataItemControlTypeId'
179 = {str} 'UIA_DescribedByPropertyId'
180 = {str} 'UIA_DockDockPositionPropertyId'
181 = {str} 'UIA_DockPatternId'
182 = {str} 'UIA_DocumentControlTypeId'
183 = {str} 'UIA_EditControlTypeId'
184 = {str} 'UIA_ExpandCollapseExpandCollapseStatePropertyId'
185 = {str} 'UIA_ExpandCollapsePatternId'
186 = {str} 'UIA_FlowsToPropertyId'
187 = {str} 'UIA_FontNameAttributeId'
188 = {str} 'UIA_FontSizeAttributeId'
189 = {str} 'UIA_FontWeightAttributeId'
190 = {str} 'UIA_ForegroundColorAttributeId'
191 = {str} 'UIA_FrameworkIdPropertyId'
192 = {str} 'UIA_GridColumnCountPropertyId'
193 = {str} 'UIA_GridItemColumnPropertyId'
194 = {str} 'UIA_GridItemColumnSpanPropertyId'
195 = {str} 'UIA_GridItemContainingGridPropertyId'
196 = {str} 'UIA_GridItemPatternId'
197 = {str} 'UIA_GridItemRowPropertyId'
198 = {str} 'UIA_GridItemRowSpanPropertyId'
199 = {str} 'UIA_GridPatternId'
200 = {str} 'UIA_GridRowCountPropertyId'
201 = {str} 'UIA_GroupControlTypeId'
202 = {str} 'UIA_HasKeyboardFocusPropertyId'
203 = {str} 'UIA_HeaderControlTypeId'
204 = {str} 'UIA_HeaderItemControlTypeId'
205 = {str} 'UIA_HelpTextPropertyId'
206 = {str} 'UIA_HorizontalTextAlignmentAttributeId'
207 = {str} 'UIA_HyperlinkControlTypeId'
208 = {str} 'UIA_ImageControlTypeId'
209 = {str} 'UIA_IndentationFirstLineAttributeId'
210 = {str} 'UIA_IndentationLeadingAttributeId'
211 = {str} 'UIA_IndentationTrailingAttributeId'
212 = {str} 'UIA_InputDiscardedEventId'
213 = {str} 'UIA_InputReachedOtherElementEventId'
214 = {str} 'UIA_InputReachedTargetEventId'
215 = {str} 'UIA_InvokePatternId'
216 = {str} 'UIA_Invoke_InvokedEventId'
217 = {str} 'UIA_IsContentElementPropertyId'
218 = {str} 'UIA_IsControlElementPropertyId'
219 = {str} 'UIA_IsDataValidForFormPropertyId'
220 = {str} 'UIA_IsDockPatternAvailablePropertyId'
221 = {str} 'UIA_IsEnabledPropertyId'
222 = {str} 'UIA_IsExpandCollapsePatternAvailablePropertyId'
223 = {str} 'UIA_IsGridItemPatternAvailablePropertyId'
224 = {str} 'UIA_IsGridPatternAvailablePropertyId'
225 = {str} 'UIA_IsHiddenAttributeId'
226 = {str} 'UIA_IsInvokePatternAvailablePropertyId'
227 = {str} 'UIA_IsItalicAttributeId'
228 = {str} 'UIA_IsItemContainerPatternAvailablePropertyId'
229 = {str} 'UIA_IsKeyboardFocusablePropertyId'
230 = {str} 'UIA_IsLegacyIAccessiblePatternAvailablePropertyId'
231 = {str} 'UIA_IsMultipleViewPatternAvailablePropertyId'
232 = {str} 'UIA_IsOffscreenPropertyId'
233 = {str} 'UIA_IsPasswordPropertyId'
234 = {str} 'UIA_IsRangeValuePatternAvailablePropertyId'
235 = {str} 'UIA_IsReadOnlyAttributeId'
236 = {str} 'UIA_IsRequiredForFormPropertyId'
237 = {str} 'UIA_IsScrollItemPatternAvailablePropertyId'
238 = {str} 'UIA_IsScrollPatternAvailablePropertyId'
239 = {str} 'UIA_IsSelectionItemPatternAvailablePropertyId'
240 = {str} 'UIA_IsSelectionPatternAvailablePropertyId'
241 = {str} 'UIA_IsSubscriptAttributeId'
242 = {str} 'UIA_IsSuperscriptAttributeId'
243 = {str} 'UIA_IsSynchronizedInputPatternAvailablePropertyId'
244 = {str} 'UIA_IsTableItemPatternAvailablePropertyId'
245 = {str} 'UIA_IsTablePatternAvailablePropertyId'
246 = {str} 'UIA_IsTextPatternAvailablePropertyId'
247 = {str} 'UIA_IsTogglePatternAvailablePropertyId'
248 = {str} 'UIA_IsTransformPatternAvailablePropertyId'
249 = {str} 'UIA_IsValuePatternAvailablePropertyId'
250 = {str} 'UIA_IsVirtualizedItemPatternAvailablePropertyId'
251 = {str} 'UIA_IsWindowPatternAvailablePropertyId'
252 = {str} 'UIA_ItemContainerPatternId'
253 = {str} 'UIA_ItemStatusPropertyId'
254 = {str} 'UIA_ItemTypePropertyId'
255 = {str} 'UIA_LabeledByPropertyId'
256 = {str} 'UIA_LayoutInvalidatedEventId'
257 = {str} 'UIA_LegacyIAccessibleChildIdPropertyId'
258 = {str} 'UIA_LegacyIAccessibleDefaultActionPropertyId'
259 = {str} 'UIA_LegacyIAccessibleDescriptionPropertyId'
260 = {str} 'UIA_LegacyIAccessibleHelpPropertyId'
261 = {str} 'UIA_LegacyIAccessibleKeyboardShortcutPropertyId'
262 = {str} 'UIA_LegacyIAccessibleNamePropertyId'
263 = {str} 'UIA_LegacyIAccessiblePatternId'
264 = {str} 'UIA_LegacyIAccessibleRolePropertyId'
265 = {str} 'UIA_LegacyIAccessibleSelectionPropertyId'
266 = {str} 'UIA_LegacyIAccessibleStatePropertyId'
267 = {str} 'UIA_LegacyIAccessibleValuePropertyId'
268 = {str} 'UIA_ListControlTypeId'
269 = {str} 'UIA_ListItemControlTypeId'
270 = {str} 'UIA_LocalizedControlTypePropertyId'
271 = {str} 'UIA_MarginBottomAttributeId'
272 = {str} 'UIA_MarginLeadingAttributeId'
273 = {str} 'UIA_MarginTopAttributeId'
274 = {str} 'UIA_MarginTrailingAttributeId'
275 = {str} 'UIA_MenuBarControlTypeId'
276 = {str} 'UIA_MenuClosedEventId'
277 = {str} 'UIA_MenuControlTypeId'
278 = {str} 'UIA_MenuItemControlTypeId'
279 = {str} 'UIA_MenuModeEndEventId'
280 = {str} 'UIA_MenuModeStartEventId'
281 = {str} 'UIA_MenuOpenedEventId'
282 = {str} 'UIA_MultipleViewCurrentViewPropertyId'
283 = {str} 'UIA_MultipleViewPatternId'
284 = {str} 'UIA_MultipleViewSupportedViewsPropertyId'
285 = {str} 'UIA_NamePropertyId'
286 = {str} 'UIA_NativeWindowHandlePropertyId'
287 = {str} 'UIA_OrientationPropertyId'
288 = {str} 'UIA_OutlineStylesAttributeId'
289 = {str} 'UIA_OverlineColorAttributeId'
290 = {str} 'UIA_OverlineStyleAttributeId'
291 = {str} 'UIA_PaneControlTypeId'
292 = {str} 'UIA_ProcessIdPropertyId'
293 = {str} 'UIA_ProgressBarControlTypeId'
294 = {str} 'UIA_ProviderDescriptionPropertyId'
295 = {str} 'UIA_RadioButtonControlTypeId'
296 = {str} 'UIA_RangeValueIsReadOnlyPropertyId'
297 = {str} 'UIA_RangeValueLargeChangePropertyId'
298 = {str} 'UIA_RangeValueMaximumPropertyId'
299 = {str} 'UIA_RangeValueMinimumPropertyId'
300 = {str} 'UIA_RangeValuePatternId'
301 = {str} 'UIA_RangeValueSmallChangePropertyId'
302 = {str} 'UIA_RangeValueValuePropertyId'
303 = {str} 'UIA_RuntimeIdPropertyId'
304 = {str} 'UIA_ScrollBarControlTypeId'
305 = {str} 'UIA_ScrollHorizontalScrollPercentPropertyId'
306 = {str} 'UIA_ScrollHorizontalViewSizePropertyId'
307 = {str} 'UIA_ScrollHorizontallyScrollablePropertyId'
308 = {str} 'UIA_ScrollItemPatternId'
309 = {str} 'UIA_ScrollPatternId'
310 = {str} 'UIA_ScrollVerticalScrollPercentPropertyId'
311 = {str} 'UIA_ScrollVerticalViewSizePropertyId'
312 = {str} 'UIA_ScrollVerticallyScrollablePropertyId'
313 = {str} 'UIA_SelectionCanSelectMultiplePropertyId'
314 = {str} 'UIA_SelectionIsSelectionRequiredPropertyId'
315 = {str} 'UIA_SelectionItemIsSelectedPropertyId'
316 = {str} 'UIA_SelectionItemPatternId'
317 = {str} 'UIA_SelectionItemSelectionContainerPropertyId'
318 = {str} 'UIA_SelectionItem_ElementAddedToSelectionEventId'
319 = {str} 'UIA_SelectionItem_ElementRemovedFromSelectionEventId'
320 = {str} 'UIA_SelectionItem_ElementSelectedEventId'
321 = {str} 'UIA_SelectionPatternId'
322 = {str} 'UIA_SelectionSelectionPropertyId'
323 = {str} 'UIA_Selection_InvalidatedEventId'
324 = {str} 'UIA_SeparatorControlTypeId'
325 = {str} 'UIA_SliderControlTypeId'
326 = {str} 'UIA_SpinnerControlTypeId'
327 = {str} 'UIA_SplitButtonControlTypeId'
328 = {str} 'UIA_StatusBarControlTypeId'
329 = {str} 'UIA_StrikethroughColorAttributeId'
330 = {str} 'UIA_StrikethroughStyleAttributeId'
331 = {str} 'UIA_StructureChangedEventId'
332 = {str} 'UIA_SynchronizedInputPatternId'
333 = {str} 'UIA_TabControlTypeId'
334 = {str} 'UIA_TabItemControlTypeId'
335 = {str} 'UIA_TableColumnHeadersPropertyId'
336 = {str} 'UIA_TableControlTypeId'
337 = {str} 'UIA_TableItemColumnHeaderItemsPropertyId'
338 = {str} 'UIA_TableItemPatternId'
339 = {str} 'UIA_TableItemRowHeaderItemsPropertyId'
340 = {str} 'UIA_TablePatternId'
341 = {str} 'UIA_TableRowHeadersPropertyId'
342 = {str} 'UIA_TableRowOrColumnMajorPropertyId'
343 = {str} 'UIA_TabsAttributeId'
344 = {str} 'UIA_TextControlTypeId'
345 = {str} 'UIA_TextFlowDirectionsAttributeId'
346 = {str} 'UIA_TextPatternId'
347 = {str} 'UIA_Text_TextChangedEventId'
348 = {str} 'UIA_Text_TextSelectionChangedEventId'
349 = {str} 'UIA_ThumbControlTypeId'
350 = {str} 'UIA_TitleBarControlTypeId'
351 = {str} 'UIA_TogglePatternId'
352 = {str} 'UIA_ToggleToggleStatePropertyId'
353 = {str} 'UIA_ToolBarControlTypeId'
354 = {str} 'UIA_ToolTipClosedEventId'
355 = {str} 'UIA_ToolTipControlTypeId'
356 = {str} 'UIA_ToolTipOpenedEventId'
357 = {str} 'UIA_TransformCanMovePropertyId'
358 = {str} 'UIA_TransformCanResizePropertyId'
359 = {str} 'UIA_TransformCanRotatePropertyId'
360 = {str} 'UIA_TransformPatternId'
361 = {str} 'UIA_TreeControlTypeId'
362 = {str} 'UIA_TreeItemControlTypeId'
363 = {str} 'UIA_UnderlineColorAttributeId'
364 = {str} 'UIA_UnderlineStyleAttributeId'
365 = {str} 'UIA_ValueIsReadOnlyPropertyId'
366 = {str} 'UIA_ValuePatternId'
367 = {str} 'UIA_ValueValuePropertyId'
368 = {str} 'UIA_VirtualizedItemPatternId'
369 = {str} 'UIA_WindowCanMaximizePropertyId'
370 = {str} 'UIA_WindowCanMinimizePropertyId'
371 = {str} 'UIA_WindowControlTypeId'
372 = {str} 'UIA_WindowIsModalPropertyId'
373 = {str} 'UIA_WindowIsTopmostPropertyId'
374 = {str} 'UIA_WindowPatternId'
375 = {str} 'UIA_WindowWindowInteractionStatePropertyId'
376 = {str} 'UIA_WindowWindowVisualStatePropertyId'
377 = {str} 'UIA_Window_WindowClosedEventId'
378 = {str} 'UIA_Window_WindowOpenedEventId'
379 = {str} 'Union'
380 = {str} 'VARIANT'
381 = {str} 'WINFUNCTYPE'
382 = {str} 'WSTRING'
383 = {str} 'WinDLL'
384 = {str} 'WinError'
385 = {str} 'WindowInteractionState'
386 = {str} 'WindowInteractionState_BlockedByModalWindow'
387 = {str} 'WindowInteractionState_Closing'
388 = {str} 'WindowInteractionState_NotResponding'
389 = {str} 'WindowInteractionState_ReadyForUserInteraction'
390 = {str} 'WindowInteractionState_Running'
391 = {str} 'WindowVisualState'
392 = {str} 'WindowVisualState_Maximized'
393 = {str} 'WindowVisualState_Minimized'
394 = {str} 'WindowVisualState_Normal'
395 = {str} '_944DE083_8FB8_45CF_BCB7_C477ACB2F897_0_1_0'
396 = {str} '__all__'
397 = {str} '__builtins__'
398 = {str} '__doc__'
399 = {str} '__file__'
400 = {str} '__name__'
401 = {str} '__package__'
402 = {str} '_check_version'
403 = {str} '_lcid'
404 = {str} '_midlSAFEARRAY'
405 = {str} 'addressof'
406 = {str} 'alignment'
407 = {str} 'byref'
408 = {str} 'c_bool'
409 = {str} 'c_buffer'
410 = {str} 'c_byte'
411 = {str} 'c_char'
412 = {str} 'c_char_p'
413 = {str} 'c_double'
414 = {str} 'c_float'
415 = {str} 'c_int'
416 = {str} 'c_int16'
417 = {str} 'c_int32'
418 = {str} 'c_int64'
419 = {str} 'c_int8'
420 = {str} 'c_long'
421 = {str} 'c_longdouble'
422 = {str} 'c_longlong'
423 = {str} 'c_short'
424 = {str} 'c_size_t'
425 = {str} 'c_ssize_t'
426 = {str} 'c_ubyte'
427 = {str} 'c_uint'
428 = {str} 'c_uint16'
429 = {str} 'c_uint32'
430 = {str} 'c_uint64'
431 = {str} 'c_uint8'
432 = {str} 'c_ulong'
433 = {str} 'c_ulonglong'
434 = {str} 'c_ushort'
435 = {str} 'c_void_p'
436 = {str} 'c_voidp'
437 = {str} 'c_wchar'
438 = {str} 'c_wchar_p'
439 = {str} 'cast'
440 = {str} 'cdll'
441 = {str} 'comtypes'
442 = {str} 'create_string_buffer'
443 = {str} 'create_unicode_buffer'
444 = {str} 'dispid'
445 = {str} 'get_errno'
446 = {str} 'get_last_error'
447 = {str} 'helpstring'
448 = {str} 'memmove'
449 = {str} 'memset'
450 = {str} 'oledll'
451 = {str} 'pointer'
452 = {str} 'py_object'
453 = {str} 'pydll'
454 = {str} 'pythonapi'
455 = {str} 'resize'
456 = {str} 'set_conversion_mode'
457 = {str} 'set_errno'
458 = {str} 'set_last_error'
459 = {str} 'sizeof'
460 = {str} 'string_at'
461 = {str} 'tagPOINT'
462 = {str} 'tagRECT'
463 = {str} 'typelib_path'
464 = {str} 'windll'
465 = {str} 'wintypes'
466 = {str} 'wstring_at'
__len__ = {int} 467
```

**Comment by beuaaa** [comment]
> According to https://docs.microsoft.com/en-us/windows/win32/winauto/uiauto-controltype-ids

> UIA_AppBarControlTypeId50040  Identifies the AppBar control type. Supported starting with Windows 8.1.

> UIA_SemanticZoomControlTypeId50039 Identifies the SemanticZoom control type. Supported starting with Windows 8.

In your self._control_types you don't have AppBar, it's normal  because it is supported starting with Windows 8.1 and you have Windows 8.
In my self._control_types I don't have AppBar and SemanticZoom and it's not normal. But my inspect.exe displays SemanticZoom. So I don't understand.

**Comment by airelil** [comment]
@beuaaa , you can try to re-generate the COM interfaces in comtypes package. Typically, it means locating your Python comtypes installation and deleting the contents of `gen` folder. Since I work with conda environments I have several installations comtypes and Python. For example, the comtypes for Python 3.7 environmenton my machine is located under:
`C:\Users\XXXX\Miniconda3\envs\py37\Lib\site-packages\comtypes\gen`
Once the content of this folder is deleted, running `python -m "pywinauto"` would be enough to re-generate the files. 
You can also explore the files (but don't change!) The SemantiZoom definitions can be found in _944DE083_8FB8_45CF_BCB7_C477ACB2F897_0_1_0.py That's the list of files on my machine:
![image](https://user-images.githubusercontent.com/795040/79079018-87638480-7d60-11ea-93c0-54cb3438248b.png)

**Comment by beuaaa** [comment]
@airelil I deleted Lib\site-packages\comtypes\gen and regeneraetd it running python -m "pywinauto" and now I have SemanticZoom and AppBar in self._control_types!

Maybe when I first started Pywinauto in this env , it was on Windows 7, it generated Lib\site-packages\comtypes\gen without SemanticZoom and AppBar.

Thank you very much for your help!

**Comment by airelil** [comment]
Glad it worked out for you. You may want to update your question on StackOverflow, this can help to others.

**Comment by beuaaa** [comment]
I have already updated my question on StackOverflow.

**Comment by vasily-v-ryabov** [comment]
This is good, but we need to think how to detect version mismatch between comtypes cached code and `UIAutomationCore.dll`.

**Comment by beuaaa** [comment]
Do i have to reopen the issue?

**Comment by vasily-v-ryabov** [comment]
@beuaaa I think we can file separate issue. It would be low priority for now.
