### ISSUE TITLE
Shell_TrayWnd  class is not working

### ISSUE THREAD

**Issue by rambabu3381** [pywinauto/pywinauto#927]
Hi !

This is my code:
```python
from pywinauto import application
import time
app = application.Application()
app1 = application.Application(backend="uia").connect(path="explorer.exe")
sys_tray = app1.window(class_name="Shell_TrayWnd")
sys_tray.child_window(title="myapplication_name").click_input(double=True)
time.sleep(2)
```

This code is working sometimes and sometimes I am getting weird error.
This is the error I am facing when I run the code I cannot able to figure out this.
I need your help .
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\rchepala\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pywinauto\application.py", line 613, in print_control_identifiers
    this_ctrl = self.__resolve_control(self.criteria)[-1]
  File "C:\Users\rchepala\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pywinauto\application.py", line 261, in __resolve_control
    raise e.original_exception
  File "C:\Users\rchepala\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pywinauto\timings.py", line 436, in wait_until_passes
    func_val = func(*args, **kwargs)
  File "C:\Users\rchepala\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pywinauto\application.py", line 203, in __get_ctrl
    dialog = self.backend.generic_wrapper_class(findwindows.find_element(**criteria[0]))
  File "C:\Users\rchepala\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pywinauto\findwindows.py", line 84, in find_element
    elements = find_elements(**kwargs)
  File "C:\Users\rchepala\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pywinauto\findwindows.py", line 305, in find_elements
    elements = findbestmatch.find_best_control_matches(best_match, wrapped_elems)
  File "C:\Users\rchepala\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pywinauto\findbestmatch.py", line 536, in find_best_control_matches
    raise MatchError(items = name_control_map.keys(), tofind = search_text)
pywinauto.findbestmatch.MatchError: Could not find 'ShellTrayWnd' in 'dict_keys(['Python38-32', 'CabinetWClass', 'Python38-32CabinetWClass'])'
```

**Comment by vasily-v-ryabov** [comment]
Try this:
```python
from pywinauto import Desktop
#...
sys_tray = Desktop(backend="uia").window(class_name="Shell_TrayWnd")
```

**Comment by rambabu3381** [comment]
yes worked thank you
