### ISSUE TITLE
Waiting for the element availability & Visibility

### ISSUE THREAD

**Issue by jjbright** [pywinauto/pywinauto#936]
## Expected Behavior
After an action like button click, we have to wait for the next element to be loaded and available for action

## Actual Behavior
When a search operation is called from a 'Search' button click, I give sleep(seconds) with a tentative timing to delay the next line of code execution.  If the search operation is taking more than the time to give results  and the sleep(seconds) exceeded, automatically the next thing happens and goes ahead to click the 'Reset' button 

## Steps to Reproduce the Problem
N/A

## Short Example of Code to Demonstrate the Problem
```
mainPanel.child_window(auto_id='searchButton', control_type='Button').click_input()
sleep(6)
ImageGrab.grab().save("results.png")
mainPanel.child_window(auto_id='resetButton', control_type='Button').click_input()
```

## Specifications

  - Pywinauto version: 0.6.8
  - Python version and bitness:  3.7.4 64 bit
  - Platform and OS: Windows 10

**Comment by airelil** [comment]
Is it something similar to this `wait` method?
https://github.com/pywinauto/pywinauto/blob/5fc0a7f05fa626c1830be5ef32878f76bea08f34/pywinauto/base_application.py#L498

**Comment by jjbright** [comment]
@airelil  Correct, but after the search button clicks the page will load a results table... how to wait for that control to appear?
If I have to navigate to that control, I've to get that control like below
`results = mainPanel.child_window(auto_id="results",  control_type="Table")`

So I do a sleep to get that control, meanwhile if the search takes more time this table control doesn't appear and throws error as elementnotfound

**Comment by airelil** [comment]
@jjbright, that's exactly the point of `WindowSpecification` concept. It "describes" the control we want to access and pywinauto tries to resolve it according to specified criteria. The `wait` method enhances this ability by asking pywinauto to perform this search again and again with the specified `interval` until it times out or is found. Let me refer you one more time to our unit tests. These examples show how we wait for an element to be resolved by `control_type` or `automation_id`  AND be visible.
https://github.com/pywinauto/pywinauto/blob/5fc0a7f05fa626c1830be5ef32878f76bea08f34/pywinauto/unittests/test_common_controls.py#L540
https://github.com/pywinauto/pywinauto/blob/5fc0a7f05fa626c1830be5ef32878f76bea08f34/pywinauto/unittests/test_common_controls.py#L529

**Comment by vasily-v-ryabov** [comment]
@jjbright Let's take a look at the docs chapter [Waiting for Long Operations](https://pywinauto.readthedocs.io/en/latest/wait_long_operations.html). If you don't need exception to be raised after timeout, there are methods `exists(timeout=10)` and method `.is_visible()` that both return `bool` value.

**Comment by vasily-v-ryabov** [comment]
BTW, it could be mentioned in the docs (I mean exception-less functions). Let's keep it open.

**Comment by jjbright** [comment]
@airelil @vasily-v-ryabov  I've tried these guidances and here is the outcome.

1. When I have a proper result is returned,  there are no issues.  I changed the code as @airelil advised
`results = mainPanel.child_window(auto_id="results", control_type="Table").wait('visible')`

2. When a search didn't return a result, I get exceptions.
    So I tried the guidance of @vasily-v-ryabov by using `exist(timeout=10)` and `is_visible()`
     Both fails with exceptions

```
Traceback (most recent call last):
  File "C:\Python\Python37\lib\site-packages\pywinauto\application.py", line 258, in __resolve_control
    criteria)
  File "C:\Python\Python37\lib\site-packages\pywinauto\timings.py", line 458, in wait_until_passes
    raise err
pywinauto.timings.TimeoutError
```
Guide me if I could follow a better way, but for now I'm proceeding with the `wait('visible')` method as success scenario and the exception as failure scenario.

Once again I humbly appreciate both of your support and I look forward to continuing.

**Comment by jjbright** [comment]
**Just a clarification on my requirement:**
I do search operations in my application with multiple set of test data, 

- when the backend returns the resultset, I get a table displayed in the screen
    I need to read the data from the appropriate columns and assert it with the test data. _unable to succeed in this step, which I referred to issue #566 _
    Log the result as Success.
- when the backend returns no resultset, I get a message displayed in the screen as 'No data found'
    Log the result as failed.

For now, the wait('visible') is a workaround for #936

**Comment by vasily-v-ryabov** [comment]
If you call `.is_visible()` for WindowSpecification object, it initiates the search procedure which fails with exception. Method `.exists(timeout=10)` shouldn't raise an exception. So please make sure that `.exists()` returned `True` first, then call `.is_visible()` for the wrapper object found automatically. `.exists()` is a method of WindowSpecification, while `.is_visible()` is a wrapper method.

**Comment by jjbright** [comment]
@vasily-v-ryabov let me try it, humbled by your help
