### ISSUE TITLE
select() for TreeView items (and similar) leads error if this selection calls other dialogs etc

### ISSUE THREAD

**Issue by eratheo** [pywinauto/pywinauto#937]
## Expected Behavior
`studio.child_window(title="Open Session", auto_id="PART_TextBlock", control_type="Text").parent().select()` for List or Tree items which call for another dialog etc. should not cause errors or exceptions

## Actual Behavior
`studio.child_window(title="Open Session", auto_id="PART_TextBlock", control_type="Text").parent().select()` for List or Tree items which call for another dialog etc. causes error. And breaks the script for further execution.
`Traceback (most recent call last):
  File "C:/Python/Projects/automation/index_.py", line 11, in <module>
    studio.child_window(title="Open Session", auto_id="PART_TextBlock", control_type="Text").parent().select()
  File "C:\Python\Python38\lib\site-packages\pywinauto\controls\uiawrapper.py", line 605, in select
    self.iface_selection_item.Select()
_ctypes.COMError: (-2146233083, None, (None, None, None, 0, None))`

## Steps to Reproduce the Problem

  1. Use select() for item in List or Tree view which calls new dialog for user to select something 

## Specifications

  - Pywinauto version: 0.6.8
  - Python version and bitness: 3.8.2 x64
  - Platform and OS: Windows 10 x64

**Comment by airelil** [comment]
Seems that the parent does not have Select interface. Can you print `parent().wrapper_object()`? Would be interesting to see what type of the control it is.

**Comment by eratheo** [comment]
> Seems that the parent does not have Select interface. Can you print `parent().wrapper_object()`? Would be interesting to see what type of the control it is.

```
Traceback (most recent call last):
  File "C:/Python/Projects/automation/index_.py", line 10, in <module>
    print(studio.child_window(title="Open Session", auto_id="PART_TextBlock", control_type="Text").parent().wrapper_object())
AttributeError: 'ListItemWrapper' object has no attribute 'wrapper_object'
```

It actually selects the item, but then new dialog appears, and script is not completed, it 'waits' for something else, while the dialog is open.

**Comment by airelil** [comment]
You mean the "select" method is blocked until some action on the new appeared dialog is taken?

**Comment by eratheo** [comment]
> You mean the "select" method is blocked until some action on the new appeared dialog is taken?

Yes, something like that. It calls dialog, but does not "finish" itself, so nothing after "select" executes.

**Comment by airelil** [comment]
Did you consider than running another code in a separate thread to handle the new dialog? Using the python `threading` module should be pretty simple, but notice the official warning from the threading docs:
> In CPython, due to the Global Interpreter Lock, only one thread can execute Python code at once (even though certain performance-oriented libraries might overcome this limitation). If you want your application to make better use of the computational resources of multi-core machines, you are advised to use multiprocessing or concurrent.futures.ProcessPoolExecutor. However, threading is still an appropriate model if you want to run multiple I/O-bound tasks simultaneously.

**Comment by eratheo** [comment]
@airelil thanks for the tip. Not familiar with `threading`, but I will learn more and try to use. Anyway, this particular issue currently exists for several wrappers.

**Comment by airelil** [comment]
As I understand you already discussed the issue with @vasily-v-ryabov. I marked the issue as enhancement

**Comment by eratheo** [comment]
@airelil yes, we discussed it some time ago, but I haven't reported it as he suggested. Fixed it 🤗

**Comment by deven-s** [comment]
Hi @eratheo Could you post what fix worked for you. That will be really helpful.

Actually same behavior I'm observing. I have a tree it expands initial 2 elements but it fails and stuck at next element at 3rd level, I have tried - 
`expand()` and it hangs execution without error but with error popup, 
`sub_elements()` Called on same element and it returns [](empty) list
`children()` called on same element and this also returns [] list
`select()` called on same element and it hangs the execution without error but generates the error popup.

When this element expanded manually it takes 1-2 seconds to load the children tree nodes under it. This tree node seems static type.
