### ISSUE TITLE
How to make it work on Ubuntu?

### ISSUE THREAD

**Issue by lanzorg** [pywinauto/pywinauto#951]
I installed pywinauto like this on Ubuntu:

```sh
pip3 install -U https://github.com/pywinauto/pywinauto/archive/atspi.zip
```

And run this Python script:

```python
from pywinauto.application import WindowSpecification
from pywinauto.controls import atspiwrapper
from pywinauto.linux.application import Application
app = Application().start("firefox")
```

But I get this error:

```sh
Traceback (most recent call last):
  File "demo.py", line 1, in <module>
    from pywinauto.application import WindowSpecification
  File "/home/lan/.local/lib/python3.8/site-packages/pywinauto/__init__.py", line 95, in <module>
    from . import findwindows
  File "/home/lan/.local/lib/python3.8/site-packages/pywinauto/findwindows.py", line 40, in <module>
    from . import controls
ImportError: cannot import name 'controls' from partially initialized module 'pywinauto' (most likely due to a circular import) (/home/lan/.local/lib/python3.8/site-packages/pywinauto/__init__.py)
```

**Comment by airelil** [comment]
@lanzorg, the general pywinauto workflow shouldn't be different for Linux platform. You only need to make import to Application, similar as on Win platform:
```python
from pywinauto import Application
app = Application().start("firefox")

# Connect to the actual firefox process forked by launcher
app = Application()
app.connect(path="firefox")
```
But please remember that the current Linux support is only at early alpha stage and far away from perfect.

**Comment by benoit-pierre** [comment]
The `controls` package is missing on Linux because it's not installed:
```diff
 setup.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git i/setup.py w/setup.py
index f3a4804..45f33a6 100644
--- i/setup.py
+++ w/setup.py
@@ -66,7 +66,7 @@ def setup_path(path = ""):
     packages = ["pywinauto", "pywinauto.tests", "pywinauto.controls", "pywinauto.linux"]
 else:
     install_requires = ['six', 'python-xlib']
-    packages = ["pywinauto", "pywinauto.linux"]
+    packages = ["pywinauto", "pywinauto.controls", "pywinauto.linux"]
 
 setup(name='pywinauto',
     version = '0.6.8',
```

**Comment by sasananas1** [comment]
it helped me solve the problem with installing on ubuntu 20.04
