### ISSUE TITLE
Accessing all Data in a Table

### ISSUE THREAD

**Issue by dschiller** [pywinauto/pywinauto#985]
## Expected Behavior

Accesing all Items in a Table

## Actual Behavior

Just get the visible Items and need to move vertical and horizontal Scrollbars to see all Data

## Steps to Reproduce the Problem

  1. Have a UIA App with Scrollviewer and a Table inside
  2. If Table is wider and longer then the Scrollviewer I jsut get the visible Items back as Children

## Specifications

  - Pywinauto version: 0.6.6
  - Python version and bitness: 3.7 x64
  - Platform and OS: Win 10

**Comment by airelil** [comment]
See my comment about virtualized items in an old issue: https://github.com/pywinauto/pywinauto/issues/941#issuecomment-640023029 . Hope it can give you a direction to look at.

Also Microsoft docs: https://docs.microsoft.com/en-us/windows/win32/winauto/uiauto-workingwithvirtualizeditems

**Comment by dschiller** [comment]
Hey Valentin, thank's for that. But that doesn't change the Behaviour. I can not access Columns which are unvisible. How you think the `get_item()` Method could help here ?

Thank's a lot!

**Comment by airelil** [comment]
You mentioned that you have to force vertical scrolling.That sounds as quite related to virtualized items and get_item could be of use here to bring the full row. Did you try it? Does item_count method returns correct number of rows?

BTW, what do you get on call of get_column and column_count methods?

**Comment by dschiller** [comment]
`item_count` brings only the visible Items of a Row back.

**Comment by dschiller** [comment]
`column_count*  brings the correct Column Number.

**Comment by dschiller** [comment]
`get_column` doesn't find any.

```
    print('get_column:', query.get_column(0))
  File "C:\Program Files\Python37\lib\site-packages\pywinauto\controls\uia_controls.py", line 758, in get_column
    col = self.columns()[col_index]
IndexError: list index out of range
```

**Comment by airelil** [comment]
You could try to access a particular column from the row as pywinauto does for the rows in the ListView: https://github.com/pywinauto/pywinauto/blob/4eec32e81cc3e5666eee57419c32a59ac22db667/pywinauto/controls/uia_controls.py#L923
Let's say, if you get your row, it most probably will be ListItemWrapper.
```python
import uia_defines

# assuming you have a UIA list_wrapper instance, let's try to get columns for the row 1
#...
row_wrp = list_wrp.get_item(1);

try:
    com_elem = 0
    # try to get to the last column in the row
    for _ in range(0, list_wrp.column_count()):
        com_elem = row_wrp.iface_item_container.FindItemByProperty(com_elem, 0, IUIA().ui_automation_client.VARIANT.empty.vt)
    # Try to load element using VirtualizedItem pattern
    try:
        uia_defines.get_elem_interface(com_elem, "VirtualizedItem").Realize()
    except NoPatternInterfaceError:
        pass
    itm = uiawrapper.UIAWrapper(UIAElementInfo(com_elem))
    print(itm, itm.text)   # we got some column here
except (NoPatternInterfaceError, ValueError, AttributeError):
    # we're out of luck here
     print("Item container interface is not supported by the control")
```
PS: this is "pseudo code" based on piece of code linked above. I didn't check it as I don't have any app to reproduce the issue.
MS doc about FindItemByProperty: https://docs.microsoft.com/en-us/windows/win32/api/uiautomationcore/nf-uiautomationcore-iitemcontainerprovider-finditembyproperty

**Comment by dschiller** [comment]
Thank you Valentin, that is amazing! I will try that soon.

**Comment by dschiller** [comment]
```
print('query:', query)
    print('column_count:', query.column_count())
    print('get_column:', query.get_item(2))

    list_wrp = query
    row_wrp = list_wrp.get_item(2);

    try:
        com_elem = 0
        # try to get to the last column in the row
        for _ in range(0, list_wrp.column_count()):
            com_elem = row_wrp.iface_item_container.FindItemByProperty(com_elem, 0, IUIA().ui_automation_client.VARIANT.empty.vt)
        # Try to load element using VirtualizedItem pattern
        try:
            uia_defines.get_elem_interface(com_elem, "VirtualizedItem").Realize()
        except:
            pass
        itm = uiawrapper.UIAWrapper(UIAElementInfo(com_elem))
        print(itm, itm.text)   # we got some column here
    except (ValueError, AttributeError):
        # we're out of luck here
        print("Item container interface is not supported by the control")
```

Results in:

```
query: uia_controls.ListViewWrapper - '', ListView
column_count: 9
get_column: uia_controls.ListItemWrapper - 'False', DataItem
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\pywinauto\uia_defines.py", line 232, in get_elem_interface
    iface = cur_ptrn.QueryInterface(cls_name)
  File "C:\Program Files\Python37\lib\site-packages\comtypes\__init__.py", line 1158, in QueryInterface
    self.__com_QueryInterface(byref(iid), byref(p))
ValueError: NULL COM pointer access

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\AutoQA\TestSuite\ITSM 8.7.0\Debug\Workcenter\getQueryDataOnForm.py", line 349, in <module>
    getQueryData(Scenario)
  File "C:\AutoQA\TestSuite\ITSM 8.7.0\Debug\Workcenter\getQueryDataOnForm.py", line 291, in getQueryData
    com_elem = row_wrp.iface_item_container.FindItemByProperty(com_elem, 0, IUIA().ui_automation_client.VARIANT.empty.vt)
  File "C:\Program Files\Python37\lib\site-packages\pywinauto\controls\uiawrapper.py", line 132, in __get__
    value = self.fget(obj)
  File "C:\Program Files\Python37\lib\site-packages\pywinauto\controls\uiawrapper.py", line 329, in iface_item_container
    return uia_defs.get_elem_interface(elem, "ItemContainer")
  File "C:\Program Files\Python37\lib\site-packages\pywinauto\uia_defines.py", line 234, in get_elem_interface
    raise NoPatternInterfaceError()
pywinauto.uia_defines.NoPatternInterfaceError
```
