### ISSUE TITLE
child_window raises ElementNotFoundError on element can be displayed by print_control_identifiers

### ISSUE THREAD

**Issue by simohauml** [pywinauto/pywinauto#993]
## Expected Behavior
Get the child element (control type Edit) with child_window(title="PET WB", auto_id="textBox", control_type="Edit") and set up new text in the edit control with set_text()

## Actual Behavior
`>>> txb_custom.child_window(title="PET WB", auto_id="textBox", control_type="Edit").set_text("test")
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\site-packages\pywinauto\application.py", line 250, in __resolve_control
    ctrl = wait_until_passes(
  File "C:\Program Files\Python38\lib\site-packages\pywinauto\timings.py", line 458, in wait_until_passes
    raise err
pywinauto.timings.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#81>", line 1, in <module>
    txb_custom.child_window(title="PET WB", auto_id="textBox", control_type="Edit").set_text("test")
  File "C:\Program Files\Python38\lib\site-packages\pywinauto\application.py", line 379, in __getattribute__
    ctrls = self.__resolve_control(self.criteria)
  File "C:\Program Files\Python38\lib\site-packages\pywinauto\application.py", line 261, in __resolve_control
    raise e.original_exception
  File "C:\Program Files\Python38\lib\site-packages\pywinauto\timings.py", line 436, in wait_until_passes
    func_val = func(*args, **kwargs)
  File "C:\Program Files\Python38\lib\site-packages\pywinauto\application.py", line 222, in __get_ctrl
    ctrl = self.backend.generic_wrapper_class(findwindows.find_element(**ctrl_criteria))
  File "C:\Program Files\Python38\lib\site-packages\pywinauto\findwindows.py", line 87, in find_element
    raise ElementNotFoundError(kwargs)
pywinauto.findwindows.ElementNotFoundError: {'title': 'PET WB', 'auto_id': 'textBox', 'control_type': 'Edit', 'top_level_only': False, 'parent': <uia_element_info.UIAElementInfo - '', TextBoxWithEllipsis, None>, 'backend': 'uia'}`

## Steps to Reproduce the Problem

  1. Load the app, get an element node and name it txb_custom.
  2. Try to get an child element of txb_custom with txb_custom.child_window(title="PET WB", auto_id="textBox", control_type="Edit").set_text("test")
  3. Here is what print_control_identifiers() shows:
`>>> txb_custom.print_control_identifiers()
Control Identifiers:

Custom - ''    (L997, T127, R1075, B177)
['PET WBCustom', 'Custom']
child_window(auto_id="textBox", control_type="Custom")
   | 
   | Edit - 'PET WB'    (L997, T127, R1075, B177)
   | ['Edit', 'PET WBEdit']
   | child_window(title="PET WB", auto_id="textBox", control_type="Edit")
   |    | 
   |    | ScrollBar - ''    (L0, T0, R0, B0)
   |    | ['ScrollBar', 'ScrollBar0', 'ScrollBar1']
   |    | child_window(auto_id="VerticalScrollBar", control_type="ScrollBar")
   |    | 
   |    | ScrollBar - ''    (L0, T0, R0, B0)
   |    | ['ScrollBar2']
   |    | child_window(auto_id="HorizontalScrollBar", control_type="ScrollBar")
   | 
   | Static - 'PET WB'    (L997, T150, R1075, B177)
   | ['Static', 'PET WB', 'PET WBStatic']
   | child_window(title="PET WB", auto_id="textBlock", control_type="Text")`

4. The Static element can be found successfully with txb_custom.child_window(title="PET WB", auto_id="textBlock", control_type="Text")

5. txb_custom.iter_children() generates two elements:
uia_controls.EditWrapper - 'PET WB', Edit
uia_controls.StaticWrapper - 'PET WB', Static

`And next(txb_custom.iter_children()).set_text("test") gets following error:
Traceback (most recent call last):
  File "<pyshell#36>", line 1, in <module>
    next(txb_iter).set_text("test")
  File "C:\Program Files\Python38\lib\site-packages\pywinauto\controls\uia_controls.py", line 426, in set_edit_text
    self.verify_actionable()
  File "C:\Program Files\Python38\lib\site-packages\pywinauto\base_wrapper.py", line 680, in verify_actionable
    self.verify_visible()
  File "C:\Program Files\Python38\lib\site-packages\pywinauto\base_wrapper.py", line 703, in verify_visible
    raise ElementNotVisible()
pywinauto.base_wrapper.ElementNotVisible`

## Specifications

  - Pywinauto version: 0.6.8
  - Python version and bitness: 3.8.5
  - Platform and OS: Windows 10 LTSC 10.0.17763 64bit

**Comment by showkeyjar** [comment]
same problem +1

**Comment by jefferson-terrawise** [comment]
Same issue here

**Comment by jefferson-terrawise** [comment]
Hi junkmd, thanks for the reply. I've tried setting `visible_only=False` without success.

The offending line:
example_win.child_window(title="Events", control_type="TTabSheet",visible_only = False).click_input()

Error msg:
pywinauto.findwindows.ElementNotFoundError: {'title': 'Events', 'control_type': 'TTabSheet', 'visible_only': False, 'top_level_only': False, 'parent': <win32_element_info.HwndElementInfo - 'example.plo (Template - Environmental Plantings Method)', TDocEditForm, 134578>, 'backend': 'win32'}

example_win.print_control_identifiers() output:
[output.txt](https://github.com/pywinauto/pywinauto/files/12246132/output.txt)
